// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// Dispatch loop initialisation, jump table setup, and exit handlers.

// func initJumpTable(table *[256]uintptr)
//
// Populates the 256-entry dispatch table with handler addresses.
// Tier 1 opcodes get their specific handler addresses; all other
// entries point to the tier2Fallback handler.
//
// Takes table (*[256]uintptr) at FP+0.
TEXT ·initJumpTable(SB), NOSPLIT, $0-8
	MOVD table+0(FP), R0

	MOVD $·tier2Fallback(SB), R1
	MOVD $256, R2

initjt_fill:
	MOVD R1, (R0)
	ADD  $8, R0, R0
	SUB  $1, R2, R2
	CBNZ R2, initjt_fill

	MOVD table+0(FP), R0

	MOVD $·handlerNop(SB), R1
	MOVD R1, 0(R0)

	MOVD $·handlerMoveInt(SB), R1
	MOVD R1, 16(R0)

	MOVD $·handlerMoveFloat(SB), R1
	MOVD R1, 24(R0)

	MOVD $·handlerLoadIntConst(SB), R1
	MOVD R1, 32(R0)

	MOVD $·handlerLoadFloatConst(SB), R1
	MOVD R1, 40(R0)

	MOVD $·handlerLoadBool(SB), R1
	MOVD R1, 48(R0)

	MOVD $·handlerLoadIntConstSmall(SB), R1
	MOVD R1, 56(R0)

	MOVD $·handlerAddInt(SB), R1
	MOVD R1, 64(R0)

	MOVD $·handlerSubInt(SB), R1
	MOVD R1, 72(R0)

	MOVD $·handlerMulInt(SB), R1
	MOVD R1, 80(R0)

	MOVD $·handlerDivInt(SB), R1
	MOVD R1, 88(R0)

	MOVD $·handlerRemInt(SB), R1
	MOVD R1, 96(R0)

	MOVD $·handlerNegInt(SB), R1
	MOVD R1, 104(R0)

	MOVD $·handlerIncInt(SB), R1
	MOVD R1, 112(R0)

	MOVD $·handlerDecInt(SB), R1
	MOVD R1, 120(R0)

	MOVD $·handlerBitAnd(SB), R1
	MOVD R1, 128(R0)

	MOVD $·handlerBitOr(SB), R1
	MOVD R1, 136(R0)

	MOVD $·handlerBitXor(SB), R1
	MOVD R1, 144(R0)

	MOVD $·handlerBitAndNot(SB), R1
	MOVD R1, 152(R0)

	MOVD $·handlerBitNot(SB), R1
	MOVD R1, 160(R0)

	MOVD $·handlerShiftLeft(SB), R1
	MOVD R1, 168(R0)

	MOVD $·handlerShiftRight(SB), R1
	MOVD R1, 176(R0)

	MOVD $·handlerAddFloat(SB), R1
	MOVD R1, 184(R0)

	MOVD $·handlerSubFloat(SB), R1
	MOVD R1, 192(R0)

	MOVD $·handlerMulFloat(SB), R1
	MOVD R1, 200(R0)

	MOVD $·handlerDivFloat(SB), R1
	MOVD R1, 208(R0)

	MOVD $·handlerNegFloat(SB), R1
	MOVD R1, 216(R0)

	MOVD $·handlerEqInt(SB), R1
	MOVD R1, 224(R0)

	MOVD $·handlerNeInt(SB), R1
	MOVD R1, 232(R0)

	MOVD $·handlerLtInt(SB), R1
	MOVD R1, 240(R0)

	MOVD $·handlerLeInt(SB), R1
	MOVD R1, 248(R0)

	MOVD $·handlerGtInt(SB), R1
	MOVD R1, 256(R0)

	MOVD $·handlerGeInt(SB), R1
	MOVD R1, 264(R0)

	MOVD $·handlerEqFloat(SB), R1
	MOVD R1, 272(R0)

	MOVD $·handlerNeFloat(SB), R1
	MOVD R1, 280(R0)

	MOVD $·handlerLtFloat(SB), R1
	MOVD R1, 288(R0)

	MOVD $·handlerLeFloat(SB), R1
	MOVD R1, 296(R0)

	MOVD $·handlerGtFloat(SB), R1
	MOVD R1, 304(R0)

	MOVD $·handlerGeFloat(SB), R1
	MOVD R1, 312(R0)

	MOVD $·handlerIntToFloat(SB), R1
	MOVD R1, 320(R0)

	MOVD $·handlerFloatToInt(SB), R1
	MOVD R1, 328(R0)

	MOVD $·handlerNot(SB), R1
	MOVD R1, 336(R0)

	MOVD $·handlerJump(SB), R1
	MOVD R1, 344(R0)

	MOVD $·handlerJumpIfTrue(SB), R1
	MOVD R1, 352(R0)

	MOVD $·handlerJumpIfFalse(SB), R1
	MOVD R1, 360(R0)

	MOVD $·handlerCallInline(SB), R1
	MOVD R1, 368(R0)

	MOVD $·handlerReturnInline(SB), R1
	MOVD R1, 376(R0)

	MOVD $·handlerReturnVoidInline(SB), R1
	MOVD R1, 384(R0)

	MOVD $·handlerTailCallExit(SB), R1
	MOVD R1, 392(R0)

	MOVD $·handlerSubIntConst(SB), R1
	MOVD R1, 400(R0)

	MOVD $·handlerAddIntConst(SB), R1
	MOVD R1, 408(R0)

	MOVD $·handlerLeIntConstJumpFalse(SB), R1
	MOVD R1, 416(R0)

	MOVD $·handlerLtIntConstJumpFalse(SB), R1
	MOVD R1, 424(R0)

	MOVD $·handlerEqIntConstJumpFalse(SB), R1
	MOVD R1, 432(R0)

	MOVD $·handlerEqIntConstJumpTrue(SB), R1
	MOVD R1, 440(R0)

	MOVD $·handlerGeIntConstJumpFalse(SB), R1
	MOVD R1, 448(R0)

	MOVD $·handlerGtIntConstJumpFalse(SB), R1
	MOVD R1, 456(R0)

	MOVD $·handlerMulIntConst(SB), R1
	MOVD R1, 464(R0)

	MOVD $·handlerAddIntJump(SB), R1
	MOVD R1, 472(R0)

	MOVD $·handlerIncIntJumpLt(SB), R1
	MOVD R1, 480(R0)

	MOVD $·handlerMathSqrt(SB), R1
	MOVD R1, 488(R0)

	MOVD $·handlerMathAbs(SB), R1
	MOVD R1, 496(R0)

	MOVD $·handlerMathFloor(SB), R1
	MOVD R1, 504(R0)

	MOVD $·handlerMathCeil(SB), R1
	MOVD R1, 512(R0)

	MOVD $·handlerMathTrunc(SB), R1
	MOVD R1, 520(R0)

	MOVD $·handlerMathRound(SB), R1
	MOVD R1, 528(R0)

	MOVD $·handlerLenString(SB), R1
	MOVD R1, 536(R0)

	MOVD $·handlerStringIndex(SB), R1
	MOVD R1, 544(R0)

	MOVD $·handlerEqString(SB), R1
	MOVD R1, 552(R0)

	MOVD $·handlerNeString(SB), R1
	MOVD R1, 560(R0)

	MOVD $·handlerSliceString(SB), R1
	MOVD R1, 568(R0)

	MOVD $·handlerStringIndexToInt(SB), R1
	MOVD R1, 576(R0)

	MOVD $·handlerLenStringLtJumpFalse(SB), R1
	MOVD R1, 584(R0)

	RET

// func dispatchLoop(ctx *DispatchContext)
//
// Entry point for the ASM dispatch loop. Loads ctx into registers and
// performs the first dispatch. Subsequent dispatches happen at the tail
// of each handler via the DISPATCH_NEXT macro.
TEXT ·dispatchLoop(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R19
	MOVD 0(R19), R22
	MOVD 8(R19), R21
	MOVD 16(R19), R20
	MOVD 24(R19), R23
	MOVD 40(R19), R24
	MOVD 56(R19), R26
	MOVD 88(R19), R25
	DISPATCH_NEXT()

// tier2Fallback is the default handler for non-Tier-1 opcodes.
// Un-advances pc and returns to Go with EXIT_TIER2.
TEXT ·tier2Fallback(SB), NOSPLIT, $0
	SUB  $1, R20, R20
	MOVD R20, 16(R19)
	MOVD $EXIT_TIER2, R0
	MOVD R0, 96(R19)
	MOVD R20, 104(R19)
	RET

// handlerCallExit exits to Go with EXIT_CALL for dedicated OpCall handling.
TEXT ·handlerCallExit(SB), NOSPLIT, $0
	SUB  $1, R20, R20
	MOVD R20, 16(R19)
	MOVD $EXIT_CALL, R0
	MOVD R0, 96(R19)
	MOVD R20, 104(R19)
	RET

// handlerReturnExit exits to Go with EXIT_RETURN for dedicated OpReturn handling.
TEXT ·handlerReturnExit(SB), NOSPLIT, $0
	SUB  $1, R20, R20
	MOVD R20, 16(R19)
	MOVD $EXIT_RETURN, R0
	MOVD R0, 96(R19)
	MOVD R20, 104(R19)
	RET

// handlerReturnVoidExit exits to Go with EXIT_RETURN_VOID for dedicated OpReturnVoid handling.
TEXT ·handlerReturnVoidExit(SB), NOSPLIT, $0
	SUB  $1, R20, R20
	MOVD R20, 16(R19)
	MOVD $EXIT_RETURN_VOID, R0
	MOVD R0, 96(R19)
	MOVD R20, 104(R19)
	RET

// handlerTailCallExit exits to Go with EXIT_TAIL_CALL for dedicated OpTailCall handling.
TEXT ·handlerTailCallExit(SB), NOSPLIT, $0
	SUB  $1, R20, R20
	MOVD R20, 16(R19)
	MOVD $EXIT_TAIL_CALL, R0
	MOVD R0, 96(R19)
	MOVD R20, 104(R19)
	RET
