// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// Inline call and return handlers.

// handlerCallInline handles OpCall with ASM-inlined fast path.
TEXT ·handlerCallInline(SB), NOSPLIT, $0
	MOVQ    DX, CX
	SHRQ    $16, CX

	MOVQ    CTX_ASM_CALL_INFO_BASE(R15), AX
	TESTQ   AX, AX
	JZ      ci_fallback
	SHLQ    $ACI_SIZE_SHIFT, CX
	LEAQ    (AX)(CX*1), AX

	CMPQ    ACI_IS_FAST_PATH(AX), $0
	JE      ci_fallback

	MOVQ    CTX_FRAME_POINTER(R15), SI
	LEAQ    1(SI), DI
	CMPQ    DI, CTX_DEPTH_LIMIT(R15)
	JGE     ci_overflow

	CMPQ    DI, CTX_CSTACK_LEN(R15)
	JGE     ci_fallback

	MOVQ    CTX_ARENA_INT_IDX(R15), BX
	ADDQ    ACI_CALLEE_NUM_INTS(AX), BX
	CMPQ    BX, CTX_ARENA_INT_CAP(R15)
	JG      ci_fallback

	MOVQ    CTX_ARENA_FLT_IDX(R15), BX
	ADDQ    ACI_CALLEE_NUM_FLOATS(AX), BX
	CMPQ    BX, CTX_ARENA_FLT_CAP(R15)
	JG      ci_fallback

	MOVQ    CTX_DISPATCH_SAVES(R15), BX
	MOVQ    SI, CX
	SHLQ    $5, CX
	LEAQ    (BX)(CX*1), BX
	MOVQ    R12, 0(BX)
	MOVQ    R13, 8(BX)
	MOVQ    R11, 16(BX)
	MOVQ    72(R15), CX
	MOVQ    CX, 24(BX)

	MOVQ    CTX_CSTACK_BASE(R15), BX
	MOVQ    $CALLFRAME_SIZE, CX
	IMULQ   SI, CX
	LEAQ    (BX)(CX*1), CX
	MOVQ    R14, CF_PROGRAM_COUNTER(CX)

	MOVQ    $CALLFRAME_SIZE, DX
	IMULQ   DI, DX
	LEAQ    (BX)(DX*1), BX

	MOVQ    DI, CTX_FRAME_POINTER(R15)

	MOVQ    CTX_ARENA_INT_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+0)(BX)
	MOVQ    CTX_ARENA_FLT_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+8)(BX)
	MOVQ    CTX_ARENA_STR_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+16)(BX)
	MOVQ    CTX_ARENA_GEN_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+24)(BX)
	MOVQ    CTX_ARENA_BOOL_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+32)(BX)
	MOVQ    CTX_ARENA_UINT_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+40)(BX)
	MOVQ    CTX_ARENA_CPLX_IDX(R15), CX
	MOVQ    CX, (CF_ARENA_SAVE+48)(BX)

	MOVQ    CTX_ARENA_INT_IDX(R15), CX
	MOVQ    CTX_ARENA_INT_SLAB(R15), DX
	LEAQ    (DX)(CX*8), DX
	MOVQ    ACI_CALLEE_NUM_INTS(AX), DI
	MOVQ    DX, 0(BX)
	MOVQ    DI, 8(BX)
	MOVQ    DI, 16(BX)
	ADDQ    DI, CX
	MOVQ    CX, CTX_ARENA_INT_IDX(R15)

	MOVQ    CTX_ARENA_FLT_IDX(R15), CX
	MOVQ    CTX_ARENA_FLT_SLAB(R15), DX
	LEAQ    (DX)(CX*8), DX
	MOVQ    ACI_CALLEE_NUM_FLOATS(AX), DI
	MOVQ    DX, 24(BX)
	MOVQ    DI, 32(BX)
	MOVQ    DI, 40(BX)
	ADDQ    DI, CX
	MOVQ    CX, CTX_ARENA_FLT_IDX(R15)

	CMPQ    ACI_IS_FAST_PATH(AX), $2
	JNE     ci_full_register_alloc

	XORQ    CX, CX
	MOVQ    CX, CF_REGS_STRINGS_PTR(BX)
	MOVQ    CX, (CF_REGS_STRINGS_PTR+8)(BX)
	MOVQ    CX, (CF_REGS_STRINGS_PTR+16)(BX)
	MOVQ    CX, 72(BX)
	MOVQ    CX, 80(BX)
	MOVQ    CX, 88(BX)
	MOVQ    CX, CF_REGS_BOOLS_PTR(BX)
	MOVQ    CX, (CF_REGS_BOOLS_PTR+8)(BX)
	MOVQ    CX, (CF_REGS_BOOLS_PTR+16)(BX)
	MOVQ    CX, CF_REGS_UINTS_PTR(BX)
	MOVQ    CX, (CF_REGS_UINTS_PTR+8)(BX)
	MOVQ    CX, (CF_REGS_UINTS_PTR+16)(BX)
	MOVQ    CX, 144(BX)
	MOVQ    CX, 152(BX)
	MOVQ    CX, 160(BX)
	JMP     ci_register_alloc_done

ci_full_register_alloc:
	MOVQ    ACI_CALLEE_NUM_STRINGS(AX), DI
	TESTQ   DI, DI
	JZ      ci_zero_strings
	MOVQ    CTX_ARENA_STR_IDX(R15), CX
	LEAQ    (CX)(DI*1), SI
	CMPQ    SI, CTX_ARENA_STR_CAP(R15)
	JG      ci_fallback
	MOVQ    CTX_ARENA_STR_SLAB(R15), DX
	SHLQ    $4, CX
	LEAQ    (DX)(CX*1), DX
	MOVQ    DX, CF_REGS_STRINGS_PTR(BX)
	MOVQ    DI, (CF_REGS_STRINGS_PTR+8)(BX)
	MOVQ    DI, (CF_REGS_STRINGS_PTR+16)(BX)
	MOVQ    SI, CTX_ARENA_STR_IDX(R15)
	JMP     ci_strings_done

ci_zero_strings:
	MOVQ    $0, CF_REGS_STRINGS_PTR(BX)
	MOVQ    $0, (CF_REGS_STRINGS_PTR+8)(BX)
	MOVQ    $0, (CF_REGS_STRINGS_PTR+16)(BX)

ci_strings_done:
	XORQ    CX, CX
	MOVQ    CX, 72(BX)
	MOVQ    CX, 80(BX)
	MOVQ    CX, 88(BX)

	MOVQ    ACI_CALLEE_NUM_BOOLS(AX), DI
	TESTQ   DI, DI
	JZ      ci_zero_bools
	MOVQ    CTX_ARENA_BOOL_IDX(R15), CX
	LEAQ    (CX)(DI*1), SI
	CMPQ    SI, CTX_ARENA_BOOL_CAP(R15)
	JG      ci_fallback
	MOVQ    CTX_ARENA_BOOL_SLAB(R15), DX
	LEAQ    (DX)(CX*1), DX
	MOVQ    DX, CF_REGS_BOOLS_PTR(BX)
	MOVQ    DI, (CF_REGS_BOOLS_PTR+8)(BX)
	MOVQ    DI, (CF_REGS_BOOLS_PTR+16)(BX)
	MOVQ    SI, CTX_ARENA_BOOL_IDX(R15)
	JMP     ci_bools_done

ci_zero_bools:
	MOVQ    $0, CF_REGS_BOOLS_PTR(BX)
	MOVQ    $0, (CF_REGS_BOOLS_PTR+8)(BX)
	MOVQ    $0, (CF_REGS_BOOLS_PTR+16)(BX)

ci_bools_done:
	MOVQ    ACI_CALLEE_NUM_UINTS(AX), DI
	TESTQ   DI, DI
	JZ      ci_zero_uints
	MOVQ    CTX_ARENA_UINT_IDX(R15), CX
	LEAQ    (CX)(DI*1), SI
	CMPQ    SI, CTX_ARENA_UINT_CAP(R15)
	JG      ci_fallback
	MOVQ    CTX_ARENA_UINT_SLAB(R15), DX
	LEAQ    (DX)(CX*8), DX
	MOVQ    DX, CF_REGS_UINTS_PTR(BX)
	MOVQ    DI, (CF_REGS_UINTS_PTR+8)(BX)
	MOVQ    DI, (CF_REGS_UINTS_PTR+16)(BX)
	MOVQ    SI, CTX_ARENA_UINT_IDX(R15)
	JMP     ci_uints_done

ci_zero_uints:
	MOVQ    $0, CF_REGS_UINTS_PTR(BX)
	MOVQ    $0, (CF_REGS_UINTS_PTR+8)(BX)
	MOVQ    $0, (CF_REGS_UINTS_PTR+16)(BX)

ci_uints_done:
	XORQ    CX, CX
	MOVQ    CX, 144(BX)
	MOVQ    CX, 152(BX)
	MOVQ    CX, 160(BX)

ci_register_alloc_done:
	MOVQ    CX, 176(BX)
	MOVQ    CX, 184(BX)
	MOVQ    CX, 192(BX)
	MOVQ    CX, 200(BX)
	MOVQ    CX, 232(BX)

	MOVQ    ACI_CALLEE_FUNCTION(AX), DX
	MOVQ    DX, CF_FUNCTION(BX)

	MOVQ    ACI_RET_DEST_PTR(AX), DX
	MOVQ    DX, CF_RETURNDEST_PTR(BX)
	MOVQ    ACI_RET_DEST_LEN(AX), DX
	MOVQ    DX, CF_RETURNDEST_LEN(BX)
	MOVQ    DX, CF_RETURNDEST_CAP(BX)

	MOVQ    CTX_DEFER_STACK_LEN(R15), DX
	MOVQ    DX, CF_DEFERBASE(BX)

	MOVQ    ACI_NUM_INT_ARGS(AX), CX
	TESTQ   CX, CX
	JZ      ci_no_int_args
	MOVQ    0(BX), DI
	XORQ    DX, DX

ci_int_loop:
	MOVQ    (ACI_INT_ARG_SRCS)(AX)(DX*8), SI
	MOVQ    (R8)(SI*8), SI
	MOVQ    SI, (DI)(DX*8)
	INCQ    DX
	CMPQ    DX, CX
	JL      ci_int_loop

ci_no_int_args:

	MOVQ    ACI_NUM_FLOAT_ARGS(AX), CX
	TESTQ   CX, CX
	JZ      ci_no_float_args
	MOVQ    24(BX), DI
	XORQ    DX, DX

ci_float_loop:
	MOVQ    (ACI_FLOAT_ARG_SRCS)(AX)(DX*8), SI
	MOVQ    (R9)(SI*8), SI
	MOVQ    SI, (DI)(DX*8)
	INCQ    DX
	CMPQ    DX, CX
	JL      ci_float_loop

ci_no_float_args:

	MOVQ    ACI_NUM_STRING_ARGS(AX), CX
	TESTQ   CX, CX
	JZ      ci_no_string_args
	MOVQ    CTX_STRINGS_BASE(R15), R14
	MOVQ    CF_REGS_STRINGS_PTR(BX), DI
	XORQ    DX, DX

ci_string_loop:
	MOVQ    (ACI_STRING_ARG_SRCS)(AX)(DX*8), SI
	SHLQ    $4, SI
	MOVQ    (R14)(SI*1), R13
	MOVQ    8(R14)(SI*1), SI
	MOVQ    DX, R12
	SHLQ    $4, R12
	MOVQ    R13, (DI)(R12*1)
	MOVQ    SI, 8(DI)(R12*1)
	INCQ    DX
	CMPQ    DX, CX
	JL      ci_string_loop

ci_no_string_args:

	MOVQ    ACI_NUM_BOOL_ARGS(AX), CX
	TESTQ   CX, CX
	JZ      ci_no_bool_args
	MOVQ    CTX_BOOLS_BASE(R15), R14
	MOVQ    CF_REGS_BOOLS_PTR(BX), DI
	XORQ    DX, DX

ci_bool_loop:
	MOVQ    (ACI_BOOL_ARG_SRCS)(AX)(DX*8), SI
	MOVBLZX (R14)(SI*1), SI
	MOVB    SI, (DI)(DX*1)
	INCQ    DX
	CMPQ    DX, CX
	JL      ci_bool_loop

ci_no_bool_args:

	MOVQ    ACI_NUM_UINT_ARGS(AX), CX
	TESTQ   CX, CX
	JZ      ci_no_uint_args
	MOVQ    CTX_UINTS_BASE(R15), R14
	MOVQ    CF_REGS_UINTS_PTR(BX), DI
	XORQ    DX, DX

ci_uint_loop:
	MOVQ    (ACI_UINT_ARG_SRCS)(AX)(DX*8), SI
	MOVQ    (R14)(SI*8), SI
	MOVQ    SI, (DI)(DX*8)
	INCQ    DX
	CMPQ    DX, CX
	JL      ci_uint_loop

ci_no_uint_args:

	MOVQ    CTX_ASM_CI_PTRS(R15), CX
	MOVQ    CTX_FRAME_POINTER(R15), DI
	MOVQ    ACI_CALLEE_CALL_INFO(AX), DX
	MOVQ    DX, (CX)(DI*8)
	MOVQ    DX, CTX_ASM_CALL_INFO_BASE(R15)

	MOVQ    ACI_CALLEE_BODY(AX), R12
	MOVQ    ACI_CALLEE_BODY_LEN(AX), R13
	MOVQ    ACI_CALLEE_INT_CONSTS(AX), R11
	XORQ    R14, R14
	MOVQ    0(BX), R8
	MOVQ    24(BX), R9

	MOVQ    R12, 0(R15)
	MOVQ    R13, 8(R15)
	MOVQ    R14, 16(R15)
	MOVQ    R8, 24(R15)
	MOVQ    R9, 40(R15)
	MOVQ    R11, 56(R15)
	MOVQ    ACI_CALLEE_FLT_CONSTS(AX), CX
	MOVQ    CX, 72(R15)
	MOVQ    CF_REGS_STRINGS_PTR(BX), CX
	MOVQ    CX, CTX_STRINGS_BASE(R15)
	MOVQ    CF_REGS_UINTS_PTR(BX), CX
	MOVQ    CX, CTX_UINTS_BASE(R15)
	MOVQ    CF_REGS_BOOLS_PTR(BX), CX
	MOVQ    CX, CTX_BOOLS_BASE(R15)
	DISPATCH_NEXT()

ci_fallback:
	DECQ    R14
	MOVQ    R14, 16(R15)
	MOVQ    $EXIT_CALL, 96(R15)
	MOVQ    R14, 104(R15)
	RET     

ci_overflow:
	DECQ    R14
	MOVQ    R14, 16(R15)
	MOVQ    $EXIT_CALL_OVERFLOW, 96(R15)
	MOVQ    R14, 104(R15)
	RET     

// handlerReturnInline handles OpReturn with ASM-inlined fast path.
TEXT ·handlerReturnInline(SB), NOSPLIT, $0
	MOVQ    CTX_FRAME_POINTER(R15), SI
	CMPQ    SI, CTX_BASE_FRAME_POINTER(R15)
	JLE     ri_fallback

	MOVQ    CTX_CSTACK_BASE(R15), BX
	MOVQ    $CALLFRAME_SIZE, CX
	MOVQ    SI, DI
	IMULQ   CX, DI
	LEAQ    (BX)(DI*1), DI

	MOVQ    CF_DEFERBASE(DI), CX
	CMPQ    CX, CTX_DEFER_STACK_LEN(R15)
	JNE     ri_fallback

	MOVL    DX, AX
	SHRL    $8, AX
	ANDL    $0xFF, AX

	LEAQ    -1(SI), R13
	MOVQ    $CALLFRAME_SIZE, CX
	MOVQ    R13, DX
	IMULQ   CX, DX
	LEAQ    (BX)(DX*1), R12

	TESTQ   AX, AX
	JZ      ri_no_retval
	CMPQ    AX, $1
	JNE     ri_fallback

	MOVQ    CF_RETURNDEST_PTR(DI), CX
	TESTQ   CX, CX
	JZ      ri_fallback

	MOVBLZX VL_IS_UPVALUE(CX), AX
	TESTQ   AX, AX
	JNZ     ri_fallback

	MOVBLZX VL_KIND(CX), AX
	MOVBLZX VL_REGISTER(CX), CX

	CMPQ    AX, $0
	JE      ri_check_int
	CMPQ    AX, $1
	JE      ri_check_float
	CMPQ    AX, $2
	JE      ri_check_string
	CMPQ    AX, $4
	JE      ri_check_bool
	CMPQ    AX, $5
	JE      ri_check_uint
	JMP     ri_fallback

ri_check_int:
	CMPQ    CF_REGS_INTS_LEN(DI), $0
	JE      ri_fallback

ri_copy_int:
	MOVQ    CF_REGS_INTS_PTR(DI), AX
	MOVQ    (AX), AX
	MOVQ    CF_REGS_INTS_PTR(R12), BX
	MOVQ    AX, (BX)(CX*8)
	JMP     ri_no_retval

ri_check_float:
	CMPQ    CF_REGS_FLOATS_LEN(DI), $0
	JE      ri_fallback

ri_copy_float:
	MOVQ    CF_REGS_FLOATS_PTR(DI), AX
	MOVQ    (AX), AX
	MOVQ    CF_REGS_FLOATS_PTR(R12), BX
	MOVQ    AX, (BX)(CX*8)
	JMP     ri_no_retval

ri_check_string:
	CMPQ    CF_REGS_STRINGS_LEN(DI), $0
	JE      ri_fallback
	MOVQ    CF_REGS_STRINGS_PTR(DI), AX
	MOVQ    (AX), SI
	MOVQ    8(AX), AX
	MOVQ    CF_REGS_STRINGS_PTR(R12), BX
	SHLQ    $4, CX
	MOVQ    SI, (BX)(CX*1)
	MOVQ    AX, 8(BX)(CX*1)
	JMP     ri_no_retval

ri_check_bool:
	CMPQ    CF_REGS_BOOLS_LEN(DI), $0
	JE      ri_fallback
	MOVQ    CF_REGS_BOOLS_PTR(DI), AX
	MOVBLZX (AX), AX
	MOVQ    CF_REGS_BOOLS_PTR(R12), BX
	MOVB    AX, (BX)(CX*1)
	JMP     ri_no_retval

ri_check_uint:
	CMPQ    CF_REGS_UINTS_LEN(DI), $0
	JE      ri_fallback
	MOVQ    CF_REGS_UINTS_PTR(DI), AX
	MOVQ    (AX), AX
	MOVQ    CF_REGS_UINTS_PTR(R12), BX
	MOVQ    AX, (BX)(CX*8)

ri_no_retval:
	MOVQ    CTX_ARENA_STR_IDX(R15), SI
	MOVQ    (CF_ARENA_SAVE+16)(DI), CX
	CMPQ    CX, SI
	JGE     ri_str_clear_done
	MOVQ    CTX_ARENA_STR_SLAB(R15), DX
	MOVQ    CX, AX
	SHLQ    $4, AX
	LEAQ    (DX)(AX*1), AX
	SHLQ    $4, SI
	LEAQ    (DX)(SI*1), SI

ri_str_clear_loop:
	MOVQ    $0, (AX)
	MOVQ    $0, 8(AX)
	ADDQ    $16, AX
	CMPQ    AX, SI
	JL      ri_str_clear_loop

ri_str_clear_done:
	MOVQ    (CF_ARENA_SAVE+0)(DI), AX
	MOVQ    AX, CTX_ARENA_INT_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+8)(DI), AX
	MOVQ    AX, CTX_ARENA_FLT_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+16)(DI), AX
	MOVQ    AX, CTX_ARENA_STR_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+32)(DI), AX
	MOVQ    AX, CTX_ARENA_BOOL_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+40)(DI), AX
	MOVQ    AX, CTX_ARENA_UINT_IDX(R15)

	MOVQ    R13, CTX_FRAME_POINTER(R15)

	MOVQ    CTX_ASM_CI_PTRS(R15), AX
	MOVQ    (AX)(R13*8), AX
	MOVQ    AX, CTX_ASM_CALL_INFO_BASE(R15)

	MOVQ    CF_PROGRAM_COUNTER(R12), R14
	MOVQ    CF_REGS_INTS_PTR(R12), R8
	MOVQ    CF_REGS_FLOATS_PTR(R12), R9

	MOVQ    CF_REGS_STRINGS_PTR(R12), AX
	MOVQ    AX, CTX_STRINGS_BASE(R15)
	MOVQ    CF_REGS_UINTS_PTR(R12), AX
	MOVQ    AX, CTX_UINTS_BASE(R15)
	MOVQ    CF_REGS_BOOLS_PTR(R12), AX
	MOVQ    AX, CTX_BOOLS_BASE(R15)

	MOVQ    CTX_DISPATCH_SAVES(R15), AX
	MOVQ    R13, CX
	SHLQ    $5, CX
	LEAQ    (AX)(CX*1), AX
	MOVQ    0(AX), R12
	MOVQ    8(AX), R13
	MOVQ    16(AX), R11
	MOVQ    24(AX), CX
	MOVQ    CX, 72(R15)

	MOVQ    R12, 0(R15)
	MOVQ    R13, 8(R15)
	MOVQ    R14, 16(R15)
	MOVQ    R8, 24(R15)
	MOVQ    R9, 40(R15)
	MOVQ    R11, 56(R15)
	DISPATCH_NEXT()

ri_fallback:
	DECQ    R14
	MOVQ    R14, 16(R15)
	MOVQ    $EXIT_RETURN, 96(R15)
	MOVQ    R14, 104(R15)
	RET     

// handlerReturnVoidInline handles OpReturnVoid with ASM-inlined fast path.
TEXT ·handlerReturnVoidInline(SB), NOSPLIT, $0
	MOVQ    CTX_FRAME_POINTER(R15), SI
	CMPQ    SI, CTX_BASE_FRAME_POINTER(R15)
	JLE     rvi_fallback

	MOVQ    CTX_CSTACK_BASE(R15), BX
	MOVQ    $CALLFRAME_SIZE, CX
	MOVQ    SI, DI
	IMULQ   CX, DI
	LEAQ    (BX)(DI*1), DI

	MOVQ    CF_DEFERBASE(DI), CX
	CMPQ    CX, CTX_DEFER_STACK_LEN(R15)
	JNE     rvi_fallback

	LEAQ    -1(SI), R13
	MOVQ    $CALLFRAME_SIZE, CX
	MOVQ    R13, DX
	IMULQ   CX, DX
	LEAQ    (BX)(DX*1), R12

	MOVQ    CTX_ARENA_STR_IDX(R15), SI
	MOVQ    (CF_ARENA_SAVE+16)(DI), CX
	CMPQ    CX, SI
	JGE     rvi_str_clear_done
	MOVQ    CTX_ARENA_STR_SLAB(R15), DX
	MOVQ    CX, AX
	SHLQ    $4, AX
	LEAQ    (DX)(AX*1), AX
	SHLQ    $4, SI
	LEAQ    (DX)(SI*1), SI

rvi_str_clear_loop:
	MOVQ    $0, (AX)
	MOVQ    $0, 8(AX)
	ADDQ    $16, AX
	CMPQ    AX, SI
	JL      rvi_str_clear_loop

rvi_str_clear_done:
	MOVQ    (CF_ARENA_SAVE+0)(DI), AX
	MOVQ    AX, CTX_ARENA_INT_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+8)(DI), AX
	MOVQ    AX, CTX_ARENA_FLT_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+16)(DI), AX
	MOVQ    AX, CTX_ARENA_STR_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+32)(DI), AX
	MOVQ    AX, CTX_ARENA_BOOL_IDX(R15)
	MOVQ    (CF_ARENA_SAVE+40)(DI), AX
	MOVQ    AX, CTX_ARENA_UINT_IDX(R15)

	MOVQ    R13, CTX_FRAME_POINTER(R15)

	MOVQ    CTX_ASM_CI_PTRS(R15), AX
	MOVQ    (AX)(R13*8), AX
	MOVQ    AX, CTX_ASM_CALL_INFO_BASE(R15)

	MOVQ    CF_PROGRAM_COUNTER(R12), R14
	MOVQ    CF_REGS_INTS_PTR(R12), R8
	MOVQ    CF_REGS_FLOATS_PTR(R12), R9

	MOVQ    CF_REGS_STRINGS_PTR(R12), AX
	MOVQ    AX, CTX_STRINGS_BASE(R15)
	MOVQ    CF_REGS_UINTS_PTR(R12), AX
	MOVQ    AX, CTX_UINTS_BASE(R15)
	MOVQ    CF_REGS_BOOLS_PTR(R12), AX
	MOVQ    AX, CTX_BOOLS_BASE(R15)

	MOVQ    CTX_DISPATCH_SAVES(R15), AX
	MOVQ    R13, CX
	SHLQ    $5, CX
	LEAQ    (AX)(CX*1), AX
	MOVQ    0(AX), R12
	MOVQ    8(AX), R13
	MOVQ    16(AX), R11
	MOVQ    24(AX), CX
	MOVQ    CX, 72(R15)

	MOVQ    R12, 0(R15)
	MOVQ    R13, 8(R15)
	MOVQ    R14, 16(R15)
	MOVQ    R8, 24(R15)
	MOVQ    R9, 40(R15)
	MOVQ    R11, 56(R15)
	DISPATCH_NEXT()

rvi_fallback:
	DECQ    R14
	MOVQ    R14, 16(R15)
	MOVQ    $EXIT_RETURN_VOID, 96(R15)
	MOVQ    R14, 104(R15)
	RET     
