// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// Data movement, arithmetic, and bitwise handlers.

// handlerNop does nothing.
TEXT ·handlerNop(SB), NOSPLIT, $0
	DISPATCH_NEXT()

// handlerMoveInt copies ints[B] to ints[A].
TEXT ·handlerMoveInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    (R8)(BX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerMoveFloat copies floats[B] to floats[A].
TEXT ·handlerMoveFloat(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVSD   (R9)(BX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerLoadIntConst loads intConstants[B|(C<<8)] into ints[A].
TEXT ·handlerLoadIntConst(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVWLZX BX, BX
	MOVQ    (R11)(BX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLoadFloatConst loads floatConstants[B|(C<<8)] into floats[A].
TEXT ·handlerLoadFloatConst(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVWLZX BX, BX
	MOVQ    72(R15), SI
	MOVSD   (SI)(BX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerLoadBool sets ints[A] = B (0 or 1).
TEXT ·handlerLoadBool(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    BX, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLoadIntConstSmall sets ints[A] = int64(B).
TEXT ·handlerLoadIntConstSmall(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    BX, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerAddInt sets ints[A] = ints[B] + ints[C].
TEXT ·handlerAddInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	ADDQ    (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerSubInt sets ints[A] = ints[B] - ints[C].
TEXT ·handlerSubInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	SUBQ    (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerMulInt sets ints[A] = ints[B] * ints[C].
TEXT ·handlerMulInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	IMULQ   (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerDivInt sets ints[A] = ints[B] / ints[C].
TEXT ·handlerDivInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    DX, SI
	MOVQ    AX, DI
	MOVQ    (R8)(CX*8), CX
	TESTQ   CX, CX
	JZ      dbz
	MOVQ    (R8)(BX*8), AX
	CQO     
	IDIVQ   CX
	MOVQ    AX, (R8)(DI*8)
	MOVQ    SI, DX
	DISPATCH_NEXT()

dbz:
	DIV_BY_ZERO_EXIT()

// handlerRemInt sets ints[A] = ints[B] % ints[C].
TEXT ·handlerRemInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    DX, SI
	MOVQ    AX, DI
	MOVQ    (R8)(CX*8), CX
	TESTQ   CX, CX
	JZ      dbz
	MOVQ    (R8)(BX*8), AX
	CQO     
	IDIVQ   CX
	MOVQ    DX, (R8)(DI*8)
	MOVQ    SI, DX
	DISPATCH_NEXT()

dbz:
	DIV_BY_ZERO_EXIT()

// handlerNegInt sets ints[A] = -ints[B].
TEXT ·handlerNegInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    (R8)(BX*8), SI
	NEGQ    SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerIncInt increments ints[A] by one.
TEXT ·handlerIncInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	INCQ    (R8)(AX*8)
	DISPATCH_NEXT()

// handlerDecInt decrements ints[A] by one.
TEXT ·handlerDecInt(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	DECQ    (R8)(AX*8)
	DISPATCH_NEXT()

// handlerBitAnd sets ints[A] = ints[B] & ints[C].
TEXT ·handlerBitAnd(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	ANDQ    (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerBitOr sets ints[A] = ints[B] | ints[C].
TEXT ·handlerBitOr(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	ORQ     (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerBitXor sets ints[A] = ints[B] ^ ints[C].
TEXT ·handlerBitXor(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	XORQ    (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerBitAndNot sets ints[A] = ints[B] &^ ints[C].
TEXT ·handlerBitAndNot(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(CX*8), SI
	NOTQ    SI
	ANDQ    (R8)(BX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerBitNot sets ints[A] = ^ints[B].
TEXT ·handlerBitNot(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    (R8)(BX*8), SI
	NOTQ    SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerShiftLeft sets ints[A] = ints[B] << uint(ints[C]).
TEXT ·handlerShiftLeft(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(CX*8), CX
	MOVQ    (R8)(BX*8), SI
	SHLQ    CL, SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerShiftRight sets ints[A] = ints[B] >> uint(ints[C]).
TEXT ·handlerShiftRight(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(CX*8), CX
	MOVQ    (R8)(BX*8), SI
	SARQ    CL, SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerAddFloat sets floats[A] = floats[B] + floats[C].
TEXT ·handlerAddFloat(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	ADDSD   (R9)(CX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubFloat sets floats[A] = floats[B] - floats[C].
TEXT ·handlerSubFloat(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	SUBSD   (R9)(CX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerMulFloat sets floats[A] = floats[B] * floats[C].
TEXT ·handlerMulFloat(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	MULSD   (R9)(CX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerDivFloat sets floats[A] = floats[B] / floats[C].
TEXT ·handlerDivFloat(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	DIVSD   (R9)(CX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerNegFloat sets floats[A] = -floats[B].
TEXT ·handlerNegFloat(SB), NOSPLIT, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVSD   (R9)(BX*8), X0
	MOVQ    $0x8000000000000000, SI
	MOVQ    SI, X1
	XORPD   X1, X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()
