// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSubOpRangeCheckUintJumpFalse jumps if uints[B] < ext1.a or uints[B] > ext1.b; offset packed in ext2.
TEXT ·handlerSubOpRangeCheckUintJumpFalse(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    CTX_UINTS_BASE(R15), SI
	MOVQ    (SI)(BX*8), AX
	MOVL    (R12)(R14*4), DX
	INCQ    R14
	MOVQ    DX, CX
	SHRQ    $8, CX
	MOVBLZX CL, CX
	SHRQ    $16, DX
	MOVBLZX DL, DI
	CMPQ    AX, CX
	JB      rangeCheckUintTakeJump
	CMPQ    AX, DI
	JA      rangeCheckUintTakeJump
	ADDQ    $6, R14
	JMP     rangeCheckUintDispatch
rangeCheckUintTakeJump:
	MOVL    (R12)(R14*4), DX
	INCQ    R14
	SHRQ    $8, DX
	MOVWLZX DX, AX
	MOVWQSX AX, AX
	ADDQ    $5, R14
	ADDQ    AX, R14
rangeCheckUintDispatch:
	DISPATCH_NEXT()
