// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerSubOpRangeCheckUintJumpFalse jumps if uints[B] < ext1.a or uints[B] > ext1.b; offset packed in ext2.
TEXT ·handlerSubOpRangeCheckUintJumpFalse(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD CTX_UINTS_BASE(R19), R4
	MOVD (R4)(R3<<3), R5
	MOVWU (R22)(R20<<2), R0
	ADD  $1, R20, R20
	LSR  $8, R0, R6
	AND  $0xFF, R6, R6
	LSR  $16, R0, R7
	AND  $0xFF, R7, R7
	CMP  R6, R5
	BLO  rangeCheckUintTakeJump
	CMP  R7, R5
	BHI  rangeCheckUintTakeJump
	ADD  $6, R20, R20
	B    rangeCheckUintDispatch
rangeCheckUintTakeJump:
	MOVWU (R22)(R20<<2), R8
	ADD  $1, R20, R20
	LSR  $8, R8, R8
	LSL  $48, R8, R8
	ASR  $48, R8, R8
	ADD  $5, R20, R20
	ADD  R8, R20, R20
rangeCheckUintDispatch:
	DISPATCH_NEXT()
