// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// dispatch_offsets.h: architecture-independent constants shared by both
// vm_dispatch_*_amd64.s and vm_dispatch_*_arm64.s.
//
// All offsets are verified at test time by vm_dispatch_offsets_test.go.

// DispatchContext field offsets (verified by TestDispatchContextOffsets):
//   codeBase      =   0    uintptr  pointer to Body[0]
//   codeLen       =   8    int64    number of instructions
//   pc            =  16    int64    current program counter
//   intsBase      =  24    uintptr  pointer to regs.Ints[0]
//   intsLen       =  32    int64    number of int registers
//   floatsBase    =  40    uintptr  pointer to regs.Floats[0]
//   floatsLen     =  48    int64    number of float registers
//   intConstsBase =  56    uintptr  pointer to IntConstants[0]
//   intConstsLen  =  64    int64    number of int constants
//   fltConstsBase =  72    uintptr  pointer to FloatConstants[0]
//   fltConstsLen  =  80    int64    number of float constants
//   jumpTable     =  88    uintptr  pointer to jump table[0]
//   exitReason    =  96    int64    exit reason code
//   exitPC        = 104    int64    PC at exit point

// Instruction encoding: {Op uint8, A uint8, B uint8, C uint8} = 4 bytes

// Exit reason constants:
#define EXIT_END_OF_CODE    0
#define EXIT_TIER2          1
#define EXIT_DIV_BY_ZERO    2
#define EXIT_CALL           3
#define EXIT_RETURN         4
#define EXIT_RETURN_VOID    5
#define EXIT_TAIL_CALL      6
#define EXIT_CALL_OVERFLOW  7

// callFrame size in bytes (verified by TestCallFrameOffsets).
//
// The 488-byte layout holds the scalar register banks plus six
// typed-slice header banks (Int, Float, String, Bool, Uint, Byte).
// Each typed-slice bank contributes a 24-byte slice header and an
// 8-byte arena save-point index.
#define CALLFRAME_SIZE 528

// callFrame field offsets:
#define CF_REGS_INTS_PTR         24
#define CF_REGS_INTS_LEN         32
#define CF_REGS_INTS_CAP         40
#define CF_REGS_FLOATS_PTR       48
#define CF_REGS_FLOATS_LEN       56
#define CF_REGS_FLOATS_CAP       64
#define CF_REGS_STRINGS_PTR      72
#define CF_REGS_STRINGS_LEN      80
#define CF_REGS_STRINGS_CAP      88
#define CF_REGS_GENERAL_PTR      96
#define CF_REGS_GENERAL_LEN      104
#define CF_REGS_GENERAL_CAP      112
#define CF_REGS_BOOLS_PTR        120
#define CF_REGS_BOOLS_LEN        128
#define CF_REGS_BOOLS_CAP        136
#define CF_REGS_UINTS_PTR        144
#define CF_REGS_UINTS_LEN        152
#define CF_REGS_UINTS_CAP        160
#define CF_REGS_COMPLEX_PTR      168
#define CF_REGS_COMPLEX_LEN      176
#define CF_REGS_COMPLEX_CAP      184
#define CF_REGS_SLICESINT_PTR    192
#define CF_REGS_SLICESINT_LEN    200
#define CF_REGS_SLICESINT_CAP    208
#define CF_REGS_SLICESFLOAT_PTR  216
#define CF_REGS_SLICESFLOAT_LEN  224
#define CF_REGS_SLICESFLOAT_CAP  232
#define CF_REGS_SLICESSTRING_PTR 240
#define CF_REGS_SLICESSTRING_LEN 248
#define CF_REGS_SLICESSTRING_CAP 256
#define CF_REGS_SLICESBOOL_PTR   264
#define CF_REGS_SLICESBOOL_LEN   272
#define CF_REGS_SLICESBOOL_CAP   280
#define CF_REGS_SLICESUINT_PTR   288
#define CF_REGS_SLICESUINT_LEN   296
#define CF_REGS_SLICESUINT_CAP   304
#define CF_REGS_SLICEBYTE_PTR    312
#define CF_REGS_SLICEBYTE_LEN    320
#define CF_REGS_SLICEBYTE_CAP    328
#define CF_FUNCTION              0
#define CF_SHARED_CELLS          8
#define CF_UPVALUES_PTR          336
#define CF_RETURNDEST_PTR        360
#define CF_RETURNDEST_LEN        368
#define CF_RETURNDEST_CAP        376
#define CF_PROGRAM_COUNTER       504
#define CF_DEFERBASE             512
#define CF_ARENA_SAVE            384
#define CF_HAS_GENERAL_ALLOC     520

// DispatchContext core field offsets (referenced by DISPATCH_NEXT and
// the per-handler dispatch fast paths):
#define CTX_CODE_BASE       8
#define CTX_CODE_LEN        16
#define CTX_PC              24
#define CTX_INTS_BASE       32
#define CTX_INTS_LEN        40
#define CTX_FLOATS_BASE     48
#define CTX_FLOATS_LEN      56
#define CTX_INT_CONSTS_BASE 64
#define CTX_INT_CONSTS_LEN  72
#define CTX_FLT_CONSTS_BASE 80
#define CTX_FLT_CONSTS_LEN  88
#define CTX_JUMP_TABLE      96
#define CTX_EXIT_REASON     104
#define CTX_EXIT_PC         112
// DispatchContext extended field offsets (inline call/return):
#define CTX_ASM_CALL_INFO_BASE 120
#define CTX_CSTACK_BASE        128
#define CTX_CSTACK_LEN         136
#define CTX_FRAME_POINTER      144
#define CTX_BASE_FRAME_POINTER 152
#define CTX_DEPTH_LIMIT        160
#define CTX_ARENA_INT_SLAB     168
#define CTX_ARENA_INT_CAP      176
#define CTX_ARENA_INT_IDX      184
#define CTX_ARENA_FLT_SLAB     192
#define CTX_ARENA_FLT_CAP      200
#define CTX_ARENA_FLT_IDX      208
#define CTX_ARENA_STR_IDX      216
#define CTX_ARENA_GEN_IDX      224
#define CTX_ARENA_BOOL_IDX     232
#define CTX_ARENA_UINT_IDX     240
#define CTX_ARENA_CPLX_IDX     248
#define CTX_DEFER_STACK_LEN    256
#define CTX_ASM_CI_PTRS        264
#define CTX_DISPATCH_SAVES     272
#define CTX_STRINGS_BASE       280
#define CTX_UINTS_BASE         288
#define CTX_BOOLS_BASE         296
#define CTX_ARENA_STR_SLAB     304
#define CTX_ARENA_STR_CAP      312
#define CTX_ARENA_BOOL_SLAB    320
#define CTX_ARENA_BOOL_CAP     328
#define CTX_ARENA_UINT_SLAB    336
#define CTX_ARENA_UINT_CAP     344
#define CTX_SLICES_INT_BASE    352
#define CTX_SLICES_FLOAT_BASE  360
#define CTX_SLICES_STRING_BASE 368
#define CTX_SLICES_BOOL_BASE   376
#define CTX_SLICES_UINT_BASE   384
#define CTX_COMPLEX_BASE       392
#define CTX_STR_CONSTS_BASE    400
#define CTX_STR_CONSTS_LEN     408
#define CTX_BOOL_CONSTS_BASE   416
#define CTX_BOOL_CONSTS_LEN    424
#define CTX_SAVED_PC           432
#define CTX_TIER2_RESULT       440

// Phase B: pinned table bases for struct-field ASM handlers.
// structLayoutTable holds compile-time-resolved {offset, kind, ...}
// per field-access site; ASM reads the entry at body[pc].c to
// compute the unsafe field pointer without a Go round-trip.
// typeTable holds reflect.Type slots used by tier-1 typed-nil and
// type-driven ops.
#define CTX_STRUCT_LAYOUT_TABLE_BASE 448
#define CTX_STRUCT_LAYOUT_TABLE_LEN  456
#define CTX_TYPE_TABLE_BASE          464
#define CTX_TYPE_TABLE_LEN           472

// Phase E: typed []byte register bank base.
// Each slot is a 24-byte slice header (ptr+len+cap). Used by
// tier-1 byte-slice ASM sub-ops for chunk[i] / chunk[s:e] /
// make([]byte) / range over []byte without leaving the loop.
#define CTX_SLICES_BYTE_BASE 480

// Phase J.3: typed []byte arena slab (24-byte slice headers).
// Read by the inline-call allocator to bump-allocate the callee's
// slicesByte register bank from the dispatch context.
#define CTX_ARENA_SLICEBYTE_SLAB 488
#define CTX_ARENA_SLICEBYTE_CAP  496
#define CTX_ARENA_SLICEBYTE_IDX  504
#define CTX_ARENA_SLICEINT_IDX   512
#define CTX_ARENA_SLICEFLT_IDX   520
#define CTX_ARENA_SLICESTR_IDX   528
#define CTX_ARENA_SLICEBOOL_IDX  536
#define CTX_ARENA_SLICEUINT_IDX  544

// structFieldLayout is 16 bytes. Verified by
// TestStructFieldLayoutSize. The shift exists so ASM can compute
// `&layoutTable[idx]` as `base + (idx << LAYOUT_SIZE_SHIFT)`.
#define LAYOUT_SIZE_SHIFT 4

// structFieldLayout field offsets (verified by
// TestStructFieldLayoutOffsets). Only the fields ASM reads are
// exposed; the Path[] / PathLength fields are safe-build-only and
// not addressed from ASM.
//
//   Offset         uint32 at +0   field byte offset within deref'd struct
//   TypeIndex      uint16 at +4   typeTable index of struct type (panic msgs)
//   Path[4]        4×uint8 at +6  reflect.Field index walk (safe build)
//   PathLength     uint8  at +10
//   Kind           uint8  at +11  reflect.Kind of leaf field
//   RegisterKind   uint8  at +12  registerKind of leaf field
//   Flags          uint8  at +13
//   FieldTypeIndex uint16 at +14  typeTable index of leaf type (registerGeneral)
#define OFF_LAYOUT_OFFSET           0
#define OFF_LAYOUT_TYPE_INDEX       4
#define OFF_LAYOUT_KIND             11
#define OFF_LAYOUT_REGISTER_KIND    12
#define OFF_LAYOUT_FLAGS            13
#define OFF_LAYOUT_FIELD_TYPE_INDEX 14

// reflect.Kind enum values (from $GOROOT/src/reflect/type.go).
// Pinned by TestReflectKindConstants. Stable across Go 1.x; Phase B
// ASM handlers compare layout.Kind against these to dispatch the
// typed read/write.
#define REFLECT_INVALID 0
#define REFLECT_BOOL    1
#define REFLECT_INT     2
#define REFLECT_INT8    3
#define REFLECT_INT16   4
#define REFLECT_INT32   5
#define REFLECT_INT64   6
#define REFLECT_UINT    7
#define REFLECT_UINT8   8
#define REFLECT_UINT16  9
#define REFLECT_UINT32  10
#define REFLECT_UINT64  11
#define REFLECT_UINTPTR 12
#define REFLECT_FLOAT32 13
#define REFLECT_FLOAT64 14
#define REFLECT_INTERFACE 20
#define REFLECT_POINTER 22

// reflect.Value flag word bits (from $GOROOT/src/reflect/value.go,
// mirrored in interp_domain/reflect_value_unsafe.go). Pinned by
// TestReflectValueFlagConstants. Phase B ASM handlers extract the
// receiver's Kind via flag & FLAG_KIND_MASK and check the
// FLAG_INDIR bit to decide whether ptr is *T (storage) or T itself.
#define FLAG_KIND_MASK 0x1F
#define FLAG_INDIR     0x80
#define FLAG_ADDR      0x100

// asmCallInfo field offsets (verified by TestASMCallInfoOffsets):
#define ACI_CALLEE_FUNCTION      0
#define ACI_CALLEE_BODY          8
#define ACI_CALLEE_BODY_LEN      16
#define ACI_CALLEE_INT_CONSTS    24
#define ACI_CALLEE_FLT_CONSTS    32
#define ACI_CALLEE_NUM_INTS      40
#define ACI_CALLEE_NUM_FLOATS    48
#define ACI_NUM_INT_ARGS         56
#define ACI_INT_ARG_SRCS         64
#define ACI_NUM_FLOAT_ARGS       128
#define ACI_FLOAT_ARG_SRCS       136
#define ACI_NUM_RETURNS          200
#define ACI_RET_DEST_KIND        208
#define ACI_RET_DEST_REG         216
#define ACI_RET_DEST_PTR         224
#define ACI_RET_DEST_LEN         232
#define ACI_CALLEE_CALL_INFO     240
#define ACI_IS_FAST_PATH         248
#define ACI_CALLEE_NUM_STRINGS   256
#define ACI_CALLEE_NUM_BOOLS     264
#define ACI_CALLEE_NUM_UINTS     272
#define ACI_NUM_STRING_ARGS      280
#define ACI_STRING_ARG_SRCS      288
#define ACI_NUM_BOOL_ARGS        352
#define ACI_BOOL_ARG_SRCS        360
#define ACI_NUM_UINT_ARGS        424
#define ACI_UINT_ARG_SRCS        432
#define ACI_CALLEE_STR_CONSTS    496
#define ACI_CALLEE_BOOL_CONSTS   504
#define ACI_CALLEE_NUM_GENERAL   512
#define ACI_NUM_GENERAL_ARGS     520
#define ACI_GENERAL_ARG_SRCS     528
#define ACI_CALLEE_NUM_SLICEBYTE 592
#define ACI_NUM_SLICEBYTE_ARGS   600
#define ACI_SLICEBYTE_ARG_SRCS   608

// sizeof(asmCallInfo) = 1024 (power of 2, use shift).
#define ACI_SIZE_SHIFT 10

// varLocation field offsets:
#define VL_UPVALUE_INDEX 16
#define VL_REGISTER      26
#define VL_KIND          27
#define VL_IS_UPVALUE    28
