//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}

func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	// line pages/main.pk:23:8
	if true {
		tempVar1.Children = append(tempVar1.Children, staticNode_1)
	}
	// line pages/main.pk:24:8
	if false {
		tempVar1.Children = append(tempVar1.Children, staticNode_2)
	}
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticNode_1         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_1_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_2         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 24
	staticNode_2_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 24
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "p"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "This should be visible."
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "p"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0.TextContent = "This should NOT be visible."
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_003_p_if_true/dist/pages/pages_main_594861c5", BuildAST)
}
