//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_card_bfc4a3cf

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}

// line partials/card.pk:34
type Props struct {
	Secret string `prop:"server.secret"`
	Config string `prop:"server.config"`
	User   string `prop:"server.user"`
}

// line partials/card.pk:40
func Render(r *piko.RequestData, props Props) (Props, piko.Metadata, error) {
	return props, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := Props{}
	if propsData != nil {
		p, ok := propsData.(Props)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/card.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(3)
	tempVar1.Children = tempVar2Slice
	// line partials/card.pk:23
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "p"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	// line partials/card.pk:23
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeText
	tempVar6 := arena.GetDirectWriter()
	tempVar6.AppendString("Secret (should be accessible as prop): ")
	tempVar6.AppendEscapeString(pageData.Secret)
	tempVar5.TextContentWriter = tempVar6
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	// line partials/card.pk:24
	tempVar7 := arena.GetNode()
	tempVar7.NodeType = pikoruntime.NodeElement
	tempVar7.TagName = "p"
	tempVar7.Attributes = staticAttrs_3
	_, tempVar8Slice := arena.GetChildSlice(1)
	tempVar7.Children = tempVar8Slice
	// line partials/card.pk:24
	tempVar9 := arena.GetNode()
	tempVar9.NodeType = pikoruntime.NodeText
	tempVar10 := arena.GetDirectWriter()
	tempVar10.AppendString("Config (should be accessible as prop): ")
	tempVar10.AppendEscapeString(pageData.Config)
	tempVar9.TextContentWriter = tempVar10
	tempVar7.Children = append(tempVar7.Children, tempVar9)
	tempVar1.Children = append(tempVar1.Children, tempVar7)
	// line partials/card.pk:25
	tempVar11 := arena.GetNode()
	tempVar11.NodeType = pikoruntime.NodeElement
	tempVar11.TagName = "p"
	tempVar11.Attributes = staticAttrs_4
	_, tempVar12Slice := arena.GetChildSlice(1)
	tempVar11.Children = tempVar12Slice
	// line partials/card.pk:25
	tempVar13 := arena.GetNode()
	tempVar13.NodeType = pikoruntime.NodeText
	tempVar14 := arena.GetDirectWriter()
	tempVar14.AppendString("User (should be accessible as prop): ")
	tempVar14.AppendEscapeString(pageData.User)
	tempVar13.TextContentWriter = tempVar14
	tempVar11.Children = append(tempVar11.Children, tempVar13)
	tempVar1.Children = append(tempVar1.Children, tempVar11)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 23
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 24
	staticAttrs_4 []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 25
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "info-card"}, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "card"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_069_server_prefixed_attribute_filtering/dist/partials/partials_card_bfc4a3cf", BuildAST)
}
