// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package apitest

import (
	"bytes"
	"context"
	"fmt"
	"maps"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
	"piko.sh/piko/internal/logger/logger_domain"
	"piko.sh/piko/wdk/safedisk"
)

// Surface represents the collection of public API members to be tested.
// The key is the simple, exported name of the member (e.g., "MyType"),
// and the value is the Go entity itself (e.g., MyType{}, MyFunc).
type Surface map[string]any

// Check runs a golden file test for a given API surface.
//
// It creates a YAML version of the API and compares it against a golden file.
// The test fails if they differ. If you pass the '-update' flag to 'go test',
// it updates the golden file with the new API output.
//
// Takes t (*testing.T) which is the testing context from your test function.
// Takes surface (Surface) which is the map that defines your public API.
// Takes goldenFile (string) which is the path to the golden file, usually
// relative to the test file's folder.
func Check(t *testing.T, surface Surface, goldenFile string) {
	t.Helper()

	yamlNode, err := generateAPISnapshotYAML(surface)
	require.NoError(t, err, "Failed to generate YAML API snapshot")

	var buffer bytes.Buffer
	encoder := yaml.NewEncoder(&buffer)
	encoder.SetIndent(2)
	err = encoder.Encode(yamlNode)
	require.NoError(t, err, "Failed to encode API snapshot to YAML")

	goldenDir := filepath.Dir(goldenFile)
	goldenName := filepath.Base(goldenFile)

	sandbox, err := safedisk.NewSandbox(goldenDir, safedisk.ModeReadWrite)
	require.NoError(t, err, "Failed to create sandbox for golden file directory")
	defer func() {
		if closeErr := sandbox.Close(); closeErr != nil {
			_, l := logger_domain.From(context.Background(), log)
			l.Warn("Failed to close sandbox", logger_domain.Error(closeErr), logger_domain.String("dir", goldenDir))
		}
	}()

	if *update {
		err = sandbox.WriteFile(goldenName, buffer.Bytes(), 0600)
		require.NoError(t, err, "Failed to write golden file")
		t.Logf("Golden file updated: %s", goldenFile)
	}

	expected, err := sandbox.ReadFile(goldenName)
	if safedisk.IsNotExist(err) {
		t.Fatalf("Golden file not found: %s. Run 'go test -update' to create it.", goldenFile)
	}
	require.NoError(t, err)

	require.Equal(t, string(expected), buffer.String(), "API surface has changed. Run 'go test -update' to accept the changes.")
}

// generateAPISnapshotYAML creates a YAML node tree that represents the API
// surface.
//
// Takes surface (Surface) which contains the API members to convert to YAML.
//
// Returns *yaml.Node which is the root of the YAML document tree.
// Returns error when the YAML creation fails.
func generateAPISnapshotYAML(surface Surface) (*yaml.Node, error) {
	keys := slices.Sorted(maps.Keys(surface))

	rootNode := &yaml.Node{
		Kind:        yaml.MappingNode,
		HeadComment: "Piko Public API Surface\n\nThis file is auto-generated by `go test -update`. DO NOT EDIT.\nIt is a snapshot of the public API to prevent unintentional breaking changes.",
	}

	for _, name := range keys {
		entity := surface[name]
		signature := generateSignature(name, entity)

		keyNode := &yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       name,
			LineComment: fmt.Sprintf("# Kind: %s", getEntityType(entity)),
		}

		valueNode := &yaml.Node{
			Kind:  yaml.ScalarNode,
			Value: signature,
		}
		if strings.Contains(signature, "\n") {
			valueNode.Style = yaml.LiteralStyle
		}

		rootNode.Content = append(rootNode.Content, keyNode, valueNode)
	}

	return rootNode, nil
}

// generateSignature creates a readable text form of an API member.
//
// It picks the right format based on the entity's reflect kind. Structs,
// interfaces, and functions each have their own style. For other kinds such
// as constants, variables, or type aliases, it returns the type string as is.
//
// Takes name (string) which identifies the API member being documented.
// Takes entity (any) which is the value to create a signature for.
//
// Returns string which is the formatted signature, or "nil" if entity is nil.
func generateSignature(name string, entity any) string {
	if entity == nil {
		return "nil"
	}

	typ := reflect.TypeOf(entity)

	ptrToType := typ
	if typ.Kind() != reflect.Pointer {
		ptrToType = reflect.PointerTo(typ)
	}

	if typ.Kind() == reflect.Pointer && typ.Elem().Kind() == reflect.Interface {
		typ = typ.Elem()
	}

	switch typ.Kind() {
	case reflect.Struct:
		return generateStructSignature(typ, ptrToType)
	case reflect.Interface:
		return generateInterfaceSignature(typ)
	case reflect.Func:
		return formatType(typ)
	default:
		return typ.String()
	}
}

// generateStructSignature builds a text view of a struct type, showing its
// exported fields and methods.
//
// Takes structType (reflect.Type) which is the struct type to describe.
// Takes ptrToStructType (reflect.Type) which is the pointer-to-struct type,
// used to find methods with pointer receivers.
//
// Returns string which is the formatted struct signature with exported fields
// and methods.
func generateStructSignature(structType, ptrToStructType reflect.Type) string {
	var builder strings.Builder
	builder.WriteString("struct {\n")

	exportedFieldCount := 0
	for field := range structType.Fields() {
		if field.IsExported() {
			exportedFieldCount++
			_, _ = fmt.Fprintf(&builder, "    // Field\n    %s %s\n", field.Name, formatType(field.Type))
		}
	}

	unexportedFieldCount := structType.NumField() - exportedFieldCount
	if unexportedFieldCount > 0 {
		if exportedFieldCount > 0 {
			builder.WriteString("\n")
		}
		_, _ = fmt.Fprintf(&builder, "    // (+%d unexported fields)\n", unexportedFieldCount)
	}

	wroteMethodSep := false
	for method := range ptrToStructType.Methods() {
		if method.IsExported() {
			if !wroteMethodSep && structType.NumField() > 0 {
				builder.WriteString("\n")
				wroteMethodSep = true
			}
			funcType := method.Type
			var parameters []string
			for j := 1; j < funcType.NumIn(); j++ {
				parameters = append(parameters, formatType(funcType.In(j)))
			}

			var results []string
			for out := range funcType.Outs() {
				results = append(results, formatType(out))
			}

			methodSignature := formatMethodSignature(parameters, results, funcType.IsVariadic())
			_, _ = fmt.Fprintf(&builder, "    // Method\n    %s%s\n", method.Name, methodSignature)
		}
	}

	builder.WriteString("}")
	return builder.String()
}

// generateInterfaceSignature creates a text form of an interface type for
// snapshot testing.
//
// Takes typ (reflect.Type) which is the interface type to format.
//
// Returns string which contains the interface definition with all its methods.
func generateInterfaceSignature(typ reflect.Type) string {
	var builder strings.Builder
	builder.WriteString("interface {\n")
	for method := range typ.Methods() {
		_, _ = fmt.Fprintf(&builder, "    %s%s\n", method.Name, formatFunction(method.Type))
	}
	builder.WriteString("}")
	return builder.String()
}

// formatType returns a formatted string for a reflect.Type.
//
// Takes typ (reflect.Type) which is the type to format.
//
// Returns string which is the formatted type name.
func formatType(typ reflect.Type) string {
	if typ == nil {
		return "nil"
	}
	if typ.Kind() == reflect.Func {
		return "func" + formatFunction(typ)
	}
	return typ.String()
}

// formatFunction formats a function type as a readable signature string.
//
// Takes typ (reflect.Type) which is the type to format.
//
// Returns string which is the formatted function signature, or the string
// form of the type if typ is not a function.
func formatFunction(typ reflect.Type) string {
	if typ.Kind() != reflect.Func {
		return typ.String()
	}

	var parameters []string
	for paramType := range typ.Ins() {
		parameters = append(parameters, formatType(paramType))
	}

	var results []string
	for out := range typ.Outs() {
		results = append(results, formatType(out))
	}

	return formatMethodSignature(parameters, results, typ.IsVariadic())
}

// formatMethodSignature builds the "(parameters) results" string for a method or
// function signature.
//
// Takes parameters ([]string) which contains the parameter type strings.
// Takes results ([]string) which contains the return type strings.
// Takes isVariadic (bool) which shows whether the last parameter uses variadic
// syntax.
//
// Returns string which is the formatted signature, such as "(int, string) error".
func formatMethodSignature(parameters, results []string, isVariadic bool) string {
	if isVariadic && len(parameters) > 0 {
		lastParam := &parameters[len(parameters)-1]
		*lastParam = "..." + strings.TrimPrefix(*lastParam, "[]")
	}

	paramString := strings.Join(parameters, ", ")
	resultString := strings.Join(results, ", ")

	if len(results) > 1 {
		resultString = fmt.Sprintf("(%s)", resultString)
	}

	if resultString == "" {
		return fmt.Sprintf("(%s)", paramString)
	}
	return fmt.Sprintf("(%s) %s", paramString, resultString)
}

// getEntityType returns a string that describes the kind of Go value.
//
// Takes entity (any) which is the value to check.
//
// Returns string which describes the kind, such as "Nil", "Interface", "Func",
// "Struct", "Var", or "Type".
func getEntityType(entity any) string {
	if entity == nil {
		return "Nil"
	}
	typ := reflect.TypeOf(entity)
	if typ.Kind() == reflect.Pointer && typ.Elem().Kind() == reflect.Interface {
		return "Interface"
	}

	switch typ.Kind() {
	case reflect.Func:
		return "Func"
	case reflect.Struct:
		return "Struct"
	case reflect.Interface:
		return "Interface"
	default:
		if reflect.ValueOf(entity).Kind() != reflect.TypeOf(entity).Kind() {
			return "Var"
		}
		return "Type"
	}
}
