//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_layout_ee037d9a "testcase_014_nested_partials/dist/partials/partials_layout_ee037d9a"
	partials_top_menu_a438e068 "testcase_014_nested_partials/dist/partials/partials_top_menu_a438e068"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}
var _ = partials_layout_ee037d9a.Render

// line pages/main.pk:36
func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_main_menu_page_layout_e3c2e26e_c62474ae := piko.NoProps{}
	partials_top_menu_a438e068Data_main_menu_page_layout_e3c2e26e_c62474ae, partials_top_menu_a438e068Meta_main_menu_page_layout_e3c2e26e_c62474ae, partials_top_menu_a438e068Err_main_menu_page_layout_e3c2e26e_c62474ae := partials_top_menu_a438e068.Render(r, props_main_menu_page_layout_e3c2e26e_c62474ae)
	if partials_top_menu_a438e068Err_main_menu_page_layout_e3c2e26e_c62474ae != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_top_menu_a438e068Err_main_menu_page_layout_e3c2e26e_c62474ae.Error(), "R002", "", "Partial Render() error for partials_top_menu_a438e068", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_top_menu_a438e068Data_main_menu_page_layout_e3c2e26e_c62474ae
	_ = partials_top_menu_a438e068Meta_main_menu_page_layout_e3c2e26e_c62474ae
	_ = partials_top_menu_a438e068Err_main_menu_page_layout_e3c2e26e_c62474ae
	props_page_layout_e3c2e26e := piko.NoProps{}
	partials_layout_ee037d9aData_page_layout_e3c2e26e, partials_layout_ee037d9aMeta_page_layout_e3c2e26e, partials_layout_ee037d9aErr_page_layout_e3c2e26e := partials_layout_ee037d9a.Render(r, props_page_layout_e3c2e26e)
	if partials_layout_ee037d9aErr_page_layout_e3c2e26e != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_layout_ee037d9aErr_page_layout_e3c2e26e.Error(), "R002", "", "Partial Render() error for partials_layout_ee037d9a", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_layout_ee037d9aData_page_layout_e3c2e26e
	_ = partials_layout_ee037d9aMeta_page_layout_e3c2e26e
	_ = partials_layout_ee037d9aErr_page_layout_e3c2e26e
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/layout.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	// line partials/layout.pk:23
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "header"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	// line partials/top_menu.pk:22
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "nav"
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetChildSlice(3)
	tempVar5.Children = tempVar6Slice
	tempVar5.Children = append(tempVar5.Children, staticNode_1)
	tempVar5.Children = append(tempVar5.Children, staticNode_2)
	tempVar5.Children = append(tempVar5.Children, staticNode_3)
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	tempVar1.Children = append(tempVar1.Children, staticNode_4)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1                []pikoruntime.HTMLAttribute // SOURCE: partials/layout.pk, LINE: 22
	staticAttrs_2                []pikoruntime.HTMLAttribute // SOURCE: partials/layout.pk, LINE: 23
	staticAttrs_3                []pikoruntime.HTMLAttribute // SOURCE: partials/top_menu.pk, LINE: 22
	staticNode_1                 *pikoruntime.TemplateNode   // SOURCE: partials/top_menu.pk, LINE: 23
	staticNode_1_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/top_menu.pk, LINE: 23
	staticNode_2                 *pikoruntime.TemplateNode   // SOURCE: partials/top_menu.pk, LINE: 24
	staticNode_2_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/top_menu.pk, LINE: 24
	staticNode_3                 *pikoruntime.TemplateNode   // SOURCE: partials/top_menu.pk, LINE: 25
	staticNode_3_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/top_menu.pk, LINE: 25
	staticNode_4                 *pikoruntime.TemplateNode   // SOURCE: partials/layout.pk, LINE: 26
	staticNode_4_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_4_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_4_child_1         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 24
	staticNode_4_child_1_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 24
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "layout"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "site-wrapper"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "site-header"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_top_menu_a438e068"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "top_menu"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "top-navigation"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "a"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_top_menu_a438e068"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0:0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "href", Value: "/"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Home"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "a"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_top_menu_a438e068"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0:1"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "href", Value: "/about"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0.TextContent = "About"
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "a"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_top_menu_a438e068"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0:2"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "href", Value: "/contact"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0.TextContent = "Contact"
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
	staticNode_4 = &pikoruntime.TemplateNode{}
	staticNode_4.NodeType = pikoruntime.NodeElement
	staticNode_4.TagName = "main"
	staticNode_4.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "content"})
	staticNode_4.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	staticNode_4_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0.NodeType = pikoruntime.NodeElement
	staticNode_4_child_0.TagName = "h1"
	staticNode_4_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5 partials_layout_ee037d9a"})
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"})
	staticNode_4_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_0_child_0.TextContent = "Welcome to the Nested Partials Test"
	staticNode_4_child_0.Children = append(staticNode_4_child_0.Children, staticNode_4_child_0_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_0)
	staticNode_4_child_1 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1.NodeType = pikoruntime.NodeElement
	staticNode_4_child_1.TagName = "p"
	staticNode_4_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5 partials_layout_ee037d9a"})
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"})
	staticNode_4_child_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_1_child_0.TextContent = "This content should appear inside the layout, after the top menu."
	staticNode_4_child_1.Children = append(staticNode_4_child_1.Children, staticNode_4_child_1_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_1)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_014_nested_partials/dist/pages/pages_main_594861c5", BuildAST)
}
