// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package typegen_adapters

import (
	_ "embed"

	"piko.sh/piko/internal/typegen/typegen_domain"
	"piko.sh/piko/internal/typegen/typegen_frontend"
)

// embeddedActionStubTypes contains the stub action type definitions embedded
// at build time from the piko-actions-stub.d.ts file.
//
//go:embed embedded/piko-actions-stub.d.ts
var embeddedActionStubTypes string

// NewTypeDefinitionService creates a new TypeDefinitionService with the
// embedded type definitions.
//
// This is the primary factory function for creating a TypeDefinitionService
// with:
//   - Piko framework types from typegen_frontend (generated by vite-plugin-dts)
//   - Action stub types from the embedded piko-actions-stub.d.ts
//
// Returns *typegen_domain.TypeDefinitionService which is ready for use.
func NewTypeDefinitionService() *typegen_domain.TypeDefinitionService {
	return typegen_domain.NewTypeDefinitionService(
		typegen_frontend.EmbeddedTypeDefinitions,
		embeddedActionStubTypes,
	)
}
