/* Code generated by piko; DO NOT EDIT. */

import { ActionBuilder, createActionBuilder, registerActionFunction } from '/_piko/dist/ppframework.core.es.js';
export interface IncrementInput {
}
export interface IncrementResponse {
  call_count: number;
}
/**
 * IncrementAction increments a counter.
 */
export function counterIncrement(input: IncrementInput): ActionBuilder<IncrementResponse> {
  return createActionBuilder<IncrementResponse>('counter.Increment', input);
}
export const action = {
  counter: {
    Increment: counterIncrement
  }
} as const;
registerActionFunction('counter.Increment', counterIncrement);
