// Code generated by Piko. DO NOT EDIT.

package db

var queryNameMap = map[string]string{cleanupoldresolvedreceipts: "Cleanupoldresolvedreceipts", timeoutstalereceipts: "Timeoutstalereceipts", listfailedtasks: "Listfailedtasks", createtaskwithdedup: "Createtaskwithdedup", updatetaskheartbeat: "Updatetaskheartbeat", getstaleprocessingtaskcount: "Getstaleprocessingtaskcount", listtaskstatuscounts: "Listtaskstatuscounts", listrecenttasks: "Listrecenttasks", listworkflowsummary: "Listworkflowsummary", recoverstaletasks: "Recoverstaletasks", claimstaletasksforrecovery: "Claimstaletasksforrecovery", recoverclaimedtasks: "Recoverclaimedtasks", releaserecoveryleases: "Releaserecoveryleases", getstaletasksforrecovery: "Getstaletasksforrecovery", claimtaskforrecovery: "Claimtaskforrecovery", promotescheduledtasks: "Promotescheduledtasks", pendingtaskcount: "Pendingtaskcount", createtask: "Createtask", updatetask: "Updatetask", fetchduetasks: "Fetchduetasks", createtasksbatch: "Createtasksbatch", marktasksasprocessing: "Marktasksasprocessing", createworkflowreceipt: "Createworkflowreceipt", resolveworkflowreceipts: "Resolveworkflowreceipts", getpendingreceiptsbynode: "Getpendingreceiptsbynode", getpendingreceiptsbyworkflow: "Getpendingreceiptsbyworkflow", getworkflowstatus: "Getworkflowstatus"}

func QueryNameResolver(query string) string {
	return queryNameMap[query]
}
