/* Code generated by piko; DO NOT EDIT. */

import { ActionBuilder, createActionBuilder, registerActionFunction } from '/_piko/dist/ppframework.core.es.js';
export interface MessageInput {
  text: string;
}
export interface MessageResponse {
  echo: string;
}
export function echoMessage(input: MessageInput): ActionBuilder<MessageResponse> {
  return createActionBuilder<MessageResponse>('echo.Message', input);
}
export const action = {
  echo: {
    Message: echoMessage
  }
} as const;
registerActionFunction('echo.Message', echoMessage);
