//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_item_actions_7438833b "testcase_085_p_for_with_nested_partials/dist/partials/partials_item_actions_7438833b"
	partials_item_card_e11b3960 "testcase_085_p_for_with_nested_partials/dist/partials/partials_item_card_e11b3960"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_item_card_e11b3960.Render

// line pages/main.pk:45
type Item struct {
	ID   string
	Name string
}

// line pages/main.pk:50
type Response struct{ Items []Item }

// line pages/main.pk:54
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Items: []Item{{ID: "1", Name: "First"}, {ID: "2", Name: "Second"}}}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	// line pages/main.pk:24
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "div"
	loopIter_1 := pageData.Items
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(len(loopIter_1))
	tempVar3.Children = tempVar4Slice
	// line partials/item_card.pk:26:9
	if loopIter_1 != nil {
		for _, item := range loopIter_1 {
			props_item_card_item_id_item_id_item_name_item_name_db0b718d := partials_item_card_e11b3960.Props{ItemID: item.ID, ItemName: item.Name}
			partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d, partials_item_card_e11b3960Meta_item_card_item_id_item_id_item_name_item_name_db0b718d, partials_item_card_e11b3960Err_item_card_item_id_item_id_item_name_item_name_db0b718d := partials_item_card_e11b3960.Render(r, props_item_card_item_id_item_id_item_name_item_name_db0b718d)
			if partials_item_card_e11b3960Err_item_card_item_id_item_id_item_name_item_name_db0b718d != nil {
				diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_item_card_e11b3960Err_item_card_item_id_item_id_item_name_item_name_db0b718d.Error(), "R002", "", "Partial Render() error for partials_item_card_e11b3960", 0, 0)
				return nil, pikoruntime.InternalMetadata{}, diagnostics
			}
			_ = partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d
			_ = partials_item_card_e11b3960Meta_item_card_item_id_item_id_item_name_item_name_db0b718d
			_ = partials_item_card_e11b3960Err_item_card_item_id_item_id_item_name_item_name_db0b718d
			props_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54 := partials_item_actions_7438833b.Props{ItemID: partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d.ItemID, ItemName: partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d.ItemName}
			partials_item_actions_7438833bData_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54, partials_item_actions_7438833bMeta_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54, partials_item_actions_7438833bErr_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54 := partials_item_actions_7438833b.Render(r, props_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54)
			if partials_item_actions_7438833bErr_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54 != nil {
				diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_item_actions_7438833bErr_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54.Error(), "R002", "", "Partial Render() error for partials_item_actions_7438833b", 0, 0)
				return nil, pikoruntime.InternalMetadata{}, diagnostics
			}
			_ = partials_item_actions_7438833bData_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54
			_ = partials_item_actions_7438833bMeta_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54
			_ = partials_item_actions_7438833bErr_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54
			// line partials/item_card.pk:22
			tempVar5 := arena.GetNode()
			tempVar5.NodeType = pikoruntime.NodeElement
			tempVar5.TagName = "div"
			_, tempVar6Slice := arena.GetAttrSlice(4)
			tempVar5.Attributes = tempVar6Slice
			_, tempVar7Slice := arena.GetAttrWriterSlice(3)
			tempVar5.AttributeWriters = tempVar7Slice
			_, tempVar8Slice := arena.GetChildSlice(2)
			tempVar5.Children = tempVar8Slice
			tempVar5.Attributes = append(tempVar5.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_item_card_e11b3960"})
			tempVar5.Attributes = append(tempVar5.Attributes, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "item_card"})
			tempVar9 := arena.GetDirectWriter()
			tempVar9.SetName("item_id")
			tempVar9.AppendEscapeString(item.ID)
			tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar9)
			tempVar10 := arena.GetDirectWriter()
			tempVar10.SetName("item_name")
			tempVar10.AppendEscapeString(item.Name)
			tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar10)
			tempVar5.Attributes = append(tempVar5.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
			tempVar11 := arena.GetDirectWriter()
			tempVar11.SetName("p-key")
			tempVar11.AppendString("r.0:1:0.")
			tempVar11.AppendFNVString(item.ID)
			tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar11)
			// line partials/item_card.pk:23
			tempVar12 := arena.GetNode()
			tempVar12.NodeType = pikoruntime.NodeElement
			tempVar12.TagName = "span"
			_, tempVar13Slice := arena.GetAttrSlice(2)
			tempVar12.Attributes = tempVar13Slice
			_, tempVar14Slice := arena.GetAttrWriterSlice(1)
			tempVar12.AttributeWriters = tempVar14Slice
			_, tempVar15Slice := arena.GetChildSlice(1)
			tempVar12.Children = tempVar15Slice
			tempVar12.Attributes = append(tempVar12.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_item_card_e11b3960"})
			tempVar12.Attributes = append(tempVar12.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-name"})
			tempVar16 := arena.GetDirectWriter()
			tempVar16.SetName("p-key")
			tempVar16.AppendString("r.0:1:0.")
			tempVar16.AppendFNVString(item.ID)
			tempVar16.AppendString(":0")
			tempVar12.AttributeWriters = append(tempVar12.AttributeWriters, tempVar16)
			// line partials/item_card.pk:23
			tempVar17 := arena.GetNode()
			tempVar17.NodeType = pikoruntime.NodeText
			tempVar18 := arena.GetDirectWriter()
			tempVar18.AppendEscapeString(partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d.ItemName)
			tempVar17.TextContentWriter = tempVar18
			tempVar12.Children = append(tempVar12.Children, tempVar17)
			tempVar5.Children = append(tempVar5.Children, tempVar12)
			// line partials/item_actions.pk:22
			tempVar19 := arena.GetNode()
			tempVar19.NodeType = pikoruntime.NodeElement
			tempVar19.TagName = "div"
			_, tempVar20Slice := arena.GetAttrSlice(4)
			tempVar19.Attributes = tempVar20Slice
			_, tempVar21Slice := arena.GetAttrWriterSlice(3)
			tempVar19.AttributeWriters = tempVar21Slice
			_, tempVar22Slice := arena.GetChildSlice(2)
			tempVar19.Children = tempVar22Slice
			tempVar19.Attributes = append(tempVar19.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_item_actions_7438833b"})
			tempVar19.Attributes = append(tempVar19.Attributes, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "item_actions"})
			tempVar23 := arena.GetDirectWriter()
			tempVar23.SetName("item_id")
			tempVar23.AppendEscapeString(partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d.ItemID)
			tempVar19.AttributeWriters = append(tempVar19.AttributeWriters, tempVar23)
			tempVar24 := arena.GetDirectWriter()
			tempVar24.SetName("item_name")
			tempVar24.AppendEscapeString(partials_item_card_e11b3960Data_item_card_item_id_item_id_item_name_item_name_db0b718d.ItemName)
			tempVar19.AttributeWriters = append(tempVar19.AttributeWriters, tempVar24)
			tempVar19.Attributes = append(tempVar19.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-actions"})
			tempVar25 := arena.GetDirectWriter()
			tempVar25.SetName("p-key")
			tempVar25.AppendString("r.0:1:0.")
			tempVar25.AppendFNVString(item.ID)
			tempVar25.AppendString(":1")
			tempVar19.AttributeWriters = append(tempVar19.AttributeWriters, tempVar25)
			// line partials/item_actions.pk:23
			tempVar26 := arena.GetNode()
			tempVar26.NodeType = pikoruntime.NodeElement
			tempVar26.TagName = "button"
			_, tempVar27Slice := arena.GetAttrSlice(1)
			tempVar26.Attributes = tempVar27Slice
			_, tempVar28Slice := arena.GetAttrWriterSlice(1)
			tempVar26.AttributeWriters = tempVar28Slice
			_, tempVar29Slice := arena.GetChildSlice(1)
			tempVar26.Children = tempVar29Slice
			tempVar26.Attributes = append(tempVar26.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_item_actions_7438833b"})
			tempVar30 := arena.GetDirectWriter()
			tempVar30.SetName("p-key")
			tempVar30.AppendString("r.0:1:0.")
			tempVar30.AppendFNVString(item.ID)
			tempVar30.AppendString(":1:0")
			tempVar26.AttributeWriters = append(tempVar26.AttributeWriters, tempVar30)
			// line partials/item_actions.pk:23
			tempVar31 := arena.GetNode()
			tempVar31.NodeType = pikoruntime.NodeText
			tempVar32 := arena.GetDirectWriter()
			tempVar32.AppendString("Edit ")
			tempVar32.AppendEscapeString(partials_item_actions_7438833bData_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54.ItemName)
			tempVar31.TextContentWriter = tempVar32
			tempVar26.Children = append(tempVar26.Children, tempVar31)
			tempVar19.Children = append(tempVar19.Children, tempVar26)
			// line partials/item_actions.pk:24
			tempVar33 := arena.GetNode()
			tempVar33.NodeType = pikoruntime.NodeElement
			tempVar33.TagName = "button"
			_, tempVar34Slice := arena.GetAttrSlice(1)
			tempVar33.Attributes = tempVar34Slice
			_, tempVar35Slice := arena.GetAttrWriterSlice(1)
			tempVar33.AttributeWriters = tempVar35Slice
			_, tempVar36Slice := arena.GetChildSlice(1)
			tempVar33.Children = tempVar36Slice
			tempVar33.Attributes = append(tempVar33.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_item_actions_7438833b"})
			tempVar37 := arena.GetDirectWriter()
			tempVar37.SetName("p-key")
			tempVar37.AppendString("r.0:1:0.")
			tempVar37.AppendFNVString(item.ID)
			tempVar37.AppendString(":1:1")
			tempVar33.AttributeWriters = append(tempVar33.AttributeWriters, tempVar37)
			// line partials/item_actions.pk:24
			tempVar38 := arena.GetNode()
			tempVar38.NodeType = pikoruntime.NodeText
			tempVar39 := arena.GetDirectWriter()
			tempVar39.AppendString("Delete ")
			tempVar39.AppendEscapeString(partials_item_actions_7438833bData_item_actions_item_card_item_id_item_id_item_name_item_name_db0b718d_item_id_state_itemid_item_name_state_itemname_88a9cc54.ItemID)
			tempVar38.TextContentWriter = tempVar39
			tempVar33.Children = append(tempVar33.Children, tempVar38)
			tempVar19.Children = append(tempVar19.Children, tempVar33)
			tempVar5.Children = append(tempVar5.Children, tempVar19)
			tempVar3.Children = append(tempVar3.Children, tempVar5)
		}
	}
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticAttrs_2        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 24
	staticNode_1         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_1_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "h1"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Items List"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "items"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_085_p_for_with_nested_partials/dist/pages/pages_main_594861c5", BuildAST)
}
