//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_empty_061d668f

import (
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = piko.Metadata{}

type Response struct {
	Items      []string
	ShowBanner bool
	Message    string
}

func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Items: []string{}, ShowBanner: false, Message: ""}, piko.Metadata{Title: "Edge Cases Test", Description: ""}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diags []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diags = pikoruntime.AppendDiagnostic(diags, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diags
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diags
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	/* SOURCE: pages/empty.pk, LINE: 44 */
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	/* SOURCE: pages/empty.pk, LINE: 45 */
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "header"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	/* SOURCE: pages/empty.pk, LINE: 46 */
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "h1"
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetChildSlice(1)
	tempVar5.Children = tempVar6Slice
	/* SOURCE: pages/empty.pk, LINE: 46 */
	tempVar7 := arena.GetNode()
	tempVar7.NodeType = pikoruntime.NodeText
	tempVar7.TextContent = "Edge Cases"
	tempVar5.Children = append(tempVar5.Children, tempVar7)
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	/* SOURCE: pages/empty.pk, LINE: 48 */
	tempVar8 := arena.GetNode()
	tempVar8.NodeType = pikoruntime.NodeElement
	tempVar8.TagName = "main"
	tempVar8.Attributes = staticAttrs_4
	_, tempVar9Slice := arena.GetChildSlice(4)
	tempVar8.Children = tempVar9Slice
	/* SOURCE: pages/empty.pk, LINE: 49 */
	tempVar10 := arena.GetNode()
	tempVar10.NodeType = pikoruntime.NodeElement
	tempVar10.TagName = "section"
	tempVar10.Attributes = staticAttrs_5
	_, tempVar11Slice := arena.GetChildSlice(1)
	tempVar10.Children = tempVar11Slice
	if pageData.ShowBanner {
		tempVar10.Children = append(tempVar10.Children, staticNode_1)
	}
	tempVar8.Children = append(tempVar8.Children, tempVar10)
	/* SOURCE: pages/empty.pk, LINE: 54 */
	tempVar12 := arena.GetNode()
	tempVar12.NodeType = pikoruntime.NodeElement
	tempVar12.TagName = "section"
	tempVar12.Attributes = staticAttrs_6
	_, tempVar13Slice := arena.GetChildSlice(3)
	tempVar12.Children = tempVar13Slice
	/* SOURCE: pages/empty.pk, LINE: 55 */
	tempVar14 := arena.GetNode()
	tempVar14.NodeType = pikoruntime.NodeElement
	tempVar14.TagName = "h2"
	tempVar14.Attributes = staticAttrs_7
	_, tempVar15Slice := arena.GetChildSlice(1)
	tempVar14.Children = tempVar15Slice
	/* SOURCE: pages/empty.pk, LINE: 55 */
	tempVar16 := arena.GetNode()
	tempVar16.NodeType = pikoruntime.NodeText
	tempVar16.TextContent = "Items"
	tempVar14.Children = append(tempVar14.Children, tempVar16)
	tempVar12.Children = append(tempVar12.Children, tempVar14)
	/* SOURCE: pages/empty.pk, LINE: 56 */
	tempVar17 := arena.GetNode()
	tempVar17.NodeType = pikoruntime.NodeElement
	tempVar17.TagName = "ul"
	loopIter_1 := pageData.Items
	tempVar17.Attributes = staticAttrs_8
	_, tempVar18Slice := arena.GetChildSlice(len(loopIter_1))
	tempVar17.Children = tempVar18Slice
	if loopIter_1 != nil {
		for __pikoLoopIdx, item := range loopIter_1 {
			/* SOURCE: pages/empty.pk, LINE: 57 */
			tempVar19 := arena.GetNode()
			tempVar19.NodeType = pikoruntime.NodeElement
			tempVar19.TagName = "li"
			_, tempVar20Slice := arena.GetAttrSlice(2)
			tempVar19.Attributes = tempVar20Slice
			_, tempVar21Slice := arena.GetAttrWriterSlice(1)
			tempVar19.AttributeWriters = tempVar21Slice
			_, tempVar22Slice := arena.GetChildSlice(1)
			tempVar19.Children = tempVar22Slice
			tempVar19.Attributes = append(tempVar19.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"})
			tempVar19.Attributes = append(tempVar19.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item"})
			tempVar23 := arena.GetDirectWriter()
			tempVar23.SetName("p-key")
			tempVar23.AppendString("r.0:1:1:1:0.")
			tempVar23.AppendFNVString(pikoruntime.ValueToString(__pikoLoopIdx))
			tempVar19.AttributeWriters = append(tempVar19.AttributeWriters, tempVar23)
			/* SOURCE: pages/empty.pk, LINE: 57 */
			tempVar24 := arena.GetNode()
			tempVar24.NodeType = pikoruntime.NodeText
			tempVar25 := arena.GetDirectWriter()
			tempVar25.AppendEscapeString(item)
			tempVar24.TextContentWriter = tempVar25
			tempVar19.Children = append(tempVar19.Children, tempVar24)
			tempVar17.Children = append(tempVar17.Children, tempVar19)
		}
	}
	tempVar12.Children = append(tempVar12.Children, tempVar17)
	if int64(len(pageData.Items)) == 0 {
		tempVar12.Children = append(tempVar12.Children, staticNode_2)
	}
	tempVar8.Children = append(tempVar8.Children, tempVar12)
	/* SOURCE: pages/empty.pk, LINE: 61 */
	tempVar26 := arena.GetNode()
	tempVar26.NodeType = pikoruntime.NodeElement
	tempVar26.TagName = "section"
	tempVar26.Attributes = staticAttrs_9
	_, tempVar27Slice := arena.GetChildSlice(2)
	tempVar26.Children = tempVar27Slice
	if pageData.Message != "" {
		/* SOURCE: pages/empty.pk, LINE: 62 */
		tempVar28 := arena.GetNode()
		tempVar28.NodeType = pikoruntime.NodeElement
		tempVar28.TagName = "p"
		tempVar28.Attributes = staticAttrs_10
		_, tempVar29Slice := arena.GetChildSlice(1)
		tempVar28.Children = tempVar29Slice
		/* SOURCE: pages/empty.pk, LINE: 62 */
		tempVar30 := arena.GetNode()
		tempVar30.NodeType = pikoruntime.NodeText
		tempVar31 := arena.GetDirectWriter()
		tempVar31.AppendEscapeString(pageData.Message)
		tempVar30.TextContentWriter = tempVar31
		tempVar28.Children = append(tempVar28.Children, tempVar30)
		tempVar26.Children = append(tempVar26.Children, tempVar28)
	}
	if pageData.Message == "" {
		tempVar26.Children = append(tempVar26.Children, staticNode_3)
	}
	tempVar8.Children = append(tempVar8.Children, tempVar26)
	/* SOURCE: pages/empty.pk, LINE: 65 */
	tempVar32 := arena.GetNode()
	tempVar32.NodeType = pikoruntime.NodeElement
	tempVar32.TagName = "footer"
	tempVar32.Attributes = staticAttrs_11
	_, tempVar33Slice := arena.GetChildSlice(1)
	tempVar32.Children = tempVar33Slice
	/* SOURCE: pages/empty.pk, LINE: 66 */
	tempVar34 := arena.GetNode()
	tempVar34.NodeType = pikoruntime.NodeElement
	tempVar34.TagName = "span"
	tempVar34.Attributes = staticAttrs_12
	_, tempVar35Slice := arena.GetChildSlice(1)
	tempVar34.Children = tempVar35Slice
	/* SOURCE: pages/empty.pk, LINE: 66 */
	tempVar36 := arena.GetNode()
	tempVar36.NodeType = pikoruntime.NodeText
	tempVar36.TextContent = "Only one of these"
	tempVar34.Children = append(tempVar34.Children, tempVar36)
	tempVar32.Children = append(tempVar32.Children, tempVar34)
	tempVar8.Children = append(tempVar8.Children, tempVar32)
	tempVar1.Children = append(tempVar1.Children, tempVar8)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diags
}

var (
	staticAttrs_1                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 44
	staticAttrs_10               []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 62
	staticAttrs_11               []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 65
	staticAttrs_12               []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 66
	staticAttrs_2                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 45
	staticAttrs_3                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 46
	staticAttrs_4                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 48
	staticAttrs_5                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 49
	staticAttrs_6                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 54
	staticAttrs_7                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 55
	staticAttrs_8                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 56
	staticAttrs_9                []pikoruntime.HTMLAttribute // SOURCE: pages/empty.pk, LINE: 61
	staticNode_1                 *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 50
	staticNode_1_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 51
	staticNode_1_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 51
	staticNode_2                 *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 59
	staticNode_2_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 59
	staticNode_3                 *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 63
	staticNode_3_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/empty.pk, LINE: 63
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page"}, pikoruntime.HTMLAttribute{Name: "id", Value: "edge-case-page"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page-header"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page-content"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "banner-section"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "div"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "banner"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0.TagName = "p"
	staticNode_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0:0"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "banner-text"})
	staticNode_1_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0_child_0.TextContent = "Banner Content"
	staticNode_1_child_0.Children = append(staticNode_1_child_0.Children, staticNode_1_child_0_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_6 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "list-section"}}
	staticAttrs_7 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:0"}}
	staticAttrs_8 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "item-list"}}
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "p"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:2"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "empty-message"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0.TextContent = "No items to display"
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticAttrs_9 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2"}, pikoruntime.HTMLAttribute{Name: "class", Value: "message-section"}}
	staticAttrs_10 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "message"}}
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "p"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2:1"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-message"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0.TextContent = "No message provided"
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
	staticAttrs_11 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:3"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page-footer"}}
	staticAttrs_12 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_empty_061d668f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:3:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "single-element"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_12_edge_cases/pages/pages_empty_061d668f", BuildAST)
}
