//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_layout_ee037d9a

import (
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}

// line partials/layout.pk:42
type Response struct{ Info string }

// line partials/layout.pk:46
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Info: "Layout"}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	rootAST.RootNodes = append(rootAST.RootNodes, staticNode_1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticNode_1                         *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 22
	staticNode_1_child_0                 *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 23
	staticNode_1_child_0_child_0         *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 24
	staticNode_1_child_0_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 24
	staticNode_1_child_1                 *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 26
	staticNode_1_child_1_child_0         *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 27
	staticNode_1_child_2                 *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 29
	staticNode_1_child_2_child_0         *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 30
	staticNode_1_child_2_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: partials/layout.pk, LINE: 30
)

func init() {
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "div"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 4)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "layout-container"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "layout"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 3)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0.TagName = "header"
	staticNode_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "layout-header"})
	staticNode_1_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0_child_0.TagName = "span"
	staticNode_1_child_0_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_0_child_0.Attributes = append(staticNode_1_child_0_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1_child_0_child_0.Attributes = append(staticNode_1_child_0_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"})
	staticNode_1_child_0_child_0.Attributes = append(staticNode_1_child_0_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "title"})
	staticNode_1_child_0_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0_child_0_child_0.TextContent = "Site Header"
	staticNode_1_child_0_child_0.Children = append(staticNode_1_child_0_child_0.Children, staticNode_1_child_0_child_0_child_0)
	staticNode_1_child_0.Children = append(staticNode_1_child_0.Children, staticNode_1_child_0_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticNode_1_child_1 = &pikoruntime.TemplateNode{}
	staticNode_1_child_1.NodeType = pikoruntime.NodeElement
	staticNode_1_child_1.TagName = "main"
	staticNode_1_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_1.Attributes = append(staticNode_1_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1_child_1.Attributes = append(staticNode_1_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	staticNode_1_child_1.Attributes = append(staticNode_1_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "layout-main"})
	staticNode_1_child_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_1_child_0.TagName = "piko:slot"
	staticNode_1_child_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1_child_1_child_0.Attributes = append(staticNode_1_child_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1_child_1_child_0.Attributes = append(staticNode_1_child_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"})
	staticNode_1_child_1.Children = append(staticNode_1_child_1.Children, staticNode_1_child_1_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_1)
	staticNode_1_child_2 = &pikoruntime.TemplateNode{}
	staticNode_1_child_2.NodeType = pikoruntime.NodeElement
	staticNode_1_child_2.TagName = "footer"
	staticNode_1_child_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_2.Attributes = append(staticNode_1_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1_child_2.Attributes = append(staticNode_1_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"})
	staticNode_1_child_2.Attributes = append(staticNode_1_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "layout-footer"})
	staticNode_1_child_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_2_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_2_child_0.TagName = "span"
	staticNode_1_child_2_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_2_child_0.Attributes = append(staticNode_1_child_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_layout_ee037d9a"})
	staticNode_1_child_2_child_0.Attributes = append(staticNode_1_child_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0"})
	staticNode_1_child_2_child_0.Attributes = append(staticNode_1_child_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "title"})
	staticNode_1_child_2_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_2_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_2_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_2_child_0_child_0.TextContent = "Site Footer"
	staticNode_1_child_2_child_0.Children = append(staticNode_1_child_2_child_0.Children, staticNode_1_child_2_child_0_child_0)
	staticNode_1_child_2.Children = append(staticNode_1_child_2.Children, staticNode_1_child_2_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_2)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_091_slotted_content_scoping/dist/partials/partials_layout_ee037d9a", BuildAST)
}
