//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_browser_4016e9df

import (
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}

// line partials/browser.pk:71
type Props struct {
	ShowItems bool `prop:"show_items"`
}

// line partials/browser.pk:75
func Render(r *piko.RequestData, props Props) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := Props{}
	if propsData != nil {
		p, ok := propsData.(Props)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/browser.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(3)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	// line partials/browser.pk:27:10
	if !props.ShowItems {
		tempVar1.Children = append(tempVar1.Children, staticNode_2)
	}
	// line partials/browser.pk:31:10
	if props.ShowItems {
		tempVar1.Children = append(tempVar1.Children, staticNode_3)
	}
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1                []pikoruntime.HTMLAttribute // SOURCE: partials/browser.pk, LINE: 22
	staticNode_1                 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 23
	staticNode_1_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 24
	staticNode_1_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 24
	staticNode_2                 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 27
	staticNode_2_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 28
	staticNode_2_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 28
	staticNode_3                 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 31
	staticNode_3_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 32
	staticNode_3_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 32
	staticNode_3_child_1         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 33
	staticNode_3_child_1_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 33
	staticNode_3_child_2         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 34
	staticNode_3_child_2_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 34
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "browser-container"}, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "browser"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "header"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "browser-header"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0.TagName = "h2"
	staticNode_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"})
	staticNode_1_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0_child_0.TextContent = "Items Browser"
	staticNode_1_child_0.Children = append(staticNode_1_child_0.Children, staticNode_1_child_0_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "div"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-results"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeElement
	staticNode_2_child_0.TagName = "p"
	staticNode_2_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"})
	staticNode_2_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0_child_0.TextContent = "No items found."
	staticNode_2_child_0.Children = append(staticNode_2_child_0.Children, staticNode_2_child_0_child_0)
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "div"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "items-grid"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 3)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeElement
	staticNode_3_child_0.TagName = "div"
	staticNode_3_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0"})
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
	staticNode_3_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0_child_0.TextContent = "Item 1"
	staticNode_3_child_0.Children = append(staticNode_3_child_0.Children, staticNode_3_child_0_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
	staticNode_3_child_1 = &pikoruntime.TemplateNode{}
	staticNode_3_child_1.NodeType = pikoruntime.NodeElement
	staticNode_3_child_1.TagName = "div"
	staticNode_3_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3_child_1.Attributes = append(staticNode_3_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_3_child_1.Attributes = append(staticNode_3_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:1"})
	staticNode_3_child_1.Attributes = append(staticNode_3_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
	staticNode_3_child_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_1_child_0.TextContent = "Item 2"
	staticNode_3_child_1.Children = append(staticNode_3_child_1.Children, staticNode_3_child_1_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_1)
	staticNode_3_child_2 = &pikoruntime.TemplateNode{}
	staticNode_3_child_2.NodeType = pikoruntime.NodeElement
	staticNode_3_child_2.TagName = "div"
	staticNode_3_child_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3_child_2.Attributes = append(staticNode_3_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_3_child_2.Attributes = append(staticNode_3_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:2"})
	staticNode_3_child_2.Attributes = append(staticNode_3_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
	staticNode_3_child_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_2_child_0.TextContent = "Item 3"
	staticNode_3_child_2.Children = append(staticNode_3_child_2.Children, staticNode_3_child_2_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_2)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_107_p_if_css_scoping_in_partial/dist/partials/partials_browser_4016e9df", BuildAST)
}
