// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

/* Code generated by piko; DO NOT EDIT. */

package pages_article_1466cebc

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html"
	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"sort"
	"strconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = json.Compact
var _ = base64.StdEncoding
var _ = pikoruntime.EvaluateTruthiness
var _ = piko.Metadata{}

type Response struct {
	ArticleTitle  string
	ArticleAuthor string
	PublishedDate string
	Content       string
}

func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	articleID := r.URL.Query().Get("id")
	title := "Default Article"
	author := "Unknown Author"
	date := "2024-01-01"
	content := "This is the default article content."
	if articleID == "featured" {
		title = "Featured: Building Web Apps with Piko"
		author = "Jane Developer"
		date = "2024-06-15"
		content = "Learn how to build modern web applications using the Piko framework."
	} else if articleID == "tutorial" {
		title = "Tutorial: Getting Started"
		author = "John Coder"
		date = "2024-05-20"
		content = "A comprehensive guide to getting started with Piko."
	}
	return Response{ArticleTitle: title, ArticleAuthor: author, PublishedDate: date, Content: content}, piko.Metadata{Title: title, Description: "Article: " + title}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}
func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diags []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diags = pikoruntime.AppendDiagnostic(diags, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diags
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: []string{}}, diags
	}
	rootAST := &pikoruntime.TemplateAST{}
	rootAST.RootNodes = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar1 := pikoruntime.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "article"
	tempVar1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar1.Children = make([]*pikoruntime.TemplateNode, 0, 3)
	tempVar1.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar1.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar1.Attributes = append(tempVar1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "article-page"})
	tempVar1.Attributes = append(tempVar1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"})
	tempVar2 := pikoruntime.GetNode()
	tempVar2.NodeType = pikoruntime.NodeElement
	tempVar2.TagName = "header"
	tempVar2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar2.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	tempVar2.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar2.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar2.Attributes = append(tempVar2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "article-header"})
	tempVar2.Attributes = append(tempVar2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	tempVar3 := pikoruntime.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "h1"
	tempVar3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar3.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar3.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar3.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "article-title"})
	tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"})
	tempVar4 := pikoruntime.GetNode()
	tempVar4.NodeType = pikoruntime.NodeText
	tempVar4.TextContent = html.EscapeString(pageData.ArticleTitle)
	tempVar3.Children = append(tempVar3.Children, tempVar4)
	tempVar2.Children = append(tempVar2.Children, tempVar3)
	tempVar5 := pikoruntime.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "div"
	tempVar5.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar5.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	tempVar5.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar5.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar5.Attributes = append(tempVar5.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "article-meta"})
	tempVar5.Attributes = append(tempVar5.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1"})
	tempVar6 := pikoruntime.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "span"
	tempVar6.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar6.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	tempVar6.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar6.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar6.Attributes = append(tempVar6.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "author"})
	tempVar6.Attributes = append(tempVar6.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1:0"})
	tempVar6.Children = append(tempVar6.Children, staticNode_1)
	tempVar7 := pikoruntime.GetNode()
	tempVar7.NodeType = pikoruntime.NodeElement
	tempVar7.TagName = "span"
	tempVar7.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar7.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar7.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar7.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar7.Attributes = append(tempVar7.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "author-name"})
	tempVar7.Attributes = append(tempVar7.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1:0:1"})
	tempVar8 := pikoruntime.GetNode()
	tempVar8.NodeType = pikoruntime.NodeText
	tempVar8.TextContent = html.EscapeString(pageData.ArticleAuthor)
	tempVar7.Children = append(tempVar7.Children, tempVar8)
	tempVar6.Children = append(tempVar6.Children, tempVar7)
	tempVar5.Children = append(tempVar5.Children, tempVar6)
	tempVar9 := pikoruntime.GetNode()
	tempVar9.NodeType = pikoruntime.NodeElement
	tempVar9.TagName = "span"
	tempVar9.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar9.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	tempVar9.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar9.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar9.Attributes = append(tempVar9.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "date"})
	tempVar9.Attributes = append(tempVar9.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1:1"})
	tempVar9.Children = append(tempVar9.Children, staticNode_2)
	tempVar10 := pikoruntime.GetNode()
	tempVar10.NodeType = pikoruntime.NodeElement
	tempVar10.TagName = "time"
	tempVar10.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar10.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar10.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar10.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar10.Attributes = append(tempVar10.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "published-date"})
	tempVar10.Attributes = append(tempVar10.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1:1:1"})
	tempVar11 := pikoruntime.GetNode()
	tempVar11.NodeType = pikoruntime.NodeText
	tempVar11.TextContent = html.EscapeString(pageData.PublishedDate)
	tempVar10.Children = append(tempVar10.Children, tempVar11)
	tempVar9.Children = append(tempVar9.Children, tempVar10)
	tempVar5.Children = append(tempVar5.Children, tempVar9)
	tempVar2.Children = append(tempVar2.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar2)
	tempVar12 := pikoruntime.GetNode()
	tempVar12.NodeType = pikoruntime.NodeElement
	tempVar12.TagName = "section"
	tempVar12.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar12.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar12.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar12.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar12.Attributes = append(tempVar12.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "article-content"})
	tempVar12.Attributes = append(tempVar12.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	tempVar13 := pikoruntime.GetNode()
	tempVar13.NodeType = pikoruntime.NodeElement
	tempVar13.TagName = "p"
	tempVar13.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar13.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar13.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar13.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar13.Attributes = append(tempVar13.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "content-text"})
	tempVar13.Attributes = append(tempVar13.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"})
	tempVar14 := pikoruntime.GetNode()
	tempVar14.NodeType = pikoruntime.NodeText
	tempVar14.TextContent = html.EscapeString(pageData.Content)
	tempVar13.Children = append(tempVar13.Children, tempVar14)
	tempVar12.Children = append(tempVar12.Children, tempVar13)
	tempVar1.Children = append(tempVar1.Children, tempVar12)
	tempVar1.Children = append(tempVar1.Children, staticNode_3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: []string{}}
	return rootAST, internalMetaResult, diags
}

var ( // SOURCE: pages/article.pk, LINE: 49
	staticNode_1                 *pikoruntime.TemplateNode // SOURCE: pages/article.pk, LINE: 50
	staticNode_2                 *pikoruntime.TemplateNode // SOURCE: pages/article.pk, LINE: 56
	staticNode_3                 *pikoruntime.TemplateNode // SOURCE: pages/article.pk, LINE: 57
	staticNode_3_child_0         *pikoruntime.TemplateNode // SOURCE: pages/article.pk, LINE: 57
	staticNode_3_child_0_child_0 *pikoruntime.TemplateNode
)

func init() {
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeText
	staticNode_1.TextContent = "By "
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeText
	staticNode_2.TextContent = "Published: "
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "footer"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "article-footer"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeElement
	staticNode_3_child_0.TagName = "p"
	staticNode_3_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0"})
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "footer-note"})
	staticNode_3_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0_child_0.TextContent = "Thank you for reading!"
	staticNode_3_child_0.Children = append(staticNode_3_child_0.Children, staticNode_3_child_0_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_25_metadata/pages/pages_article_1466cebc", BuildAST)
}
