//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_factory_default_937e675c

import (
	"cmp"
	fmt "fmt"
	"html"
	"sort"
	"strconv"
	models "testcase_072_prop_tags_comprehensive/pkg/models"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}

// line partials/factory-default.pk:37
func GetDefaultOptions() models.AvatarOptions {
	return models.AvatarOptions{Size: 48, Shape: "circle"}
}

// line partials/factory-default.pk:44
type Props struct {
	Options models.AvatarOptions `prop:"options" factory:"GetDefaultOptions"`
}

// line partials/factory-default.pk:48
type Response struct {
	Options     models.AvatarOptions
	SizeDisplay string
}

// line partials/factory-default.pk:53
func Render(r *piko.RequestData, props Props) (Response, piko.Metadata, error) {
	return Response{Options: props.Options, SizeDisplay: fmt.Sprintf("%dpx", props.Options.Size)}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := Props{}
	if propsData != nil {
		p, ok := propsData.(Props)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/factory-default.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetAttrWriterSlice(1)
	tempVar1.AttributeWriters = tempVar2Slice
	_, tempVar3Slice := arena.GetChildSlice(1)
	tempVar1.Children = tempVar3Slice
	tempVar4 := pikoruntime.ClassesFromStringBytesArena(arena, "avatar avatar-"+pageData.Options.Shape)
	if tempVar4 != nil {
		tempVar5 := arena.GetDirectWriter()
		tempVar5.SetName("class")
		tempVar5.AppendPooledBytes(tempVar4)
		tempVar1.AttributeWriters = append(tempVar1.AttributeWriters, tempVar5)
	}
	// line partials/factory-default.pk:23
	tempVar6 := arena.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "span"
	tempVar6.Attributes = staticAttrs_2
	tempVar7 := arena.GetDirectWriter()
	tempVar7.AppendEscapeString(pageData.SizeDisplay)
	tempVar6.TextContentWriter = tempVar7
	tempVar1.Children = append(tempVar1.Children, tempVar6)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: partials/factory-default.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: partials/factory-default.pk, LINE: 23
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_factory_default_937e675c"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "factory-default"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_factory_default_937e675c"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_072_prop_tags_comprehensive/dist/partials/partials_factory_default_937e675c", BuildAST)
}
