// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package interp_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpvalueDescriptor struct {
	_tab flatbuffers.Struct
}

func (rcv *UpvalueDescriptor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpvalueDescriptor) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *UpvalueDescriptor) Index() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *UpvalueDescriptor) MutateIndex(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *UpvalueDescriptor) Kind() RegisterKind {
	return RegisterKind(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(1)))
}
func (rcv *UpvalueDescriptor) MutateKind(n RegisterKind) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(1), int8(n))
}

func (rcv *UpvalueDescriptor) IsLocal() bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *UpvalueDescriptor) MutateIsLocal(n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func CreateUpvalueDescriptor(builder *flatbuffers.Builder, index byte, kind RegisterKind, isLocal bool) flatbuffers.UOffsetT {
	builder.Prep(1, 3)
	builder.PrependBool(isLocal)
	builder.PrependInt8(int8(kind))
	builder.PrependByte(index)
	return builder.Offset()
}
