// Code generated by 'piko extract'. DO NOT EDIT.

package driven_system_symbols

import (
	"reflect"

	"piko.sh/piko/wdk/interp/interp_link"
)

func init() {
	Symbols["weak"] = map[string]reflect.Value{"Pointer": reflect.ValueOf(interp_link.WrapType("Pointer", 1, []interp_link.GenericField{}))}
}
