// Code generated by 'piko extract'. DO NOT EDIT.

package driven_system_symbols

import (
	mail "net/mail"
	"reflect"
)

func init() {
	Symbols["net/mail"] = map[string]reflect.Value{"Address": reflect.ValueOf((*mail.Address)(nil)), "AddressParser": reflect.ValueOf((*mail.AddressParser)(nil)), "ErrHeaderNotPresent": reflect.ValueOf(&mail.ErrHeaderNotPresent).Elem(), "Header": reflect.ValueOf((*mail.Header)(nil)), "Message": reflect.ValueOf((*mail.Message)(nil)), "ParseAddress": reflect.ValueOf(mail.ParseAddress), "ParseAddressList": reflect.ValueOf(mail.ParseAddressList), "ParseDate": reflect.ValueOf(mail.ParseDate), "ReadMessage": reflect.ValueOf(mail.ReadMessage)}
}
