// Code generated by 'piko extract'. DO NOT EDIT.

//go:build !js || !wasm

package driven_system_symbols

import (
	"go/importer"
	"go/types"
)

var TypesPackages = make(map[string]*types.Package)

func init() {
	imp := importer.Default()
	for _, path := range []string{"errors", "sync", "io", "bytes", "cmp", "slices", "time", "context", "strconv", "encoding/base64", "math", "path", "os", "fmt", "strings", "encoding/json", "html", "sort", "regexp", "maps"} {
		pkg, err := imp.Import(path)
		if err == nil {
			TypesPackages[path] = pkg
		}
	}
}
