// Code generated by 'piko extract'. DO NOT EDIT.

package driven_system_symbols

import (
	rand "crypto/rand"
	"reflect"
)

func init() {
	Symbols["crypto/rand"] = map[string]reflect.Value{"Int": reflect.ValueOf(rand.Int), "Prime": reflect.ValueOf(rand.Prime), "Read": reflect.ValueOf(rand.Read), "Reader": reflect.ValueOf(&rand.Reader).Elem(), "Text": reflect.ValueOf(rand.Text)}
}
