// Code generated by 'piko extract'. DO NOT EDIT.

package driven_system_symbols

import (
	cgi "net/http/cgi"
	"reflect"
)

func init() {
	Symbols["net/http/cgi"] = map[string]reflect.Value{"Handler": reflect.ValueOf((*cgi.Handler)(nil)), "Request": reflect.ValueOf(cgi.Request), "RequestFromMap": reflect.ValueOf(cgi.RequestFromMap), "Serve": reflect.ValueOf(cgi.Serve)}
}
