//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_form_container_f99427c7 "testcase_092_css_cross_partial_descendant/dist/partials/partials_form_container_f99427c7"
	partials_input_fields_e97d8559 "testcase_092_css_cross_partial_descendant/dist/partials/partials_input_fields_e97d8559"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}
var _ = partials_form_container_f99427c7.Render

func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_form_container_d718ca7a := piko.NoProps{}
	partials_form_container_f99427c7Data_form_container_d718ca7a, partials_form_container_f99427c7Meta_form_container_d718ca7a, partials_form_container_f99427c7Err_form_container_d718ca7a := partials_form_container_f99427c7.Render(r, props_form_container_d718ca7a)
	if partials_form_container_f99427c7Err_form_container_d718ca7a != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_form_container_f99427c7Err_form_container_d718ca7a.Error(), "R002", "", "Partial Render() error for partials_form_container_f99427c7", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_form_container_f99427c7Data_form_container_d718ca7a
	_ = partials_form_container_f99427c7Meta_form_container_d718ca7a
	_ = partials_form_container_f99427c7Err_form_container_d718ca7a
	props_input_fields_form_container_d718ca7a_99ba1996 := piko.NoProps{}
	partials_input_fields_e97d8559Data_input_fields_form_container_d718ca7a_99ba1996, partials_input_fields_e97d8559Meta_input_fields_form_container_d718ca7a_99ba1996, partials_input_fields_e97d8559Err_input_fields_form_container_d718ca7a_99ba1996 := partials_input_fields_e97d8559.Render(r, props_input_fields_form_container_d718ca7a_99ba1996)
	if partials_input_fields_e97d8559Err_input_fields_form_container_d718ca7a_99ba1996 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_input_fields_e97d8559Err_input_fields_form_container_d718ca7a_99ba1996.Error(), "R002", "", "Partial Render() error for partials_input_fields_e97d8559", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_input_fields_e97d8559Data_input_fields_form_container_d718ca7a_99ba1996
	_ = partials_input_fields_e97d8559Meta_input_fields_form_container_d718ca7a_99ba1996
	_ = partials_input_fields_e97d8559Err_input_fields_form_container_d718ca7a_99ba1996
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(2)
	rootAST.RootNodes = append(rootAST.RootNodes, staticNode_1)
	// line partials/form_container.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(3)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_2)
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeFragment
	_, tempVar4Slice := arena.GetAttrSlice(4)
	tempVar3.Attributes = tempVar4Slice
	_, tempVar5Slice := arena.GetChildSlice(2)
	tempVar3.Children = tempVar5Slice
	tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "input_fields"})
	tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1"})
	tempVar3.Children = append(tempVar3.Children, staticNode_3)
	tempVar3.Children = append(tempVar3.Children, staticNode_4)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	tempVar1.Children = append(tempVar1.Children, staticNode_5)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1                []pikoruntime.HTMLAttribute // SOURCE: partials/form_container.pk, LINE: 22
	staticNode_1                 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 22
	staticNode_1_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 22
	staticNode_2                 *pikoruntime.TemplateNode   // SOURCE: partials/form_container.pk, LINE: 23
	staticNode_2_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/form_container.pk, LINE: 23
	staticNode_3                 *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 22
	staticNode_3_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 23
	staticNode_3_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 23
	staticNode_3_child_1         *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 24
	staticNode_4                 *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 26
	staticNode_4_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 27
	staticNode_4_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 27
	staticNode_4_child_1         *pikoruntime.TemplateNode   // SOURCE: partials/input_fields.pk, LINE: 28
	staticNode_5                 *pikoruntime.TemplateNode   // SOURCE: partials/form_container.pk, LINE: 25
	staticNode_5_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/form_container.pk, LINE: 25
)

func init() {
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "h1"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "page-title"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Registration"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_form_container_f99427c7"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "form_container"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "form"}}
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "h2"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_form_container_f99427c7"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:0"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "form-title"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0.TextContent = "Contact Form"
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "div"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 5)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1:0"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "input-group"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-fragment", Value: "input_fields_c8540647"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-fragment-id", Value: "0"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeElement
	staticNode_3_child_0.TagName = "label"
	staticNode_3_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1:0:0"})
	staticNode_3_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0_child_0.TextContent = "Name"
	staticNode_3_child_0.Children = append(staticNode_3_child_0.Children, staticNode_3_child_0_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
	staticNode_3_child_1 = &pikoruntime.TemplateNode{}
	staticNode_3_child_1.NodeType = pikoruntime.NodeElement
	staticNode_3_child_1.TagName = "input"
	staticNode_3_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3_child_1.Attributes = append(staticNode_3_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	staticNode_3_child_1.Attributes = append(staticNode_3_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1:0:1"})
	staticNode_3_child_1.Attributes = append(staticNode_3_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "type", Value: "text"})
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_1)
	staticNode_4 = &pikoruntime.TemplateNode{}
	staticNode_4.NodeType = pikoruntime.NodeElement
	staticNode_4.TagName = "div"
	staticNode_4.Attributes = make([]pikoruntime.HTMLAttribute, 0, 5)
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1:1"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "input-group"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-fragment", Value: "input_fields_c8540647"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-fragment-id", Value: "1"})
	staticNode_4.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	staticNode_4_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0.NodeType = pikoruntime.NodeElement
	staticNode_4_child_0.TagName = "label"
	staticNode_4_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1:1:0"})
	staticNode_4_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_0_child_0.TextContent = "Email"
	staticNode_4_child_0.Children = append(staticNode_4_child_0.Children, staticNode_4_child_0_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_0)
	staticNode_4_child_1 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1.NodeType = pikoruntime.NodeElement
	staticNode_4_child_1.TagName = "input"
	staticNode_4_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_input_fields_e97d8559"})
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:1:1:1"})
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "type", Value: "email"})
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_1)
	staticNode_5 = &pikoruntime.TemplateNode{}
	staticNode_5.NodeType = pikoruntime.NodeElement
	staticNode_5.TagName = "button"
	staticNode_5.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_5.Attributes = append(staticNode_5.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_form_container_f99427c7"})
	staticNode_5.Attributes = append(staticNode_5.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1:2"})
	staticNode_5.Attributes = append(staticNode_5.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "submit"})
	staticNode_5.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_5_child_0 = &pikoruntime.TemplateNode{}
	staticNode_5_child_0.NodeType = pikoruntime.NodeText
	staticNode_5_child_0.TextContent = "Submit"
	staticNode_5.Children = append(staticNode_5.Children, staticNode_5_child_0)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_092_css_cross_partial_descendant/dist/pages/pages_main_594861c5", BuildAST)
}
