//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_categories_5130e719

import (
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = piko.Metadata{}

type Product struct {
	Name  string
	Price string
}
type Category struct {
	Name     string
	Products []Product
}
type Response struct{ Categories []Category }

func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Categories: []Category{{Name: "Electronics", Products: []Product{{Name: "Laptop", Price: "$999"}, {Name: "Phone", Price: "$599"}}}, {Name: "Books", Products: []Product{{Name: "Go Programming", Price: "$39"}, {Name: "Clean Code", Price: "$45"}, {Name: "Design Patterns", Price: "$55"}}}, {Name: "Clothing", Products: []Product{{Name: "T-Shirt", Price: "$25"}}}}}, piko.Metadata{Title: "Product Categories"}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diags []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diags = pikoruntime.AppendDiagnostic(diags, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diags
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diags
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	/* SOURCE: pages/categories.pk, LINE: 71 */
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	/* SOURCE: pages/categories.pk, LINE: 72 */
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "h1"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	/* SOURCE: pages/categories.pk, LINE: 72 */
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeText
	tempVar5.TextContent = "Product Catalogue"
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	/* SOURCE: pages/categories.pk, LINE: 73 */
	tempVar6 := arena.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "div"
	loopIter_1 := pageData.Categories
	tempVar6.Attributes = staticAttrs_3
	_, tempVar7Slice := arena.GetChildSlice(len(loopIter_1))
	tempVar6.Children = tempVar7Slice
	if loopIter_1 != nil {
		for __pikoLoopIdx, category := range loopIter_1 {
			/* SOURCE: pages/categories.pk, LINE: 74 */
			tempVar8 := arena.GetNode()
			tempVar8.NodeType = pikoruntime.NodeElement
			tempVar8.TagName = "section"
			_, tempVar9Slice := arena.GetAttrSlice(2)
			tempVar8.Attributes = tempVar9Slice
			_, tempVar10Slice := arena.GetAttrWriterSlice(1)
			tempVar8.AttributeWriters = tempVar10Slice
			_, tempVar11Slice := arena.GetChildSlice(2)
			tempVar8.Children = tempVar11Slice
			tempVar8.Attributes = append(tempVar8.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"})
			tempVar8.Attributes = append(tempVar8.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "category"})
			tempVar12 := arena.GetDirectWriter()
			tempVar12.SetName("p-key")
			tempVar12.AppendString("r.0:1:0.")
			tempVar12.AppendFNVString(pikoruntime.ValueToString(__pikoLoopIdx))
			tempVar8.AttributeWriters = append(tempVar8.AttributeWriters, tempVar12)
			/* SOURCE: pages/categories.pk, LINE: 75 */
			tempVar13 := arena.GetNode()
			tempVar13.NodeType = pikoruntime.NodeElement
			tempVar13.TagName = "h2"
			_, tempVar14Slice := arena.GetAttrSlice(2)
			tempVar13.Attributes = tempVar14Slice
			_, tempVar15Slice := arena.GetAttrWriterSlice(1)
			tempVar13.AttributeWriters = tempVar15Slice
			_, tempVar16Slice := arena.GetChildSlice(1)
			tempVar13.Children = tempVar16Slice
			tempVar13.Attributes = append(tempVar13.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"})
			tempVar13.Attributes = append(tempVar13.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "category-name"})
			tempVar17 := arena.GetDirectWriter()
			tempVar17.SetName("p-key")
			tempVar17.AppendString("r.0:1:0.")
			tempVar17.AppendFNVString(pikoruntime.ValueToString(category))
			tempVar17.AppendString(":0")
			tempVar13.AttributeWriters = append(tempVar13.AttributeWriters, tempVar17)
			/* SOURCE: pages/categories.pk, LINE: 75 */
			tempVar18 := arena.GetNode()
			tempVar18.NodeType = pikoruntime.NodeText
			tempVar19 := arena.GetDirectWriter()
			tempVar19.AppendEscapeString(category.Name)
			tempVar18.TextContentWriter = tempVar19
			tempVar13.Children = append(tempVar13.Children, tempVar18)
			tempVar8.Children = append(tempVar8.Children, tempVar13)
			/* SOURCE: pages/categories.pk, LINE: 76 */
			tempVar20 := arena.GetNode()
			tempVar20.NodeType = pikoruntime.NodeElement
			tempVar20.TagName = "ul"
			loopIter_2 := category.Products
			_, tempVar21Slice := arena.GetAttrSlice(2)
			tempVar20.Attributes = tempVar21Slice
			_, tempVar22Slice := arena.GetAttrWriterSlice(1)
			tempVar20.AttributeWriters = tempVar22Slice
			_, tempVar23Slice := arena.GetChildSlice(len(loopIter_2))
			tempVar20.Children = tempVar23Slice
			tempVar20.Attributes = append(tempVar20.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"})
			tempVar20.Attributes = append(tempVar20.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "product-list"})
			tempVar24 := arena.GetDirectWriter()
			tempVar24.SetName("p-key")
			tempVar24.AppendString("r.0:1:0.")
			tempVar24.AppendFNVString(pikoruntime.ValueToString(category))
			tempVar24.AppendString(":1")
			tempVar20.AttributeWriters = append(tempVar20.AttributeWriters, tempVar24)
			if loopIter_2 != nil {
				for __pikoLoopIdx2, product := range loopIter_2 {
					/* SOURCE: pages/categories.pk, LINE: 77 */
					tempVar25 := arena.GetNode()
					tempVar25.NodeType = pikoruntime.NodeElement
					tempVar25.TagName = "li"
					_, tempVar26Slice := arena.GetAttrSlice(2)
					tempVar25.Attributes = tempVar26Slice
					_, tempVar27Slice := arena.GetAttrWriterSlice(1)
					tempVar25.AttributeWriters = tempVar27Slice
					_, tempVar28Slice := arena.GetChildSlice(2)
					tempVar25.Children = tempVar28Slice
					tempVar25.Attributes = append(tempVar25.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"})
					tempVar25.Attributes = append(tempVar25.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "product"})
					tempVar29 := arena.GetDirectWriter()
					tempVar29.SetName("p-key")
					tempVar29.AppendString("r.0:1:0.")
					tempVar29.AppendFNVString(pikoruntime.ValueToString(category))
					tempVar29.AppendString(":1:0.")
					tempVar29.AppendFNVString(pikoruntime.ValueToString(__pikoLoopIdx2))
					tempVar25.AttributeWriters = append(tempVar25.AttributeWriters, tempVar29)
					/* SOURCE: pages/categories.pk, LINE: 78 */
					tempVar30 := arena.GetNode()
					tempVar30.NodeType = pikoruntime.NodeElement
					tempVar30.TagName = "span"
					_, tempVar31Slice := arena.GetAttrSlice(2)
					tempVar30.Attributes = tempVar31Slice
					_, tempVar32Slice := arena.GetAttrWriterSlice(1)
					tempVar30.AttributeWriters = tempVar32Slice
					_, tempVar33Slice := arena.GetChildSlice(1)
					tempVar30.Children = tempVar33Slice
					tempVar30.Attributes = append(tempVar30.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"})
					tempVar30.Attributes = append(tempVar30.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "product-name"})
					tempVar34 := arena.GetDirectWriter()
					tempVar34.SetName("p-key")
					tempVar34.AppendString("r.0:1:0.")
					tempVar34.AppendFNVString(pikoruntime.ValueToString(category))
					tempVar34.AppendString(":1:0.")
					tempVar34.AppendFNVString(pikoruntime.ValueToString(product))
					tempVar34.AppendString(":0")
					tempVar30.AttributeWriters = append(tempVar30.AttributeWriters, tempVar34)
					/* SOURCE: pages/categories.pk, LINE: 78 */
					tempVar35 := arena.GetNode()
					tempVar35.NodeType = pikoruntime.NodeText
					tempVar36 := arena.GetDirectWriter()
					tempVar36.AppendEscapeString(product.Name)
					tempVar35.TextContentWriter = tempVar36
					tempVar30.Children = append(tempVar30.Children, tempVar35)
					tempVar25.Children = append(tempVar25.Children, tempVar30)
					/* SOURCE: pages/categories.pk, LINE: 79 */
					tempVar37 := arena.GetNode()
					tempVar37.NodeType = pikoruntime.NodeElement
					tempVar37.TagName = "span"
					_, tempVar38Slice := arena.GetAttrSlice(2)
					tempVar37.Attributes = tempVar38Slice
					_, tempVar39Slice := arena.GetAttrWriterSlice(1)
					tempVar37.AttributeWriters = tempVar39Slice
					_, tempVar40Slice := arena.GetChildSlice(1)
					tempVar37.Children = tempVar40Slice
					tempVar37.Attributes = append(tempVar37.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"})
					tempVar37.Attributes = append(tempVar37.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "product-price"})
					tempVar41 := arena.GetDirectWriter()
					tempVar41.SetName("p-key")
					tempVar41.AppendString("r.0:1:0.")
					tempVar41.AppendFNVString(pikoruntime.ValueToString(category))
					tempVar41.AppendString(":1:0.")
					tempVar41.AppendFNVString(pikoruntime.ValueToString(product))
					tempVar41.AppendString(":1")
					tempVar37.AttributeWriters = append(tempVar37.AttributeWriters, tempVar41)
					/* SOURCE: pages/categories.pk, LINE: 79 */
					tempVar42 := arena.GetNode()
					tempVar42.NodeType = pikoruntime.NodeText
					tempVar43 := arena.GetDirectWriter()
					tempVar43.AppendEscapeString(product.Price)
					tempVar42.TextContentWriter = tempVar43
					tempVar37.Children = append(tempVar37.Children, tempVar42)
					tempVar25.Children = append(tempVar25.Children, tempVar37)
					tempVar20.Children = append(tempVar20.Children, tempVar25)
				}
			}
			tempVar8.Children = append(tempVar8.Children, tempVar20)
			tempVar6.Children = append(tempVar6.Children, tempVar8)
		}
	}
	tempVar1.Children = append(tempVar1.Children, tempVar6)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diags
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: pages/categories.pk, LINE: 71
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: pages/categories.pk, LINE: 72
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: pages/categories.pk, LINE: 73
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "catalogue"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_categories_5130e719"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "categories"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_14_nested_loops/pages/pages_categories_5130e719", BuildAST)
}
