//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_browser_4016e9df "testcase_107_p_if_css_scoping_in_partial/dist/partials/partials_browser_4016e9df"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_browser_4016e9df.Render

// line pages/main.pk:36
func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_browser_show_items_true_c57d7a47 := partials_browser_4016e9df.Props{ShowItems: true}
	partials_browser_4016e9dfData_browser_show_items_true_c57d7a47, partials_browser_4016e9dfMeta_browser_show_items_true_c57d7a47, partials_browser_4016e9dfErr_browser_show_items_true_c57d7a47 := partials_browser_4016e9df.Render(r, props_browser_show_items_true_c57d7a47)
	if partials_browser_4016e9dfErr_browser_show_items_true_c57d7a47 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_browser_4016e9dfErr_browser_show_items_true_c57d7a47.Error(), "R002", "", "Partial Render() error for partials_browser_4016e9df", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_browser_4016e9dfData_browser_show_items_true_c57d7a47
	_ = partials_browser_4016e9dfMeta_browser_show_items_true_c57d7a47
	_ = partials_browser_4016e9dfErr_browser_show_items_true_c57d7a47
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	// line partials/browser.pk:22
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "div"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(3)
	tempVar3.Children = tempVar4Slice
	tempVar3.Children = append(tempVar3.Children, staticNode_2)
	// line partials/browser.pk:27:10
	if !props_browser_show_items_true_c57d7a47.ShowItems {
		tempVar3.Children = append(tempVar3.Children, staticNode_3)
	}
	// line partials/browser.pk:31:10
	if props_browser_show_items_true_c57d7a47.ShowItems {
		tempVar3.Children = append(tempVar3.Children, staticNode_4)
	}
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1                []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticAttrs_2                []pikoruntime.HTMLAttribute // SOURCE: partials/browser.pk, LINE: 22
	staticNode_1                 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_1_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_2                 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 23
	staticNode_2_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 24
	staticNode_2_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 24
	staticNode_3                 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 27
	staticNode_3_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 28
	staticNode_3_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 28
	staticNode_4                 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 31
	staticNode_4_child_0         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 32
	staticNode_4_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 32
	staticNode_4_child_1         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 33
	staticNode_4_child_1_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 33
	staticNode_4_child_2         *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 34
	staticNode_4_child_2_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/browser.pk, LINE: 34
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "h1"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "P-If CSS Scoping Test"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "browser"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "browser-container"}}
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "header"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "browser-header"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeElement
	staticNode_2_child_0.TagName = "h2"
	staticNode_2_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0"})
	staticNode_2_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0_child_0.TextContent = "Items Browser"
	staticNode_2_child_0.Children = append(staticNode_2_child_0.Children, staticNode_2_child_0_child_0)
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "div"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-results"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeElement
	staticNode_3_child_0.TagName = "p"
	staticNode_3_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:0"})
	staticNode_3_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0_child_0.TextContent = "No items found."
	staticNode_3_child_0.Children = append(staticNode_3_child_0.Children, staticNode_3_child_0_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
	staticNode_4 = &pikoruntime.TemplateNode{}
	staticNode_4.NodeType = pikoruntime.NodeElement
	staticNode_4.TagName = "div"
	staticNode_4.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "items-grid"})
	staticNode_4.Children = make([]*pikoruntime.TemplateNode, 0, 3)
	staticNode_4_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0.NodeType = pikoruntime.NodeElement
	staticNode_4_child_0.TagName = "div"
	staticNode_4_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2:0"})
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
	staticNode_4_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_0_child_0.TextContent = "Item 1"
	staticNode_4_child_0.Children = append(staticNode_4_child_0.Children, staticNode_4_child_0_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_0)
	staticNode_4_child_1 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1.NodeType = pikoruntime.NodeElement
	staticNode_4_child_1.TagName = "div"
	staticNode_4_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2:1"})
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
	staticNode_4_child_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_1_child_0.TextContent = "Item 2"
	staticNode_4_child_1.Children = append(staticNode_4_child_1.Children, staticNode_4_child_1_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_1)
	staticNode_4_child_2 = &pikoruntime.TemplateNode{}
	staticNode_4_child_2.NodeType = pikoruntime.NodeElement
	staticNode_4_child_2.TagName = "div"
	staticNode_4_child_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4_child_2.Attributes = append(staticNode_4_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_browser_4016e9df"})
	staticNode_4_child_2.Attributes = append(staticNode_4_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:2:2"})
	staticNode_4_child_2.Attributes = append(staticNode_4_child_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "item-card"})
	staticNode_4_child_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_2_child_0.TextContent = "Item 3"
	staticNode_4_child_2.Children = append(staticNode_4_child_2.Children, staticNode_4_child_2_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_2)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_107_p_if_css_scoping_in_partial/dist/pages/pages_main_594861c5", BuildAST)
}
