//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_search_3cd6b932

import (
	"fmt"
	"html"
	"sort"
	strconv "strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = piko.Metadata{}

type Response struct {
	Query      string
	Category   string
	Sort       string
	Page       int
	HasQuery   bool
	HasFilters bool
}

func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	query := r.QueryParam("q")
	category := r.QueryParam("category")
	sort := r.QueryParam("sort")
	pageString := r.QueryParam("page")
	if sort == "" {
		sort = "relevance"
	}
	page := 1
	if pageString != "" {
		if p, err := strconv.Atoi(pageString); err == nil && p > 0 {
			page = p
		}
	}
	hasFilters := category != "" || sort != "relevance"
	return Response{Query: query, Category: category, Sort: sort, Page: page, HasQuery: query != "", HasFilters: hasFilters}, piko.Metadata{Title: "Search Results"}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diags []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diags = pikoruntime.AppendDiagnostic(diags, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diags
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diags
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	/* SOURCE: pages/search.pk, LINE: 71 */
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(4)
	tempVar1.Children = tempVar2Slice
	/* SOURCE: pages/search.pk, LINE: 72 */
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "h1"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	/* SOURCE: pages/search.pk, LINE: 72 */
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeText
	tempVar5.TextContent = "Search"
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	/* SOURCE: pages/search.pk, LINE: 73 */
	tempVar6 := arena.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "section"
	tempVar6.Attributes = staticAttrs_3
	_, tempVar7Slice := arena.GetChildSlice(2)
	tempVar6.Children = tempVar7Slice
	if pageData.HasQuery {
		/* SOURCE: pages/search.pk, LINE: 74 */
		tempVar8 := arena.GetNode()
		tempVar8.NodeType = pikoruntime.NodeElement
		tempVar8.TagName = "div"
		tempVar8.Attributes = staticAttrs_4
		_, tempVar9Slice := arena.GetChildSlice(1)
		tempVar8.Children = tempVar9Slice
		/* SOURCE: pages/search.pk, LINE: 75 */
		tempVar10 := arena.GetNode()
		tempVar10.NodeType = pikoruntime.NodeElement
		tempVar10.TagName = "p"
		tempVar10.Attributes = staticAttrs_5
		_, tempVar11Slice := arena.GetChildSlice(2)
		tempVar10.Children = tempVar11Slice
		/* SOURCE: pages/search.pk, LINE: 75 */
		tempVar12 := arena.GetNode()
		tempVar12.NodeType = pikoruntime.NodeText
		tempVar12.TextContent = "Searching for: "
		tempVar10.Children = append(tempVar10.Children, tempVar12)
		/* SOURCE: pages/search.pk, LINE: 75 */
		tempVar13 := arena.GetNode()
		tempVar13.NodeType = pikoruntime.NodeElement
		tempVar13.TagName = "span"
		tempVar13.Attributes = staticAttrs_6
		_, tempVar14Slice := arena.GetChildSlice(1)
		tempVar13.Children = tempVar14Slice
		/* SOURCE: pages/search.pk, LINE: 75 */
		tempVar15 := arena.GetNode()
		tempVar15.NodeType = pikoruntime.NodeText
		tempVar16 := arena.GetDirectWriter()
		tempVar16.AppendEscapeString(pageData.Query)
		tempVar15.TextContentWriter = tempVar16
		tempVar13.Children = append(tempVar13.Children, tempVar15)
		tempVar10.Children = append(tempVar10.Children, tempVar13)
		tempVar8.Children = append(tempVar8.Children, tempVar10)
		tempVar6.Children = append(tempVar6.Children, tempVar8)
	} else {
		tempVar6.Children = append(tempVar6.Children, staticNode_1)
	}
	tempVar1.Children = append(tempVar1.Children, tempVar6)
	/* SOURCE: pages/search.pk, LINE: 81 */
	tempVar17 := arena.GetNode()
	tempVar17.NodeType = pikoruntime.NodeElement
	tempVar17.TagName = "section"
	tempVar17.Attributes = staticAttrs_7
	_, tempVar18Slice := arena.GetChildSlice(2)
	tempVar17.Children = tempVar18Slice
	if pageData.HasFilters {
		/* SOURCE: pages/search.pk, LINE: 82 */
		tempVar19 := arena.GetNode()
		tempVar19.NodeType = pikoruntime.NodeElement
		tempVar19.TagName = "div"
		tempVar19.Attributes = staticAttrs_8
		_, tempVar20Slice := arena.GetChildSlice(3)
		tempVar19.Children = tempVar20Slice
		/* SOURCE: pages/search.pk, LINE: 83 */
		tempVar21 := arena.GetNode()
		tempVar21.NodeType = pikoruntime.NodeElement
		tempVar21.TagName = "p"
		tempVar21.Attributes = staticAttrs_9
		_, tempVar22Slice := arena.GetChildSlice(1)
		tempVar21.Children = tempVar22Slice
		/* SOURCE: pages/search.pk, LINE: 83 */
		tempVar23 := arena.GetNode()
		tempVar23.NodeType = pikoruntime.NodeText
		tempVar23.TextContent = "Active Filters:"
		tempVar21.Children = append(tempVar21.Children, tempVar23)
		tempVar19.Children = append(tempVar19.Children, tempVar21)
		if pageData.Category != "" {
			/* SOURCE: pages/search.pk, LINE: 84 */
			tempVar24 := arena.GetNode()
			tempVar24.NodeType = pikoruntime.NodeElement
			tempVar24.TagName = "p"
			tempVar24.Attributes = staticAttrs_10
			_, tempVar25Slice := arena.GetChildSlice(2)
			tempVar24.Children = tempVar25Slice
			/* SOURCE: pages/search.pk, LINE: 84 */
			tempVar26 := arena.GetNode()
			tempVar26.NodeType = pikoruntime.NodeText
			tempVar26.TextContent = "Category: "
			tempVar24.Children = append(tempVar24.Children, tempVar26)
			/* SOURCE: pages/search.pk, LINE: 84 */
			tempVar27 := arena.GetNode()
			tempVar27.NodeType = pikoruntime.NodeElement
			tempVar27.TagName = "span"
			tempVar27.Attributes = staticAttrs_11
			_, tempVar28Slice := arena.GetChildSlice(1)
			tempVar27.Children = tempVar28Slice
			/* SOURCE: pages/search.pk, LINE: 84 */
			tempVar29 := arena.GetNode()
			tempVar29.NodeType = pikoruntime.NodeText
			tempVar30 := arena.GetDirectWriter()
			tempVar30.AppendEscapeString(pageData.Category)
			tempVar29.TextContentWriter = tempVar30
			tempVar27.Children = append(tempVar27.Children, tempVar29)
			tempVar24.Children = append(tempVar24.Children, tempVar27)
			tempVar19.Children = append(tempVar19.Children, tempVar24)
		}
		/* SOURCE: pages/search.pk, LINE: 85 */
		tempVar31 := arena.GetNode()
		tempVar31.NodeType = pikoruntime.NodeElement
		tempVar31.TagName = "p"
		tempVar31.Attributes = staticAttrs_12
		_, tempVar32Slice := arena.GetChildSlice(2)
		tempVar31.Children = tempVar32Slice
		/* SOURCE: pages/search.pk, LINE: 85 */
		tempVar33 := arena.GetNode()
		tempVar33.NodeType = pikoruntime.NodeText
		tempVar33.TextContent = "Sort: "
		tempVar31.Children = append(tempVar31.Children, tempVar33)
		/* SOURCE: pages/search.pk, LINE: 85 */
		tempVar34 := arena.GetNode()
		tempVar34.NodeType = pikoruntime.NodeElement
		tempVar34.TagName = "span"
		tempVar34.Attributes = staticAttrs_13
		_, tempVar35Slice := arena.GetChildSlice(1)
		tempVar34.Children = tempVar35Slice
		/* SOURCE: pages/search.pk, LINE: 85 */
		tempVar36 := arena.GetNode()
		tempVar36.NodeType = pikoruntime.NodeText
		tempVar37 := arena.GetDirectWriter()
		tempVar37.AppendEscapeString(pageData.Sort)
		tempVar36.TextContentWriter = tempVar37
		tempVar34.Children = append(tempVar34.Children, tempVar36)
		tempVar31.Children = append(tempVar31.Children, tempVar34)
		tempVar19.Children = append(tempVar19.Children, tempVar31)
		tempVar17.Children = append(tempVar17.Children, tempVar19)
	} else {
		tempVar17.Children = append(tempVar17.Children, staticNode_2)
	}
	tempVar1.Children = append(tempVar1.Children, tempVar17)
	/* SOURCE: pages/search.pk, LINE: 91 */
	tempVar38 := arena.GetNode()
	tempVar38.NodeType = pikoruntime.NodeElement
	tempVar38.TagName = "section"
	tempVar38.Attributes = staticAttrs_14
	_, tempVar39Slice := arena.GetChildSlice(1)
	tempVar38.Children = tempVar39Slice
	/* SOURCE: pages/search.pk, LINE: 92 */
	tempVar40 := arena.GetNode()
	tempVar40.NodeType = pikoruntime.NodeElement
	tempVar40.TagName = "p"
	tempVar40.Attributes = staticAttrs_15
	_, tempVar41Slice := arena.GetChildSlice(2)
	tempVar40.Children = tempVar41Slice
	/* SOURCE: pages/search.pk, LINE: 92 */
	tempVar42 := arena.GetNode()
	tempVar42.NodeType = pikoruntime.NodeText
	tempVar42.TextContent = "Page: "
	tempVar40.Children = append(tempVar40.Children, tempVar42)
	/* SOURCE: pages/search.pk, LINE: 92 */
	tempVar43 := arena.GetNode()
	tempVar43.NodeType = pikoruntime.NodeElement
	tempVar43.TagName = "span"
	tempVar43.Attributes = staticAttrs_16
	_, tempVar44Slice := arena.GetChildSlice(1)
	tempVar43.Children = tempVar44Slice
	/* SOURCE: pages/search.pk, LINE: 92 */
	tempVar45 := arena.GetNode()
	tempVar45.NodeType = pikoruntime.NodeText
	tempVar46 := arena.GetDirectWriter()
	tempVar46.AppendString(strconv.FormatInt(int64(pageData.Page), 10))
	tempVar45.TextContentWriter = tempVar46
	tempVar43.Children = append(tempVar43.Children, tempVar45)
	tempVar40.Children = append(tempVar40.Children, tempVar43)
	tempVar38.Children = append(tempVar38.Children, tempVar40)
	tempVar1.Children = append(tempVar1.Children, tempVar38)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diags
}

var (
	staticAttrs_1                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 71
	staticAttrs_10               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 84
	staticAttrs_11               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 84
	staticAttrs_12               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 85
	staticAttrs_13               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 85
	staticAttrs_14               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 91
	staticAttrs_15               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 92
	staticAttrs_16               []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 92
	staticAttrs_2                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 72
	staticAttrs_3                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 73
	staticAttrs_4                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 74
	staticAttrs_5                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 75
	staticAttrs_6                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 75
	staticAttrs_7                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 81
	staticAttrs_8                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 82
	staticAttrs_9                []pikoruntime.HTMLAttribute // SOURCE: pages/search.pk, LINE: 83
	staticNode_1                 *pikoruntime.TemplateNode   // SOURCE: pages/search.pk, LINE: 77
	staticNode_1_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/search.pk, LINE: 78
	staticNode_1_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/search.pk, LINE: 78
	staticNode_2                 *pikoruntime.TemplateNode   // SOURCE: pages/search.pk, LINE: 87
	staticNode_2_child_0         *pikoruntime.TemplateNode   // SOURCE: pages/search.pk, LINE: 88
	staticNode_2_child_0_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/search.pk, LINE: 88
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "search-page"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "search-status"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "has-query"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "query-display"}}
	staticAttrs_6 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "query-value"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "div"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-query"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0.TagName = "p"
	staticNode_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:0"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-query-message"})
	staticNode_1_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0_child_0.TextContent = "Enter a search term"
	staticNode_1_child_0.Children = append(staticNode_1_child_0.Children, staticNode_1_child_0_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_7 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"}, pikoruntime.HTMLAttribute{Name: "class", Value: "filters"}}
	staticAttrs_8 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "active-filters"}}
	staticAttrs_9 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "filters-label"}}
	staticAttrs_10 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "category-filter"}}
	staticAttrs_11 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0:1:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "category-value"}}
	staticAttrs_12 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0:2"}, pikoruntime.HTMLAttribute{Name: "class", Value: "sort-filter"}}
	staticAttrs_13 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0:2:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "sort-value"}}
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "div"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:1"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-filters"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeElement
	staticNode_2_child_0.TagName = "p"
	staticNode_2_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"})
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:1:0"})
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "no-filters-message"})
	staticNode_2_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0_child_0.TextContent = "No filters applied"
	staticNode_2_child_0.Children = append(staticNode_2_child_0.Children, staticNode_2_child_0_child_0)
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticAttrs_14 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:3"}, pikoruntime.HTMLAttribute{Name: "class", Value: "pagination"}}
	staticAttrs_15 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:3:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page-info"}}
	staticAttrs_16 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_search_3cd6b932"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:3:0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page-value"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_18_query_params/pages/pages_search_3cd6b932", BuildAST)
}
