//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_row_actions_c2843091 "testcase_133_partial_sibling_of_nested_loop/dist/partials/partials_row_actions_c2843091"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_row_actions_c2843091.Render

// line pages/main.pk:52
type Cell struct{ Text string }

// line pages/main.pk:56
type Row struct {
	ID    string
	Title string
	Cells []Cell
}

// line pages/main.pk:62
type Response struct {
	ContainerID  string
	CategoryName string
	Rows         []Row
}

// line pages/main.pk:68
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{ContainerID: "container-abc", CategoryName: "Category A", Rows: []Row{{ID: "1", Title: "First Row", Cells: []Cell{{Text: "A"}, {Text: "B"}}}, {ID: "2", Title: "Second Row", Cells: []Cell{{Text: "C"}, {Text: "D"}}}}}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(1)
	tempVar1.Children = tempVar2Slice
	// line pages/main.pk:23
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "table"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	// line pages/main.pk:24
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "tbody"
	loopIter_1 := pageData.Rows
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetChildSlice(len(loopIter_1))
	tempVar5.Children = tempVar6Slice
	// line pages/main.pk:25:13
	if loopIter_1 != nil {
		for _, row := range loopIter_1 {
			props_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af := partials_row_actions_c2843091.Props{CategoryName: pageData.CategoryName, ContainerID: pageData.ContainerID, RowID: row.ID, RowTitle: row.Title}
			partials_row_actions_c2843091Data_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af, partials_row_actions_c2843091Meta_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af, partials_row_actions_c2843091Err_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af := partials_row_actions_c2843091.Render(r, props_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af)
			if partials_row_actions_c2843091Err_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af != nil {
				diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_row_actions_c2843091Err_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af.Error(), "R002", "", "Partial Render() error for partials_row_actions_c2843091", 0, 0)
				return nil, pikoruntime.InternalMetadata{}, diagnostics
			}
			_ = partials_row_actions_c2843091Data_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af
			_ = partials_row_actions_c2843091Meta_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af
			_ = partials_row_actions_c2843091Err_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af
			// line pages/main.pk:25
			tempVar7 := arena.GetNode()
			tempVar7.NodeType = pikoruntime.NodeElement
			tempVar7.TagName = "tr"
			loopIter_2 := row.Cells
			_, tempVar8Slice := arena.GetAttrSlice(2)
			tempVar7.Attributes = tempVar8Slice
			_, tempVar9Slice := arena.GetAttrWriterSlice(1)
			tempVar7.AttributeWriters = tempVar9Slice
			_, tempVar10Slice := arena.GetChildSlice(1 + len(loopIter_2))
			tempVar7.Children = tempVar10Slice
			tempVar7.Attributes = append(tempVar7.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
			tempVar7.Attributes = append(tempVar7.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "row-wrapper"})
			tempVar11 := arena.GetDirectWriter()
			tempVar11.SetName("p-key")
			tempVar11.AppendString("r.0:0:0:0.")
			tempVar11.AppendFNVString(row.ID)
			tempVar7.AttributeWriters = append(tempVar7.AttributeWriters, tempVar11)
			// line pages/main.pk:26:15
			if loopIter_2 != nil {
				for idx, cell := range loopIter_2 {
					// line pages/main.pk:26
					tempVar12 := arena.GetNode()
					tempVar12.NodeType = pikoruntime.NodeElement
					tempVar12.TagName = "td"
					_, tempVar13Slice := arena.GetAttrSlice(2)
					tempVar12.Attributes = tempVar13Slice
					_, tempVar14Slice := arena.GetAttrWriterSlice(1)
					tempVar12.AttributeWriters = tempVar14Slice
					_, tempVar15Slice := arena.GetChildSlice(1)
					tempVar12.Children = tempVar15Slice
					tempVar12.Attributes = append(tempVar12.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
					tempVar12.Attributes = append(tempVar12.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "data-cell"})
					tempVar16 := arena.GetDirectWriter()
					tempVar16.SetName("p-key")
					tempVar16.AppendString("r.0:0:0:0.")
					tempVar16.AppendFNVString(row.ID)
					tempVar16.AppendString(":0.")
					tempVar16.AppendInt(int64(idx))
					tempVar12.AttributeWriters = append(tempVar12.AttributeWriters, tempVar16)
					// line pages/main.pk:27
					tempVar17 := arena.GetNode()
					tempVar17.NodeType = pikoruntime.NodeElement
					tempVar17.TagName = "span"
					_, tempVar18Slice := arena.GetAttrSlice(1)
					tempVar17.Attributes = tempVar18Slice
					_, tempVar19Slice := arena.GetAttrWriterSlice(1)
					tempVar17.AttributeWriters = tempVar19Slice
					tempVar17.Attributes = append(tempVar17.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
					tempVar20 := arena.GetDirectWriter()
					tempVar20.SetName("p-key")
					tempVar20.AppendString("r.0:0:0:0.")
					tempVar20.AppendFNVString(row.ID)
					tempVar20.AppendString(":0.")
					tempVar20.AppendInt(int64(idx))
					tempVar20.AppendString(":0")
					tempVar17.AttributeWriters = append(tempVar17.AttributeWriters, tempVar20)
					tempVar21 := arena.GetDirectWriter()
					tempVar21.AppendEscapeString(cell.Text)
					tempVar17.TextContentWriter = tempVar21
					tempVar12.Children = append(tempVar12.Children, tempVar17)
					tempVar7.Children = append(tempVar7.Children, tempVar12)
				}
			}
			// line pages/main.pk:29
			tempVar22 := arena.GetNode()
			tempVar22.NodeType = pikoruntime.NodeElement
			tempVar22.TagName = "td"
			_, tempVar23Slice := arena.GetAttrSlice(2)
			tempVar22.Attributes = tempVar23Slice
			_, tempVar24Slice := arena.GetAttrWriterSlice(1)
			tempVar22.AttributeWriters = tempVar24Slice
			_, tempVar25Slice := arena.GetChildSlice(1)
			tempVar22.Children = tempVar25Slice
			tempVar22.Attributes = append(tempVar22.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
			tempVar22.Attributes = append(tempVar22.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "actions"})
			tempVar26 := arena.GetDirectWriter()
			tempVar26.SetName("p-key")
			tempVar26.AppendString("r.0:0:0:0.")
			tempVar26.AppendFNVString(row.ID)
			tempVar26.AppendString(":1")
			tempVar22.AttributeWriters = append(tempVar22.AttributeWriters, tempVar26)
			// line partials/row_actions.pk:22
			tempVar27 := arena.GetNode()
			tempVar27.NodeType = pikoruntime.NodeElement
			tempVar27.TagName = "div"
			_, tempVar28Slice := arena.GetAttrSlice(4)
			tempVar27.Attributes = tempVar28Slice
			_, tempVar29Slice := arena.GetAttrWriterSlice(5)
			tempVar27.AttributeWriters = tempVar29Slice
			_, tempVar30Slice := arena.GetChildSlice(3)
			tempVar27.Children = tempVar30Slice
			tempVar27.Attributes = append(tempVar27.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_row_actions_c2843091"})
			tempVar27.Attributes = append(tempVar27.Attributes, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "row_actions"})
			tempVar31 := arena.GetDirectWriter()
			tempVar31.SetName("category_name")
			tempVar31.AppendEscapeString(pageData.CategoryName)
			tempVar27.AttributeWriters = append(tempVar27.AttributeWriters, tempVar31)
			tempVar32 := arena.GetDirectWriter()
			tempVar32.SetName("container_id")
			tempVar32.AppendEscapeString(pageData.ContainerID)
			tempVar27.AttributeWriters = append(tempVar27.AttributeWriters, tempVar32)
			tempVar33 := arena.GetDirectWriter()
			tempVar33.SetName("row_id")
			tempVar33.AppendEscapeString(row.ID)
			tempVar27.AttributeWriters = append(tempVar27.AttributeWriters, tempVar33)
			tempVar34 := arena.GetDirectWriter()
			tempVar34.SetName("row_title")
			tempVar34.AppendEscapeString(row.Title)
			tempVar27.AttributeWriters = append(tempVar27.AttributeWriters, tempVar34)
			tempVar27.Attributes = append(tempVar27.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "row-actions"})
			tempVar35 := arena.GetDirectWriter()
			tempVar35.SetName("p-key")
			tempVar35.AppendString("r.0:0:0:0.")
			tempVar35.AppendFNVString(row.ID)
			tempVar35.AppendString(":1:0")
			tempVar27.AttributeWriters = append(tempVar27.AttributeWriters, tempVar35)
			// line partials/row_actions.pk:23
			tempVar36 := arena.GetNode()
			tempVar36.NodeType = pikoruntime.NodeElement
			tempVar36.TagName = "button"
			_, tempVar37Slice := arena.GetAttrSlice(2)
			tempVar36.Attributes = tempVar37Slice
			_, tempVar38Slice := arena.GetAttrWriterSlice(1)
			tempVar36.AttributeWriters = tempVar38Slice
			_, tempVar39Slice := arena.GetChildSlice(1)
			tempVar36.Children = tempVar39Slice
			tempVar36.Attributes = append(tempVar36.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_row_actions_c2843091"})
			tempVar36.Attributes = append(tempVar36.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "edit-btn"})
			tempVar40 := arena.GetDirectWriter()
			tempVar40.SetName("p-key")
			tempVar40.AppendString("r.0:0:0:0.")
			tempVar40.AppendFNVString(row.ID)
			tempVar40.AppendString(":1:0:0")
			tempVar36.AttributeWriters = append(tempVar36.AttributeWriters, tempVar40)
			// line partials/row_actions.pk:23
			tempVar41 := arena.GetNode()
			tempVar41.NodeType = pikoruntime.NodeText
			tempVar42 := arena.GetDirectWriter()
			tempVar42.AppendString("Edit ")
			tempVar42.AppendEscapeString(partials_row_actions_c2843091Data_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af.DisplayTitle)
			tempVar41.TextContentWriter = tempVar42
			tempVar36.Children = append(tempVar36.Children, tempVar41)
			tempVar27.Children = append(tempVar27.Children, tempVar36)
			// line partials/row_actions.pk:24
			tempVar43 := arena.GetNode()
			tempVar43.NodeType = pikoruntime.NodeElement
			tempVar43.TagName = "a"
			_, tempVar44Slice := arena.GetAttrSlice(2)
			tempVar43.Attributes = tempVar44Slice
			_, tempVar45Slice := arena.GetAttrWriterSlice(2)
			tempVar43.AttributeWriters = tempVar45Slice
			_, tempVar46Slice := arena.GetChildSlice(1)
			tempVar43.Children = tempVar46Slice
			tempVar43.Attributes = append(tempVar43.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_row_actions_c2843091"})
			tempVar47 := arena.GetDirectWriter()
			tempVar47.SetName("href")
			tempVar47.AppendEscapeString(partials_row_actions_c2843091Data_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af.EditURL)
			tempVar43.AttributeWriters = append(tempVar43.AttributeWriters, tempVar47)
			tempVar43.Attributes = append(tempVar43.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "edit-link"})
			tempVar48 := arena.GetDirectWriter()
			tempVar48.SetName("p-key")
			tempVar48.AppendString("r.0:0:0:0.")
			tempVar48.AppendFNVString(row.ID)
			tempVar48.AppendString(":1:0:1")
			tempVar43.AttributeWriters = append(tempVar43.AttributeWriters, tempVar48)
			// line partials/row_actions.pk:24
			tempVar49 := arena.GetNode()
			tempVar49.NodeType = pikoruntime.NodeText
			tempVar50 := arena.GetDirectWriter()
			tempVar50.AppendString("Go to ")
			tempVar50.AppendEscapeString(partials_row_actions_c2843091Data_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af.DisplayTitle)
			tempVar49.TextContentWriter = tempVar50
			tempVar43.Children = append(tempVar43.Children, tempVar49)
			tempVar27.Children = append(tempVar27.Children, tempVar43)
			// line partials/row_actions.pk:25
			tempVar51 := arena.GetNode()
			tempVar51.NodeType = pikoruntime.NodeElement
			tempVar51.TagName = "span"
			_, tempVar52Slice := arena.GetAttrSlice(2)
			tempVar51.Attributes = tempVar52Slice
			_, tempVar53Slice := arena.GetAttrWriterSlice(1)
			tempVar51.AttributeWriters = tempVar53Slice
			_, tempVar54Slice := arena.GetChildSlice(1)
			tempVar51.Children = tempVar54Slice
			tempVar51.Attributes = append(tempVar51.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_row_actions_c2843091"})
			tempVar51.Attributes = append(tempVar51.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "category"})
			tempVar55 := arena.GetDirectWriter()
			tempVar55.SetName("p-key")
			tempVar55.AppendString("r.0:0:0:0.")
			tempVar55.AppendFNVString(row.ID)
			tempVar55.AppendString(":1:0:2")
			tempVar51.AttributeWriters = append(tempVar51.AttributeWriters, tempVar55)
			// line partials/row_actions.pk:25
			tempVar56 := arena.GetNode()
			tempVar56.NodeType = pikoruntime.NodeText
			tempVar57 := arena.GetDirectWriter()
			tempVar57.AppendEscapeString(partials_row_actions_c2843091Data_row_actions_category_name_state_categoryname_container_id_state_containerid_row_id_row_id_row_title_row_title_839351af.CategoryLabel)
			tempVar56.TextContentWriter = tempVar57
			tempVar51.Children = append(tempVar51.Children, tempVar56)
			tempVar27.Children = append(tempVar27.Children, tempVar51)
			tempVar22.Children = append(tempVar22.Children, tempVar27)
			tempVar7.Children = append(tempVar7.Children, tempVar22)
			tempVar5.Children = append(tempVar5.Children, tempVar7)
		}
	}
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 23
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 24
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "container"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_133_partial_sibling_of_nested_loop/dist/pages/pages_main_594861c5", BuildAST)
}
