// Code generated by Piko. DO NOT EDIT.

package db

import "context"

const getstaleprocessingtaskcount = `SELECT COUNT(*) FROM tasks
WHERE status = 'PROCESSING'
AND updated_at < ?;`

type GetStaleProcessingTaskCountRow struct {
	Count int64 `json:"count"`
}

func (queries *Queries) GetStaleProcessingTaskCount(ctx context.Context, updatedAt int64) (GetStaleProcessingTaskCountRow, error) {
	var row GetStaleProcessingTaskCountRow
	err := queries.reader.QueryRowContext(ctx, getstaleprocessingtaskcount, updatedAt).Scan(&row.Count)
	if err != nil {
		return GetStaleProcessingTaskCountRow{}, err
	}
	return row, nil
}

const updatetaskheartbeat = `UPDATE tasks
SET updated_at = ?
WHERE id = ? AND status = 'PROCESSING';`

type UpdateTaskHeartbeatParams struct {
	UpdatedAt int64
	ID        string
}

func (queries *Queries) UpdateTaskHeartbeat(ctx context.Context, params UpdateTaskHeartbeatParams) error {
	_, err := queries.writer.ExecContext(ctx, updatetaskheartbeat, params.UpdatedAt, params.ID)
	return err
}
