// Code generated by Piko. DO NOT EDIT.

package db

import (
	"slices"
	"strconv"
	"strings"
)

type pikoSliceExpansionSpec struct {
	Placeholder int
	Count       int
}

func pikoExpandSlicePlaceholders(query string, specs []pikoSliceExpansionSpec) string {
	if len(specs) == 0 {
		return query
	}

	sorted := make([]pikoSliceExpansionSpec, len(specs))
	copy(sorted, specs)
	slices.SortFunc(sorted, func(a, b pikoSliceExpansionSpec) int {
		return a.Placeholder - b.Placeholder
	})

	type mapping struct {
		newStart int
		count    int
	}
	remap := make(map[int]mapping, len(sorted))
	pos := 1
	for _, spec := range sorted {
		remap[spec.Placeholder] = mapping{newStart: pos, count: spec.Count}
		if spec.Count > 0 {
			pos += spec.Count
		}
	}

	type occurrence struct {
		start       int
		end         int
		originalNum int
		inParens    bool
	}

	var occurrences []occurrence
	i := 0
	for i < len(query) {
		if query[i] == '?' && i+1 < len(query) && query[i+1] >= '1' && query[i+1] <= '9' {
			start := i
			i++
			numStart := i
			for i < len(query) && query[i] >= '0' && query[i] <= '9' {
				i++
			}
			n, _ := strconv.Atoi(query[numStart:i])
			inParens := start > 0 && query[start-1] == '(' && i < len(query) && query[i] == ')'
			occurrences = append(occurrences, occurrence{start: start, end: i, originalNum: n, inParens: inParens})
		} else {
			i++
		}
	}

	if len(occurrences) == 0 {
		return query
	}

	var b strings.Builder
	b.Grow(len(query) + len(occurrences)*4)
	prevEnd := 0
	for _, occ := range occurrences {
		m, ok := remap[occ.originalNum]
		if !ok {
			continue
		}
		replStart := occ.start
		replEnd := occ.end
		var replacement string
		switch {
		case m.count == 0 && occ.inParens:
			replacement = "(NULL)"
			replStart--
			replEnd++
		case m.count > 1 && occ.inParens:
			var sb strings.Builder
			sb.Grow(m.count*4 + 2)
			sb.WriteByte('(')
			for j := range m.count {
				if j > 0 {
					sb.WriteByte(',')
				}
				sb.WriteByte('?')
				sb.WriteString(strconv.Itoa(m.newStart + j))
			}
			sb.WriteByte(')')
			replacement = sb.String()
			replStart--
			replEnd++
		default:
			replacement = "?" + strconv.Itoa(m.newStart)
		}
		b.WriteString(query[prevEnd:replStart])
		b.WriteString(replacement)
		prevEnd = replEnd
	}
	b.WriteString(query[prevEnd:])
	return b.String()
}
