// Code generated by Piko. DO NOT EDIT.

package db

import "context"

const createworkflowreceipt = `INSERT INTO workflow_receipts (
    id, workflow_id, node_id, status, created_at, updated_at
) VALUES (?, ?, ?, 'PENDING', ?, ?);`

type CreateWorkflowReceiptParams struct {
	ID         string
	WorkflowID string
	NodeID     string
	CreatedAt  int64
	UpdatedAt  int64
}

func (queries *Queries) CreateWorkflowReceipt(ctx context.Context, params CreateWorkflowReceiptParams) error {
	_, err := queries.writer.ExecContext(ctx, createworkflowreceipt, params.ID, params.WorkflowID, params.NodeID, params.CreatedAt, params.UpdatedAt)
	return err
}

const getpendingreceiptsbynode = `SELECT id, workflow_id, created_at
FROM workflow_receipts
WHERE node_id = ? AND status = 'PENDING';`

type GetPendingReceiptsByNodeRow struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (queries *Queries) GetPendingReceiptsByNode(ctx context.Context, nodeID string) ([]GetPendingReceiptsByNodeRow, error) {
	rows, err := queries.reader.QueryContext(ctx, getpendingreceiptsbynode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetPendingReceiptsByNodeRow
	for rows.Next() {
		var row GetPendingReceiptsByNodeRow
		if err := rows.Scan(&row.ID, &row.WorkflowID, &row.CreatedAt); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const getpendingreceiptsbyworkflow = `SELECT id, workflow_id, node_id, created_at
FROM workflow_receipts
WHERE workflow_id = ? AND status = 'PENDING';`

type GetPendingReceiptsByWorkflowRow struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	NodeID     string `json:"node_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (queries *Queries) GetPendingReceiptsByWorkflow(ctx context.Context, workflowID string) ([]GetPendingReceiptsByWorkflowRow, error) {
	rows, err := queries.reader.QueryContext(ctx, getpendingreceiptsbyworkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetPendingReceiptsByWorkflowRow
	for rows.Next() {
		var row GetPendingReceiptsByWorkflowRow
		if err := rows.Scan(&row.ID, &row.WorkflowID, &row.NodeID, &row.CreatedAt); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const getworkflowstatus = `SELECT EXISTS(
    SELECT 1 FROM tasks
    WHERE workflow_id = ?
    AND status NOT IN ('COMPLETE', 'FAILED')
) AS has_incomplete;`

type GetWorkflowStatusRow struct {
	HasIncomplete bool `json:"has_incomplete"`
}

func (queries *Queries) GetWorkflowStatus(ctx context.Context, workflowID string) (GetWorkflowStatusRow, error) {
	var row GetWorkflowStatusRow
	err := queries.reader.QueryRowContext(ctx, getworkflowstatus, workflowID).Scan(&row.HasIncomplete)
	if err != nil {
		return GetWorkflowStatusRow{}, err
	}
	return row, nil
}

const resolveworkflowreceipts = `UPDATE workflow_receipts
SET status = 'RESOLVED',
    error_message = ?,
    updated_at = ?,
    resolved_at = ?
WHERE workflow_id = ? AND status = 'PENDING';`

type ResolveWorkflowReceiptsParams struct {
	ErrorMessage *string
	UpdatedAt    int64
	ResolvedAt   *int64
	WorkflowID   string
}

func (queries *Queries) ResolveWorkflowReceipts(ctx context.Context, params ResolveWorkflowReceiptsParams) (int64, error) {
	results, err := queries.writer.ExecContext(ctx, resolveworkflowreceipts, params.ErrorMessage, params.UpdatedAt, params.ResolvedAt, params.WorkflowID)
	if err != nil {
		return 0, err
	}
	return results.RowsAffected()
}
