/* Code generated by piko; DO NOT EDIT. */

import { ActionBuilder, createActionBuilder } from '/_piko/dist/ppframework.core.es.js';
export interface CreateInput {
  product: string;
  quantity: number;
  shippingAddress: Address;
}
export interface CreateResponse {
  product: string;
  quantity: number;
  street: string;
  city: string;
  postcode: string;
}
/**
 * CreateAction handles order creation with nested address.
 */
export function orderCreate(input: CreateInput): ActionBuilder<CreateResponse> {
  return createActionBuilder<CreateResponse>('order.Create', input);
}
export const action = {
  order: {
    Create: orderCreate
  }
} as const;
