//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}

// line pages/main.pk:45
func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string = []string{"p-partial"}

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(7)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	tempVar1.Children = append(tempVar1.Children, staticNode_2)
	tempVar1.Children = append(tempVar1.Children, staticNode_3)
	tempVar1.Children = append(tempVar1.Children, staticNode_4)
	// line pages/main.pk:32
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "p-partial"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetAttrWriterSlice(1)
	tempVar3.AttributeWriters = tempVar4Slice
	tempVar5 := arena.GetDirectWriter()
	tempVar5.SetName("title")
	tempVar5.AppendString("Card A")
	tempVar3.AttributeWriters = append(tempVar3.AttributeWriters, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	// line pages/main.pk:34
	tempVar6 := arena.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "p-partial"
	tempVar6.Attributes = staticAttrs_3
	_, tempVar7Slice := arena.GetAttrWriterSlice(1)
	tempVar6.AttributeWriters = tempVar7Slice
	tempVar8 := arena.GetDirectWriter()
	tempVar8.SetName("title")
	tempVar8.AppendString("Card B")
	tempVar6.AttributeWriters = append(tempVar6.AttributeWriters, tempVar8)
	tempVar1.Children = append(tempVar1.Children, tempVar6)
	// line pages/main.pk:36
	tempVar9 := arena.GetNode()
	tempVar9.NodeType = pikoruntime.NodeElement
	tempVar9.TagName = "p-partial"
	tempVar9.Attributes = staticAttrs_4
	_, tempVar10Slice := arena.GetAttrWriterSlice(1)
	tempVar9.AttributeWriters = tempVar10Slice
	tempVar11 := arena.GetDirectWriter()
	tempVar11.SetName("title")
	tempVar11.AppendString("Card C")
	tempVar9.AttributeWriters = append(tempVar9.AttributeWriters, tempVar11)
	tempVar1.Children = append(tempVar1.Children, tempVar9)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticAttrs_2        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 32
	staticAttrs_3        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 34
	staticAttrs_4        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 36
	staticNode_1         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_1_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_2         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 24
	staticNode_2_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 24
	staticNode_3         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 29
	staticNode_4         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 30
	staticNode_4_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 30
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "h1"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Nested Partials with Scoped Refs Test"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "p"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0.TextContent = " This page tests that p-ref is scoped to each partial. Multiple partials can have the same ref name without conflict. "
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "input"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 6)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-ref", Value: "inputField"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "data-pk-partial", Value: "pages_main_594861c5"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "type", Value: "text"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "placeholder", Value: "Page-level input"})
	staticNode_4 = &pikoruntime.TemplateNode{}
	staticNode_4.NodeType = pikoruntime.NodeElement
	staticNode_4.TagName = "button"
	staticNode_4.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:3"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-on:click", Value: "eyJmIjoiZm9jdXNQYWdlSW5wdXQiLCJhIjpbXX0"})
	staticNode_4.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_0.TextContent = "Focus Page Input"
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_0)
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:4"}, pikoruntime.HTMLAttribute{Name: "name", Value: "card"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:5"}, pikoruntime.HTMLAttribute{Name: "name", Value: "card"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:6"}, pikoruntime.HTMLAttribute{Name: "name", Value: "card"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_083_pk_p_ref_nested_scoping/dist/pages/pages_main_594861c5", BuildAST)
}
