//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_level1_d7f1f2b7 "testcase_099_partial_external_pkg_import_deep_nesting/dist/partials/partials_level1_d7f1f2b7"
	partials_level2_a0cb46b5 "testcase_099_partial_external_pkg_import_deep_nesting/dist/partials/partials_level2_a0cb46b5"
	partials_level3_b25210fb "testcase_099_partial_external_pkg_import_deep_nesting/dist/partials/partials_level3_b25210fb"
	formatter "testcase_099_partial_external_pkg_import_deep_nesting/pkg/formatter"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_level1_d7f1f2b7.Render

// line pages/main.pk:35
func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_level1_content_hello_deep_world_c6871fc3 := partials_level1_d7f1f2b7.Props{Content: "hello deep world"}
	partials_level1_d7f1f2b7Data_level1_content_hello_deep_world_c6871fc3, partials_level1_d7f1f2b7Meta_level1_content_hello_deep_world_c6871fc3, partials_level1_d7f1f2b7Err_level1_content_hello_deep_world_c6871fc3 := partials_level1_d7f1f2b7.Render(r, props_level1_content_hello_deep_world_c6871fc3)
	if partials_level1_d7f1f2b7Err_level1_content_hello_deep_world_c6871fc3 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_level1_d7f1f2b7Err_level1_content_hello_deep_world_c6871fc3.Error(), "R002", "", "Partial Render() error for partials_level1_d7f1f2b7", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_level1_d7f1f2b7Data_level1_content_hello_deep_world_c6871fc3
	_ = partials_level1_d7f1f2b7Meta_level1_content_hello_deep_world_c6871fc3
	_ = partials_level1_d7f1f2b7Err_level1_content_hello_deep_world_c6871fc3
	props_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf := partials_level2_a0cb46b5.Props{Text: props_level1_content_hello_deep_world_c6871fc3.Content}
	partials_level2_a0cb46b5Data_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf, partials_level2_a0cb46b5Meta_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf, partials_level2_a0cb46b5Err_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf := partials_level2_a0cb46b5.Render(r, props_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf)
	if partials_level2_a0cb46b5Err_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_level2_a0cb46b5Err_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf.Error(), "R002", "", "Partial Render() error for partials_level2_a0cb46b5", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_level2_a0cb46b5Data_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf
	_ = partials_level2_a0cb46b5Meta_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf
	_ = partials_level2_a0cb46b5Err_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf
	props_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e := partials_level3_b25210fb.Props{Message: props_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf.Text}
	partials_level3_b25210fbData_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e, partials_level3_b25210fbMeta_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e, partials_level3_b25210fbErr_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e := partials_level3_b25210fb.Render(r, props_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e)
	if partials_level3_b25210fbErr_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_level3_b25210fbErr_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e.Error(), "R002", "", "Partial Render() error for partials_level3_b25210fb", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_level3_b25210fbData_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e
	_ = partials_level3_b25210fbMeta_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e
	_ = partials_level3_b25210fbErr_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	// line partials/level1.pk:22
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "div"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(1)
	tempVar3.Children = tempVar4Slice
	// line partials/level2.pk:22
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "div"
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetAttrWriterSlice(1)
	tempVar5.AttributeWriters = tempVar6Slice
	_, tempVar7Slice := arena.GetChildSlice(1)
	tempVar5.Children = tempVar7Slice
	tempVar8 := arena.GetDirectWriter()
	tempVar8.SetName("text")
	tempVar8.AppendEscapeString(props_level1_content_hello_deep_world_c6871fc3.Content)
	tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar8)
	// line partials/level3.pk:22
	tempVar9 := arena.GetNode()
	tempVar9.NodeType = pikoruntime.NodeElement
	tempVar9.TagName = "div"
	tempVar9.Attributes = staticAttrs_4
	_, tempVar10Slice := arena.GetAttrWriterSlice(1)
	tempVar9.AttributeWriters = tempVar10Slice
	_, tempVar11Slice := arena.GetChildSlice(1)
	tempVar9.Children = tempVar11Slice
	tempVar12 := arena.GetDirectWriter()
	tempVar12.SetName("message")
	tempVar12.AppendEscapeString(props_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf.Text)
	tempVar9.AttributeWriters = append(tempVar9.AttributeWriters, tempVar12)
	// line partials/level3.pk:23
	tempVar13 := arena.GetNode()
	tempVar13.NodeType = pikoruntime.NodeElement
	tempVar13.TagName = "span"
	tempVar13.Attributes = staticAttrs_5
	_, tempVar14Slice := arena.GetChildSlice(1)
	tempVar13.Children = tempVar14Slice
	// line partials/level3.pk:23
	tempVar15 := arena.GetNode()
	tempVar15.NodeType = pikoruntime.NodeText
	tempVar16 := arena.GetDirectWriter()
	tempVar16.AppendEscapeString(formatter.FormatDeep(props_level3_level2_level1_content_hello_deep_world_c6871fc3_text_props_content_af16c4bf_message_props_text_ef3bd93e.Message))
	tempVar15.TextContentWriter = tempVar16
	tempVar13.Children = append(tempVar13.Children, tempVar15)
	tempVar9.Children = append(tempVar9.Children, tempVar13)
	tempVar5.Children = append(tempVar5.Children, tempVar9)
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticAttrs_2        []pikoruntime.HTMLAttribute // SOURCE: partials/level1.pk, LINE: 22
	staticAttrs_3        []pikoruntime.HTMLAttribute // SOURCE: partials/level2.pk, LINE: 22
	staticAttrs_4        []pikoruntime.HTMLAttribute // SOURCE: partials/level3.pk, LINE: 22
	staticAttrs_5        []pikoruntime.HTMLAttribute // SOURCE: partials/level3.pk, LINE: 23
	staticNode_1         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_1_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "page"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "h1"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Deep Nesting Test"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level1_d7f1f2b7"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level1"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "level1"}, pikoruntime.HTMLAttribute{Name: "content", Value: "hello deep world"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level2_a0cb46b5"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level2"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "level2"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level3_b25210fb"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "level3"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level3_b25210fb"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0:0"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_099_partial_external_pkg_import_deep_nesting/dist/pages/pages_main_594861c5", BuildAST)
}
