/* Code generated by piko; DO NOT EDIT. */

import { ActionBuilder, createActionBuilder, registerActionFunction } from '/_piko/dist/ppframework.core.es.js';
export interface ProcessInput {
  delayMs: number;
}
export interface ProcessResponse {
  completed: boolean;
  message: string;
}
/**
 * ProcessAction processes with a configurable delay.
 */
export function slowProcess(input: ProcessInput): ActionBuilder<ProcessResponse> {
  return createActionBuilder<ProcessResponse>('slow.Process', input);
}
export const action = {
  slow: {
    Process: slowProcess
  }
} as const;
registerActionFunction('slow.Process', slowProcess);
