// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DiagnosticFB struct {
	_tab flatbuffers.Table
}

func GetRootAsDiagnosticFB(buf []byte, offset flatbuffers.UOffsetT) *DiagnosticFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DiagnosticFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishDiagnosticFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDiagnosticFB(buf []byte, offset flatbuffers.UOffsetT) *DiagnosticFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DiagnosticFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDiagnosticFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DiagnosticFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DiagnosticFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DiagnosticFB) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DiagnosticFB) Severity() Severity {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Severity(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DiagnosticFB) MutateSeverity(n Severity) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *DiagnosticFB) Location(obj *LocationFB) *LocationFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LocationFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DiagnosticFB) Expression() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DiagnosticFB) SourcePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DiagnosticFB) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DiagnosticFB) RelatedInfo(obj *DiagnosticRelatedInfoFB, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DiagnosticFB) RelatedInfoLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DiagnosticFB) Data(obj *DiagnosticDataEntryFB, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DiagnosticFB) DataByKey(obj *DiagnosticDataEntryFB, key string) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		return obj.LookupByKey(key, x, rcv._tab.Bytes)
	}
	return false
}

func (rcv *DiagnosticFB) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DiagnosticFB) SourceLength() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DiagnosticFB) MutateSourceLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func DiagnosticFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func DiagnosticFBAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func DiagnosticFBAddSeverity(builder *flatbuffers.Builder, severity Severity) {
	builder.PrependByteSlot(1, byte(severity), 0)
}
func DiagnosticFBAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(location), 0)
}
func DiagnosticFBAddExpression(builder *flatbuffers.Builder, expression flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(expression), 0)
}
func DiagnosticFBAddSourcePath(builder *flatbuffers.Builder, sourcePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(sourcePath), 0)
}
func DiagnosticFBAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(code), 0)
}
func DiagnosticFBAddRelatedInfo(builder *flatbuffers.Builder, relatedInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(relatedInfo), 0)
}
func DiagnosticFBStartRelatedInfoVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DiagnosticFBAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(data), 0)
}
func DiagnosticFBStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DiagnosticFBAddSourceLength(builder *flatbuffers.Builder, sourceLength int32) {
	builder.PrependInt32Slot(8, sourceLength, 0)
}
func DiagnosticFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
