// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DirectWriterFB struct {
	_tab flatbuffers.Table
}

func GetRootAsDirectWriterFB(buf []byte, offset flatbuffers.UOffsetT) *DirectWriterFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DirectWriterFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishDirectWriterFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDirectWriterFB(buf []byte, offset flatbuffers.UOffsetT) *DirectWriterFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DirectWriterFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDirectWriterFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DirectWriterFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DirectWriterFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DirectWriterFB) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DirectWriterFB) Parts(obj *WriterPartFB, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DirectWriterFB) PartsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DirectWriterFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DirectWriterFBAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func DirectWriterFBAddParts(builder *flatbuffers.Builder, parts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(parts), 0)
}
func DirectWriterFBStartPartsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DirectWriterFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
