// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IndexExprFB struct {
	_tab flatbuffers.Table
}

func GetRootAsIndexExprFB(buf []byte, offset flatbuffers.UOffsetT) *IndexExprFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IndexExprFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishIndexExprFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIndexExprFB(buf []byte, offset flatbuffers.UOffsetT) *IndexExprFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IndexExprFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIndexExprFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IndexExprFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IndexExprFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IndexExprFB) Base(obj *ExpressionNodeFB) *ExpressionNodeFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ExpressionNodeFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *IndexExprFB) Index(obj *ExpressionNodeFB) *ExpressionNodeFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ExpressionNodeFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *IndexExprFB) Optional() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *IndexExprFB) MutateOptional(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *IndexExprFB) RelativeLocation(obj *LocationFB) *LocationFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LocationFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func IndexExprFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func IndexExprFBAddBase(builder *flatbuffers.Builder, base flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(base), 0)
}
func IndexExprFBAddIndex(builder *flatbuffers.Builder, index flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(index), 0)
}
func IndexExprFBAddOptional(builder *flatbuffers.Builder, optional bool) {
	builder.PrependBoolSlot(2, optional, false)
}
func IndexExprFBAddRelativeLocation(builder *flatbuffers.Builder, relativeLocation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(relativeLocation), 0)
}
func IndexExprFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
