// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IntegerLiteralFB struct {
	_tab flatbuffers.Table
}

func GetRootAsIntegerLiteralFB(buf []byte, offset flatbuffers.UOffsetT) *IntegerLiteralFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IntegerLiteralFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishIntegerLiteralFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIntegerLiteralFB(buf []byte, offset flatbuffers.UOffsetT) *IntegerLiteralFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IntegerLiteralFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIntegerLiteralFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IntegerLiteralFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IntegerLiteralFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IntegerLiteralFB) Value() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IntegerLiteralFB) MutateValue(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *IntegerLiteralFB) RelativeLocation(obj *LocationFB) *LocationFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LocationFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func IntegerLiteralFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IntegerLiteralFBAddValue(builder *flatbuffers.Builder, value int64) {
	builder.PrependInt64Slot(0, value, 0)
}
func IntegerLiteralFBAddRelativeLocation(builder *flatbuffers.Builder, relativeLocation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(relativeLocation), 0)
}
func IntegerLiteralFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
