// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResolvedTypeInfoFB struct {
	_tab flatbuffers.Table
}

func GetRootAsResolvedTypeInfoFB(buf []byte, offset flatbuffers.UOffsetT) *ResolvedTypeInfoFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResolvedTypeInfoFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishResolvedTypeInfoFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResolvedTypeInfoFB(buf []byte, offset flatbuffers.UOffsetT) *ResolvedTypeInfoFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResolvedTypeInfoFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResolvedTypeInfoFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ResolvedTypeInfoFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResolvedTypeInfoFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResolvedTypeInfoFB) TypeExprString() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResolvedTypeInfoFB) PackageAlias() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResolvedTypeInfoFB) CanonicalPackagePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResolvedTypeInfoFB) InitialPackagePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResolvedTypeInfoFB) InitialFilePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResolvedTypeInfoFB) IsSynthetic() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ResolvedTypeInfoFB) MutateIsSynthetic(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *ResolvedTypeInfoFB) IsExportedPackageSymbol() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ResolvedTypeInfoFB) MutateIsExportedPackageSymbol(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func ResolvedTypeInfoFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ResolvedTypeInfoFBAddTypeExprString(builder *flatbuffers.Builder, typeExprString flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(typeExprString), 0)
}
func ResolvedTypeInfoFBAddPackageAlias(builder *flatbuffers.Builder, packageAlias flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(packageAlias), 0)
}
func ResolvedTypeInfoFBAddCanonicalPackagePath(builder *flatbuffers.Builder, canonicalPackagePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(canonicalPackagePath), 0)
}
func ResolvedTypeInfoFBAddInitialPackagePath(builder *flatbuffers.Builder, initialPackagePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(initialPackagePath), 0)
}
func ResolvedTypeInfoFBAddInitialFilePath(builder *flatbuffers.Builder, initialFilePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(initialFilePath), 0)
}
func ResolvedTypeInfoFBAddIsSynthetic(builder *flatbuffers.Builder, isSynthetic bool) {
	builder.PrependBoolSlot(5, isSynthetic, false)
}
func ResolvedTypeInfoFBAddIsExportedPackageSymbol(builder *flatbuffers.Builder, isExportedPackageSymbol bool) {
	builder.PrependBoolSlot(6, isExportedPackageSymbol, false)
}
func ResolvedTypeInfoFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
