// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TemplateLiteralFB struct {
	_tab flatbuffers.Table
}

func GetRootAsTemplateLiteralFB(buf []byte, offset flatbuffers.UOffsetT) *TemplateLiteralFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TemplateLiteralFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishTemplateLiteralFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTemplateLiteralFB(buf []byte, offset flatbuffers.UOffsetT) *TemplateLiteralFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TemplateLiteralFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTemplateLiteralFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TemplateLiteralFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TemplateLiteralFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TemplateLiteralFB) Parts(obj *TemplateLiteralPartFB, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TemplateLiteralFB) PartsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TemplateLiteralFB) RelativeLocation(obj *LocationFB) *LocationFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LocationFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TemplateLiteralFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TemplateLiteralFBAddParts(builder *flatbuffers.Builder, parts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(parts), 0)
}
func TemplateLiteralFBStartPartsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TemplateLiteralFBAddRelativeLocation(builder *flatbuffers.Builder, relativeLocation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(relativeLocation), 0)
}
func TemplateLiteralFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
