// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ast_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TemplateLiteralPartFB struct {
	_tab flatbuffers.Table
}

func GetRootAsTemplateLiteralPartFB(buf []byte, offset flatbuffers.UOffsetT) *TemplateLiteralPartFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TemplateLiteralPartFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishTemplateLiteralPartFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTemplateLiteralPartFB(buf []byte, offset flatbuffers.UOffsetT) *TemplateLiteralPartFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TemplateLiteralPartFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTemplateLiteralPartFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TemplateLiteralPartFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TemplateLiteralPartFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TemplateLiteralPartFB) IsLiteral() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TemplateLiteralPartFB) MutateIsLiteral(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *TemplateLiteralPartFB) Literal() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TemplateLiteralPartFB) RawExpression() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TemplateLiteralPartFB) Expression(obj *ExpressionNodeFB) *ExpressionNodeFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ExpressionNodeFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TemplateLiteralPartFB) Location(obj *LocationFB) *LocationFB {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LocationFB)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TemplateLiteralPartFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TemplateLiteralPartFBAddIsLiteral(builder *flatbuffers.Builder, isLiteral bool) {
	builder.PrependBoolSlot(0, isLiteral, false)
}
func TemplateLiteralPartFBAddLiteral(builder *flatbuffers.Builder, literal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(literal), 0)
}
func TemplateLiteralPartFBAddRawExpression(builder *flatbuffers.Builder, rawExpression flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(rawExpression), 0)
}
func TemplateLiteralPartFBAddExpression(builder *flatbuffers.Builder, expression flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(expression), 0)
}
func TemplateLiteralPartFBAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(location), 0)
}
func TemplateLiteralPartFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
