//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_child_card_c2888b08

import (
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}

// line partials/child_card.pk:36
type Response struct{ Info string }

// line partials/child_card.pk:40
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Info: "Child"}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	rootAST.RootNodes = append(rootAST.RootNodes, staticNode_1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticNode_1                         *pikoruntime.TemplateNode // SOURCE: partials/child_card.pk, LINE: 22
	staticNode_1_child_0                 *pikoruntime.TemplateNode // SOURCE: partials/child_card.pk, LINE: 23
	staticNode_1_child_0_child_0         *pikoruntime.TemplateNode // SOURCE: partials/child_card.pk, LINE: 24
	staticNode_1_child_0_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: partials/child_card.pk, LINE: 24
)

func init() {
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "div"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 4)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "child-wrapper"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_card_c2888b08"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "child_card"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0.TagName = "div"
	staticNode_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_card_c2888b08"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "card"})
	staticNode_1_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0_child_0.TagName = "span"
	staticNode_1_child_0_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 3)
	staticNode_1_child_0_child_0.Attributes = append(staticNode_1_child_0_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_card_c2888b08"})
	staticNode_1_child_0_child_0.Attributes = append(staticNode_1_child_0_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"})
	staticNode_1_child_0_child_0.Attributes = append(staticNode_1_child_0_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "title"})
	staticNode_1_child_0_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0_child_0_child_0.TextContent = "Child Card Title"
	staticNode_1_child_0_child_0.Children = append(staticNode_1_child_0_child_0.Children, staticNode_1_child_0_child_0_child_0)
	staticNode_1_child_0.Children = append(staticNode_1_child_0.Children, staticNode_1_child_0_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_090_css_scoping_proper_isolation/dist/partials/partials_child_card_c2888b08", BuildAST)
}
