// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

/* Code generated by piko; DO NOT EDIT. */

package pages_auth_eadff339

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html"
	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"sort"
	"strconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = json.Compact
var _ = base64.StdEncoding
var _ = pikoruntime.EvaluateTruthiness
var _ = piko.Metadata{}

type Response struct {
	IsLoggedIn bool
	IsAdmin    bool
	Username   string
}

func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	isLoggedIn := false
	isAdmin := false
	username := ""
	authState := r.URL.Query().Get("auth")
	if authState == "user" {
		isLoggedIn = true
		username = "JohnDoe"
	} else if authState == "admin" {
		isLoggedIn = true
		isAdmin = true
		username = "AdminUser"
	}
	return Response{IsLoggedIn: isLoggedIn, IsAdmin: isAdmin, Username: username}, piko.Metadata{Title: "Authentication State"}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}
func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diags []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diags = pikoruntime.AppendDiagnostic(diags, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diags
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: []string{}}, diags
	}
	rootAST := &pikoruntime.TemplateAST{}
	rootAST.RootNodes = make([]*pikoruntime.TemplateNode, 0, 1)
	tempVar1 := pikoruntime.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar1.Children = make([]*pikoruntime.TemplateNode, 0, 3)
	tempVar1.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar1.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar1.Attributes = append(tempVar1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "auth-container"})
	tempVar1.Attributes = append(tempVar1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"})
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	tempVar2 := pikoruntime.GetNode()
	tempVar2.NodeType = pikoruntime.NodeElement
	tempVar2.TagName = "section"
	tempVar2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar2.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	tempVar2.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar2.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar2.Attributes = append(tempVar2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "user-status"})
	tempVar2.Attributes = append(tempVar2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"})
	if pageData.IsLoggedIn {
		tempVar3 := pikoruntime.GetNode()
		tempVar3.NodeType = pikoruntime.NodeElement
		tempVar3.TagName = "div"
		tempVar3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
		tempVar3.Children = make([]*pikoruntime.TemplateNode, 0, 3)
		tempVar3.OnEvents = make(map[string][]pikoruntime.Directive)
		tempVar3.CustomEvents = make(map[string][]pikoruntime.Directive)
		tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "logged-in"})
		tempVar3.Attributes = append(tempVar3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"})
		tempVar4 := pikoruntime.GetNode()
		tempVar4.NodeType = pikoruntime.NodeElement
		tempVar4.TagName = "p"
		tempVar4.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
		tempVar4.Children = make([]*pikoruntime.TemplateNode, 0, 1)
		tempVar4.OnEvents = make(map[string][]pikoruntime.Directive)
		tempVar4.CustomEvents = make(map[string][]pikoruntime.Directive)
		tempVar4.Attributes = append(tempVar4.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "welcome-message"})
		tempVar4.Attributes = append(tempVar4.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:0"})
		tempVar5 := pikoruntime.GetNode()
		tempVar5.NodeType = pikoruntime.NodeText
		tempVar5.TextContent = "Welcome, " + html.EscapeString(pageData.Username) + "!"
		tempVar4.Children = append(tempVar4.Children, tempVar5)
		tempVar3.Children = append(tempVar3.Children, tempVar4)
		if pageData.IsAdmin {
			tempVar3.Children = append(tempVar3.Children, staticNode_2)
		} else {
			tempVar3.Children = append(tempVar3.Children, staticNode_3)
		}
		tempVar2.Children = append(tempVar2.Children, tempVar3)
	} else {
		tempVar2.Children = append(tempVar2.Children, staticNode_4)
	}
	tempVar1.Children = append(tempVar1.Children, tempVar2)
	tempVar6 := pikoruntime.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "section"
	tempVar6.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	tempVar6.Children = make([]*pikoruntime.TemplateNode, 0, 3)
	tempVar6.OnEvents = make(map[string][]pikoruntime.Directive)
	tempVar6.CustomEvents = make(map[string][]pikoruntime.Directive)
	tempVar6.Attributes = append(tempVar6.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "permissions"})
	tempVar6.Attributes = append(tempVar6.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"})
	tempVar6.Children = append(tempVar6.Children, staticNode_5)
	if pageData.IsAdmin {
		tempVar6.Children = append(tempVar6.Children, staticNode_6)
	} else {
		tempVar6.Children = append(tempVar6.Children, staticNode_7)
	}
	tempVar1.Children = append(tempVar1.Children, tempVar6)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: []string{}}
	return rootAST, internalMetaResult, diags
}

var ( // SOURCE: pages/auth.pk, LINE: 40
	staticNode_1                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 41
	staticNode_1_child_0         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 41
	staticNode_1_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 46
	staticNode_2                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 47
	staticNode_2_child_0         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 47
	staticNode_2_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 49
	staticNode_3                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 50
	staticNode_3_child_0         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 50
	staticNode_3_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 53
	staticNode_4                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 54
	staticNode_4_child_0         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 54
	staticNode_4_child_0_child_0 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 55
	staticNode_4_child_1         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 55
	staticNode_4_child_1_child_0 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 59
	staticNode_5                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 59
	staticNode_5_child_0         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 60
	staticNode_6                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 60
	staticNode_6_child_0         *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 61
	staticNode_7                 *pikoruntime.TemplateNode // SOURCE: pages/auth.pk, LINE: 61
	staticNode_7_child_0         *pikoruntime.TemplateNode
)

func init() {
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "header"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "auth-header"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeElement
	staticNode_1_child_0.TagName = "h1"
	staticNode_1_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 1)
	staticNode_1_child_0.Attributes = append(staticNode_1_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"})
	staticNode_1_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0_child_0.TextContent = "Authentication Demo"
	staticNode_1_child_0.Children = append(staticNode_1_child_0.Children, staticNode_1_child_0_child_0)
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeElement
	staticNode_2.TagName = "div"
	staticNode_2.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:1"})
	staticNode_2.Attributes = append(staticNode_2.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "admin-badge"})
	staticNode_2.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0.NodeType = pikoruntime.NodeElement
	staticNode_2_child_0.TagName = "span"
	staticNode_2_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:1:0"})
	staticNode_2_child_0.Attributes = append(staticNode_2_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "badge admin"})
	staticNode_2_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_2_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_2_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_2_child_0_child_0.TextContent = "Administrator"
	staticNode_2_child_0.Children = append(staticNode_2_child_0.Children, staticNode_2_child_0_child_0)
	staticNode_2.Children = append(staticNode_2.Children, staticNode_2_child_0)
	staticNode_3 = &pikoruntime.TemplateNode{}
	staticNode_3.NodeType = pikoruntime.NodeElement
	staticNode_3.TagName = "div"
	staticNode_3.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:2"})
	staticNode_3.Attributes = append(staticNode_3.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "user-badge"})
	staticNode_3.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0.NodeType = pikoruntime.NodeElement
	staticNode_3_child_0.TagName = "span"
	staticNode_3_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:2:0"})
	staticNode_3_child_0.Attributes = append(staticNode_3_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "badge user"})
	staticNode_3_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_3_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_3_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_3_child_0_child_0.TextContent = "Regular User"
	staticNode_3_child_0.Children = append(staticNode_3_child_0.Children, staticNode_3_child_0_child_0)
	staticNode_3.Children = append(staticNode_3.Children, staticNode_3_child_0)
	staticNode_4 = &pikoruntime.TemplateNode{}
	staticNode_4.NodeType = pikoruntime.NodeElement
	staticNode_4.TagName = "div"
	staticNode_4.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"})
	staticNode_4.Attributes = append(staticNode_4.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "logged-out"})
	staticNode_4.Children = make([]*pikoruntime.TemplateNode, 0, 2)
	staticNode_4_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0.NodeType = pikoruntime.NodeElement
	staticNode_4_child_0.TagName = "p"
	staticNode_4_child_0.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:0"})
	staticNode_4_child_0.Attributes = append(staticNode_4_child_0.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "login-prompt"})
	staticNode_4_child_0.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_0_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_0_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_0_child_0.TextContent = "Please log in to continue"
	staticNode_4_child_0.Children = append(staticNode_4_child_0.Children, staticNode_4_child_0_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_0)
	staticNode_4_child_1 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1.NodeType = pikoruntime.NodeElement
	staticNode_4_child_1.TagName = "button"
	staticNode_4_child_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:1"})
	staticNode_4_child_1.Attributes = append(staticNode_4_child_1.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "login-btn"})
	staticNode_4_child_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_4_child_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_4_child_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_4_child_1_child_0.TextContent = "Sign In"
	staticNode_4_child_1.Children = append(staticNode_4_child_1.Children, staticNode_4_child_1_child_0)
	staticNode_4.Children = append(staticNode_4.Children, staticNode_4_child_1)
	staticNode_5 = &pikoruntime.TemplateNode{}
	staticNode_5.NodeType = pikoruntime.NodeElement
	staticNode_5.TagName = "h2"
	staticNode_5.Attributes = make([]pikoruntime.HTMLAttribute, 0, 1)
	staticNode_5.Attributes = append(staticNode_5.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0"})
	staticNode_5.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_5_child_0 = &pikoruntime.TemplateNode{}
	staticNode_5_child_0.NodeType = pikoruntime.NodeText
	staticNode_5_child_0.TextContent = "Access Level"
	staticNode_5.Children = append(staticNode_5.Children, staticNode_5_child_0)
	staticNode_6 = &pikoruntime.TemplateNode{}
	staticNode_6.NodeType = pikoruntime.NodeElement
	staticNode_6.TagName = "p"
	staticNode_6.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_6.Attributes = append(staticNode_6.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:1"})
	staticNode_6.Attributes = append(staticNode_6.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "access-admin"})
	staticNode_6.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_6_child_0 = &pikoruntime.TemplateNode{}
	staticNode_6_child_0.NodeType = pikoruntime.NodeText
	staticNode_6_child_0.TextContent = "Full administrative access"
	staticNode_6.Children = append(staticNode_6.Children, staticNode_6_child_0)
	staticNode_7 = &pikoruntime.TemplateNode{}
	staticNode_7.NodeType = pikoruntime.NodeElement
	staticNode_7.TagName = "p"
	staticNode_7.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_7.Attributes = append(staticNode_7.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:2"})
	staticNode_7.Attributes = append(staticNode_7.Attributes, pikoruntime.HTMLAttribute{Name: "class", Value: "access-default"})
	staticNode_7.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_7_child_0 = &pikoruntime.TemplateNode{}
	staticNode_7_child_0.NodeType = pikoruntime.NodeText
	staticNode_7_child_0.TextContent = "Standard access only"
	staticNode_7.Children = append(staticNode_7.Children, staticNode_7_child_0)
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_13_else_directive/pages/pages_auth_eadff339", BuildAST)
}
