//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_card_bfc4a3cf "testcase_110_partial_import_function_call/dist/partials/partials_card_bfc4a3cf"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_card_bfc4a3cf.Render

// line pages/main.pk:27
type Response struct{ FormattedPrice string }

// line pages/main.pk:31
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{FormattedPrice: partials_card_bfc4a3cf.FormatPrice(100)}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_card_price_100_05e4dc0a := partials_card_bfc4a3cf.Props{Price: 100}
	partials_card_bfc4a3cfData_card_price_100_05e4dc0a, partials_card_bfc4a3cfMeta_card_price_100_05e4dc0a, partials_card_bfc4a3cfErr_card_price_100_05e4dc0a := partials_card_bfc4a3cf.Render(r, props_card_price_100_05e4dc0a)
	if partials_card_bfc4a3cfErr_card_price_100_05e4dc0a != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_card_bfc4a3cfErr_card_price_100_05e4dc0a.Error(), "R002", "", "Partial Render() error for partials_card_bfc4a3cf", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_card_bfc4a3cfData_card_price_100_05e4dc0a
	_ = partials_card_bfc4a3cfMeta_card_price_100_05e4dc0a
	_ = partials_card_bfc4a3cfErr_card_price_100_05e4dc0a
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(3)
	// line partials/card.pk:35
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(1)
	tempVar1.Children = tempVar2Slice
	// line partials/card.pk:35
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeText
	tempVar4 := arena.GetDirectWriter()
	tempVar4.AppendEscapeString(partials_card_bfc4a3cf.FormatPrice(props_card_price_100_05e4dc0a.Price))
	tempVar3.TextContentWriter = tempVar4
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	// line pages/main.pk:39
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "p"
	tempVar5.Attributes = staticAttrs_2
	_, tempVar6Slice := arena.GetChildSlice(1)
	tempVar5.Children = tempVar6Slice
	// line pages/main.pk:39
	tempVar7 := arena.GetNode()
	tempVar7.NodeType = pikoruntime.NodeText
	tempVar8 := arena.GetDirectWriter()
	tempVar8.AppendString("From Render: ")
	tempVar8.AppendEscapeString(pageData.FormattedPrice)
	tempVar7.TextContentWriter = tempVar8
	tempVar5.Children = append(tempVar5.Children, tempVar7)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar5)
	// line pages/main.pk:40
	tempVar9 := arena.GetNode()
	tempVar9.NodeType = pikoruntime.NodeElement
	tempVar9.TagName = "p"
	tempVar9.Attributes = staticAttrs_3
	_, tempVar10Slice := arena.GetChildSlice(1)
	tempVar9.Children = tempVar10Slice
	// line pages/main.pk:40
	tempVar11 := arena.GetNode()
	tempVar11.NodeType = pikoruntime.NodeText
	tempVar12 := arena.GetDirectWriter()
	tempVar12.AppendString("From Template: ")
	tempVar12.AppendEscapeString(partials_card_bfc4a3cf.FormatPrice(200))
	tempVar11.TextContentWriter = tempVar12
	tempVar9.Children = append(tempVar9.Children, tempVar11)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar9)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 35
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 39
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 40
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "card"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "card"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.1"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.2"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_110_partial_import_function_call/dist/pages/pages_main_594861c5", BuildAST)
}
