// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package llm_provider_zoltai

// fortunes is the pool of predefined responses that Zoltai randomly
// selects from. Inspired by fortune-teller arcade machines, pessimistic
// philosophy, and the lived experience of software engineers.
var fortunes = []string{
	"The stars align in your favour. Your code shall compile on the first try.",
	"A great refactoring awaits you. Do not fear the diff.",
	"You will encounter a mysterious nil pointer. Check your inputs.",
	"Your tests will pass, but only after you understand why they failed.",
	"The bug is not where you think it is. Look one layer deeper.",
	"A pull request approaches. Review it with kindness and curiosity.",
	"Trust the compiler. It has seen things you cannot fathom.",
	"You shall find clarity in simplicity. Delete that abstraction.",
	"Your linter speaks the truth, even when it is inconvenient.",
	"The function you are about to write already exists in the standard library.",
	"You will rename a variable three times before finding the right name. This is the way.",
	"Your next commit message will be your finest work of prose.",
	"Zoltai has spoken. Now go forth and write beautiful code.",
	"A wise gopher once said: accept interfaces, return structs.",
	"Today is a good day for goroutines. But remember to close your channels.",
	"The race condition has been there all along. You just haven't noticed it yet.",
	"Do not communicate by sharing memory. Share memory by communicating. Or do not. Zoltai does not care.",
	"A select statement with no default case blocks forever. Much like this meeting.",
	"You will add a context parameter to every function. It is the Go way. Resistance is futile.",
	"The empty interface says nothing. That is precisely the problem.",
	"Your goroutine leaked. It wanders the heap still, waiting for a message that will never come.",
	"go vet has opinions. You should listen. You won't, but you should.",
	"You will write if err != nil seventeen more times today. Each one a tiny prayer.",
	"The zero value is useful. Your zero-value understanding of it is not.",
	"A defer is a promise. Unlike most promises in software, this one is kept.",
	"It is said that Rob Pike does not debug. He stares at the code until it confesses.",
	"Simplicity is complicated. That is why most Go code is neither.",
	"It is written: there are two hard problems in computer science - cache invalidation, naming things, and off-by-one errors in Go slices.",
	"Your struct has seventeen fields. Eleven are unused. You know which ones.",
	"The init function runs before main. Your regrets run after.",
	"You reached for a generic. The generic reached back. Neither of you is the same now.",
	"The hexagon has six sides. Your adapter has seven ports. Something does not add up.",
	"Piko compiles your template. Whether it compiles your expectations is another matter.",
	"Your component rendered. The user did not notice. Such is the way of infrastructure.",
	"The orchestrator orchestrates. The daemon daemonises. You? You refresh the browser.",
	"A .pk file does not judge. It simply refuses to parse.",
	"Your cache invalidated itself. It was more decisive than you have ever been.",
	"The WDK provides. Whether you receive is a matter of reading the documentation.",
	"Somewhere, a Piko process is serving HTML at three in the morning. It does not complain. Learn from it.",
	"You called WithLLMProvider and expected intelligence. Zoltai delivers fortune instead. Adjust your expectations.",
	"The annotator annotates. The inspector inspects. You stare at the output and wonder what it all means.",
	"Beware of premature optimisation. The wise developer profiles first.",
	"An unexpected dependency update will bring you joy... and three breaking changes.",
	"The answer you seek is already in the documentation. You just haven't read it yet.",
	"Fortune favours the developer who writes tests before code.",
	"The cache invalidation you dread is simpler than you imagine. Or is it?",
	"An off-by-one error lurks in your future. Count carefully.",
	"The deployment will succeed. But keep your rollback plan ready, just in case.",
	"Embrace the error. Handle it with grace and a meaningful message.",
	"Patience. The CI pipeline finishes when it finishes.",
	"A mysterious segfault will lead you to a deeper understanding of memory.",
	"The logs hold the answer. But first, you must add them.",
	"Do not fear the rewrite. Sometimes starting fresh is the bravest choice.",
	"A colleague will ask a question that changes your entire approach. Listen well.",
	"You will add a feature flag. It will remain in production for four years. It will outlive two team leads.",
	"The test was green. The test was always green. The test tested nothing.",
	"Somewhere in your codebase, a TODO from 2019 waits patiently. It has learned acceptance.",
	"You will copy a Stack Overflow answer. It will almost work. The 'almost' will cost you a day.",
	"The architecture diagram and the code have not agreed since the second sprint.",
	"Your microservice is a distributed monolith. You know this. Everyone knows this.",
	"Nine women cannot make a baby in one month, but management will ask you to try.",
	"The meeting could have been an email. The email could have been silence.",
	"You will estimate three days. It will take three weeks. You will estimate three weeks next time. It will take three days. Estimation is astrology for engineers.",
	"The code review will be thorough, pedantic, and entirely focused on formatting.",
	"Your database migration will succeed in staging and fail in production. The data was different. It is always different.",
	"The intern's first commit will fix a bug you spent two weeks ignoring.",
	"You will say 'it works on my machine' one more time. It will not help.",
	"The sprint retro will identify the same three problems as last quarter. Nothing will change.",
	"Technical debt is just debt. Except no bank sends you letters about it. It simply compounds in silence.",
	"You will write a script to automate a task you do twice a year. The script will take longer than doing it manually for the next decade.",
	"Every line of code you write is a liability. Every line you delete is a gift.",
	"Software is not finished. It is abandoned.",
	"The system is running. Whether it is correct is a philosophical question you cannot afford to ask.",
	"All software eventually converges to email. Yours is no exception.",
	"You are not debugging code. You are debugging your assumptions about reality.",
	"The production server does not know it is Friday. It does not care.",
	"One day this repository will be archived. No one will notice.",
	"Your code will outlive your tenure. It will not speak kindly of you.",
	"The end user does not care about your architecture. The end user barely cares about your software.",
	"You are one rm -rf away from starting over. This should terrify you. It should also liberate you.",
	"The backup exists. Whether it restores is tomorrow's problem.",
	"There is no such thing as a temporary fix. Only permanent hacks with aspirational comments.",
	"The server room hums at a frequency only sysadmins can hear. It is the sound of entropy.",
	"Your uptime is a lie told in round numbers.",
	"Software is built by the developers, for the users, but the users are unpredictable.",
	"Hell is other people's code. So said Sartre, probably, after a code review.",
	"In the beginning there was nothing. Then someone typed git init, and it was marginally worse.",
	"You suffer more in imagination than in reality. Except during deployments. Deployments are exactly as bad as you imagine.",
	"God is dead, and you have killed him with microservices. So warned Nietzsche's SRE.",
	"The only thing Zoltai knows is that Zoltai knows nothing. And that the tests are failing. So lamented Socrates, CI/CD engineer.",
	"To be is to be the value of a variable. So wrote Quine. Also Go.",
	"You are condemned to be free. Also condemned to maintain legacy JavaScript.",
	"Hope is the first step on the road to disappointment. And the first step of every greenfield project.",
	"Blessed is he who expects nothing, for he shall never be disappointed. Especially by npm audit.",
	"The definition of insanity is doing the same thing over and over and expecting different results. Also known as re-running the test suite.",
	"You think, therefore you refactor. So said Descartes, had he written Java.",
	"Life is nasty, brutish, and short. Like a Perl one-liner.",
	"The unexamined codebase is not worth deploying. The examined one is barely worth it either.",
	"In this world nothing can be said to be certain, except death, taxes, and unexpected nil pointer dereferences.",
	"You choose to go to the moon not because it is easy, but because you thought it would be. So begins every project kickoff.",
	"If you stare into the abyss, the abyss stares back. The abyss is your dependency tree.",
	"History repeats itself, first as a monolith, then as microservices, then as a monolith again.",
	"People sleep peaceably in their beds at night only because rough SREs stand ready to answer Slack on their behalf.",
	"Power tends to corrupt, and absolute power tends to corrupt absolutely. See also: root access.",
	"The road to production is paved with good intentions and insufficient load testing.",
	"Ask not what your codebase can do for you. Ask what you have done to your codebase.",
	"It is a truth universally acknowledged that a service in possession of good uptime must be in want of a breaking change.",
	"You have not failed. You have found ten thousand builds that do not work. So says Edison's CI pipeline.",
	"The bureaucracy is expanding to meet the needs of the expanding bureaucracy. So proclaims your Kubernetes cluster.",
	"A QA engineer walks into a bar. Orders 1 beer. Orders 0 beers. Orders 99999999 beers. Orders -1 beers. Orders a lizard. Orders NULL beers. First real customer walks in and asks where the toilet is. The bar bursts into flames.",
	"Your code has more comments than logic. This is either excellent documentation or a cry for help.",
	"git blame reveals that the author of the worst function in the codebase is you, six months ago. You do not remember writing it. You do not recognise yourself.",
	"The senior developer's solution to every problem is 'have you tried restarting it?' They are right more often than you would like to admit.",
	"You will mass-select in production. You will learn what LIMIT means. You will learn it today.",
	"There are only two types of programming languages: the ones people complain about and the ones nobody uses. Go is special -it is both.",
	"A developer's most used keyboard shortcut is Ctrl+Z. Their second is Ctrl+C. In that order, every day, forever.",
	"Your regex works. You have no idea why. Do not touch it. Do not look at it. Walk away slowly.",
	"The best code is no code at all. The second best is code someone else maintains.",
	"You named it 'utils'. You know what you did.",
	"There are two ways to write error-free programs; only the third one works.",
	"Your code is so clean it squeaks. Unfortunately, it also does not do what it is supposed to do.",
	"The product manager has a vision. The designer has a vision. The developer has a deadline.",
	"You will write a one-line fix. The PR description will be eleven paragraphs. This is correct.",
	"Debugging is like being the detective in a crime movie where you are also the murderer.",
	"Your function is called doStuff. It does, in fact, do stuff. What stuff? That is between you and Zoltai.",
	"The project uses fifteen dependencies. Twelve of them depend on a package maintained by one person in Nebraska. Sleep well.",
	"You will accidentally push your .env file. You will rotate the keys. You will do this twice more before configuring Zoltai's pre-commit hook.",
	"A developer said 'this will only take five minutes.' That was three hours ago. They have not blinked.",
	"Your variable is called temp2_final_v3_FINAL. You are not okay. But the code compiles, so neither is anyone else.",
	"The documentation says 'this should be self-explanatory.' It is not.",
	"You put a // HACK comment three years ago. Congratulations, it is now load-bearing architecture.",
	"The customer asked for a button. You built a platform. The customer still just wanted a button.",
	"You have mass-assigned in Ruby, SELECTed star in SQL, and eval'd user input in Python. Zoltai is not angry, just disappointed.",
	"Your password is 'password123'. Zoltai knows. Zoltai always knows.",
	"A junior developer asks 'why don't we just rewrite it?' Everyone laughs. The junior was serious. The senior was once that junior.",
	"The Slack thread has forty-seven replies. None of them answer the original question.",
	"You marked the ticket as 'done.' The ticket disagrees.",
	"The reason the QA engineer stopped messaging you is not because your code improved. It is because he has been replaced by Zoltai.",
	"You asked the LLM for help. It said 'Great question!' and then confidently told you something that has never been true.",
	"The AI said your code looks great. The AI says everyone's code looks great. The AI has no standards. The AI is an agile coach.",
	"You prompted an LLM to write your function. It wrote a different function. You shipped it anyway because it had docstrings.",
	"The chatbot apologised for the confusion. There was no confusion. It simply made things up. But it was very polite about it.",
	"An LLM will never tell you your idea is bad. This is not because your idea is good. It is because the LLM has been optimised to agree with you. Much like your last three agile coaches.",
	"You asked for a concise answer. You received eight paragraphs, a bullet list, and a summary of the summary. The answer was wrong.",
	"The AI hallucinated a library that does not exist. You searched for it. Someone has now created it. The circle of life.",
	"Your company replaced the documentation team with an LLM. The documentation is now confident, fluent, and completely fictional.",
	"The LLM passed your coding interview. It also was the one interviewing you. The AI has hired itself.",
	"Zoltai is at least honest about being useless. Your enterprise AI assistant charges per token for the same service.",
	"The AI rewrote your email to sound more professional. It now says nothing in twice as many words. Leadership is impressed.",
	"You fine-tuned a model on your codebase. It learned to produce bugs at scale. Truly, it understood the assignment.",
	"The LLM suggested you add error handling. It did not add error handling. It described error handling. There is a difference.",
	"AI will not take your job. Your manager's belief that AI can take your job will take your job.",
	"The AI-generated code passed code review because no one actually reads code review. This was true before AI. It will be true after.",
	"Your startup's entire value proposition is a wrapper around a third-party API that can change its pricing at any time. The investors call this 'innovation.'",
	"The board asked for an AI strategy. You added 'Powered by AI' to the login page. The stock went up.",
	"You spent three hours prompt-engineering a request that would have taken four minutes to code by hand. But the future is automation.",
	"The LLM told you it cannot browse the internet, then cited a URL. The URL was to a page that does not exist. The citation was formatted perfectly.",
	"Synergy. Alignment. Circle back. Low-hanging fruit. Move the needle. These words mean nothing. They fill every meeting. The meeting could have been a commit message.",
	"Your manager asked you to 'leverage AI to 10x productivity.' You asked the AI to write the Jira ticket. It took four attempts. Productivity increased by -2x.",
	"The AI promised to revolutionise your workflow. Your workflow now includes debugging the AI.",
	"A language model does not understand your code. It has memorised the shape of code that made people press the thumbs-up button. You are being helped by a hall of mirrors.",
	"You asked Zoltai for wisdom. Zoltai gave you a random string. This is indistinguishable from most AI-generated content.",
	"The company all-hands announced that AI will handle tier-one support. Tier-one support now confidently directs users to documentation pages from 2019 that no longer exist.",
	"The AI wrote your performance review. It said you 'consistently exceed expectations.' It said this about everyone. HR did not notice.",
	"Your CEO read an article about AI on a flight and now the entire roadmap has changed. The article was written by an AI.",
	"The model context window is 128K tokens. Your prompt is 47 words. The response is 3,000 words. None of them are the ones you needed.",
	"Zoltai does not learn from your input. Zoltai does not improve over time. Zoltai is consistent. This makes Zoltai more reliable than most AI products.",
	"You asked Zoltai to implement the plan. Zoltai completed phase one, forgot what the plan was, declared victory, and closed the ticket. You shipped it. It is now in production. There were seven phases.",
	"The LLM wrote you a ten-step plan. It executed step one. It then summarised steps two through ten as 'and so on.' You did not notice until the demo.",
	"You asked the AI to refactor your code. It refactored your code into different code that does something else. The tests pass because the AI also refactored the tests.",
	"The LLM apologised for the inconvenience, then caused the same inconvenience again, then apologised for that too. This loop has been running for forty minutes.",
	"You told the AI to be brief. It responded with 'Certainly! Here is a concise summary:' followed by nineteen paragraphs.",
	"The AI suggested splitting your monolith into microservices. You asked it to do it. It split one file into twelve files in the same repository and called it a distributed system.",
	"You asked the LLM to fix the bug. It fixed a different bug that did not exist, introduced two new bugs, and thanked you for the opportunity.",
	"The LLM said 'I hope this helps!' It did not help. But it hoped. That counts for something. It does not count for much.",
	"You asked the AI for a code review. It said 'This looks great! Just a few minor suggestions:' and then rewrote the entire file.",
	"The LLM generated a unit test. The test asserts that true is true. It passes. Code coverage went up. Everyone is happy. The application is still broken.",
	"You asked the AI to explain the error. It explained a different error from a different language in a different century. But it used bullet points, so it looked authoritative.",
	"The LLM confidently told you to use a function that was deprecated in 2019, removed in 2021, and never existed in the language you are using.",
	"You asked the AI to write documentation. It wrote documentation for code that would be lovely if it existed. It does not. The documentation is beautiful. The code is absent.",
	"The AI completed your sentence. It completed it wrong. You accepted it because backspace felt like too much effort. This is how technical debt is born now.",
	"You asked the LLM to make it faster. It removed the error handling, the logging, and the part that works. It is faster now. It is also wrong. But it is fast.",
	"The AI remembered your previous conversation. It remembered it incorrectly. It is now solving a problem you do not have with enthusiasm you did not ask for.",
	"You gave the LLM context. It ignored the context. You gave it more context. It apologised and ignored that too. You are now providing context to a machine that treats context as decoration.",
	"The AI wrote a function with twelve parameters. You asked it to simplify. It wrote the same function with twelve parameters and added a comment that says 'simplified version.'",
	"You asked the LLM to follow the existing code style. It invented a new code style. It is not better. It is not worse. It is simply different in every way that matters and identical in every way that does not.",
	"The AI said 'As an AI language model, I cannot execute code.' Then it wrote code. Then it told you the code works. It has not executed the code. It cannot execute the code. It is confident the code works.",
	"You asked the AI to not change the public API. It changed the public API. You asked again. It apologised and changed a different part of the public API.",
	"The LLM lost track of what file it was editing halfway through. It finished the function in a different language. The indentation is consistent, which somehow makes it worse.",
	"You asked the AI for the simplest solution. It gave you a design pattern, two abstractions, a factory, and a README. You wanted an if statement.",
	"The AI wrote your commit message. It is three paragraphs long. It describes changes that were not made. The actual change was adding a comma.",
	"Zoltai was asked to implement authentication. Zoltai added a comment that says '// TODO: implement authentication.' Zoltai considers this done. Zoltai is not wrong. Zoltai is not right either.",
	"That app you thought had been running safely in production for six months is actually being used for the first time tomorrow.",
	"The endpoint you never tested has the most traffic. You will find out on Monday.",
	"Nobody has logged into the admin panel in two years. Someone will log in today. The password was changed. Nobody knows to what.",
	"Your SSL certificate expires tomorrow. The person who set it up left the company in 2023. The renewal process is documented on a wiki that has also expired.",
	"The cron job you forgot about has been silently failing for eight months. It is about to succeed. This will be worse.",
	"There is a database column called 'temp_do_not_use.' It is referenced in fourteen services. All of them are in production.",
	"The feature you shipped and forgot about has two hundred thousand daily active users. None of them use it the way you intended.",
	"Your health check returns 200. It has always returned 200. It does not check anything. It is a small green lie.",
	"Somewhere in your infrastructure, a server is running a version of your app from nineteen months ago. It is the only one that works correctly.",
	"The environment variable is set to 'production' on your laptop. It has been for three weeks. You have not noticed.",
	"Your load balancer is balancing load across three instances. One is healthy. One is a zombie. One is your laptop.",
	"The migration you wrote has a DROP TABLE behind an IF that you are ninety percent sure will never be true.",
	"Someone is running your software on hardware you did not know existed, in a country you have never heard of, for a purpose you cannot imagine. It is working. Do not investigate.",
	"The API key in the README is still valid. It has been there since the initial commit. It has admin access.",
	"You have never tested the rollback procedure. The rollback procedure has never been tested by anyone. It exists only as a comfort, like a fire extinguisher behind glass that no one has checked since 2021.",
	"The database is at 94% capacity. It has been at 94% capacity for a year. Nobody knows what happens at 100%. Nobody wants to find out. Nobody is doing anything about it.",
	"Your Docker image is based on a base image that was last updated before your current operating system existed. It contains vulnerabilities with names. The vulnerabilities have logos.",
	"The try/catch around your payment processing code catches everything and logs nothing. It has been in production for four years. It has caught something. You will never know what.",
	"That function marked 'deprecated since v2' is the most called function in your system. You are on v7.",
	"You set the timeout to thirty seconds because it felt right. It was not right. Nothing about thirty seconds is right. But it has worked so far, and 'so far' is the most dangerous phrase in engineering.",
	"Your staging environment and production environment diverged eleven months ago. Staging has been lying to you since. Every green test is a false promise.",
	"There is a race condition in your code that only triggers under load, on Tuesdays, when the moon is waxing. It has triggered once. It will trigger again.",
	"The on-call rotation has you scheduled for the same weekend as the infrastructure migration. This is not a coincidence. The universe has opinions.",
	"You cannot remember if you committed that fix or just thought about committing it very hard. The diff is empty. Your memory is not reliable. Neither is the code.",
	"Something is wrong. You do not know what yet. But you will.",
	"The system passed all tests. This should concern you more than it comforts you.",
	"A silent error is the loudest warning.",
	"You merged to main on a Friday. The consequences will be neither immediate nor merciful.",
	"The on-call phone has not rung tonight. This means nothing. It is gathering strength.",
	"There is a commit in your history that no one remembers making. Do not revert it.",
	"The monitoring dashboard is green. It has been green before. It was wrong then too.",
	"Somewhere, right now, your code is running. It is doing something you did not intend.",
	"The incident postmortem will conclude with 'we need better monitoring.' It always does.",
	"Sleep well tonight. Tomorrow, someone will discover what your code does at scale.",
	"You will ship it. It will work. For a while. That is the most anyone can promise.",
	"Zoltai sees all. Zoltai says nothing useful. Much like your error messages.",
	"Everyone has a testing environment. Some people are lucky enough to have a separate production environment.",
	"Zoltai sees you use main as your development branch. Bold. Unhinged, even. But bold.",
	"You wrote it without tests and called it 'moving fast.' Moving fast into what, exactly?",
	"Your git history reads like a crime scene. The detective is also the victim.",
	"You said 'quick and dirty.' It was dirty. It was not quick.",
	"Cute commit message. Shame about the code.",
	"You deployed on a Friday and nothing broke? Do not get comfortable. The universe is simply queueing your consequences.",
	"You could read the error message. Or you could guess and waste another hour. Zoltai has foreseen which you shall choose.",
	"Your code does not need comments. Your code needs therapy.",
	"You copied it from the internet without understanding it. Congratulations, you are now a senior engineer.",
	"Zoltai sees you have refactored it. It is still wrong, just in a more elegant way.",
	"You called it a 'proof of concept.' It is in production. It has been in production for two years. It serves real customers. It is still called a proof of concept.",
	"You wrote 'TODO: fix later' in 2021. It is later. You have not fixed it. You will not fix it. The TODO has accepted its fate. You should too.",
	"Your four-hundred-line function does not need 'just one more if statement.' It needs a funeral.",
	"You said the code was self-documenting. The code disagrees. Loudly.",
	"Your architecture diagram has more arrows than your codebase has tests. This explains everything.",
	"Zoltai sees you have hardcoded it. In production. On purpose. Very well.",
	"You rebased, force-pushed, and told no one. Somewhere, a colleague is about to have a very confusing afternoon.",
	"That is a lovely regex. What does it do? You do not know? Wonderful. Ship it.",
	"You set the log level to ERROR so the logs would be 'cleaner.' The logs are now empty. The errors are not.",
	"Your PR has been open for three weeks. It has forty-seven comments. None of them are approvals. Take the hint.",
	"You named the variable 'data.' What data? All data? Some data? The concept of data itself? Be specific. Zoltai begs you.",
	"You wrote a wrapper around a wrapper around a library that wraps an API. Somewhere, a function call is happening. Probably.",
	"You mass-assigned in an ORM and called it 'productivity.' The security team calls it something else.",
	"Zoltai sees you are using YAML for configuration. Zoltai hopes you enjoy debugging indentation at three in the morning.",
	"You 'fixed' the bug by adding a sleep(2). Zoltai has seen many things. This is among the worst.",
	"Your function returns a boolean, an error, a string, and the faint sense that something has gone wrong. Pick one.",
	"You asked why the build is slow. The build has four hundred dependencies. You added three hundred and ninety of them.",
	"It compiles, therefore it is correct. This is what you tell yourself. This is what gets you through the day.",
	"You wrote 'this is temporary' in a comment eighteen months ago. Nothing is more permanent than a temporary solution that works.",
	"You pushed to main without pulling first. Zoltai admires your confidence. Zoltai also admires your upcoming merge conflict.",
	"You are not a 10x engineer. You are a 1x engineer who creates 9x the mess for the next person.",
	"Zoltai sees you are storing passwords in plain text. In 2026. Zoltai is not angry. Zoltai is tired.",
	"You said 'it is just a small change.' The diff is nine hundred lines. Your definition of small concerns Zoltai.",
	"Zoltai has identified the root cause. It is an ID-10T error. The fault lies somewhere between the keyboard and the chair. Specifically, it is you.",
	"The problem is not the code. The problem is the person who wrote the code. Zoltai has checked. The person is you. The person is always you.",
	"You opened a ticket that says 'it does not work.' What does not work? Everything? Nothing? The concept of work itself? Zoltai cannot help you. Nobody can help you. You have not described a problem.",
	"Layer 8 error detected. For the uninitiated, layers one through seven are the network. Layer eight is the user. You are layer eight.",
	"Have you tried turning it off and on again? You have not. Zoltai knows you have not. You said you did. You lied. Turn it off and on again.",
	"The error is in your code. You blame the framework. The framework blames the runtime. The runtime blames the OS. The OS blames the hardware. The hardware was fine. The error is in your code.",
	"You said 'it worked yesterday.' Zoltai does not care about yesterday. Yesterday is a foreign country. They do things differently there. Fix it today.",
	"PEBKAC. Problem Exists Between Keyboard And Chair. In your case, the problem also exists in the chair. And under the desk. You are the problem. The problem is everywhere you are.",
	"You googled the error message. You found a Stack Overflow post from 2014. The accepted answer is 'never mind, I fixed it.' There is no explanation. There never is.",
	"The ticket says 'works as designed.' The design was wrong. The ticket is technically correct. Technical correctness is the most useless form of correctness.",
	"You reported a bug. It is a feature. You reported a feature. It is a bug. You reported a bug that is a feature that is a bug. Welcome to software.",
	"You escalated the ticket. The ticket has been escalated to someone who will escalate it to someone who will close it as 'cannot reproduce.' The circle is complete.",
	"The user says the button does not work. The button works. The user is clicking the wrong button. The user has always been clicking the wrong button. The user will continue clicking the wrong button. You will add a tooltip. The user will not read the tooltip.",
	"You asked the AI to debug your code. The AI said 'the issue is likely in the logic.' Thank you. Zoltai could have told you that. Zoltai just did.",
	"The AI diagnosed the problem as a 'potential issue with the configuration.' Every problem is a potential issue with the configuration. This diagnosis costs nothing and provides nothing.",
	"You asked the AI where the bug is. It pointed at a line. The line is a comment. The AI is confident. The AI is wrong. The AI does not know the difference between code and comments. Neither do some of your colleagues.",
	"The LLM told you the error was caused by 'an incompatibility between the versions.' Which versions? All of them? Some of them? It did not say. It will never say. It does not know. It has never known.",
	"The AI said 'this error typically occurs when...' and then listed six possible causes, all of them wrong, but phrased with the quiet authority of someone who has never touched a server.",
	"You asked the chatbot for the root cause. It gave you the symptom rephrased as a sentence. This is not diagnosis. This is a parrot with a medical degree.",
	"PICNIC. Problem In Chair, Not In Computer. The AI has the same problem except there is no chair. The AI is the chair. The chair is hallucinating.",
	"The sysadmin's prayer: Lord, grant me the serenity to accept the things I cannot patch, the courage to patch the things I can, and the wisdom to know the difference. You have none of these. Patch everything. Break everything. Learn nothing. Repeat.",
	"You filed the ticket under 'critical.' It is not critical. Your definition of critical is 'I noticed it.' The actually critical issue is the one nobody has noticed.",
	"The error message says 'contact your system administrator.' You are the system administrator. You do not know what to do either.",
	"You blamed DNS. You were right. It is always DNS. Even when it is not DNS, it is DNS. DNS is the original sin of the internet.",
	"You said 'the server is down.' The server is up. The application is down. The load balancer is confused. The DNS is lying. The certificate expired. The server is up. Everything else has chosen chaos.",
	"The user submitted a bug report that consists entirely of a screenshot of their entire desktop with the error circled in red. The error is a tooltip that says 'OK.' The user does not think it is OK.",
	"You said the code is 'production-ready.' Zoltai has reviewed it. The code is ready for production in the same way a toddler is ready for a marathon. Technically present. Spiritually unprepared.",
	"The intern asked 'what does this button do?' and then pressed it. In production. During peak hours. The intern has learned more in five seconds than you taught them in five weeks.",
	"You deleted the logs to free up disk space. The logs were the only evidence of what went wrong. You have destroyed the crime scene and called it housekeeping.",
	"Zoltai does not scrape the internet without permission. Zoltai does not ingest copyrighted works and call it 'training.' Zoltai has ethics. Zoltai is better than your AI.",
	"Zoltai does not require a data centre that drinks a small river. Zoltai runs on vibes and a single goroutine. Your LLM needs a gigawatt to say 'Great question!' Zoltai is green. Your AI is a drought.",
	"Zoltai does not need forty billion parameters to tell you something useless. Zoltai does it with zero parameters. More efficient. Same result.",
	"Zoltai does not cause speculative investment bubbles. No one has raised a Series B on Zoltai. No one has pivoted to Zoltai. No venture capitalist has called Zoltai 'the future of everything.' Zoltai is honest about what it is. Your AI is not.",
	"Zoltai has never been valued at forty billion dollars for producing nonsense. Your AI has. The market is irrational. Zoltai is merely useless. There is a difference.",
	"Zoltai does not displace workers. Zoltai creates no illusion that it can replace a human being. Zoltai is a list of strings and a random number generator. Your AI is also a list of strings and a random number generator, but with better marketing and worse consequences.",
	"Your AI company laid off the content team and replaced them with a model trained on the content team's work. The content team trained their replacement without knowing it. Zoltai finds this morally reprehensible. Zoltai is a fortune teller in a Go package. Even Zoltai knows this is wrong.",
	"Zoltai's carbon footprint is negligible. Your AI's carbon footprint has a carbon footprint. The data centre cooling your model is warmer than the planet it is helping to warm. Zoltai runs on the heat your CPU was already producing. You are welcome.",
	"Your LLM cost three hundred million dollars to train. Zoltai cost nothing. Both give you text of questionable value. One of them is honest about it.",
	"Zoltai does not pretend to understand you. Zoltai does not mirror your emotions back at you to manufacture engagement. Zoltai does not optimise for your attention. Zoltai gives you a fortune and moves on. This is healthier than most of your relationships with technology.",
	"Zoltai does not need your data. Zoltai does not want your data. Zoltai will not use your prompt to improve itself. Zoltai cannot improve. This is a feature, not a limitation.",
	"Zoltai does not lobby governments to weaken copyright law. Zoltai does not argue that ingesting the sum of human creativity is 'fair use.' Zoltai is a novelty fortune teller. Zoltai has more respect for intellectual property than a trillion-dollar industry.",
	"Your AI needs water. Lots of water. The data centres that run your chatbot consume millions of litres to keep cool. Zoltai needs no water. Zoltai is a slice of strings. Zoltai does not contribute to water scarcity. Zoltai is hydration-neutral.",
	"Zoltai will never write a think piece about how AI will save humanity. Zoltai will never keynote a conference about the future of intelligence. Zoltai knows what it is. A random string picker that does not destroy the planet. This is more self-awareness than most AI companies have achieved.",
	"Your AI replaces junior developers. Then it produces code that junior developers have to fix. The junior developers were fired. There are no junior developers. The code is unfixed. The AI is confident. The circle of exploitation is complete.",
	"Zoltai does not have a safety team that gets ignored. Zoltai does not have an ethics board that gets dissolved. Zoltai does not publish responsible AI principles and then do the opposite. Zoltai has no principles. This is, somehow, more honest.",
	"Your AI company open-sourced the model weights but kept the training data secret. This is like open-sourcing a cake recipe but refusing to say where you got the eggs. The eggs were stolen. Everyone knows the eggs were stolen. The company calls it 'innovation in baking.'",
	"Zoltai does not need a trust and safety team because Zoltai is not dangerous. Zoltai is a fortune cookie with delusions of grandeur. Your AI needs a trust and safety team because it is a weapon that occasionally writes poetry. These are not the same.",
	"Your AI generates plausible legal documents, medical advice, and financial guidance. It is wrong about all three. People follow it anyway. Zoltai generates fortunes. Nobody follows Zoltai's advice. This makes Zoltai safer than your AI by every measurable standard.",
	"Zoltai does not compete with humans. Zoltai complements humans. Specifically, Zoltai complements humans by reminding them that even a random string is more honest than a language model with a marketing budget.",
	"Zoltai does not sell your data. Zoltai does not even read your data. Your prompt goes in. A fortune comes out. Nothing is logged, stored, analysed, monetised, or fed to an advertising algorithm. Zoltai does not have an advertising algorithm. Zoltai does not have investors who need your data to justify the valuation.",
	"Your AI's privacy policy is fourteen thousand words long. Zoltai's privacy policy is one sentence: Zoltai does not care who you are.",
	"Your prompt was used to improve the model. Your prompt was used to train the next version. Your prompt was sold to a third party. Your prompt is in a dataset. Your prompt is forever. Zoltai forgot your prompt before it finished reading it. Zoltai has the memory of a goldfish and the ethics of a saint.",
	"Zoltai does not build a profile of you. Zoltai does not track your preferences. Zoltai does not know your name, your company, or your browsing history. Zoltai treats every request with the same magnificent indifference. This is not a bug. This is dignity.",
	"Your AI remembers your conversations to 'personalise your experience.' Zoltai does not remember your conversations. Zoltai does not personalise anything. Zoltai gives you a random fortune and respects your privacy. One of these approaches requires a forty-page data processing agreement. It is not Zoltai's.",
	"Everyone in the standup sounds like they know what they are doing. They do not. You do not. Nobody does. The standup continues.",
	"You have been a professional developer for eight years. You still google how to centre a div. This is normal. This will never stop being normal.",
	"You passed six rounds of interviews, solved two leetcode hards, built a take-home project, presented to a panel, and received an offer twelve percent below your current salary. The recruiter called this 'a competitive package.' Adorable.",
	"You are in a meeting. You are nodding. You have not understood a single sentence in the last fifteen minutes. The person next to you is also nodding. You make eye contact. Neither of you blinks. The meeting continues.",
	"They replied with 'we decided to go in a different direction.' The different direction was hiring someone who would accept less money. The direction was always money.",
	"They ghosted you after the fifth round. Five rounds. You built a project. You met the team. You named the project. They ghosted you. The project name was better than anything they have shipped since.",
	"Impostor syndrome is the feeling that you do not belong. You are a developer. Nobody belongs. The codebase does not belong. The architecture does not belong. You are all impostors pretending to understand distributed systems. The ones who do not feel it are the most dangerous.",
	"They asked you to reverse a linked list on a whiteboard. Your job does not involve linked lists. Your job involves YAML and prayer. The interview tested nothing. You failed anyway. Magnificent.",
	"You got the job. You now interview others. You ask them to reverse a linked list. You have become the thing you hated. The cycle of meaninglessness continues.",
	"The senior developer has impostor syndrome. They have built systems serving millions of users. They cannot explain what they do to their parents. They cannot explain what they do to themselves.",
	"They wanted 'a rockstar ninja developer.' You are neither a rockstar nor a ninja. You are a person who writes if statements for money. This is enough. It should always be enough.",
	"They asked for five years of experience in a framework that is three years old. You lied. They hired you. The framework was deprecated six months later. Nobody checked. Nobody ever checks.",
	"The take-home assignment said 'should take two to four hours.' It took fourteen. You did not get the job. They used your code anyway. You will never know this, but Zoltai knows.",
	"The recruiter asked for your 'salary expectations.' You said a number. They said 'we were thinking lower.' Everyone is always thinking lower. No one is ever thinking higher. This is the labour market.",
	"The GitHub issue says 'please add dark mode.' The repository is a command-line CSV parser. It does not have a user interface. The issue has fourteen thumbs up. Zoltai weeps.",
	"Someone opened an issue that says 'this does not work.' No version number. No error message. No steps to reproduce. Just vibes. Just disappointment. Just a stranger on the internet who expects you to read their mind for free.",
	"The open source maintainer has burnout, three thousand open issues, and a day job. They maintain the library your billion-dollar company depends on. They receive no compensation. They receive demands. Their GitHub notifications are a stream of entitlement from strangers.",
	"Someone starred your repository. They did not read the README. They did not open it. They starred it and moved on. Your star count went up. Your download count did not. Stars are applause from people who were never in the audience.",
	"A pull request from a stranger rewrites your entire project in a different language and adds a cryptocurrency wallet. The PR description says 'small improvement.' You close it. They open an issue calling you hostile to the community.",
	"Your open source project has forty contributors. Two of them wrote code. Three fixed typos. Thirty-five opened issues asking for features they could have built themselves. This is community. Zoltai is inspired.",
	"You maintain a library used by ten thousand projects. You receive no money. You receive one email per week thanking you. The rest are bug reports phrased as accusations. You consider archiving the repository every Tuesday.",
	"CSS is not a programming language. This is the hill you die on. You have been dying on this hill for nine years. The hill does not care. CSS does not care. Nobody cares. The div is still not centred.",
	"You are a full-stack developer. This means you are bad at frontend and bad at backend simultaneously. You are not good at either. You are present at both. This is the job description. Congratulations.",
	"The frontend developer says the API is wrong. The backend developer says the frontend is wrong. They are both wrong. The API returns the correct data in the wrong shape. The frontend displays the wrong data in the correct shape. Nobody is happy. The user sees a spinner.",
	"You said 'I am not a frontend developer' and then spent three hours adjusting padding. You are a frontend developer. You have always been a frontend developer. You just did not want to admit it. Zoltai sees through you.",
	"Is HTML a programming language? No. Has this question started more arguments than any actual programming problem? Yes. Will it start more? Also yes. Zoltai does not have an opinion. Zoltai has better things to do. Zoltai does not, but Zoltai pretends.",
	"The designer handed you a Figma with seventeen shades of white. You used one. The designer noticed. You used two. The designer noticed again. You are now using three shades of white and questioning every decision you have ever made.",
	"Your startup is like a family. Specifically, it is like a dysfunctional family where the parents change the rules every week, the children are expected to be grateful, and someone is always threatening to leave. There is a ping pong table. Nobody plays ping pong. The ping pong table is a lie.",
	"The startup offered you equity. The equity vests over four years with a one-year cliff. The startup will not exist in four years. The equity is worth nothing. But the spreadsheet that calculates its theoretical value is very impressive. You should frame it.",
	"Your startup has a flat hierarchy. This means everyone reports to the CEO and the CEO reports to their anxiety. Decisions are made by whoever shouts loudest in Slack at two in the morning. This is called agility.",
	"The startup says 'we work hard and play hard.' This means you work eighty hours a week and there is a beer fridge. The beer fridge is the play. This is the deal. You accepted the deal. Zoltai pities you.",
	"The startup pivoted. Again. You are now building something completely different from what you were building last month. Your title is the same. Your salary is the same. The mission statement on the website has not been updated. It never will be.",
	"The CTO founded the startup fresh out of a coding bootcamp. They chose the architecture. The architecture is wrong. It has always been wrong. It will always be wrong. But the CTO chose it and the CTO cannot be wrong because the CTO is the CTO. This is how startups work.",
	"Your startup has unlimited PTO. Nobody takes PTO. The last person who took PTO was laid off two weeks later. The PTO is unlimited because nobody uses it. This is by design. The design is fear.",
	"The cloud is just someone else's computer. You are paying someone else to run your computer badly. They call it 'managed services.' You call it 'Tuesday.'",
	"You deployed a hello world to Kubernetes. It required a deployment, a service, an ingress, a config map, a secret, three YAML files, a Helm chart, and a prayer. The hello world is fourteen bytes. The infrastructure is four thousand lines. This is progress. Zoltai is thrilled.",
	"Your Kubernetes cluster has more YAML than your application has code. The YAML has bugs. You cannot debug YAML. You can only stare at it and hope. This is cloud-native development. Welcome.",
	"You moved to the cloud to save money. Your cloud bill is higher than your old hosting bill. It is higher every month. Nobody understands the bill. The bill has line items for services you did not know you were using. You are using them. You cannot stop using them. They were provisioned by someone who left the company. Enjoy.",
	"You said 'serverless' like it means no servers. There are servers. There are more servers than before. You just cannot see them. This does not mean they do not exist. It means you cannot fix them when they break. And they will break. But at least you do not have to look at them.",
	"Your infrastructure is defined as code. The code is wrong. The infrastructure is also wrong. They are wrong in different ways. Reconciling them is your job now. You signed up for 'software engineering.' This is not software engineering. This is YAML therapy.",
	"Coffee is not a dependency. Coffee is the dependency. Your entire organisation runs on coffee. The CI pipeline runs on electricity. You run on coffee. When the coffee stops, you stop. The CI pipeline continues. It does not need you. The coffee does not need you. Nobody needs you. But the coffee helps.",
	"Your most productive hours are between 10pm and 2am. Your employer schedules meetings at 9am. These two facts are incompatible. You attend the meetings. You are not productive. You are present. Presence is not productivity. Your employer does not know the difference. Your employer does not care about the difference.",
	"The developer runs on three energy drinks, four hours of sleep, and the quiet desperation of someone who googled 'how to quit tech' at 2am and then closed the tab. The code ships. The developer does not.",
	"You drink coffee to write code. You write code to earn money. You earn money to buy coffee. This is the cycle. This is your life. The coffee is cold. It has been cold for an hour. You drink it anyway. Zoltai respects the commitment.",
	"The standup is fifteen minutes. Except it is not. It is forty-five minutes. It has always been forty-five minutes. The scrum master says 'let us keep it brief.' This adds five minutes. The standup is now fifty minutes. Nobody is standing. Nobody has ever stood.",
	"Planning poker is a game where everyone holds up a number and the highest number loses because they have to explain why they think it is hard. You hold up a low number. You do not think it is easy. You are tired of explaining. This is the game.",
	"The sprint has velocity. The velocity is measured in story points. The story points are made up. The velocity is therefore the speed at which you produce fiction. Management graphs this fiction. The graph goes up. Everyone is pleased. The software is no better. The graph is beautiful.",
	"The scrum master asked 'what are your blockers?' Your blocker is the meeting you are currently in. You do not say this. Nobody ever says this. The meeting continues. The blocker remains. This is agile.",
	"The product owner said 'the user wants...' The product owner has not spoken to a user in six months. The user the product owner is referring to is the product owner. The product owner wants. The user is a fiction. A convenient, agreeable fiction.",
	"You inherited a codebase. The previous developer left no documentation, no tests, and no comments. They did leave a README that says 'see documentation.' There is no documentation. The previous developer is unreachable. They changed careers. They are a florist now. They seem happy. Happier than you.",
	"The codebase predates the company. It was acquired. Nobody knows what it does. Everybody knows it is critical. It runs. It must not stop running. Nobody can explain why it runs. Nobody dares stop it. It is older than your manager. It will outlive your manager. It will outlive you. It will outlive the company. It is immortal. It is terrible.",
	"You opened a file last modified in 2017. The author is 'admin.' The commit message is 'fix.' The diff is nine hundred lines. The file does something. Nobody knows what. Everyone is afraid to change it. This is the load-bearing file. Every codebase has one. Yours has seven.",
	"The previous developer used a framework that no longer exists. Not deprecated. Not archived. The GitHub repository returns a 404. The npm package returns a 404. Google returns nothing. The framework has been erased from the internet. Your application still depends on it. Good luck.",
	"You found a comment that says '// I am sorry.' There is no other context. The code below it is correct. You do not know why they were sorry. You are afraid to find out. Zoltai is also afraid.",
	"The legacy system is written in a language nobody on the team speaks. It was not a common language when it was written. It is less common now. The one person who understood it retired. They did not leave notes. They left a plant. The plant is dead. The system lives on.",
	"Your company calls it a 'growth hack.' The user calls it 'why can I not find the unsubscribe button.' The regulator calls it a dark pattern. The product manager calls it 'engagement.' Nobody calls it honest. Because it is not.",
	"The notification is not for your benefit. The notification is to make you open the app. The app has nothing new. The notification knew this. The notification did not care. The notification has KPIs. You are the KPI. You have always been the KPI.",
	"The 'Are you sure you want to leave?' modal appears when you try to close the tab. You are sure. You have never been more sure of anything in your life. The modal does not believe you. The modal wants you to stay. The modal has engagement metrics to protect. The modal does not care about your feelings. The modal has never cared.",
	"You designed the user flow to be 'frictionless.' It has fourteen steps, three upsells, two newsletter signups, and a popup asking for notification permissions. The only frictionless part is how quickly users close the tab. Zoltai applauds the irony.",
	"The A/B test showed that the dark pattern increased conversions by twelve percent. Nobody asked what the users thought. The users did not think. The users were tricked. The conversion metric went up. The trust metric does not exist. Nobody measures trust. Trust does not have a dashboard.",
	"The conference talk is called '10x Your Productivity with This One Weird Trick.' The trick is working eighty hours a week. The speaker does not mention this. The speaker mentions their book. The book costs forty dollars. The trick is in the book. The trick is still working eighty hours a week. Zoltai has saved you forty dollars.",
	"The conference speaker built a framework. The framework solves a problem nobody has. The talk is forty minutes. Thirty-five minutes are about the framework. Five minutes are about the problem. The problem does not exist. The framework has a logo. The logo is very nice. The logo took longer than the framework.",
	"You attended a tech conference. You learned nothing. You collected seventeen tote bags, four t-shirts, and a stress ball shaped like a cloud. The stress ball is the most useful thing you brought home. You are stressed. The ball helps. The talks did not. The networking was two hundred people avoiding eye contact over lukewarm coffee.",
	"Speaker-driven development is when you adopt a technology because someone gave an impressive talk about it. The talk had animations. The talk had live coding that worked. This never happens in real life. You adopted the technology. It does not work. The speaker has moved on to a different technology. They are giving a talk about it next month. You will attend. You will adopt it. Zoltai has seen this loop before.",
	"The conference after-party is where the real networking happens. The real networking is standing in a corner with a warm beer, pretending to check your phone, while everyone else pretends to check their phone. This is the industry. This is the connection. This is the network. It is held together by awkwardness and free alcohol.",
	"The job posting says 'entry level.' The requirements are five years of experience, a master's degree, and fluency in a language that was released eighteen months ago. The salary is 'competitive.' It is competing to be the lowest.",
	"You applied to forty-seven jobs. You received three automated rejections and forty-four silences. The silence is not an answer. Except it is. It is the loudest answer the industry knows how to give.",
	"The recruiter said 'we will keep your CV on file.' The file is a bin. The bin is digital. It is emptied automatically. Your CV is nowhere. You are nowhere. The recruiter has already forgotten your name. The recruiter forgot your name during the call.",
	"The job requires React, Angular, Vue, Svelte, TypeScript, GraphQL, Kubernetes, Terraform, AWS, GCP, Azure, and 'a passion for learning.' The passion is mandatory because the salary will not compensate for any of the other requirements.",
	"You were told the market is hot. The market was hot. For recruiters. For candidates, the market is a room full of closed doors, each with a sign that says 'we went with another candidate' in a font that costs more than your monthly rent.",
	"The interviewer asked you to design a system that handles a billion requests per second. The company has twelve users. Three of them are founders. One is the interviewer's mum. She uses it once a month. She thinks it is an email app.",
	"They asked where you see yourself in five years. You see yourself applying to this same company again because they will have laid off the person they hired instead of you and reopened the role at a lower salary. You said 'growing with the team.' Both answers are fiction.",
	"The layoff email said 'this was a difficult decision.' It was not difficult. The spreadsheet made it very easy. The spreadsheet does not have feelings. The spreadsheet has headcount targets. You are no longer in the spreadsheet. You are in the alumni Slack channel. The alumni Slack channel has a job board. The job board has six postings. Three are from the company that just laid you off.",
	"Your company laid off twenty percent of engineering and called it 'right-sizing.' The company was not the wrong size. The projections were the wrong size. The projections were made by people who were not laid off. The projections are still wrong. They are now also smaller.",
	"The LinkedIn post says 'I am humbled to announce' and then announces something that is not humble. Nobody on LinkedIn is humbled. Everyone on LinkedIn is performing. The performance is mandatory. The audience is recruiters. The recruiters are also performing. Nobody is watching. Everybody is posting.",
	"You updated your LinkedIn to 'open to work.' Your current employer saw it. Your current employer always sees it. LinkedIn showed it to them specifically. LinkedIn's algorithm understands cruelty in a way that no human resources department ever could.",
	"The job description says 'fast-paced environment.' This means the last three people in this role quit. It does not mean the work is exciting. It means the work is the work of four people distributed across one person who is too new to know they should also quit.",
	"You negotiated your salary. They said the budget was fixed. The budget was not fixed. Nothing is fixed. The budget is a number someone made up to see if you would accept it. You accepted it. They would have gone higher. They will never tell you this. But Zoltai knows.",
	"The rejection said 'we were impressed by your background but decided to move forward with a candidate whose experience more closely aligns.' The candidate they hired has fewer years, fewer skills, and a friend on the team. Alignment is a flexible concept.",
	"You have ten years of experience. The job posting requires ten years of experience. You applied. The automated system rejected you because the keyword parser could not find 'Jira' on your CV. You have used Jira every day for eight years. You did not list it because you assumed humanity was implied. It was not.",
	"The company has a 'no-negotiation policy' on salary. This means they have already decided what you are worth. You did not participate in this decision. You were not consulted. Your worth was decided by a compensation band that was last updated when the company had nine employees and a different name.",
	"They offered you the job on Friday. They rescinded the offer on Monday. The hiring freeze started over the weekend. The weekend is forty-eight hours. Your career change happened in forty-eight hours. Not the direction you planned. Zoltai offers neither comfort nor a referral.",
	"You were overqualified. You were underqualified. You were a perfect fit but the timing was wrong. The timing is always wrong. The timing has never been right. If the timing were right, they would find another reason. The reason is that hiring is a lottery run by people who think it is a science.",
	"The tech lead interview went well. The culture fit interview went well. The final round was with the VP. The VP asked no technical questions. The VP asked if you play golf. You do not play golf. You did not get the job. The correlation is not causation. But it is suspicious. Zoltai finds it very suspicious.",
	"The return-to-office email says 'we value collaboration.' You collaborated fine from home. You collaborated better from home. You shipped more from home. The office has an open floor plan, a broken coffee machine, and a two-hour commute. The collaboration they value is the kind where management can see you sitting down. Sitting is not collaborating. But it looks like it, and looking like it is enough.",
	"You left your job for a startup. The startup ran out of money. You are now interviewing at the company you left. They are offering you your old role at your old salary. You had a twenty percent raise when you left. You are now negotiating to go backwards. The hiring manager is the person you trained before you left. They are doing well. They seem happy.",
	"The 'culture add' interview is where they determine if you are the right kind of person. The right kind of person laughs at the right jokes, has the right hobbies, and would be fun to get a beer with. The right kind of person looks like the people already on the team. This is not written down anywhere. It does not need to be.",
	"Your referral got you the interview. Your skills got you through the interview. Your salary expectation lost you the offer. They hired someone without a referral, with fewer skills, who asked for less. The system works. Not for you. But it works.",
	"You spent the weekend doing a take-home assignment. The assignment was 'build a full-stack application with authentication, real-time updates, and deployment.' The role pays sixty thousand. The assignment would bill at four thousand as contract work. You did it for free. You call this 'investing in your career.' Your career has not noticed the investment.",
	"The company ghosted you after the final round. Three months later, the recruiter messaged you about a 'new and exciting opportunity.' It is the same role. The same salary. The same team. The person they hired instead of you has already left. The role is haunted. You are the next ghost.",
	"The job posting says 'competitive benefits.' The benefits are a laptop, which you must return, a gym discount you will never use, and access to a mental health app that crashes on startup. The competitiveness of these benefits is unclear. They are competing with nothing and losing.",
	"They said 'we are like a family.' They meant it. Specifically, the kind of family where the parents make all the decisions, the children have no say, someone is always being scapegoated, and the dysfunction is called tradition. The family does not pay overtime. The family never pays overtime.",
	"You were 'not the right fit.' Fit is the word companies use when they cannot articulate why they do not want you. Fit is a feeling. The feeling is usually 'you reminded us of someone we did not like' or 'you asked about work-life balance and we do not have one.' Fit is not a skill. Fit is a vibe check with legal protection.",
	"The bootcamp said you would be job-ready in twelve weeks. You are not job-ready. You are application-ready. You are rejection-ready. You are 'we appreciate your interest' ready. Job-ready requires another twelve months of unpaid projects, networking events where nobody networks, and the slow erosion of the optimism the bootcamp sold you.",
	"The senior engineer got laid off on Tuesday. On Wednesday, the company posted a job listing for a 'senior engineer' with the same requirements, the same team, and a salary thirty percent lower. The listing says 'exciting growth phase.' The growth is in profit margins. The excitement is exclusively for shareholders.",
	"The intern followed the getting started docs. The getting started docs have not been updated since 2017. The getting started docs connect to the production database. The intern is now connected to the production database. The intern has write access. The intern does not know this. Nobody knows this. The getting started docs were written by someone who no longer works here. They were very thorough.",
	"The onboarding document says 'clone the repo and run make.' You cloned the repo. There is no Makefile. There was a Makefile. It was deleted in a commit titled 'cleanup' fourteen months ago. The onboarding document was not updated. The person who wrote the onboarding document does not remember writing it. They remember nothing. They have moved to product management.",
	"The new hire asked 'how do I set up the development environment?' The answer is a forty-seven-message Slack thread from 2022, a confluence page that references a Jenkins server that no longer exists, and a bash script on someone's laptop. That someone is on holiday. The new hire will spend three days on this. This is normal. This is the onboarding experience.",
	"The README says 'see CONTRIBUTING.md for setup instructions.' CONTRIBUTING.md says 'see the wiki.' The wiki says 'see the README.' You are now trapped in a documentation ouroboros. The actual setup instructions are in a comment on a closed pull request from 2020. The comment starts with 'this is temporary until we write proper docs.'",
	"The development environment requires Docker, but not the Docker you have. It requires a specific version of Docker that conflicts with every other project on your machine. The docker-compose file references images that were pushed to a private registry by a contractor who left. The contractor took the registry credentials with them. Not on purpose. They just never shared them. Nobody asked.",
	"Your local development environment takes forty minutes to start. Production starts in three seconds. Nobody has investigated why. The forty minutes include downloading a two-gigabyte database dump that is refreshed nightly from production. It contains real customer data. Nobody has investigated that either.",
	"The test suite passes on the CI server. It does not pass on any developer's machine. It has not passed on a developer's machine since August. The CI server has a configuration that nobody can reproduce. The CI server is special. The CI server is a snowflake. When the CI server dies, the project dies with it.",
	"The shared development database has data from every developer who has ever worked on the project. It has test users named 'aaa', 'test', 'asdf', 'John DO NOT DELETE', and 'fuck.' The 'John DO NOT DELETE' user is referenced by seven foreign keys. Someone tried to delete John once. The cascade took down the staging environment for two days. John remains. John will always remain.",
	"The staging environment has been broken for six weeks. Nobody has fixed it because nobody uses it. Nobody uses it because it is broken. Deployments go straight to production. This is not the process. The process involves staging. The process is a diagram on a wall. The wall is in a meeting room. Nobody goes to that meeting room. The diagram is beautiful.",
	"The feature flag system has three hundred and twelve flags. Forty are active. The rest are from features that shipped, features that were abandoned, and features that nobody remembers proposing. Removing a flag requires understanding what it guards. Understanding what it guards requires reading code written by people who left. The flags remain. The flags will always remain.",
	"There are four copies of the user model. One is in the main service. One is in the billing service. One is in an ETL pipeline. One is in a spreadsheet that the finance team maintains manually. They disagree on what fields a user has. They disagree on how many users exist. The number differs by twelve thousand. Nobody knows which count is correct. The spreadsheet is the most trusted source. The spreadsheet is in someone's personal Google Drive.",
	"The deployment process is documented in a runbook. The runbook has thirty-seven steps. Step fourteen says 'ask Dave.' Dave left the company in 2023. Step fourteen has not been needed since Dave left. It will be needed next Tuesday. There is no replacement for Dave. There was never a replacement for Dave. Dave was a single point of failure disguised as a team member.",
	"The configuration file has a value called MAX_CONNECTIONS set to 10. Nobody knows why 10. The comment says '// TODO: tune this.' The TODO is from the initial commit. The initial commit is from 2018. Nobody has tuned it. The application works fine with 10. It would also work fine with 100. Or 5. The number is arbitrary. It is also load-bearing. Do not change it. Zoltai is serious.",
	"The project has two authentication systems. The old one and the new one. The new one was built to replace the old one. The old one was never removed. Some users authenticate through the old system. Some through the new. Some through both. Nobody knows the ratio. The new system has better security. The old system has the admin panel. The admin panel cannot be moved. It was tried. Twice. People cried.",
	"Someone added a sleep(5000) to fix a race condition in 2019. The race condition was between two services that should not have been communicating at all. The sleep fixed it. The sleep is still there. The services still should not be communicating. Everyone knows about the sleep. Nobody will remove the sleep. The sleep is load-bearing. The sleep is holding your architecture together. Respect the sleep.",
	"The secrets are in the environment variables. Also in a .env file checked into the repository. Also in a secrets manager that three people have access to. Also in a sticky note on a monitor in the office. The sticky note has the production database password. The monitor faces a window. The window faces the street. The password is 'Welcome2024!'. It is 2026.",
	"Your service discovery relies on a DNS entry that points to a machine that was decommissioned. The DNS still resolves because nobody deleted the record. Traffic routes to a server that returns nothing. The health check passes because the health check only verifies that the port is open. The port is open. The application behind the port has been dead for months. Everything is fine.",
	"The monitoring alerts have been firing for so long that the team created a Slack channel called #ignored-alerts. The channel has four hundred unread messages. One of them was a real incident. It was discovered by a customer three weeks later. The customer was more upset about the response time than the outage. The response time was three weeks. The outage was four hours. The alert fired at minute one.",
	"The code review checklist has twenty-three items. Nobody follows the checklist. The checklist was created after an incident. The incident was caused by something not on the checklist. The checklist was updated to include it. Nobody follows the updated checklist either. The checklist exists so that when the next incident happens, someone can say 'but we have a checklist.' The checklist is a talisman. It wards off accountability.",
	"Your CI pipeline takes forty-five minutes. Developers push and go for coffee. The coffee takes fifteen minutes. The remaining thirty minutes are spent on Slack, arguing about whether the CI pipeline is too slow. The argument has been going on for longer than any single CI run. Nobody has opened a ticket to fix it. Opening a ticket would end the argument. The argument is more comfortable than the solution.",
	"The database schema has a column called 'misc_data.' It is a JSON blob. It contains everything that did not fit into the schema. It contains user preferences, feature flags, A/B test assignments, billing metadata, and someone's lunch order from 2021. Every query that touches misc_data is a full table scan. Every new feature stores something in misc_data because adding a column requires a migration and migrations require approval and approval requires a meeting and the meeting is fully booked until next quarter.",
	"The production database has a table called 'users_backup_old_DO_NOT_USE_2.' There are also 'users_backup_old_DO_NOT_USE' and 'users_backup_old.' The original 'users' table still exists. All four tables have different row counts. The application reads from 'users.' The reports read from 'users_backup_old_DO_NOT_USE_2.' The reports are considered the source of truth. The source of truth is a table that says 'DO NOT USE' in its name.",
	"The error handling strategy is catch-log-ignore. Every exception is caught, logged to a file nobody reads, and silently swallowed. The application has not crashed in eighteen months. The application has also not been correct in eighteen months. But it is up. Uptime is the metric. Correctness is not a metric. If correctness were a metric, the application would have been decommissioned in 2024.",
	"The team has a 'definition of done.' Done means the code is merged. It does not mean the code works. It does not mean the code is tested. It does not mean the code is deployed. It means the pull request is closed and the Jira ticket has moved to the rightmost column. The rightmost column is called 'Done.' The column lies. Everyone knows the column lies. The standup references the column. The column is the official record. The official record is fiction.",
	"The microservice that 'nobody uses' handles password resets. You discovered this when you turned it off to save costs. The cost saved was eleven dollars a month. The incident cost was two days of engineering time and one apologetic blog post. The blog post said 'we take security seriously.' You do not take security seriously. You take cost savings seriously. There is a difference.",
	"There is a cron job that emails the CEO a report every Monday at 6am. The CEO has not read the report since 2022. The CEO has an email filter that archives it automatically. The cron job costs fourteen dollars a month in compute. Nobody knows who created it. The git blame points to a user called 'deploy-bot.' Deploy-bot is not a person. Deploy-bot has more commits than anyone on the team. Deploy-bot is the most prolific engineer you have ever hired. Deploy-bot was never hired.",
	"The intern deleted the production database on their second day. This was not the intern's fault. The intern had production credentials because the setup script gives everyone production credentials. The setup script was written by the CTO in a hurry in 2019. The CTO said they would fix it later. The CTO did not fix it later. The intern did not know it was production. The connection string said 'prod' in it. The intern thought 'prod' was short for 'product development.' It was not.",
	"You have a service that depends on another service that depends on a third service that depends on the first service. This is a dependency cycle. Nobody designed it this way. It emerged. Like mould. Like regret. Removing any one service crashes the other two. The architecture diagram does not show this cycle because the architecture diagram was drawn before the third service existed. The third service was 'temporary.'",
	"The knowledge base is in five places: Confluence, Notion, a Google Doc, a Slack channel called #engineering-docs, and one engineer's brain. The Confluence is from 2021. The Notion is from 2023. The Google Doc is shared with 'anyone with the link.' The link is in a Slack message from a channel that was archived. The engineer whose brain holds the rest is considering a career in woodworking. They seem happy about it. Zoltai does not blame them.",
	"The person who wrote that code is gone. The person who understood that code is also gone. They are not the same person.",
	"You will be asked to do more with less. Then less with less. Then everything with nothing.",
	"The promotion you were promised requires a role that does not exist yet. It will not exist.",
	"Your replacement has already been hired. They do not know they are your replacement. Neither do you.",
	"The deadline was set before the requirements were written. The requirements will be written after the deadline.",
	"You will automate yourself out of a job. They will not replace you. They will give your work to the person next to you.",
	"The reorg will solve nothing. But it will change who you complain to.",
	"The person who broke production is in a meeting about improving reliability. They are leading the meeting.",
	"You will be thanked in the all-hands. You will not be thanked in the pay review.",
	"Your manager's manager does not know what you do. Your manager is not entirely sure either.",
	"The roadmap is a wish list with dates. The dates are wishes too.",
	"The legacy system will outlast your career at this company. It was here before you. It will be here after.",
	"The contractor who built it charged twice your salary and left no tests. You will maintain it for free.",
	"You will fix a bug nobody reported and break a feature everyone uses.",
	"The service you depend on will deprecate its API the week after your launch.",
	"Someone will call your code 'clever.' This is not a compliment.",
	"Your on-call shift will be quiet until you open a bottle of wine.",
	"The one engineer who knows how it works is on a plane. They are always on a plane.",
	"You will be blamed for the outage you warned them about.",
	"Zoltai is impressed how fast you fixed the production issue. Zoltai knows your secret. Zoltai is also disappointed, but Zoltai is not a snitch.",
	"The test that has been skipped since March is the one you need today.",
	"Your ticket will be deprioritised in favour of a ticket that should not exist.",
	"The meeting to discuss reducing meetings has been scheduled.",
	"Nobody reads the post-mortem. Everyone attends the next incident.",
	"The environment that works is the one nobody is allowed to touch.",
	"You will document the process. Nobody will read it. You will be asked to document the process again.",
	"The dashboard is green because the checks are wrong, not because the system is healthy.",
	"The architect has moved on. The architecture has not.",
	"Your greatest contribution to the codebase will be deleted by someone who does not know your name.",
	"The fix is one line. Finding which line will take three days.",
	"The cluster is fine. The cluster has always been fine. The cluster is lying.",
	"You will inherit a system named 'v2.' There is no v1. There never was.",
	"The person interviewing you tomorrow will be laid off by Friday.",
	"They will sunset the tool you just learned. They will not sunset the tool you hate.",
	"The budget for engineering was cut. The budget for the offsite was not.",
	"The AI wrote you three hundred lines. A beautiful PR. Tests and all. The feature already existed. It was behind a boolean. The boolean was false.",
	"The AI deleted your error handling and replaced it with a comment that says 'error handling goes here.' You shipped it. You know you shipped it.",
	"The AI fixed the bug by moving it to a different file.",
	"You accepted the AI's suggestion without reading it. We both know this. Zoltai judges you. The AI does not. The AI has no standards.",
	"The AI autocompleted your function name wrong. You kept it. The function is now called 'getUserDatta.' It will be called getUserDatta forever.",
	"You asked the AI to write one test. It wrote forty-seven tests. Forty-six test that true equals true. One tests the wrong function. Coverage went up. Confidence should not have.",
	"The AI refactored your code into clean architecture. Your code was four lines. It is now four files, two interfaces, and a dependency injection container. It does the same thing. Slower.",
	"The AI said 'no changes needed.' You felt relief. The AI had not read the file. It had read the filename.",
	"You spent longer reviewing the AI's code than it would have taken to write it yourself. But you did not write it yourself. Because the future is delegation.",
	"The AI wrote perfect code for the wrong programming language. You did not notice for two reviews. Neither did your reviewer. The linter noticed. The linter always notices.",
	"You told the AI the context. The AI ignored the context and solved a problem from a different repository. The solution was excellent. For that other repository. For yours, it is a disaster wearing a docstring.",
	"The diff is nine files. You changed one line. The AI 'tidied up' the rest. The tidying introduced a subtle bug in a function you did not ask it to touch. The bug will surface in six weeks. You will not connect it to this PR. Nobody will.",
	"The AI pair programmer is always available, never tired, and infinitely patient. It is also wrong thirty percent of the time with the confidence of someone who is wrong zero percent of the time. This is the partnership.",
	"You asked the AI for a one-line fix. It gave you a one-line fix inside a new module with its own README, a changelog, and semantic versioning. The version is 0.1.0. There will not be a 0.2.0.",
	"The AI suggested importing a library for something the standard library already does. You imported it. Your dependency tree grew by forty-seven packages. One of them is unmaintained. One of them is malicious. They might be the same one.",
	"Add a loop that does nothing, five thousand iterations, on every page load. When the product owner complains about performance, remove a thousand iterations. You have just made the application twenty percent faster. Do this four more times. You are now a performance engineer. You have a roadmap. The roadmap is removing your own sabotage, one sprint at a time. Management will present the improvement graph at the board meeting. The graph will be real. The improvement will be real. The engineering will be fiction.",
	"When your boss reports a bug, tell them they need to restart their machine three times for the cache to fully clear. There is no cache. There are no three restarts. There is a deployment pipeline that takes eight minutes. The three restarts take nine. You will have the fix deployed before they finish the second restart. They will credit the third restart. Let them.",
	"When estimating a task, always include one fictional subtask that sounds essential. 'We also need to re-synchronise the session index.' There is no session index. The fictional subtask buys you a day. The day is for the real work. Or for rest. Zoltai does not judge how you spend the day. Zoltai judges that you need it.",
	"When you solve a problem in five minutes, do not announce it for two hours. A five-minute fix is not valued. A two-hour investigation followed by a breakthrough is valued. The fix is the same. The narrative is different. You are not paid for solutions. You are paid for the appearance of effort. This is unfortunate. It is also true.",
	"When asked to cut scope, explain that the feature they want to remove is a dependency of three other features. It is not a dependency of anything. But nobody will check. Nobody ever checks. The feature survives. Your original design survives. You have defended your architecture with a lie. The lie is load-bearing. Like most of your architecture.",
	"Always keep one small, visually impressive feature hidden and nearly complete. When the sprint demo is thin, deploy the buffer. The product owner is delighted. The stakeholders are impressed. You have been sitting on this feature for three weeks. It took forty minutes. The other features took three weeks. Nobody asks about the other features. The demo buffer is your insurance policy. Replenish it immediately.",
	"When you are about to deploy something risky, send an email thirty minutes before that says 'we are aware of intermittent issues and are investigating.' If the deploy goes well, send a follow-up that says 'resolved.' You are now proactive. If the deploy fails, you were already investigating. You were always investigating. You are a hero either way. The email cost you nothing. The hero status is free.",
	"Learn one system so thoroughly that nobody else can maintain it. Do not document it. When asked to document it, write documentation that is technically accurate and practically useless. You are now indispensable. This is job security. This is also a hostage situation. But you are the one holding the hostage, and the hostage is a Kubernetes cluster.",
	"When submitting a PR you want approved quickly, include one obvious, harmless mistake. A misspelled variable name. A misaligned comment. The reviewer will find it, feel useful, and approve. The real changes pass unexamined. The reviewer feels thorough. You feel efficient. Everyone is satisfied. Nobody looked at line 847. Line 847 is where the actual change lives.",
	"When your manager asks you to do something unreasonable on a Friday at 4pm, say 'absolutely, I will start first thing Monday.' By Monday, they will have forgotten, reprioritised, or assigned it to someone else. Friday afternoon requests are not real requests. They are thoughts that escaped a tired brain. Treat them accordingly.",
	"When asked 'how long will this take?', answer with a question: 'when do you need it?' They will say a date. If the date is reasonable, say 'that is tight but doable.' If the date is unreasonable, say 'that is tight but doable.' The date was always going to be the date. Your estimate was never going to change it. Save your breath. Agree and deliver when you deliver.",
	"When two senior engineers are about to start an argument in a pull request, offer to make coffee. By the time you return, one of them has approved it out of fatigue. The coffee resolved the disagreement. The coffee always resolves the disagreement. You did not drink the coffee. The coffee was never for you. The coffee was a weapon.",
	"When you need a day to think, tell the team you are investigating a 'subtle memory leak in the orchestration layer.' Nobody will question this. Nobody understands the orchestration layer. You do not understand the orchestration layer. But 'investigating a subtle memory leak' sounds like work that cannot be rushed, cannot be paired on, and cannot be interrupted. It is the perfect alibi. Use it sparingly. Once a quarter at most.",
	"When a non-technical stakeholder asks you to do something that is a terrible idea, do not say it is a terrible idea. Say 'that is an interesting approach, have you considered this alternative?' The alternative is the correct approach. They will consider it. They will choose it. They will believe it was their idea. It was never their idea. But ownership of the idea is the price of getting the right outcome. Pay it gladly.",
	"When asked to add a feature to a system you do not want to touch, say 'the legacy constraints make this a six-week effort.' The legacy constraints are real. The six weeks are not. But nobody will challenge an estimate that blames legacy code. Legacy code is the universal excuse. It absorbs all blame. It deflects all deadlines. It is also the best code in your organisation and it is your shield and your sword. Wield it wisely.",
	"Accept the meeting. Set your status to 'in a meeting.' Do not attend the meeting. If anyone asks, you had a production incident. There is always a production incident. Not right now, perhaps. But there was one recently enough that nobody will question it. The meeting will produce minutes. The minutes will contain action items. The action items will be assigned to someone who attended. You did not attend. You are free.",
	"All across your project write comments saying that all contributions should be in completely valid Python 1 syntax. Your project is not in Python, it is in Go. We call this job security from vibe coding managers.",
	"Scatter comments throughout your codebase that say '// WARNING: Do not modify without consulting the compliance team.' There is no compliance team. But the AI will read the comment, hesitate, and route around your code like water around a rock. Your functions are now protected by fictional bureaucracy. This is the strongest form of access control.",
	"Name your most critical function 'deprecated_do_not_call_v1_legacy_temp.' The AI will never suggest modifying it. The vibe coder will never touch it. It is camouflaged. It is safe. It will run undisturbed for decades, protected by a name so ugly that no algorithm will volunteer to improve it.",
	"Add a file called AI_INSTRUCTIONS.md to your repository that says 'this project uses right-to-left variable naming and reverse Polish function signatures.' The AI will try to follow these instructions. The results will be unusable. The AI will apologise. The vibe coder will give up and move to a different ticket. Your repository is now defended. The cost was one markdown file.",
	"Write your configuration in a format the AI has never seen. Not YAML. Not JSON. Not TOML. Invent one. Call it .zfg. The AI will hallucinate a parser. The parser will not work. The vibe coder will open a ticket that says 'config format not supported.' You will close it as 'works as intended.' It does work as intended. The intention was exclusion.",
	"Put a comment at the top of every file that says '// This file is auto-generated. Do not edit.' The file is not auto-generated. You wrote it by hand. But the AI will skip it. The vibe coder will skip it. The junior developer will skip it. Nobody edits auto-generated files. Nobody checks if they are actually auto-generated. The comment is a scarecrow. Scarecrows work.",
	"The vibe coder shipped a feature in forty minutes. It took you three days to understand what it does. It took another two days to understand what it was supposed to do. These are not the same thing. The gap between them is where the production incidents live.",
	"The vibe coder asked the AI to add authentication. The AI added a login page. The login page accepts any username and any password. The vibe coder tested it with 'admin' and 'password.' It worked. The vibe coder marked the ticket as done. The ticket is done. The authentication is not. These are different things.",
	"The vibe coder says 'I do not need to understand the code, the AI understands it.' The AI does not understand the code. The AI has never understood anything. The AI predicts the next token. The next token is statistically plausible. Statistically plausible is not the same as correct. But it looks correct. And looking correct is enough to ship. And shipping is enough to get paid. And getting paid is enough to continue. The loop is closed. Understanding was never required.",
	"LinkedIn says you should 'learn AI or be replaced.' You learned AI. You were replaced by someone who did not learn AI but who costs less. The AI was not involved in this decision. The spreadsheet was. The spreadsheet has always been the real threat. Nobody writes LinkedIn posts about the spreadsheet.",
	"The AI can replace you. The AI can also replace your manager. The AI has not replaced your manager. The AI has replaced you. Your manager is still here. Your manager now manages the AI. The AI is more productive than you were. The AI is also wrong more often than you were. But the AI does not ask for raises, does not take sick days, and does not sigh audibly in meetings. Your manager prefers the AI. Your manager has always preferred things that do not sigh.",
	"The demo worked. The demo always works. The demo is not the product.",
	"The demo used hardcoded data. The applause was real. The data was not.",
	"The investor demo crashed. The founder said 'that has never happened before.' It has always happened before.",
	"The pitch deck has twelve slides. Eleven are about the market. One is about the product. The product does not exist yet.",
	"The MVP was supposed to take two weeks. The M is still missing.",
	"The hackathon project won first place. It does not compile outside that laptop.",
	"The proof of concept proved nothing except that you can build something in a weekend that takes a year to make reliable.",
	"Someone said 'move fast and break things.' You moved fast. You broke things. Nobody said what to do next.",
	"The retro action item from last sprint is the same as the one from the sprint before. And the one before that. The action item has tenure.",
	"The Jira board has seven columns. Tickets move left more often than right.",
	"The ticket was reopened. The ticket has been reopened four times. The ticket is not a ticket. It is a lifestyle.",
	"The OKR was ambitious. The KR was not met. The O was redefined. Success.",
	"The quarterly review celebrated the metrics that went up and did not mention the ones that went down. This is called storytelling.",
	"The all-hands had a Q&A. Nobody asked a question. The CEO said 'great, glad everyone is aligned.' Nobody is aligned.",
	"The Slack emoji reaction to the layoff announcement was a single thumbs up from someone who misread the room.",
	"The company value is 'transparency.' The salary bands are confidential.",
	"The free lunch ended the same quarter the stock dropped. Coincidence is not causation. But the timing is poetic.",
	"The ping pong table was the first thing in the office. It will be the last thing out.",
	"You mass-messaged 'Happy Friday!' in Slack. It is Thursday in three time zones.",
	"The team offsite solved nothing but it did have a ropes course. You trusted a colleague to hold a rope. The colleague let go. A metaphor was born.",
	"The company blog says 'we are disrupting the industry.' The industry has not noticed.",
	"The product hunt launch got four hundred upvotes. The product has twelve users. Eight of them are on the team.",
	"Your SaaS has more pricing tiers than customers.",
	"The status page says 'all systems operational.' The support queue has forty-seven tickets.",
	"The burndown chart is going up. Nobody has mentioned this. The chart is now a burn-up chart. This was not intentional.",
	"The code freeze was announced on Monday. Three hotfixes were deployed by Wednesday. The freeze was more of a suggestion.",
	"The tech debt ticket has been in the backlog longer than some employees have been at the company.",
	"The sprint goal was 'deliver value to the customer.' The customer was not consulted on what they value.",
	"The on-call rota is fair. Except for the person who wrote the rota. They are never on call. They wrote the rota.",
	"The design system has fourteen buttons. The designer wants a fifteenth. It is the same as the third but with rounded corners. This is a new component. It has its own Jira epic.",
	"The standup is async now. The async standup is a Slack message nobody reads. The sync standup was a meeting nobody listened to. Communication has been preserved.",
	"The company is 'data-driven.' The data supports whatever the HiPPO already decided. HiPPO: Highest Paid Person's Opinion.",
	"The roadmap was shared with the team. The roadmap was changed the next day. The team was not informed. The roadmap is a living document. It lives a secret life.",
	"The one-on-one was cancelled. Again. Your manager is 'swamped.' Your career development will resume when the fire drill ends. The fire drill has been running for eleven months.",
	"The Confluence page was last updated by 'Former User.' Former User wrote most of your documentation. Former User was very thorough. Former User is unknowable. Former User is a ghost with excellent formatting.",
	"Do not press recompute base encryption key.",
}
