//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_parent_f5d0595c

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_child_d247007e "testcase_026_cross_package_context_confusion/dist/partials/partials_child_d247007e"
	data_a "testcase_026_cross_package_context_confusion/pkg/data_a"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}
var _ = partials_child_d247007e.Render

// line partials/parent.pk:35
type Response struct{ Data data_a.ParentData }

// line partials/parent.pk:39
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Data: data_a.ParentData{ValueForChild: "This value comes from the parent"}}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_child_forwarded_prop_state_data_valueforchild_96702156 := partials_child_d247007e.Props{ForwardedProp: pageData.Data.ValueForChild}
	partials_child_d247007eData_child_forwarded_prop_state_data_valueforchild_96702156, partials_child_d247007eMeta_child_forwarded_prop_state_data_valueforchild_96702156, partials_child_d247007eErr_child_forwarded_prop_state_data_valueforchild_96702156 := partials_child_d247007e.Render(r, props_child_forwarded_prop_state_data_valueforchild_96702156)
	if partials_child_d247007eErr_child_forwarded_prop_state_data_valueforchild_96702156 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_child_d247007eErr_child_forwarded_prop_state_data_valueforchild_96702156.Error(), "R002", "", "Partial Render() error for partials_child_d247007e", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_child_d247007eData_child_forwarded_prop_state_data_valueforchild_96702156
	_ = partials_child_d247007eMeta_child_forwarded_prop_state_data_valueforchild_96702156
	_ = partials_child_d247007eErr_child_forwarded_prop_state_data_valueforchild_96702156
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/parent.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(1)
	tempVar1.Children = tempVar2Slice
	// line partials/child.pk:22
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "div"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetAttrWriterSlice(2)
	tempVar3.AttributeWriters = tempVar4Slice
	_, tempVar5Slice := arena.GetChildSlice(2)
	tempVar3.Children = tempVar5Slice
	tempVar6 := arena.GetDirectWriter()
	tempVar6.SetName("data-received")
	tempVar6.AppendEscapeString(props_child_forwarded_prop_state_data_valueforchild_96702156.ForwardedProp)
	tempVar3.AttributeWriters = append(tempVar3.AttributeWriters, tempVar6)
	tempVar7 := arena.GetDirectWriter()
	tempVar7.SetName("forwarded-prop")
	tempVar7.AppendEscapeString(pageData.Data.ValueForChild)
	tempVar3.AttributeWriters = append(tempVar3.AttributeWriters, tempVar7)
	tempVar3.Children = append(tempVar3.Children, staticNode_1)
	// line partials/child.pk:23
	tempVar8 := arena.GetNode()
	tempVar8.NodeType = pikoruntime.NodeElement
	tempVar8.TagName = "span"
	tempVar8.Attributes = staticAttrs_3
	tempVar9 := arena.GetDirectWriter()
	tempVar9.AppendString(strconv.FormatInt(int64(partials_child_d247007eData_child_forwarded_prop_state_data_valueforchild_96702156.OwnData.InternalValue), 10))
	tempVar8.TextContentWriter = tempVar9
	tempVar3.Children = append(tempVar3.Children, tempVar8)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: partials/parent.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 22
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 23
	staticNode_1  *pikoruntime.TemplateNode   // SOURCE: partials/child.pk, LINE: 22
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "parent-wrapper"}, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_parent_f5d0595c"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "parent"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "child"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "child-component"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeText
	staticNode_1.TextContent = " Child&#39;s own state: "
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_026_cross_package_context_confusion/dist/partials/partials_parent_f5d0595c", BuildAST)
}
