// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package generator_domain

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"io/fs"
	paths "path"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"golang.org/x/sync/errgroup"
	"golang.org/x/sync/syncmap"
	"piko.sh/piko/internal/annotator/annotator_domain"
	"piko.sh/piko/internal/annotator/annotator_dto"
	"piko.sh/piko/internal/ast/ast_domain"
	"piko.sh/piko/internal/collection/collection_dto"
	"piko.sh/piko/internal/config"
	"piko.sh/piko/internal/coordinator/coordinator_domain"
	"piko.sh/piko/internal/generator/generator_dto"
	"piko.sh/piko/internal/logger/logger_domain"
	"piko.sh/piko/internal/resolver/resolver_domain"
	"piko.sh/piko/internal/seo/seo_adapters"
	"piko.sh/piko/wdk/safedisk"
)

const (
	// generatorCausationID is the identifier used to track causation in
	// observability traces for generator operations.
	generatorCausationID = "piko-generator-service"

	// distPackageBoilerplate is the content for the placeholder file in the dist
	// package directory. Unlike other generated files, this placeholder does not
	// include the analysis build constraint so it is always visible to the
	// compiler.
	distPackageBoilerplate = `package dist
// This package contains generated Piko component files.
`

	// DirPermission is the permission mode for creating directories (rwxr-x---).
	// Uses 0750: owner rwx, group rx, others none.
	DirPermission = 0750

	// FilePermission is the file mode for new files (owner read-write, group
	// read). Uses 0640: owner rw, group r, others none.
	FilePermission = 0640

	// PublicDirPermission is for directories that must be world-readable
	// (rwxr-xr-x). Used for generated assets served to browsers.
	PublicDirPermission = 0o755

	// PublicFilePermission is the file mode for world-readable files (rw-r--r--).
	// Used for generated assets served to browsers.
	PublicFilePermission = 0o644

	// distDir is the folder name where generated output files are written.
	distDir = "dist"

	// logKeyCollection is the logger key for collection names.
	logKeyCollection = "collection"

	// emptyActionsStub is the TypeScript content for an empty actions file.
	// PKC components always import from actions.gen.ts, so we need this stub even
	// when no actions are discovered to prevent module load failures.
	emptyActionsStub = `// Auto-generated action types - DO NOT EDIT
// Generated by piko action-generator (empty stub)
import { ActionBuilder, createActionBuilder } from '/_piko/dist/ppframework.core.es.js';
export const action = {} as const;
`
)

// generatorService implements the GeneratorService interface.
// It coordinates the Piko compilation pipeline by calling the annotator
// service first, then directing its adapters to emit code.
type generatorService struct {
	// fsWriter writes generated code files to the file system.
	fsWriter FSWriterPort

	// manifestEmitter writes compilation manifests.
	manifestEmitter ManifestEmitterPort

	// coordinator manages the annotation process across all entry points.
	coordinator coordinator_domain.CoordinatorService

	// resolver resolves Piko-style paths and provides module information.
	resolver resolver_domain.ResolverPort

	// registerEmitter creates the content for the register aggregator file.
	registerEmitter RegisterEmitterPort

	// codeEmitterFactory creates code emitters for output generation.
	codeEmitterFactory CodeEmitterFactoryPort

	// collectionEmitter creates static collection files from annotated content.
	collectionEmitter CollectionEmitterPort

	// searchIndexEmitter creates search indexes for collections; nil skips
	// search index generation.
	searchIndexEmitter SearchIndexEmitterPort

	// pkJSEmitter writes client-side JavaScript files for pages; nil means
	// no JavaScript output is created.
	pkJSEmitter PKJSEmitterPort

	// i18nEmitter creates the i18n FlatBuffer binary file; nil skips generation.
	i18nEmitter I18nEmitterPort

	// actionGenerator generates action code files; nil skips action generation.
	actionGenerator ActionGeneratorPort

	// manifestBuilder builds manifest files from the generated artefacts.
	manifestBuilder *ManifestBuilder

	// seoService creates SEO files for the project; nil turns off SEO creation.
	seoService SEOServicePort

	// baseSandbox provides sandboxed access to the project root directory
	// for file operations that are not routed through port interfaces.
	baseSandbox safedisk.Sandbox

	// baseDir is the absolute path to the project root directory.
	baseDir string

	// enablePrerendering controls whether static HTML is prerendered.
	enablePrerendering bool

	// stripHTMLComments removes HTML comments from generated output.
	stripHTMLComments bool

	// enableDwarfLineDirectives emits valid DWARF //line directives in
	// generated code so debuggers can map back to .pk files.
	enableDwarfLineDirectives bool
}

// GeneratorPorts groups all adapter ports required by the generator service.
// It follows the dependency injection pattern to reduce parameter count in
// constructors.
type GeneratorPorts struct {
	// FSWriter writes generated output to the file system.
	FSWriter FSWriterPort

	// ManifestEmitter writes the generated manifest data to its output
	// destination.
	ManifestEmitter ManifestEmitterPort

	// Coordinator distributes work across generators.
	Coordinator coordinator_domain.CoordinatorService

	// Resolver finds Go source files using path resolution.
	Resolver resolver_domain.ResolverPort

	// RegisterEmitter writes the register function for generated code.
	RegisterEmitter RegisterEmitterPort

	// CodeEmitterFactory creates code file emitters for each package.
	CodeEmitterFactory CodeEmitterFactoryPort

	// CollectionEmitter writes collection data files and Go
	// wrappers to the output.
	CollectionEmitter CollectionEmitterPort

	// SearchIndexEmitter outputs search index data for the site.
	SearchIndexEmitter SearchIndexEmitterPort

	// PKJSEmitter outputs pre-processed front-end JavaScript files.
	PKJSEmitter PKJSEmitterPort

	// I18nEmitter writes translation data to the output.
	I18nEmitter I18nEmitterPort

	// ActionGenerator creates action code files from the ActionManifest.
	ActionGenerator ActionGeneratorPort

	// SEOService provides search engine optimisation features.
	SEOService SEOServicePort

	// BaseSandbox provides sandboxed access to the project root directory for file
	// operations not routed through port interfaces. If nil in non-WASM mode, a
	// NoOpSandbox is created from the base directory.
	BaseSandbox safedisk.Sandbox

	// SandboxFactory creates sandboxes with validated paths. When set and
	// BaseSandbox is nil, the factory is used before falling back to
	// NewNoOpSandbox.
	SandboxFactory safedisk.Factory
}

// GeneratorServiceOption configures the generator service.
type GeneratorServiceOption func(*generatorServiceOptions)

// generatorServiceOptions holds optional configuration for the generator
// service.
type generatorServiceOptions struct {
	// distSandbox is an optional sandbox for dist folder operations.
	// If nil, a sandbox will be created from the base folder.
	distSandbox safedisk.Sandbox

	// inMemoryMode skips filesystem operations such as creating the dist folder.
	// Use this for WASM or testing where file access is not available.
	inMemoryMode bool

	// enablePrerendering controls whether static HTML is prerendered at
	// generation time. When set, fully-static template subtrees are rendered
	// to HTML bytes during code generation.
	enablePrerendering bool

	// stripHTMLComments removes HTML comments from generated output.
	stripHTMLComments bool

	// enableDwarfLineDirectives emits valid DWARF //line directives in
	// generated code so debuggers can map back to .pk files.
	enableDwarfLineDirectives bool
}

// Generate orchestrates the full annotation and generation pipeline for a
// single entry-point component. It is a convenience wrapper for development
// and single-file builds.
//
// Takes request (generator_dto.GenerateRequest) which specifies the source path
// and generation options.
//
// Returns *generator_dto.GeneratedArtefact which contains the generated
// output for the component.
// Returns error when annotation, component resolution, or generation fails.
func (s *generatorService) Generate(
	ctx context.Context,
	request generator_dto.GenerateRequest,
) (*generator_dto.GeneratedArtefact, error) {
	ctx, span, l := log.Span(ctx, "GeneratorService.Generate", logger_domain.String("sourcePath", request.SourcePath))
	defer span.End()

	generateCount.Add(ctx, 1)
	startTime := time.Now()
	defer func() {
		duration := time.Since(startTime)
		generateDuration.Record(ctx, float64(duration.Milliseconds()))
	}()

	l.Trace("Starting single-file compilation pipeline...")

	projectResult, err := s.runSingleFileAnnotation(ctx, request)
	if err != nil {
		generateErrorCount.Add(ctx, 1)
		return nil, fmt.Errorf("running single-file annotation for %q: %w", request.SourcePath, err)
	}

	targetResult, mainComponent, err := s.resolveTargetComponent(ctx, request, projectResult)
	if err != nil {
		generateErrorCount.Add(ctx, 1)
		return nil, fmt.Errorf("resolving target component for %q: %w", request.SourcePath, err)
	}

	genCtx := &singleFileGenerationContext{
		request:       request,
		targetResult:  targetResult,
		mainComponent: mainComponent,
		projectResult: projectResult,
	}
	artefact, err := s.generateAndFinaliseArtefact(ctx, genCtx)
	if err != nil {
		generateErrorCount.Add(ctx, 1)
		return nil, fmt.Errorf("generating artefact for %q: %w", request.SourcePath, err)
	}

	l.Trace("Single-file compilation pipeline finished successfully.")
	return artefact, nil
}

// Resolver returns the path resolver for this service.
//
// Returns resolver_domain.ResolverPort which is the path resolver instance.
func (s *generatorService) Resolver() resolver_domain.ResolverPort {
	return s.resolver
}

// GenerateProject orchestrates the full compilation pipeline for an entire
// project. It annotates all entry points and their dependencies, generates Go
// code for every discovered component (pages and partials), and finally
// produces a project manifest and a registration file.
//
// Actions are auto-discovered from the actions/ directory during annotation.
//
// Takes entryPoints ([]annotator_dto.EntryPoint) which lists the pages
// and layouts to compile.
//
// Returns artefacts ([]*generator_dto.GeneratedArtefact) which contains
// the generated Go source files.
// Returns manifest (*generator_dto.Manifest) which describes the
// project's pages, partials, and routes.
// Returns err (error) when any phase of the pipeline fails.
func (s *generatorService) GenerateProject(
	ctx context.Context,
	entryPoints []annotator_dto.EntryPoint,
) (artefacts []*generator_dto.GeneratedArtefact, manifest *generator_dto.Manifest, err error) {
	ctx, span, _ := log.Span(ctx, "GeneratorService.GenerateProject")
	defer span.End()

	generateProjectCount.Add(ctx, 1)
	startTime := time.Now()
	defer func() {
		generateProjectDuration.Record(ctx, float64(time.Since(startTime).Milliseconds()))
		if err != nil {
			generateProjectErrorCount.Add(ctx, 1)
		}
	}()

	projectResult, err := s.runAnnotationPhase(ctx, entryPoints)
	if err != nil {
		return nil, nil, fmt.Errorf("running annotation phase: %w", err)
	}

	return s.EmitProject(ctx, projectResult)
}

// EmitProject runs the post-annotation emission pipeline: static collections,
// search indexes, i18n, actions, parallel code generation, manifest building,
// and SEO artefacts. It takes a pre-computed annotation result so the caller
// can run annotation once and fan out emission and asset building in parallel.
//
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which contains
// the annotated project data from AnnotateProject.
//
// Returns []*generator_dto.GeneratedArtefact which contains all generated Go
// source files.
// Returns *generator_dto.Manifest which describes the project's pages,
// partials, and routes.
// Returns error when any emission step fails.
func (s *generatorService) EmitProject(
	ctx context.Context,
	projectResult *annotator_dto.ProjectAnnotationResult,
) ([]*generator_dto.GeneratedArtefact, *generator_dto.Manifest, error) {
	ctx, span, l := log.Span(ctx, "GeneratorService.EmitProject")
	defer span.End()

	if len(projectResult.ComponentResults) == 0 {
		l.Internal("No components found in the project, nothing to generate.")
		return []*generator_dto.GeneratedArtefact{}, &generator_dto.Manifest{}, nil
	}

	collectionPackagePaths, collectionItems, err := s.generateStaticCollections(ctx, projectResult)
	if err != nil {
		return nil, nil, fmt.Errorf("generating static collections: %w", err)
	}

	if err := s.generateSearchIndexes(ctx, collectionItems); err != nil {
		return nil, nil, fmt.Errorf("generating search indexes: %w", err)
	}

	if err := s.generateI18nFlatBuffer(ctx); err != nil {
		return nil, nil, fmt.Errorf("generating i18n FlatBuffer: %w", err)
	}

	actionsPackagePath, err := s.generateActionFiles(ctx, projectResult)
	if err != nil {
		return nil, nil, fmt.Errorf("generating action files: %w", err)
	}

	artefactMap, err := s.generateComponentsInParallel(ctx, projectResult)
	if err != nil {
		return nil, nil, fmt.Errorf("generating components in parallel: %w", err)
	}

	allArtefacts, allPackagePaths, err := s.aggregateArtefactsAndDiagnostics(ctx, artefactMap, projectResult)
	if err != nil {
		return nil, nil, fmt.Errorf("aggregating artefacts and diagnostics: %w", err)
	}

	return s.finaliseProjectGeneration(ctx, projectResult, allArtefacts, allPackagePaths, collectionPackagePaths, actionsPackagePath)
}

// AnnotateProject runs only the annotation phase of the compilation pipeline,
// returning the project analysis result without generating any code. This is
// used by assets-only builds where the FinalAssetManifest is needed but code
// emission and formatting are not.
//
// Takes entryPoints ([]annotator_dto.EntryPoint) which contains the source
// files to analyse.
//
// Returns *annotator_dto.ProjectAnnotationResult which contains the
// FinalAssetManifest and all component metadata.
// Returns error when annotation fails.
func (s *generatorService) AnnotateProject(
	ctx context.Context,
	entryPoints []annotator_dto.EntryPoint,
) (*annotator_dto.ProjectAnnotationResult, error) {
	return s.runAnnotationPhase(ctx, entryPoints)
}

// finaliseProjectGeneration completes project generation by building the
// manifest and running cleanup tasks.
//
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which contains
// the annotated project data.
// Takes allArtefacts ([]*generator_dto.GeneratedArtefact) which holds the
// generated artefacts to include in the manifest.
// Takes allPackagePaths ([]string) which lists the package paths to register.
// Takes collectionPackagePaths ([]string) which lists additional collection
// package paths to append.
// Takes actionsPackagePath (string) which specifies the actions package path, or
// empty if none.
//
// Returns []*generator_dto.GeneratedArtefact which contains all registered
// artefacts.
// Returns *generator_dto.Manifest which is the built project manifest.
// Returns error when manifest building fails.
func (s *generatorService) finaliseProjectGeneration(
	ctx context.Context,
	projectResult *annotator_dto.ProjectAnnotationResult,
	allArtefacts []*generator_dto.GeneratedArtefact,
	allPackagePaths, collectionPackagePaths []string,
	actionsPackagePath string,
) ([]*generator_dto.GeneratedArtefact, *generator_dto.Manifest, error) {
	ctx, l := logger_domain.From(ctx, log)
	allPackagePaths = append(allPackagePaths, collectionPackagePaths...)
	if actionsPackagePath != "" {
		allPackagePaths = append(allPackagePaths, actionsPackagePath)
	}

	manifest, allArtefacts, err := s.buildManifestAndRegister(ctx, allArtefacts, allPackagePaths)
	if err != nil {
		return nil, nil, fmt.Errorf("building manifest and register file: %w", err)
	}

	s.generateSEOArtefacts(ctx, projectResult)
	s.cleanOrphanedDirs(ctx, projectResult.VirtualModule)
	l.Internal("Project generation finished successfully.")
	return allArtefacts, manifest, nil
}

// runSingleFileAnnotation runs the annotation process for a single file.
//
// Takes request (generator_dto.GenerateRequest) which specifies the file to
// annotate.
//
// Returns *annotator_dto.ProjectAnnotationResult which contains the annotation
// output for the file.
// Returns error when the annotation process fails.
func (s *generatorService) runSingleFileAnnotation(
	ctx context.Context,
	request generator_dto.GenerateRequest,
) (*annotator_dto.ProjectAnnotationResult, error) {
	entryPoints := []annotator_dto.EntryPoint{{
		Path:              request.SourcePath,
		IsPage:            request.IsPage,
		IsPublic:          false,
		IsEmail:           false,
		VirtualPageSource: nil,
	}}
	return s.coordinator.GetResult(ctx, entryPoints, coordinator_domain.WithCausationID(generatorCausationID))
}

// resolveTargetComponent finds the target component from the annotation result.
//
// Takes request (generator_dto.GenerateRequest) which specifies the source path to
// find.
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which contains
// the annotated project data.
//
// Returns *annotator_dto.AnnotationResult which is the annotation result for
// the target component.
// Returns *annotator_dto.VirtualComponent which is the main component at the
// entry point.
// Returns error when the path cannot be found, the entry point is not in the
// graph, or compilation failed with errors.
func (s *generatorService) resolveTargetComponent(
	ctx context.Context,
	request generator_dto.GenerateRequest,
	projectResult *annotator_dto.ProjectAnnotationResult,
) (*annotator_dto.AnnotationResult, *annotator_dto.VirtualComponent, error) {
	absoluteSourcePath, err := s.resolver.ResolvePKPath(ctx, request.SourcePath, "")
	if err != nil {
		return nil, nil, fmt.Errorf("could not resolve entry point path '%s': %w", request.SourcePath, err)
	}

	hashedName, ok := projectResult.VirtualModule.Graph.PathToHashedName[absoluteSourcePath]
	if !ok {
		return nil, nil, fmt.Errorf("internal error: no hash found for entry point %s", request.SourcePath)
	}

	targetResult, ok := projectResult.ComponentResults[hashedName]
	if !ok {
		if ast_domain.HasErrors(projectResult.AllDiagnostics) {
			formattedErrors := annotator_domain.FormatAllDiagnostics(projectResult.AllDiagnostics, projectResult.AllSourceContents)
			return nil, nil, fmt.Errorf("compilation failed with errors:\n%s", formattedErrors)
		}
		return nil, nil, fmt.Errorf("internal error: no annotation result found for entry point %s", request.SourcePath)
	}

	mainComponent := targetResult.VirtualModule.ComponentsByHash[hashedName]
	return targetResult, mainComponent, nil
}

// singleFileGenerationContext holds all the context needed for generating a
// single file.
type singleFileGenerationContext struct {
	// targetResult holds the annotation result for the file being processed.
	targetResult *annotator_dto.AnnotationResult

	// mainComponent is the component being documented in this file.
	mainComponent *annotator_dto.VirtualComponent

	// projectResult holds the project-wide annotation data, including all
	// diagnostics.
	projectResult *annotator_dto.ProjectAnnotationResult

	// request holds the parameters for the generation request.
	request generator_dto.GenerateRequest
}

// generateAndFinaliseArtefact creates the artefact and adds diagnostics to it.
//
// Takes genCtx (*singleFileGenerationContext) which holds the generation
// context, including the request and target.
//
// Returns *generator_dto.GeneratedArtefact which holds the created artefact
// with project-wide diagnostics added.
// Returns error when creation fails or the code has errors.
func (s *generatorService) generateAndFinaliseArtefact(ctx context.Context, genCtx *singleFileGenerationContext) (*generator_dto.GeneratedArtefact, error) {
	artefact, err := s.generateSingleArtefact(ctx, genCtx.request, genCtx.targetResult, genCtx.mainComponent)
	if err != nil {
		if semanticErr, ok := errors.AsType[*annotator_domain.SemanticError](err); ok {
			formattedErrors := annotator_domain.FormatAllDiagnostics(semanticErr.Diagnostics, genCtx.projectResult.AllSourceContents)
			return nil, fmt.Errorf("compilation failed with errors:\n%s", formattedErrors)
		}
		return nil, fmt.Errorf("generating single artefact: %w", err)
	}

	artefact.Result.AnnotatedAST.Diagnostics = genCtx.projectResult.AllDiagnostics
	return artefact, nil
}

// runAnnotationPhase runs dependency analysis and annotation for all parts.
//
// Actions are found from the actions/ folder during annotation.
//
// Takes entryPoints ([]annotator_dto.EntryPoint) which specifies the packages
// to analyse.
//
// Returns *annotator_dto.ProjectAnnotationResult which contains the full
// annotation results for all entry points.
// Returns error when compilation fails or a fatal error occurs during analysis.
func (s *generatorService) runAnnotationPhase(
	ctx context.Context,
	entryPoints []annotator_dto.EntryPoint,
) (*annotator_dto.ProjectAnnotationResult, error) {
	ctx, l := logger_domain.From(ctx, log)
	l.Internal("Running annotation phase for all entry points...")
	projectResult, err := s.coordinator.GetResult(
		ctx,
		entryPoints,
		coordinator_domain.WithCausationID(generatorCausationID),
	)
	if err != nil {
		if semanticErr, ok := errors.AsType[*annotator_domain.SemanticError](err); ok && projectResult != nil {
			formattedErrors := annotator_domain.FormatAllDiagnostics(semanticErr.Diagnostics, projectResult.AllSourceContents)
			return nil, fmt.Errorf("compilation failed during analysis:\n%s", formattedErrors)
		}
		return nil, fmt.Errorf("build failed with a fatal error during analysis: %w", err)
	}
	l.Internal("Annotation phase successful.")
	return projectResult, nil
}

// generateStaticCollections creates binary collection files for all static
// collections.
//
// This method gets collection data from the VirtualModule (created during
// annotation), groups items by collection, and writes binary files to
// dist/collections/{collectionName}/.
//
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which contains
// the virtual module with collection data.
//
// Returns []string which contains Go package paths for the generated
// collection packages.
// Returns map[string][]collection_dto.ContentItem which maps collection names
// to their items for search index generation.
// Returns error when any collection fails to generate.
func (s *generatorService) generateStaticCollections(
	ctx context.Context,
	projectResult *annotator_dto.ProjectAnnotationResult,
) ([]string, map[string][]collection_dto.ContentItem, error) {
	ctx, l := logger_domain.From(ctx, log)
	if s.collectionEmitter == nil {
		l.Internal("No collection emitter configured, skipping collection generation.")
		return nil, nil, nil
	}

	l.Internal("Starting static collection generation...")

	collectionItems := extractCollectionItemsFromModule(projectResult.VirtualModule)
	if len(collectionItems) == 0 {
		l.Internal("No static collections found in virtual module.")
		return nil, nil, nil
	}

	l.Internal("Found static collections to generate", logger_domain.Int("collection_count", len(collectionItems)))

	packagePaths, err := s.emitCollections(ctx, collectionItems)
	if err != nil {
		return nil, nil, fmt.Errorf("emitting static collections: %w", err)
	}

	l.Internal("Static collection generation complete", logger_domain.Int("collections_generated", len(packagePaths)))
	return packagePaths, collectionItems, nil
}

// emitCollections builds binary output for all collection items.
//
// Takes collectionItems (map[string][]collection_dto.ContentItem) which maps
// collection names to their content items.
//
// Returns []string which contains the package paths for each generated
// collection.
// Returns error when a collection fails to build.
func (s *generatorService) emitCollections(
	ctx context.Context,
	collectionItems map[string][]collection_dto.ContentItem,
) ([]string, error) {
	ctx, l := logger_domain.From(ctx, log)
	packagePaths := make([]string, 0, len(collectionItems))
	outputDir := filepath.Join(s.baseDir, distDir)

	for collectionName, items := range collectionItems {
		if ctx.Err() != nil {
			return nil, ctx.Err()
		}

		l.Trace("Generating collection",
			logger_domain.String(logKeyCollection, collectionName),
			logger_domain.Int("item_count", len(items)))

		packagePath, err := s.collectionEmitter.EmitCollection(ctx, collectionName, items, outputDir)
		if err != nil {
			return nil, fmt.Errorf("failed to generate collection %q: %w", collectionName, err)
		}

		packagePaths = append(packagePaths, packagePath)
		l.Trace("Collection generated successfully",
			logger_domain.String(logKeyCollection, collectionName),
			logger_domain.String("package_path", packagePath))
	}

	return packagePaths, nil
}

// generateSearchIndexes generates search index binaries for all static
// collections.
//
// This method builds inverted indexes for Fast and Smart modes, enabling
// zero-copy full-text search with BM25 ranking at runtime.
//
// Takes collectionItems (map[string][]collection_dto.ContentItem) which maps
// collection names to their content items.
//
// Returns error when any index fails to generate.
func (s *generatorService) generateSearchIndexes(
	ctx context.Context,
	collectionItems map[string][]collection_dto.ContentItem,
) error {
	ctx, l := logger_domain.From(ctx, log)
	if s.searchIndexEmitter == nil {
		l.Internal("No search index emitter configured, skipping search index generation.")
		return nil
	}

	if len(collectionItems) == 0 {
		l.Internal("No collections to index for search.")
		return nil
	}

	l.Internal("Starting search index generation...", logger_domain.Int("collection_count", len(collectionItems)))

	outputDir := filepath.Join(s.baseDir, distDir)

	for collectionName, items := range collectionItems {
		if ctx.Err() != nil {
			return ctx.Err()
		}

		l.Trace("Generating search indexes for collection",
			logger_domain.String(logKeyCollection, collectionName),
			logger_domain.Int("item_count", len(items)))

		modes := []string{"fast", "smart"}

		err := s.searchIndexEmitter.EmitSearchIndex(ctx, collectionName, items, outputDir, modes)
		if err != nil {
			return fmt.Errorf("failed to generate search indexes for collection %q: %w", collectionName, err)
		}

		l.Trace("Search indexes generated successfully",
			logger_domain.String(logKeyCollection, collectionName),
			logger_domain.Strings("modes", modes))
	}

	l.Internal("Search index generation complete", logger_domain.Int("collections_indexed", len(collectionItems)))
	return nil
}

// generateI18nFlatBuffer creates the i18n FlatBuffer binary file if an emitter
// is set up.
//
// Returns error when the FlatBuffer creation fails.
func (s *generatorService) generateI18nFlatBuffer(
	ctx context.Context,
) error {
	ctx, l := logger_domain.From(ctx, log)
	if s.i18nEmitter == nil {
		l.Internal("No i18n emitter configured, skipping i18n FlatBuffer generation.")
		return nil
	}

	l.Internal("Starting i18n FlatBuffer generation...")

	outputPath := filepath.Join(s.baseDir, distDir, "i18n.bin")

	if err := s.i18nEmitter.EmitI18n(ctx, outputPath); err != nil {
		return fmt.Errorf("failed to generate i18n FlatBuffer: %w", err)
	}

	l.Internal("i18n FlatBuffer generation complete", logger_domain.String("output_path", outputPath))
	return nil
}

// generateActionFiles generates action code files from the discovered
// ActionManifest if an action generator is configured.
//
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which contains
// the discovered action manifest and virtual module data.
//
// Returns string which is the package path of the generated actions package,
// or empty if no generator is configured.
// Returns error when action code generation fails.
func (s *generatorService) generateActionFiles(
	ctx context.Context,
	projectResult *annotator_dto.ProjectAnnotationResult,
) (string, error) {
	ctx, l := logger_domain.From(ctx, log)
	if s.actionGenerator == nil {
		l.Internal("No action generator configured, skipping action file generation.")
		return "", nil
	}

	manifest := projectResult.VirtualModule.ActionManifest
	outputDir := s.baseDir
	actionsGenTSPath := filepath.Join(outputDir, "dist", "ts", "actions.gen.ts")

	actionsPackagePath, err := s.generateActionSource(ctx, manifest, outputDir, actionsGenTSPath)
	if err != nil {
		return "", fmt.Errorf("generating action source: %w", err)
	}

	if err := s.emitActionsJS(ctx, actionsGenTSPath, outputDir); err != nil {
		return "", fmt.Errorf("emitting actions JavaScript: %w", err)
	}

	actionCount := 0
	if manifest != nil {
		actionCount = len(manifest.Actions)
	}
	l.Internal("Action file generation complete",
		logger_domain.Int("action_count", actionCount),
		logger_domain.String("package_path", actionsPackagePath))
	return actionsPackagePath, nil
}

// generateActionSource generates the TypeScript action source file.
//
// Takes manifest (*annotator_dto.ActionManifest) which contains the discovered
// actions to generate.
// Takes outputDir (string) which specifies the output directory path.
// Takes actionsGenTSPath (string) which specifies the path for the generated
// TypeScript file.
//
// Returns string which is the module path for the generated actions, or empty
// if no actions were found.
// Returns error when directory creation or file writing fails.
func (s *generatorService) generateActionSource(
	ctx context.Context,
	manifest *annotator_dto.ActionManifest,
	outputDir, actionsGenTSPath string,
) (string, error) {
	ctx, l := logger_domain.From(ctx, log)
	if manifest == nil || len(manifest.Actions) == 0 {
		l.Internal("No actions discovered, generating empty actions stub for components.")
		if s.baseSandbox != nil {
			relPath, _ := filepath.Rel(s.baseDir, actionsGenTSPath)
			if err := s.baseSandbox.MkdirAll(filepath.Dir(relPath), PublicDirPermission); err != nil {
				return "", fmt.Errorf("creating pk directory: %w", err)
			}
			if err := s.baseSandbox.WriteFile(relPath, []byte(emptyActionsStub), PublicFilePermission); err != nil {
				return "", fmt.Errorf("writing empty actions stub: %w", err)
			}
		}
		return "", nil
	}

	l.Internal("Starting action file generation...",
		logger_domain.Int("action_count", len(manifest.Actions)))

	moduleName := s.resolver.GetModuleName()
	if err := s.actionGenerator.GenerateActions(ctx, manifest, moduleName, outputDir); err != nil {
		return "", fmt.Errorf("failed to generate action files: %w", err)
	}
	return paths.Join(moduleName, distDir, "actions"), nil
}

// emitActionsJS transpiles the TypeScript actions file to JavaScript.
//
// Takes actionsGenTSPath (string) which is the path to the TypeScript file.
// Takes outputDir (string) which is the directory for the emitted JavaScript.
//
// Returns error when the JavaScript emission fails.
func (s *generatorService) emitActionsJS(
	ctx context.Context,
	actionsGenTSPath, outputDir string,
) error {
	ctx, l := logger_domain.From(ctx, log)
	if s.baseSandbox == nil {
		return nil
	}
	relPath, _ := filepath.Rel(s.baseDir, actionsGenTSPath)
	tsSource, err := s.baseSandbox.ReadFile(relPath)
	if err != nil || len(tsSource) == 0 {
		return nil
	}

	if _, err := s.pkJSEmitter.EmitJS(ctx, string(tsSource), "pk/actions.gen", s.resolver.GetModuleName(), outputDir, false); err != nil {
		return fmt.Errorf("failed to emit actions JavaScript: %w", err)
	}
	l.Internal("Emitted actions JavaScript for browser consumption")
	return nil
}

// workerContext holds all the shared state needed by worker goroutines during
// parallel generation.
type workerContext struct {
	// projectResult holds the pre-computed annotation results for the project.
	projectResult *annotator_dto.ProjectAnnotationResult

	// artefactMap stores generated artefacts or errors, keyed by source path.
	artefactMap *syncmap.Map
}

// generateComponentsInParallel sets up a worker pool to generate Go code for
// all components at the same time.
//
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which provides
// the annotated project with all components to generate.
//
// Returns *syncmap.Map which contains the generated results keyed by
// component hash.
// Returns error when any worker fails during code generation.
func (s *generatorService) generateComponentsInParallel(
	ctx context.Context,
	projectResult *annotator_dto.ProjectAnnotationResult,
) (*syncmap.Map, error) {
	ctx, l := logger_domain.From(ctx, log)

	virtualModule := projectResult.VirtualModule
	allComponentsToGenerate := virtualModule.ComponentsByHash

	l.Internal("Starting project generation pipeline...", logger_domain.Int("component_count", len(allComponentsToGenerate)))

	var artefactMap syncmap.Map
	g, gCtx := errgroup.WithContext(ctx)
	jobs := make(chan *annotator_dto.VirtualComponent, len(allComponentsToGenerate))

	wctx := &workerContext{
		projectResult: projectResult,
		artefactMap:   &artefactMap,
	}

	numWorkers := calculateWorkerCount(len(allComponentsToGenerate))
	for range numWorkers {
		g.Go(func() error {
			return s.processComponentWorker(gCtx, jobs, wctx)
		})
	}

	for _, vc := range allComponentsToGenerate {
		jobs <- vc
	}
	close(jobs)

	if err := g.Wait(); err != nil {
		return nil, fmt.Errorf("processing components in parallel: %w", err)
	}

	return &artefactMap, nil
}

// processComponentWorker reads components from the jobs channel and generates
// code for each one.
//
// Takes jobs (<-chan *annotator_dto.VirtualComponent) which provides
// components to process.
// Takes wctx (*workerContext) which holds shared state for the worker.
//
// Returns error when processing fails.
func (s *generatorService) processComponentWorker(
	ctx context.Context,
	jobs <-chan *annotator_dto.VirtualComponent,
	wctx *workerContext,
) error {
	ctx, l := logger_domain.From(ctx, log)

	for vc := range jobs {
		if ctx.Err() != nil {
			break
		}

		l.Trace("Worker processing component...", logger_domain.String("sourcePath", vc.Source.SourcePath))

		annotationResult, ok := wctx.projectResult.ComponentResults[vc.HashedName]
		if !ok {
			err := fmt.Errorf("internal consistency error: no annotation result found for component hash %s", vc.HashedName)
			wctx.artefactMap.Store(vc.Source.SourcePath, err)
			continue
		}

		request := generator_dto.GenerateRequest{
			SourcePath:                vc.Source.SourcePath,
			OutputPath:                vc.VirtualGoFilePath,
			PackageName:               vc.HashedName,
			BaseDir:                   s.baseDir,
			IsPage:                    vc.IsPage,
			HashedName:                vc.HashedName,
			PackagePrefix:             "",
			CanonicalGoPackagePath:    vc.CanonicalGoPackagePath,
			VirtualInstances:          convertVirtualInstances(vc.VirtualInstances),
			CollectionName:            vc.Source.CollectionName,
			VerifyGeneratedCode:       config.CompilerVerifyGeneratedCode,
			ModuleName:                s.resolver.GetModuleName(),
			IsEmail:                   vc.IsEmail,
			IsPdf:                     vc.IsPdf,
			EnablePrerendering:        s.enablePrerendering && !vc.IsEmail && !vc.IsPdf,
			EnableStaticHoisting:      config.CompilerEnableStaticHoisting,
			StripHTMLComments:         s.stripHTMLComments,
			EnableDwarfLineDirectives: s.enableDwarfLineDirectives,
		}

		artefact, err := s.generateSingleArtefact(ctx, request, annotationResult, vc)
		if err != nil {
			wctx.artefactMap.Store(request.SourcePath, err)
		} else {
			wctx.artefactMap.Store(request.SourcePath, artefact)
		}
	}
	return nil
}

// aggregateArtefactsAndDiagnostics collects all artefacts and diagnostics from
// the artefact map.
//
// Takes artefactMap (*syncmap.Map) which contains the generated artefacts or
// errors, keyed by source path.
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which provides
// the project-level diagnostics.
//
// Returns []*generator_dto.GeneratedArtefact which contains the collected
// artefacts.
// Returns []string which contains the canonical package paths of all
// components.
// Returns error when the diagnostics contain errors.
func (s *generatorService) aggregateArtefactsAndDiagnostics(
	ctx context.Context,
	artefactMap *syncmap.Map,
	projectResult *annotator_dto.ProjectAnnotationResult,
) ([]*generator_dto.GeneratedArtefact, []string, error) {
	ctx, l := logger_domain.From(ctx, log)
	var allArtefacts []*generator_dto.GeneratedArtefact
	var allDiagnostics []*ast_domain.Diagnostic
	var allPackagePaths []string

	allDiagnostics = append(allDiagnostics, projectResult.AllDiagnostics...)

	artefactMap.Range(func(key, value any) bool {
		sourcePath, ok := key.(string)
		if !ok {
			diagnostic := ast_domain.NewDiagnostic(ast_domain.Error, "Internal error: artefact map key is not a string", "", ast_domain.Location{}, "")
			allDiagnostics = append(allDiagnostics, diagnostic)
			return true
		}
		if err, isErr := value.(error); isErr {
			if semanticErr, ok := errors.AsType[*annotator_domain.SemanticError](err); ok {
				allDiagnostics = append(allDiagnostics, semanticErr.Diagnostics...)
			} else {
				diagnostic := ast_domain.NewDiagnostic(ast_domain.Error, "An unknown fatal error occurred during generation: "+err.Error(), "", ast_domain.Location{}, sourcePath)
				allDiagnostics = append(allDiagnostics, diagnostic)
			}
		} else if artefact, ok := value.(*generator_dto.GeneratedArtefact); ok {
			allArtefacts = append(allArtefacts, artefact)
			if artefact.Component != nil {
				allPackagePaths = append(allPackagePaths, artefact.Component.CanonicalGoPackagePath)
			}
		}
		return true
	})

	if ast_domain.HasErrors(allDiagnostics) {
		formattedErrors := annotator_domain.FormatAllDiagnostics(allDiagnostics, projectResult.AllSourceContents)
		l.Error("Project generation failed with errors.", logger_domain.Int("diagnostic_count", len(allDiagnostics)))
		_, _ = s.manifestBuilder.Build(allArtefacts)
		return nil, nil, fmt.Errorf("project generation failed:\n%s", formattedErrors)
	}

	return allArtefacts, allPackagePaths, nil
}

// buildManifestAndRegister builds the project manifest and adds the register
// file as an artefact.
//
// Takes allArtefacts ([]*generator_dto.GeneratedArtefact) which contains the
// generated artefacts to include in the manifest.
// Takes allPackagePaths ([]string) which lists the package paths for the
// register file.
//
// Returns *generator_dto.Manifest which contains the built project manifest.
// Returns []*generator_dto.GeneratedArtefact which includes the original
// artefacts plus the generated register file.
// Returns error when the manifest cannot be built or register file generation
// fails.
func (s *generatorService) buildManifestAndRegister(
	ctx context.Context,
	allArtefacts []*generator_dto.GeneratedArtefact,
	allPackagePaths []string,
) (*generator_dto.Manifest, []*generator_dto.GeneratedArtefact, error) {
	ctx, l := logger_domain.From(ctx, log)
	manifest, err := s.manifestBuilder.Build(allArtefacts)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to build manifest: %w", err)
	}

	registerContent, err := s.registerEmitter.Generate(ctx, allPackagePaths)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate register aggregator file: %w", err)
	}

	registerPath := paths.Join(s.baseDir, distDir, "piko_register.go")
	registerArtefact := &generator_dto.GeneratedArtefact{
		Content:       registerContent,
		SuggestedPath: registerPath,
		Result:        nil,
		Component:     nil,
		JSArtefactID:  "",
	}
	allArtefacts = append(allArtefacts, registerArtefact)
	l.Internal("Register aggregator file generated.")

	return manifest, allArtefacts, nil
}

// generateSEOArtefacts creates SEO files such as sitemap.xml and robots.txt
// if an SEO service is set.
//
// Takes projectResult (*annotator_dto.ProjectAnnotationResult) which provides
// the project data used for SEO file creation.
func (s *generatorService) generateSEOArtefacts(
	ctx context.Context,
	projectResult *annotator_dto.ProjectAnnotationResult,
) {
	ctx, l := logger_domain.From(ctx, log)
	if s.seoService == nil {
		return
	}

	l.Internal("Generating SEO artefacts (sitemap.xml, robots.txt)...")
	translator := seo_adapters.NewProjectViewTranslator()
	projectView := translator.Translate(projectResult)
	if err := s.seoService.GenerateArtefacts(ctx, projectView); err != nil {
		l.Warn("Failed to generate SEO artefacts", logger_domain.Error(err))
	} else {
		l.Internal("SEO artefacts generated successfully.")
	}
}

// generateSingleArtefact contains the core logic for generating one Go file
// from a component. It orchestrates the code emitter and packages the output
// into a self-contained GeneratedArtefact.
//
// Takes request (generator_dto.GenerateRequest) which specifies the generation
// settings and source path.
// Takes annotationResult (*annotator_dto.AnnotationResult) which provides the
// parsed annotations from the source file.
// Takes vc (*annotator_dto.VirtualComponent) which defines the component to
// generate code for.
//
// Returns *generator_dto.GeneratedArtefact which contains the generated code
// and metadata.
// Returns error when code emission fails or produces diagnostics.
func (s *generatorService) generateSingleArtefact(
	ctx context.Context,
	request generator_dto.GenerateRequest,
	annotationResult *annotator_dto.AnnotationResult,
	vc *annotator_dto.VirtualComponent,
) (*generator_dto.GeneratedArtefact, error) {
	codeEmitter := s.codeEmitterFactory.NewEmitter()
	request.CanonicalGoPackagePath = vc.CanonicalGoPackagePath

	emittedCode, emitDiags, err := codeEmitter.EmitCode(ctx, annotationResult, request)
	if err != nil {
		return nil, fmt.Errorf("fatal error emitting code for %s: %w", request.SourcePath, err)
	}
	if len(emitDiags) > 0 {
		return nil, annotator_domain.NewSemanticError(emitDiags)
	}

	logCodeEmissionDebug(ctx, request.SourcePath, emittedCode)

	jsPath := s.emitClientSideJS(ctx, request, annotationResult)

	return &generator_dto.GeneratedArtefact{
		Content:       emittedCode,
		SuggestedPath: request.OutputPath,
		Result:        annotationResult,
		Component:     vc,
		JSArtefactID:  jsPath,
	}, nil
}

// emitClientSideJS emits client-side JavaScript if configured and present.
//
// Takes request (generator_dto.GenerateRequest) which specifies the source path
// and base directory for the page.
// Takes annotationResult (*annotator_dto.AnnotationResult) which contains the
// client script to emit.
//
// Returns string which is the path to the emitted JS file, or empty string if
// not emitted.
func (s *generatorService) emitClientSideJS(
	ctx context.Context,
	request generator_dto.GenerateRequest,
	annotationResult *annotator_dto.AnnotationResult,
) string {
	if s.pkJSEmitter == nil || annotationResult.ClientScript == "" {
		return ""
	}

	ctx, l := logger_domain.From(ctx, log)
	pagePath := derivePagePath(request.SourcePath, request.BaseDir)
	outputDir := filepath.Join(s.baseDir, distDir)

	jsPath, err := s.pkJSEmitter.EmitJS(ctx, annotationResult.ClientScript, pagePath, request.ModuleName, outputDir, false)
	if err != nil {
		l.Warn("Failed to emit client-side JS, continuing without it",
			logger_domain.String("source", request.SourcePath),
			logger_domain.Error(err))
		return ""
	}

	l.Trace("Emitted client-side JS",
		logger_domain.String("source", request.SourcePath),
		logger_domain.String("jsPath", jsPath))
	return jsPath
}

// cleanOrphanedDirs removes generated directories that no longer have
// matching source files. It scans the pages, partials, and emails output
// directories and removes any subdirectories that are not present in the
// current VirtualModule's ComponentsByHash map.
//
// Takes virtualModule (*annotator_dto.VirtualModule) which contains the current
// set of valid components.
func (s *generatorService) cleanOrphanedDirs(
	ctx context.Context,
	virtualModule *annotator_dto.VirtualModule,
) {
	validHashes := make(map[string]bool)
	for hashedName := range virtualModule.ComponentsByHash {
		validHashes[hashedName] = true
	}

	targetDirs := []string{
		config.CompiledPagesTargetDir,
		config.CompiledPartialsTargetDir,
		config.CompiledEmailsTargetDir,
	}

	for _, targetDir := range targetDirs {
		if targetDir == "" {
			continue
		}
		s.cleanOrphanedInDir(ctx, targetDir, validHashes)
	}
}

// cleanOrphanedInDir removes orphaned subdirectories from a single target
// directory.
//
// Takes directory (string) which is the directory to scan for orphaned
// subdirectories.
// Takes validHashes (map[string]bool) which is the set of valid component
// hashes.
func (s *generatorService) cleanOrphanedInDir(
	ctx context.Context,
	directory string,
	validHashes map[string]bool,
) {
	ctx, l := logger_domain.From(ctx, log)
	entries, err := s.fsWriter.ReadDir(directory)
	if err != nil {
		return
	}

	for _, entry := range entries {
		if ctx.Err() != nil {
			return
		}

		if !entry.IsDir() {
			continue
		}
		dirName := entry.Name()
		if !validHashes[dirName] {
			fullPath := filepath.Join(directory, dirName)
			l.Internal("Removing orphaned generated directory", logger_domain.String("path", fullPath))
			if err := s.fsWriter.RemoveAll(fullPath); err != nil {
				l.Warn("Failed to remove orphaned directory",
					logger_domain.String("path", fullPath),
					logger_domain.Error(err))
			}
		}
	}
}

// WithInMemoryMode configures the generator for in-memory operation. This skips
// filesystem operations like creating the dist directory, making it suitable
// for WASM or testing contexts.
//
// Returns GeneratorServiceOption which configures the service for in-memory
// use.
func WithInMemoryMode() GeneratorServiceOption {
	return func(o *generatorServiceOptions) {
		o.inMemoryMode = true
	}
}

// WithDistSandbox sets a custom sandbox for dist directory operations. This
// allows mock sandboxes to be used for testing filesystem operations.
//
// If not provided, a real sandbox is created from the base directory.
//
// Takes sandbox (safedisk.Sandbox) which provides filesystem access for dist
// directory operations.
//
// Returns GeneratorServiceOption which configures the service with the given
// sandbox.
func WithDistSandbox(sandbox safedisk.Sandbox) GeneratorServiceOption {
	return func(o *generatorServiceOptions) {
		o.distSandbox = sandbox
	}
}

// WithPrerendering enables static HTML prerendering at generation time,
// rendering fully-static template subtrees to HTML bytes during code
// generation to avoid AST traversal at runtime.
//
// Email templates are never prerendered regardless of this setting.
//
// Takes enabled (bool) which activates prerendering when true.
//
// Returns GeneratorServiceOption which enables prerendering.
func WithPrerendering(enabled bool) GeneratorServiceOption {
	return func(o *generatorServiceOptions) {
		o.enablePrerendering = enabled
	}
}

// WithStripHTMLComments enables removal of HTML comments
// (<!-- ... -->) from both prerendered and runtime-rendered output.
//
// Takes enabled (bool) which activates comment stripping when true.
//
// Returns GeneratorServiceOption which enables comment stripping.
func WithStripHTMLComments(enabled bool) GeneratorServiceOption {
	return func(o *generatorServiceOptions) {
		o.stripHTMLComments = enabled
	}
}

// WithDwarfLineDirectives enables valid DWARF //line directives in
// generated Go code.
//
// When enabled, debuggers like Delve can set breakpoints on .pk
// source files. When disabled (default), the directives are emitted
// as plain comments with no DWARF effect.
//
// Takes enabled (bool) which activates DWARF line directives when
// true.
//
// Returns GeneratorServiceOption which enables DWARF line directives.
func WithDwarfLineDirectives(enabled bool) GeneratorServiceOption {
	return func(o *generatorServiceOptions) {
		o.enableDwarfLineDirectives = enabled
	}
}

// NewGeneratorService creates a new, fully configured generator
// service.
//
// It takes all its dependencies as interfaces, adhering to the
// Hexagonal architecture.
//
// Takes ctx (context.Context) which provides the context for
// construction-time operations.
// Takes pathsConfig (GeneratorPathsConfig) which provides path settings.
// Takes i18nDefaultLocale (string) which is the default locale for i18n.
// Takes ports (GeneratorPorts) which provides the required service adapters.
// Takes opts (...GeneratorServiceOption) which provides optional configuration.
//
// Returns GeneratorService which is the configured service ready for use.
// Returns error when the distribution package cannot be created.
func NewGeneratorService(ctx context.Context, pathsConfig GeneratorPathsConfig, i18nDefaultLocale string, ports GeneratorPorts, opts ...GeneratorServiceOption) (GeneratorService, error) {
	options := &generatorServiceOptions{}
	for _, opt := range opts {
		opt(options)
	}

	if !options.inMemoryMode {
		if err := ensureDistPackageExists(ctx, pathsConfig.BaseDir, options.distSandbox, ports.SandboxFactory); err != nil {
			return nil, fmt.Errorf("ensuring dist package exists: %w", err)
		}
	}

	baseSandbox := ports.BaseSandbox
	if baseSandbox == nil && !options.inMemoryMode {
		var err error
		if ports.SandboxFactory != nil {
			baseSandbox, err = ports.SandboxFactory.Create("generator base dir", pathsConfig.BaseDir, safedisk.ModeReadWrite)
		} else {
			baseSandbox, err = safedisk.NewNoOpSandbox(pathsConfig.BaseDir, safedisk.ModeReadWrite)
		}
		if err != nil {
			return nil, fmt.Errorf("failed to create base sandbox for '%s': %w", pathsConfig.BaseDir, err)
		}
	}

	return &generatorService{
		baseDir:                   pathsConfig.BaseDir,
		fsWriter:                  ports.FSWriter,
		manifestEmitter:           ports.ManifestEmitter,
		coordinator:               ports.Coordinator,
		resolver:                  ports.Resolver,
		manifestBuilder:           NewManifestBuilder(pathsConfig, i18nDefaultLocale, ports.Resolver.GetBaseDir(), WithConfigSandbox(baseSandbox)),
		registerEmitter:           ports.RegisterEmitter,
		codeEmitterFactory:        ports.CodeEmitterFactory,
		collectionEmitter:         ports.CollectionEmitter,
		searchIndexEmitter:        ports.SearchIndexEmitter,
		pkJSEmitter:               ports.PKJSEmitter,
		i18nEmitter:               ports.I18nEmitter,
		actionGenerator:           ports.ActionGenerator,
		seoService:                ports.SEOService,
		baseSandbox:               baseSandbox,
		enablePrerendering:        options.enablePrerendering,
		stripHTMLComments:         options.stripHTMLComments,
		enableDwarfLineDirectives: options.enableDwarfLineDirectives,
	}, nil
}

// GetMainComponent finds the main virtual component for an annotation result.
//
// Takes result (*annotator_dto.AnnotationResult) which provides the annotated
// AST and virtual module data to search.
//
// Returns *annotator_dto.VirtualComponent which is the main component found.
// Returns error when result is nil, missing required data, or when the
// component cannot be found due to internal data problems.
func GetMainComponent(result *annotator_dto.AnnotationResult) (*annotator_dto.VirtualComponent, error) {
	if result == nil || result.AnnotatedAST == nil || result.AnnotatedAST.SourcePath == nil {
		return nil, errors.New("internal error: annotation result is missing required data to find main component")
	}

	sourcePath := *result.AnnotatedAST.SourcePath
	hashedName, ok := result.VirtualModule.Graph.PathToHashedName[sourcePath]
	if !ok {
		return nil, fmt.Errorf("internal error: inconsistency, could not find hash for source path '%s'", sourcePath)
	}

	vc, ok := result.VirtualModule.ComponentsByHash[hashedName]
	if !ok {
		return nil, fmt.Errorf("internal error: inconsistency, could not find virtual component for hash '%s'", hashedName)
	}

	return vc, nil
}

// extractCollectionItemsFromModule groups virtual page instances by their
// collection name.
//
// Takes vm (*annotator_dto.VirtualModule) which contains the components and
// instances to process.
//
// Returns map[string][]collection_dto.ContentItem which maps each collection
// name to its content items.
func extractCollectionItemsFromModule(vm *annotator_dto.VirtualModule) map[string][]collection_dto.ContentItem {
	collectionItems := make(map[string][]collection_dto.ContentItem)

	for _, vc := range vm.ComponentsByHash {
		if !isCollectionTemplate(vc) {
			continue
		}
		for _, instance := range vc.VirtualInstances {
			if item, ok := convertVirtualInstanceToContentItem(instance); ok {
				collectionItems[vc.Source.CollectionName] = append(collectionItems[vc.Source.CollectionName], item)
			}
		}
	}

	return collectionItems
}

// isCollectionTemplate checks if a component is a collection template with
// instances.
//
// Takes vc (*annotator_dto.VirtualComponent) which is the component to check.
//
// Returns bool which is true when the component has a collection name and at
// least one virtual instance.
func isCollectionTemplate(vc *annotator_dto.VirtualComponent) bool {
	return vc.Source.HasCollection && vc.Source.CollectionName != "" && len(vc.VirtualInstances) > 0
}

// convertVirtualInstanceToContentItem converts a VirtualPageInstance to a
// ContentItem by extracting page data, content AST, excerpt AST, and raw
// content from the instance's InitialProps.
//
// Takes instance (annotator_dto.VirtualPageInstance) which is the virtual page
// to convert.
//
// Returns collection_dto.ContentItem which contains the converted content data.
// Returns bool which is false if the instance has no InitialProps.
func convertVirtualInstanceToContentItem(instance annotator_dto.VirtualPageInstance) (collection_dto.ContentItem, bool) {
	if instance.InitialProps == nil {
		return collection_dto.ContentItem{}, false
	}

	item := collection_dto.ContentItem{
		ID:             "",
		Slug:           "",
		Locale:         "",
		TranslationKey: "",
		Metadata:       make(map[string]any),
		RawContent:     "",
		ContentAST:     nil,
		ExcerptAST:     nil,
		URL:            instance.Route,
		ReadingTime:    0,
		CreatedAt:      "",
		UpdatedAt:      "",
		PublishedAt:    "",
	}

	if pageData, ok := instance.InitialProps["page"].(map[string]any); ok {
		item.Metadata = pageData
	}
	if contentAST, ok := instance.InitialProps["contentAST"].(*ast_domain.TemplateAST); ok {
		item.ContentAST = contentAST
	}
	if excerptAST, ok := instance.InitialProps["excerptAST"].(*ast_domain.TemplateAST); ok {
		item.ExcerptAST = excerptAST
	}
	if rawContent, ok := instance.InitialProps["rawContent"].(string); ok {
		item.RawContent = rawContent
	}

	return item, true
}

// calculateWorkerCount finds the best number of workers to use based on the
// CPU count and the number of components.
//
// Takes componentCount (int) which is the number of components to process.
//
// Returns int which is the worker count, always at least 1 but never more than
// the CPU count.
func calculateWorkerCount(componentCount int) int {
	return cmp.Or(min(runtime.NumCPU(), componentCount), 1)
}

// logCodeEmissionDebug logs debug details about generated code.
//
// Takes ctx (context.Context) which carries logging context.
// Takes sourcePath (string) which is the path to the source file.
// Takes code ([]byte) which is the generated code to log.
func logCodeEmissionDebug(ctx context.Context, sourcePath string, code []byte) {
	_, l := logger_domain.From(ctx, log)
	l.Trace("Code emission complete",
		logger_domain.String("source", sourcePath),
		logger_domain.Bool("has_init", strings.Contains(string(code), "func init()")),
		logger_domain.Bool("has_register", strings.Contains(string(code), "RegisterASTFunc")),
		logger_domain.Bool("has_buildast", strings.Contains(string(code), "func BuildAST")),
		logger_domain.Int("code_length", len(code)))
}

// derivePagePath gets the relative page path from a source file path.
// For example, "/project/pages/checkout.pk" with baseDir "/project"
// returns "pages/checkout".
//
// Takes sourcePath (string) which is the full path to the source file.
// Takes baseDir (string) which is the base folder for working out relative
// paths.
//
// Returns string which is the relative path without the .pk extension.
func derivePagePath(sourcePath, baseDir string) string {
	absSource, absErr := filepath.Abs(sourcePath)
	absBase, baseErr := filepath.Abs(baseDir)

	if absErr == nil && baseErr == nil {
		relPath, err := filepath.Rel(absBase, absSource)
		if err == nil && !strings.HasPrefix(relPath, "..") {
			return strings.TrimSuffix(relPath, ".pk")
		}
	}

	relPath, err := filepath.Rel(baseDir, sourcePath)
	if err != nil || strings.HasPrefix(relPath, "..") {
		relPath = filepath.Base(sourcePath)
	}
	return strings.TrimSuffix(relPath, ".pk")
}

// ensureDistPackageExists checks if the dist directory and a placeholder
// generated.go file exist to ensure it is a valid Go package. If either is
// missing, it creates them.
//
// Takes ctx (context.Context) which provides the base context for logging.
// Takes baseDir (string) which is the absolute path to the project root.
// Takes sandbox (safedisk.Sandbox) which is an optional sandbox for filesystem
// operations. If nil, a sandbox is created from the base directory.
//
// Returns error when the sandbox cannot be created, the placeholder file
// status cannot be checked, or directory or file creation fails.
func ensureDistPackageExists(ctx context.Context, baseDir string, sandbox safedisk.Sandbox, factory safedisk.Factory) error {
	outputDistDir := filepath.Join(baseDir, distDir)
	placeholderFileName := "generated.go"

	baseSandbox := sandbox
	var shouldClose bool
	if baseSandbox == nil {
		var err error
		if factory != nil {
			baseSandbox, err = factory.Create("ensure dist package", baseDir, safedisk.ModeReadWrite)
		} else {
			baseSandbox, err = safedisk.NewNoOpSandbox(baseDir, safedisk.ModeReadWrite)
		}
		if err != nil {
			return fmt.Errorf("failed to create sandbox for base directory '%s': %w", baseDir, err)
		}
		shouldClose = true
	}
	if shouldClose {
		defer func() { _ = baseSandbox.Close() }()
	}

	placeholderRelPath := filepath.Join(distDir, placeholderFileName)
	_, l := logger_domain.From(context.WithoutCancel(ctx), log)
	_, err := baseSandbox.Stat(placeholderRelPath)
	if err == nil {
		l.Internal("Placeholder 'dist/generated.go' already exists.")
		return nil
	}

	if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("failed to check status of placeholder file '%s': %w", placeholderRelPath, err)
	}

	l.Internal("Placeholder 'dist/generated.go' not found. Ensuring it and its parent directory exist.")

	if err := baseSandbox.MkdirAll(distDir, DirPermission); err != nil {
		return fmt.Errorf("failed to create dist directory at '%s': %w", outputDistDir, err)
	}

	if err := baseSandbox.WriteFile(placeholderRelPath, []byte(distPackageBoilerplate), FilePermission); err != nil {
		return fmt.Errorf("failed to write placeholder 'generated.go' in dist directory: %w", err)
	}

	l.Internal("Successfully created placeholder 'dist/generated.go'.")
	return nil
}

// convertVirtualInstances delegates to generator_dto.ConvertVirtualInstances
// so the annotator->generator translation lives in one place and cannot drift
// between the generator service and the coordinator's artefact path.
//
// Takes instances ([]annotator_dto.VirtualPageInstance) which contains the
// page instances to convert.
//
// Returns []generator_dto.VirtualPageInstanceData which contains the converted
// page instances, or nil if the input is empty.
func convertVirtualInstances(instances []annotator_dto.VirtualPageInstance) []generator_dto.VirtualPageInstanceData {
	return generator_dto.ConvertVirtualInstances(instances)
}
