//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_child_d247007e "testcase_027_deep_nested_prop_context/dist/partials/partials_child_d247007e"
	partials_parent_f5d0595c "testcase_027_deep_nested_prop_context/dist/partials/partials_parent_f5d0595c"
	grandparent_types "testcase_027_deep_nested_prop_context/pkg/grandparent_types"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_parent_f5d0595c.Render

// line pages/main.pk:33
type Response struct {
	Data grandparent_types.GrandparentState
}

// line pages/main.pk:37
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	return Response{Data: grandparent_types.GrandparentState{ValueForParent: "Top Level Value"}}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_parent_from_grandparent_state_data_valueforparent_e958c52a := partials_parent_f5d0595c.Props{FromGrandparent: pageData.Data.ValueForParent}
	partials_parent_f5d0595cData_parent_from_grandparent_state_data_valueforparent_e958c52a, partials_parent_f5d0595cMeta_parent_from_grandparent_state_data_valueforparent_e958c52a, partials_parent_f5d0595cErr_parent_from_grandparent_state_data_valueforparent_e958c52a := partials_parent_f5d0595c.Render(r, props_parent_from_grandparent_state_data_valueforparent_e958c52a)
	if partials_parent_f5d0595cErr_parent_from_grandparent_state_data_valueforparent_e958c52a != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_parent_f5d0595cErr_parent_from_grandparent_state_data_valueforparent_e958c52a.Error(), "R002", "", "Partial Render() error for partials_parent_f5d0595c", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_parent_f5d0595cData_parent_from_grandparent_state_data_valueforparent_e958c52a
	_ = partials_parent_f5d0595cMeta_parent_from_grandparent_state_data_valueforparent_e958c52a
	_ = partials_parent_f5d0595cErr_parent_from_grandparent_state_data_valueforparent_e958c52a
	props_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235 := partials_child_d247007e.Props{FromGrandparentState: props_parent_from_grandparent_state_data_valueforparent_e958c52a.FromGrandparent, FromParentState: partials_parent_f5d0595cData_parent_from_grandparent_state_data_valueforparent_e958c52a.Data.ValueForChild}
	partials_child_d247007eData_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235, partials_child_d247007eMeta_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235, partials_child_d247007eErr_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235 := partials_child_d247007e.Render(r, props_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235)
	if partials_child_d247007eErr_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_child_d247007eErr_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235.Error(), "R002", "", "Partial Render() error for partials_child_d247007e", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_child_d247007eData_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235
	_ = partials_child_d247007eMeta_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235
	_ = partials_child_d247007eErr_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/parent.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetAttrWriterSlice(1)
	tempVar1.AttributeWriters = tempVar2Slice
	_, tempVar3Slice := arena.GetChildSlice(1)
	tempVar1.Children = tempVar3Slice
	tempVar4 := arena.GetDirectWriter()
	tempVar4.SetName("from-grandparent")
	tempVar4.AppendEscapeString(pageData.Data.ValueForParent)
	tempVar1.AttributeWriters = append(tempVar1.AttributeWriters, tempVar4)
	// line partials/child.pk:22
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "div"
	tempVar5.Attributes = staticAttrs_2
	_, tempVar6Slice := arena.GetAttrWriterSlice(2)
	tempVar5.AttributeWriters = tempVar6Slice
	_, tempVar7Slice := arena.GetChildSlice(2)
	tempVar5.Children = tempVar7Slice
	tempVar8 := arena.GetDirectWriter()
	tempVar8.SetName("from-grandparent-state")
	tempVar8.AppendEscapeString(props_parent_from_grandparent_state_data_valueforparent_e958c52a.FromGrandparent)
	tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar8)
	tempVar9 := arena.GetDirectWriter()
	tempVar9.SetName("from-parent-state")
	tempVar9.AppendInt(int64(partials_parent_f5d0595cData_parent_from_grandparent_state_data_valueforparent_e958c52a.Data.ValueForChild))
	tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar9)
	// line partials/child.pk:23
	tempVar10 := arena.GetNode()
	tempVar10.NodeType = pikoruntime.NodeElement
	tempVar10.TagName = "p"
	tempVar10.Attributes = staticAttrs_3
	_, tempVar11Slice := arena.GetChildSlice(2)
	tempVar10.Children = tempVar11Slice
	tempVar10.Children = append(tempVar10.Children, staticNode_1)
	// line partials/child.pk:23
	tempVar12 := arena.GetNode()
	tempVar12.NodeType = pikoruntime.NodeElement
	tempVar12.TagName = "span"
	tempVar12.Attributes = staticAttrs_4
	tempVar13 := arena.GetDirectWriter()
	tempVar13.AppendString(strconv.FormatInt(int64(props_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235.FromParentState), 10))
	tempVar12.TextContentWriter = tempVar13
	tempVar10.Children = append(tempVar10.Children, tempVar12)
	tempVar5.Children = append(tempVar5.Children, tempVar10)
	// line partials/child.pk:24
	tempVar14 := arena.GetNode()
	tempVar14.NodeType = pikoruntime.NodeElement
	tempVar14.TagName = "p"
	tempVar14.Attributes = staticAttrs_5
	_, tempVar15Slice := arena.GetChildSlice(2)
	tempVar14.Children = tempVar15Slice
	tempVar14.Children = append(tempVar14.Children, staticNode_2)
	// line partials/child.pk:24
	tempVar16 := arena.GetNode()
	tempVar16.NodeType = pikoruntime.NodeElement
	tempVar16.TagName = "span"
	tempVar16.Attributes = staticAttrs_6
	tempVar17 := arena.GetDirectWriter()
	tempVar17.AppendEscapeString(props_child_parent_from_grandparent_state_data_valueforparent_e958c52a_from_grandparent_state_props_fromgrandparent_from_parent_state_state_data_valueforchild_35e9e235.FromGrandparentState)
	tempVar16.TextContentWriter = tempVar17
	tempVar14.Children = append(tempVar14.Children, tempVar16)
	tempVar5.Children = append(tempVar5.Children, tempVar14)
	tempVar1.Children = append(tempVar1.Children, tempVar5)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: partials/parent.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 22
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 23
	staticAttrs_4 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 23
	staticAttrs_5 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 24
	staticAttrs_6 []pikoruntime.HTMLAttribute // SOURCE: partials/child.pk, LINE: 24
	staticNode_1  *pikoruntime.TemplateNode   // SOURCE: partials/child.pk, LINE: 23
	staticNode_2  *pikoruntime.TemplateNode   // SOURCE: partials/child.pk, LINE: 24
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_parent_f5d0595c"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "parent"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "parent"}, pikoruntime.HTMLAttribute{Name: "hello", Value: "world"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "child"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "child"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeText
	staticNode_1.TextContent = "Received from parent state: "
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0:1"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1"}}
	staticNode_2 = &pikoruntime.TemplateNode{}
	staticNode_2.NodeType = pikoruntime.NodeText
	staticNode_2.TextContent = "Forwarded from grandparent state: "
	staticAttrs_6 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_child_d247007e"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1:1"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_027_deep_nested_prop_context/dist/pages/pages_main_594861c5", BuildAST)
}
