//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_level2_header_beeda5cc

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_level3_profile_9f247195 "testcase_021_deeply_nested_partials/dist/partials/partials_level3_profile_9f247195"
	partials_level4_avatar_dd5bb04f "testcase_021_deeply_nested_partials/dist/partials/partials_level4_avatar_dd5bb04f"
	partials_level5_subtext_a77f881b "testcase_021_deeply_nested_partials/dist/partials/partials_level5_subtext_a77f881b"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}
var _ = partials_level3_profile_9f247195.Render

// line partials/level2_header.pk:36
type Props struct {
	Username string `prop:"username"`
}

// line partials/level2_header.pk:40
type Response struct{ SiteName string }

// line partials/level2_header.pk:44
func Render(r *piko.RequestData, props Props) (Response, piko.Metadata, error) {
	return Response{SiteName: "MyApp"}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := Props{}
	if propsData != nil {
		p, ok := propsData.(Props)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306 := piko.NoProps{}
	partials_level5_subtext_a77f881bData_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306, partials_level5_subtext_a77f881bMeta_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306, partials_level5_subtext_a77f881bErr_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306 := partials_level5_subtext_a77f881b.Render(r, props_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306)
	if partials_level5_subtext_a77f881bErr_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_level5_subtext_a77f881bErr_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306.Error(), "R002", "", "Partial Render() error for partials_level5_subtext_a77f881b", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_level5_subtext_a77f881bData_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306
	_ = partials_level5_subtext_a77f881bMeta_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306
	_ = partials_level5_subtext_a77f881bErr_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306
	props_user_profile_username_props_username_86f07496 := partials_level3_profile_9f247195.Props{Username: props.Username}
	partials_level3_profile_9f247195Data_user_profile_username_props_username_86f07496, partials_level3_profile_9f247195Meta_user_profile_username_props_username_86f07496, partials_level3_profile_9f247195Err_user_profile_username_props_username_86f07496 := partials_level3_profile_9f247195.Render(r, props_user_profile_username_props_username_86f07496)
	if partials_level3_profile_9f247195Err_user_profile_username_props_username_86f07496 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_level3_profile_9f247195Err_user_profile_username_props_username_86f07496.Error(), "R002", "", "Partial Render() error for partials_level3_profile_9f247195", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_level3_profile_9f247195Data_user_profile_username_props_username_86f07496
	_ = partials_level3_profile_9f247195Meta_user_profile_username_props_username_86f07496
	_ = partials_level3_profile_9f247195Err_user_profile_username_props_username_86f07496
	props_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b := partials_level4_avatar_dd5bb04f.Props{Username: props_user_profile_username_props_username_86f07496.Username}
	partials_level4_avatar_dd5bb04fData_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b, partials_level4_avatar_dd5bb04fMeta_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b, partials_level4_avatar_dd5bb04fErr_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b := partials_level4_avatar_dd5bb04f.Render(r, props_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b)
	if partials_level4_avatar_dd5bb04fErr_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_level4_avatar_dd5bb04fErr_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b.Error(), "R002", "", "Partial Render() error for partials_level4_avatar_dd5bb04f", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_level4_avatar_dd5bb04fData_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b
	_ = partials_level4_avatar_dd5bb04fMeta_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b
	_ = partials_level4_avatar_dd5bb04fErr_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/level2_header.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "header"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	// line partials/level2_header.pk:23
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "div"
	tempVar3.Attributes = staticAttrs_2
	tempVar4 := arena.GetDirectWriter()
	tempVar4.AppendEscapeString(pageData.SiteName)
	tempVar3.TextContentWriter = tempVar4
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	// line partials/level3_profile.pk:22
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "div"
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetAttrWriterSlice(1)
	tempVar5.AttributeWriters = tempVar6Slice
	_, tempVar7Slice := arena.GetChildSlice(2)
	tempVar5.Children = tempVar7Slice
	tempVar8 := arena.GetDirectWriter()
	tempVar8.SetName("username")
	tempVar8.AppendEscapeString(props.Username)
	tempVar5.AttributeWriters = append(tempVar5.AttributeWriters, tempVar8)
	// line partials/level3_profile.pk:23
	tempVar9 := arena.GetNode()
	tempVar9.NodeType = pikoruntime.NodeElement
	tempVar9.TagName = "span"
	tempVar9.Attributes = staticAttrs_4
	_, tempVar10Slice := arena.GetChildSlice(2)
	tempVar9.Children = tempVar10Slice
	tempVar9.Children = append(tempVar9.Children, staticNode_1)
	// line partials/level3_profile.pk:23
	tempVar11 := arena.GetNode()
	tempVar11.NodeType = pikoruntime.NodeElement
	tempVar11.TagName = "b"
	tempVar11.Attributes = staticAttrs_5
	tempVar12 := arena.GetDirectWriter()
	tempVar12.AppendEscapeString(props_user_profile_username_props_username_86f07496.Username)
	tempVar11.TextContentWriter = tempVar12
	tempVar9.Children = append(tempVar9.Children, tempVar11)
	tempVar5.Children = append(tempVar5.Children, tempVar9)
	// line partials/level4_avatar.pk:22
	tempVar13 := arena.GetNode()
	tempVar13.NodeType = pikoruntime.NodeElement
	tempVar13.TagName = "div"
	tempVar13.Attributes = staticAttrs_6
	_, tempVar14Slice := arena.GetAttrWriterSlice(2)
	tempVar13.AttributeWriters = tempVar14Slice
	_, tempVar15Slice := arena.GetChildSlice(2)
	tempVar13.Children = tempVar15Slice
	tempVar16 := arena.GetDirectWriter()
	tempVar16.SetName("title")
	tempVar16.AppendEscapeString(props_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b.Username)
	tempVar16.AppendString(" avatar")
	tempVar13.AttributeWriters = append(tempVar13.AttributeWriters, tempVar16)
	tempVar17 := arena.GetDirectWriter()
	tempVar17.SetName("username")
	tempVar17.AppendEscapeString(props_user_profile_username_props_username_86f07496.Username)
	tempVar13.AttributeWriters = append(tempVar13.AttributeWriters, tempVar17)
	// line partials/level4_avatar.pk:23
	tempVar18 := arena.GetNode()
	tempVar18.NodeType = pikoruntime.NodeElement
	tempVar18.TagName = "span"
	tempVar18.Attributes = staticAttrs_7
	tempVar19 := arena.GetDirectWriter()
	tempVar19.AppendEscapeString(props_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b.Username)
	tempVar18.TextContentWriter = tempVar19
	tempVar13.Children = append(tempVar13.Children, tempVar18)
	// line partials/level5_subtext.pk:22
	tempVar20 := arena.GetNode()
	tempVar20.NodeType = pikoruntime.NodeElement
	tempVar20.TagName = "sub"
	tempVar20.Attributes = staticAttrs_8
	tempVar21 := arena.GetDirectWriter()
	tempVar21.AppendEscapeString(partials_level5_subtext_a77f881bData_subtext_user_avatar_user_profile_username_props_username_86f07496_username_props_username_5afb503b_75f51306.Info)
	tempVar20.TextContentWriter = tempVar21
	tempVar13.Children = append(tempVar13.Children, tempVar20)
	tempVar5.Children = append(tempVar5.Children, tempVar13)
	tempVar1.Children = append(tempVar1.Children, tempVar5)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: partials/level2_header.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: partials/level2_header.pk, LINE: 23
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: partials/level3_profile.pk, LINE: 22
	staticAttrs_4 []pikoruntime.HTMLAttribute // SOURCE: partials/level3_profile.pk, LINE: 23
	staticAttrs_5 []pikoruntime.HTMLAttribute // SOURCE: partials/level3_profile.pk, LINE: 23
	staticAttrs_6 []pikoruntime.HTMLAttribute // SOURCE: partials/level4_avatar.pk, LINE: 22
	staticAttrs_7 []pikoruntime.HTMLAttribute // SOURCE: partials/level4_avatar.pk, LINE: 23
	staticAttrs_8 []pikoruntime.HTMLAttribute // SOURCE: partials/level5_subtext.pk, LINE: 22
	staticNode_1  *pikoruntime.TemplateNode   // SOURCE: partials/level3_profile.pk, LINE: 23
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "site-header"}, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level2_header_beeda5cc"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level2_header"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level2_header_beeda5cc"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "logo"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level3_profile_9f247195"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level3_profile"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "user-profile"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level3_profile_9f247195"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeText
	staticNode_1.TextContent = "Welcome, "
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level3_profile_9f247195"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0:1"}}
	staticAttrs_6 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level4_avatar_dd5bb04f"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level4_avatar"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "avatar"}}
	staticAttrs_7 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level4_avatar_dd5bb04f"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:0"}}
	staticAttrs_8 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_level5_subtext_a77f881b"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "level5_subtext"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1:1"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_021_deeply_nested_partials/dist/partials/partials_level2_header_beeda5cc", BuildAST)
}
