//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_blog_slug_989a4cf3

import (
	"cmp"
	"fmt"
	"html"
	"sort"
	"strconv"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = cmp.Compare("", "")
var _ = piko.Metadata{}

// line pages/blog/{slug}.pk:40
type Post struct {
	Title string
	Slug  string
	URL   string
}

// line pages/blog/{slug}.pk:46
type Response struct {
	Title string
	Slug  string
	URL   string
}

// line pages/blog/{slug}.pk:52
func Render(r *piko.RequestData, props piko.NoProps) (Response, piko.Metadata, error) {
	post := piko.GetData[Post](r)
	return Response{Title: post.Title, Slug: post.Slug, URL: post.URL}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	__metadata, __contentAST, __excerptAST, __err := pikoruntime.GetStaticCollectionItem(r.Context(), "blog", cmp.Or(r.PathParam("slug"), r.PathParam("*")))
	if __err != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: pikoruntime.CollectionNotFound("blog", cmp.Or(r.PathParam("slug"), r.PathParam("*")), __err)}, nil
	}
	r = r.WithCollectionData(map[string]interface{}{"page": __metadata, "contentAST": __contentAST, "excerptAST": __excerptAST})
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	var data interface{}
	if rootMap, ok := r.CollectionData().(map[string]interface{}); ok {
		if pageVal, ok := rootMap["page"]; ok {
			data = pageVal
		} else {
			data = r.CollectionData()
		}
	}
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/blog/{slug}.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "article"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(2)
	tempVar1.Children = tempVar2Slice
	// line pages/blog/{slug}.pk:23
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "header"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(2)
	tempVar3.Children = tempVar4Slice
	// line pages/blog/{slug}.pk:24
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "h1"
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetChildSlice(1)
	tempVar5.Children = tempVar6Slice
	tempVar7 := arena.GetDirectWriter()
	tempVar7.AppendEscapeString(pageData.Title)
	tempVar5.TextContentWriter = tempVar7
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	// line pages/blog/{slug}.pk:25
	tempVar8 := arena.GetNode()
	tempVar8.NodeType = pikoruntime.NodeElement
	tempVar8.TagName = "p"
	tempVar8.Attributes = staticAttrs_4
	_, tempVar9Slice := arena.GetChildSlice(1)
	tempVar8.Children = tempVar9Slice
	// line pages/blog/{slug}.pk:26
	tempVar10 := arena.GetNode()
	tempVar10.NodeType = pikoruntime.NodeElement
	tempVar10.TagName = "span"
	tempVar10.Attributes = staticAttrs_5
	_, tempVar11Slice := arena.GetChildSlice(1)
	tempVar10.Children = tempVar11Slice
	tempVar12 := arena.GetDirectWriter()
	tempVar12.AppendEscapeString(pageData.Slug)
	tempVar10.TextContentWriter = tempVar12
	tempVar8.Children = append(tempVar8.Children, tempVar10)
	tempVar3.Children = append(tempVar3.Children, tempVar8)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	// line pages/blog/{slug}.pk:29
	tempVar13 := arena.GetNode()
	tempVar13.NodeType = pikoruntime.NodeElement
	tempVar13.TagName = "main"
	tempVar13.Attributes = staticAttrs_6
	_, tempVar14Slice := arena.GetChildSlice(1)
	tempVar13.Children = tempVar14Slice
	if contentAST := pikoruntime.GetContentAST(r.CollectionData()); contentAST != nil {
		for _, contentNode := range contentAST.RootNodes {
			tempVar13.Children = append(tempVar13.Children, contentNode)
		}
	}
	tempVar1.Children = append(tempVar1.Children, tempVar13)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	_ = data
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1 []pikoruntime.HTMLAttribute // SOURCE: pages/blog/{slug}.pk, LINE: 22
	staticAttrs_2 []pikoruntime.HTMLAttribute // SOURCE: pages/blog/{slug}.pk, LINE: 23
	staticAttrs_3 []pikoruntime.HTMLAttribute // SOURCE: pages/blog/{slug}.pk, LINE: 24
	staticAttrs_4 []pikoruntime.HTMLAttribute // SOURCE: pages/blog/{slug}.pk, LINE: 25
	staticAttrs_5 []pikoruntime.HTMLAttribute // SOURCE: pages/blog/{slug}.pk, LINE: 26
	staticAttrs_6 []pikoruntime.HTMLAttribute // SOURCE: pages/blog/{slug}.pk, LINE: 29
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_blog_slug_989a4cf3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "blog-post"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_blog_slug_989a4cf3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_blog_slug_989a4cf3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:0"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_blog_slug_989a4cf3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "meta"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_blog_slug_989a4cf3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0:1:0"}}
	staticAttrs_6 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_blog_slug_989a4cf3"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "content"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_060_collection_declarative_pcollection/dist/pages/pages_blog_slug_989a4cf3", BuildAST)
}
