//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package pages_main_594861c5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	partials_badge_63370d86 "testcase_073_multi_instance_nested_prop_bug/dist/partials/partials_badge_63370d86"
	partials_card_bfc4a3cf "testcase_073_multi_instance_nested_prop_bug/dist/partials/partials_card_bfc4a3cf"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}
var _ = partials_card_bfc4a3cf.Render

// line pages/main.pk:37
func Render(r *piko.RequestData, props piko.NoProps) (piko.NoResponse, piko.Metadata, error) {
	return piko.NoResponse{}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := piko.NoProps{}
	if propsData != nil {
		p, ok := propsData.(piko.NoProps)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	props_card_label_first_card_c872cad8 := partials_card_bfc4a3cf.Props{Label: "First Card"}
	partials_card_bfc4a3cfData_card_label_first_card_c872cad8, partials_card_bfc4a3cfMeta_card_label_first_card_c872cad8, partials_card_bfc4a3cfErr_card_label_first_card_c872cad8 := partials_card_bfc4a3cf.Render(r, props_card_label_first_card_c872cad8)
	if partials_card_bfc4a3cfErr_card_label_first_card_c872cad8 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_card_bfc4a3cfErr_card_label_first_card_c872cad8.Error(), "R002", "", "Partial Render() error for partials_card_bfc4a3cf", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_card_bfc4a3cfData_card_label_first_card_c872cad8
	_ = partials_card_bfc4a3cfMeta_card_label_first_card_c872cad8
	_ = partials_card_bfc4a3cfErr_card_label_first_card_c872cad8
	props_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae := partials_badge_63370d86.Props{Text: props_card_label_first_card_c872cad8.Label}
	partials_badge_63370d86Data_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae, partials_badge_63370d86Meta_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae, partials_badge_63370d86Err_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae := partials_badge_63370d86.Render(r, props_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae)
	if partials_badge_63370d86Err_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_badge_63370d86Err_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae.Error(), "R002", "", "Partial Render() error for partials_badge_63370d86", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_badge_63370d86Data_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae
	_ = partials_badge_63370d86Meta_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae
	_ = partials_badge_63370d86Err_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae
	props_card_label_second_card_e0600ecf := partials_card_bfc4a3cf.Props{Label: "Second Card"}
	partials_card_bfc4a3cfData_card_label_second_card_e0600ecf, partials_card_bfc4a3cfMeta_card_label_second_card_e0600ecf, partials_card_bfc4a3cfErr_card_label_second_card_e0600ecf := partials_card_bfc4a3cf.Render(r, props_card_label_second_card_e0600ecf)
	if partials_card_bfc4a3cfErr_card_label_second_card_e0600ecf != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_card_bfc4a3cfErr_card_label_second_card_e0600ecf.Error(), "R002", "", "Partial Render() error for partials_card_bfc4a3cf", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_card_bfc4a3cfData_card_label_second_card_e0600ecf
	_ = partials_card_bfc4a3cfMeta_card_label_second_card_e0600ecf
	_ = partials_card_bfc4a3cfErr_card_label_second_card_e0600ecf
	props_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64 := partials_badge_63370d86.Props{Text: props_card_label_second_card_e0600ecf.Label}
	partials_badge_63370d86Data_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64, partials_badge_63370d86Meta_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64, partials_badge_63370d86Err_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64 := partials_badge_63370d86.Render(r, props_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64)
	if partials_badge_63370d86Err_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64 != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, partials_badge_63370d86Err_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64.Error(), "R002", "", "Partial Render() error for partials_badge_63370d86", 0, 0)
		return nil, pikoruntime.InternalMetadata{}, diagnostics
	}
	_ = partials_badge_63370d86Data_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64
	_ = partials_badge_63370d86Meta_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64
	_ = partials_badge_63370d86Err_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line pages/main.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetChildSlice(3)
	tempVar1.Children = tempVar2Slice
	tempVar1.Children = append(tempVar1.Children, staticNode_1)
	// line partials/card.pk:22
	tempVar3 := arena.GetNode()
	tempVar3.NodeType = pikoruntime.NodeElement
	tempVar3.TagName = "div"
	tempVar3.Attributes = staticAttrs_2
	_, tempVar4Slice := arena.GetChildSlice(2)
	tempVar3.Children = tempVar4Slice
	// line partials/card.pk:23
	tempVar5 := arena.GetNode()
	tempVar5.NodeType = pikoruntime.NodeElement
	tempVar5.TagName = "h2"
	tempVar5.Attributes = staticAttrs_3
	_, tempVar6Slice := arena.GetChildSlice(1)
	tempVar5.Children = tempVar6Slice
	// line partials/card.pk:23
	tempVar7 := arena.GetNode()
	tempVar7.NodeType = pikoruntime.NodeText
	tempVar8 := arena.GetDirectWriter()
	tempVar8.AppendEscapeString(props_card_label_first_card_c872cad8.Label)
	tempVar7.TextContentWriter = tempVar8
	tempVar5.Children = append(tempVar5.Children, tempVar7)
	tempVar3.Children = append(tempVar3.Children, tempVar5)
	// line partials/badge.pk:22
	tempVar9 := arena.GetNode()
	tempVar9.NodeType = pikoruntime.NodeElement
	tempVar9.TagName = "span"
	tempVar9.Attributes = staticAttrs_4
	_, tempVar10Slice := arena.GetAttrWriterSlice(1)
	tempVar9.AttributeWriters = tempVar10Slice
	_, tempVar11Slice := arena.GetChildSlice(1)
	tempVar9.Children = tempVar11Slice
	tempVar12 := arena.GetDirectWriter()
	tempVar12.SetName("text")
	tempVar12.AppendEscapeString(props_card_label_first_card_c872cad8.Label)
	tempVar9.AttributeWriters = append(tempVar9.AttributeWriters, tempVar12)
	// line partials/badge.pk:22
	tempVar13 := arena.GetNode()
	tempVar13.NodeType = pikoruntime.NodeText
	tempVar14 := arena.GetDirectWriter()
	tempVar14.AppendEscapeString(props_badge_card_label_first_card_c872cad8_text_props_label_3ba509ae.Text)
	tempVar13.TextContentWriter = tempVar14
	tempVar9.Children = append(tempVar9.Children, tempVar13)
	tempVar3.Children = append(tempVar3.Children, tempVar9)
	tempVar1.Children = append(tempVar1.Children, tempVar3)
	// line partials/card.pk:22
	tempVar15 := arena.GetNode()
	tempVar15.NodeType = pikoruntime.NodeElement
	tempVar15.TagName = "div"
	tempVar15.Attributes = staticAttrs_5
	_, tempVar16Slice := arena.GetChildSlice(2)
	tempVar15.Children = tempVar16Slice
	// line partials/card.pk:23
	tempVar17 := arena.GetNode()
	tempVar17.NodeType = pikoruntime.NodeElement
	tempVar17.TagName = "h2"
	tempVar17.Attributes = staticAttrs_6
	_, tempVar18Slice := arena.GetChildSlice(1)
	tempVar17.Children = tempVar18Slice
	// line partials/card.pk:23
	tempVar19 := arena.GetNode()
	tempVar19.NodeType = pikoruntime.NodeText
	tempVar20 := arena.GetDirectWriter()
	tempVar20.AppendEscapeString(props_card_label_second_card_e0600ecf.Label)
	tempVar19.TextContentWriter = tempVar20
	tempVar17.Children = append(tempVar17.Children, tempVar19)
	tempVar15.Children = append(tempVar15.Children, tempVar17)
	// line partials/badge.pk:22
	tempVar21 := arena.GetNode()
	tempVar21.NodeType = pikoruntime.NodeElement
	tempVar21.TagName = "span"
	tempVar21.Attributes = staticAttrs_7
	_, tempVar22Slice := arena.GetAttrWriterSlice(1)
	tempVar21.AttributeWriters = tempVar22Slice
	_, tempVar23Slice := arena.GetChildSlice(1)
	tempVar21.Children = tempVar23Slice
	tempVar24 := arena.GetDirectWriter()
	tempVar24.SetName("text")
	tempVar24.AppendEscapeString(props_card_label_second_card_e0600ecf.Label)
	tempVar21.AttributeWriters = append(tempVar21.AttributeWriters, tempVar24)
	// line partials/badge.pk:22
	tempVar25 := arena.GetNode()
	tempVar25.NodeType = pikoruntime.NodeText
	tempVar26 := arena.GetDirectWriter()
	tempVar26.AppendEscapeString(props_badge_card_label_second_card_e0600ecf_text_props_label_18b1bb64.Text)
	tempVar25.TextContentWriter = tempVar26
	tempVar21.Children = append(tempVar21.Children, tempVar25)
	tempVar15.Children = append(tempVar15.Children, tempVar21)
	tempVar1.Children = append(tempVar1.Children, tempVar15)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1        []pikoruntime.HTMLAttribute // SOURCE: pages/main.pk, LINE: 22
	staticAttrs_2        []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 22
	staticAttrs_3        []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 23
	staticAttrs_4        []pikoruntime.HTMLAttribute // SOURCE: partials/badge.pk, LINE: 22
	staticAttrs_5        []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 22
	staticAttrs_6        []pikoruntime.HTMLAttribute // SOURCE: partials/card.pk, LINE: 23
	staticAttrs_7        []pikoruntime.HTMLAttribute // SOURCE: partials/badge.pk, LINE: 22
	staticNode_1         *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
	staticNode_1_child_0 *pikoruntime.TemplateNode   // SOURCE: pages/main.pk, LINE: 23
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "container"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "h1"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "pages_main_594861c5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Multiple Card Instances"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "card"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "card"}, pikoruntime.HTMLAttribute{Name: "label", Value: "First Card"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "card-title"}}
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_badge_63370d86"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "badge"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "badge"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "card"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"}, pikoruntime.HTMLAttribute{Name: "class", Value: "card"}, pikoruntime.HTMLAttribute{Name: "label", Value: "Second Card"}}
	staticAttrs_6 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_card_bfc4a3cf"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:0"}, pikoruntime.HTMLAttribute{Name: "class", Value: "card-title"}}
	staticAttrs_7 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_badge_63370d86"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "badge"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2:1"}, pikoruntime.HTMLAttribute{Name: "class", Value: "badge"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_073_multi_instance_nested_prop_bug/dist/pages/pages_main_594861c5", BuildAST)
}
