// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package search_schema_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IndexParams struct {
	_tab flatbuffers.Table
}

func GetRootAsIndexParams(buf []byte, offset flatbuffers.UOffsetT) *IndexParams {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IndexParams{}
	x.Init(buf, n+offset)
	return x
}

func FinishIndexParamsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIndexParams(buf []byte, offset flatbuffers.UOffsetT) *IndexParams {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IndexParams{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIndexParamsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IndexParams) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IndexParams) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IndexParams) Bm25K1() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.2
}

func (rcv *IndexParams) MutateBm25K1(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *IndexParams) Bm25B() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.75
}

func (rcv *IndexParams) MutateBm25B(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *IndexParams) MinTokenLength() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 2
}

func (rcv *IndexParams) MutateMinTokenLength(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *IndexParams) MaxTokenLength() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 50
}

func (rcv *IndexParams) MutateMaxTokenLength(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *IndexParams) StopWordsEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *IndexParams) MutateStopWordsEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *IndexParams) FieldWeights(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *IndexParams) FieldWeightsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IndexParams) MutateFieldWeights(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func IndexParamsStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func IndexParamsAddBm25K1(builder *flatbuffers.Builder, bm25K1 float32) {
	builder.PrependFloat32Slot(0, bm25K1, 1.2)
}
func IndexParamsAddBm25B(builder *flatbuffers.Builder, bm25B float32) {
	builder.PrependFloat32Slot(1, bm25B, 0.75)
}
func IndexParamsAddMinTokenLength(builder *flatbuffers.Builder, minTokenLength uint16) {
	builder.PrependUint16Slot(2, minTokenLength, 2)
}
func IndexParamsAddMaxTokenLength(builder *flatbuffers.Builder, maxTokenLength uint16) {
	builder.PrependUint16Slot(3, maxTokenLength, 50)
}
func IndexParamsAddStopWordsEnabled(builder *flatbuffers.Builder, stopWordsEnabled bool) {
	builder.PrependBoolSlot(4, stopWordsEnabled, true)
}
func IndexParamsAddFieldWeights(builder *flatbuffers.Builder, fieldWeights flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(fieldWeights), 0)
}
func IndexParamsStartFieldWeightsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func IndexParamsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
