// Code generated by 'piko extract'. DO NOT EDIT.

package driven_piko_symbols

import (
	"reflect"

	binder "piko.sh/piko/wdk/binder"
)

func init() {
	Symbols["piko.sh/piko/wdk/binder"] = map[string]reflect.Value{"Bind": reflect.ValueOf(binder.Bind), "BindJSON": reflect.ValueOf(binder.BindJSON), "BindMap": reflect.ValueOf(binder.BindMap), "ConverterFunc": reflect.ValueOf((*binder.ConverterFunc)(nil)), "IgnoreUnknownKeys": reflect.ValueOf(binder.IgnoreUnknownKeys), "Option": reflect.ValueOf((*binder.Option)(nil)), "RegisterConverter": reflect.ValueOf(binder.RegisterConverter), "SetIgnoreUnknownKeys": reflect.ValueOf(binder.SetIgnoreUnknownKeys), "SetMaxFormFields": reflect.ValueOf(binder.SetMaxFormFields), "SetMaxFormPathDepth": reflect.ValueOf(binder.SetMaxFormPathDepth), "SetMaxFormPathLength": reflect.ValueOf(binder.SetMaxFormPathLength), "SetMaxFormValueLength": reflect.ValueOf(binder.SetMaxFormValueLength), "SetMaxSliceSize": reflect.ValueOf(binder.SetMaxSliceSize), "WithMaxFieldCount": reflect.ValueOf(binder.WithMaxFieldCount), "WithMaxPathDepth": reflect.ValueOf(binder.WithMaxPathDepth), "WithMaxPathLength": reflect.ValueOf(binder.WithMaxPathLength), "WithMaxSliceSize": reflect.ValueOf(binder.WithMaxSliceSize), "WithMaxValueLength": reflect.ValueOf(binder.WithMaxValueLength)}
}
