//go:build !piko_analysis

/* Code generated by piko; DO NOT EDIT. */

package partials_comprehensive_3b6160d5

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	models "testcase_072_prop_tags_comprehensive/pkg/models"

	piko "piko.sh/piko"
	pikoruntime "piko.sh/piko/wdk/runtime"
	"piko.sh/piko/wdk/safeconv"
)

var _ = fmt.Println
var _ = html.EscapeString
var _ = strconv.FormatInt
var _ = sort.Strings
var _ = pikoruntime.EvaluateTruthiness
var _ = safeconv.IntToInt32
var _ = piko.Metadata{}

// line partials/comprehensive.pk:39
func GetDefaultCardOptions() models.AvatarOptions {
	return models.AvatarOptions{Size: 32, Shape: "square"}
}

// line partials/comprehensive.pk:46
type Props struct {
	Title         string               `prop:"card-title" validate:"required"`
	Description   string               `prop:"description" default:"No description provided"`
	Theme         string               `prop:"card-theme" default:"default"`
	IsHighlighted bool                 `prop:"highlighted" coerce:"true"`
	Priority      int                  `prop:"priority" coerce:"true" default:"1"`
	Options       models.AvatarOptions `prop:"options" factory:"GetDefaultCardOptions"`
}

// line partials/comprehensive.pk:55
type Response struct {
	Title         string
	Description   string
	Theme         string
	IsHighlighted bool
	Priority      int
	Options       models.AvatarOptions
}

// line partials/comprehensive.pk:64
func Render(r *piko.RequestData, props Props) (Response, piko.Metadata, error) {
	return Response{Title: props.Title, Description: props.Description, Theme: props.Theme, IsHighlighted: props.IsHighlighted, Priority: props.Priority, Options: props.Options}, piko.Metadata{}, nil
}
func CachePolicy() piko.CachePolicy {
	return piko.CachePolicy{}
}

var customTags []string

func BuildAST(r *piko.RequestData, propsData interface{}) (*pikoruntime.TemplateAST, pikoruntime.InternalMetadata, []*pikoruntime.RuntimeDiagnostic) {
	var diagnostics []*pikoruntime.RuntimeDiagnostic
	props := Props{}
	if propsData != nil {
		p, ok := propsData.(Props)
		if ok {
			props = p
		}
	}
	pageData, pageMeta, renderErr := Render(r, props)
	if renderErr != nil {
		diagnostics = pikoruntime.AppendDiagnostic(diagnostics, pikoruntime.Error, renderErr.Error(), "R001", "", "Render() error", 0, 0)
		return nil, pikoruntime.InternalMetadata{RenderError: renderErr}, diagnostics
	}
	mainCachePolicy := CachePolicy()
	if pageMeta.ServerRedirect != "" || pageMeta.ClientRedirect != "" {
		return nil, pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: nil}, diagnostics
	}
	if r.Context().Err() != nil {
		return nil, pikoruntime.InternalMetadata{RenderError: r.Context().Err()}, diagnostics
	}
	arena := pikoruntime.GetArena()
	rootAST := arena.GetTemplateAST()
	rootAST.SetArena(arena)
	rootAST.RootNodes = arena.GetRootNodesSlice(1)
	// line partials/comprehensive.pk:22
	tempVar1 := arena.GetNode()
	tempVar1.NodeType = pikoruntime.NodeElement
	tempVar1.TagName = "div"
	tempVar1.Attributes = staticAttrs_1
	_, tempVar2Slice := arena.GetAttrWriterSlice(1)
	tempVar1.AttributeWriters = tempVar2Slice
	_, tempVar3Slice := arena.GetChildSlice(5)
	tempVar1.Children = tempVar3Slice
	tempVar4 := pikoruntime.ClassesFromStringBytesArena(arena, "comprehensive-card theme-"+pageData.Theme)
	if tempVar4 != nil {
		tempVar5 := arena.GetDirectWriter()
		tempVar5.SetName("class")
		tempVar5.AppendPooledBytes(tempVar4)
		tempVar1.AttributeWriters = append(tempVar1.AttributeWriters, tempVar5)
	}
	// line partials/comprehensive.pk:23
	tempVar6 := arena.GetNode()
	tempVar6.NodeType = pikoruntime.NodeElement
	tempVar6.TagName = "h2"
	tempVar6.Attributes = staticAttrs_2
	tempVar7 := arena.GetDirectWriter()
	tempVar7.AppendEscapeString(pageData.Title)
	tempVar6.TextContentWriter = tempVar7
	tempVar1.Children = append(tempVar1.Children, tempVar6)
	// line partials/comprehensive.pk:24
	tempVar8 := arena.GetNode()
	tempVar8.NodeType = pikoruntime.NodeElement
	tempVar8.TagName = "p"
	tempVar8.Attributes = staticAttrs_3
	tempVar9 := arena.GetDirectWriter()
	tempVar9.AppendEscapeString(pageData.Description)
	tempVar8.TextContentWriter = tempVar9
	tempVar1.Children = append(tempVar1.Children, tempVar8)
	// line partials/comprehensive.pk:25:11
	if pageData.IsHighlighted {
		tempVar1.Children = append(tempVar1.Children, staticNode_1)
	}
	// line partials/comprehensive.pk:26
	tempVar10 := arena.GetNode()
	tempVar10.NodeType = pikoruntime.NodeElement
	tempVar10.TagName = "span"
	tempVar10.Attributes = staticAttrs_4
	tempVar11 := arena.GetDirectWriter()
	tempVar11.AppendString(strconv.FormatInt(int64(pageData.Priority), 10))
	tempVar10.TextContentWriter = tempVar11
	tempVar1.Children = append(tempVar1.Children, tempVar10)
	// line partials/comprehensive.pk:27
	tempVar12 := arena.GetNode()
	tempVar12.NodeType = pikoruntime.NodeElement
	tempVar12.TagName = "span"
	tempVar12.Attributes = staticAttrs_5
	tempVar13 := arena.GetDirectWriter()
	tempVar13.AppendEscapeString(pageData.Options.Shape)
	tempVar12.TextContentWriter = tempVar13
	tempVar1.Children = append(tempVar1.Children, tempVar12)
	rootAST.RootNodes = append(rootAST.RootNodes, tempVar1)
	_ = pageData
	_ = pageMeta
	_ = mainCachePolicy
	internalMetaResult := pikoruntime.InternalMetadata{Metadata: pageMeta, CachePolicy: mainCachePolicy, AssetRefs: nil, CustomTags: customTags}
	return rootAST, internalMetaResult, diagnostics
}

var (
	staticAttrs_1        []pikoruntime.HTMLAttribute // SOURCE: partials/comprehensive.pk, LINE: 22
	staticAttrs_2        []pikoruntime.HTMLAttribute // SOURCE: partials/comprehensive.pk, LINE: 23
	staticAttrs_3        []pikoruntime.HTMLAttribute // SOURCE: partials/comprehensive.pk, LINE: 24
	staticAttrs_4        []pikoruntime.HTMLAttribute // SOURCE: partials/comprehensive.pk, LINE: 26
	staticAttrs_5        []pikoruntime.HTMLAttribute // SOURCE: partials/comprehensive.pk, LINE: 27
	staticNode_1         *pikoruntime.TemplateNode   // SOURCE: partials/comprehensive.pk, LINE: 25
	staticNode_1_child_0 *pikoruntime.TemplateNode   // SOURCE: partials/comprehensive.pk, LINE: 25
)

func init() {
	staticAttrs_1 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0"}, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_comprehensive_3b6160d5"}, pikoruntime.HTMLAttribute{Name: "partial_name", Value: "comprehensive"}}
	staticAttrs_2 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_comprehensive_3b6160d5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:0"}}
	staticAttrs_3 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_comprehensive_3b6160d5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:1"}}
	staticNode_1 = &pikoruntime.TemplateNode{}
	staticNode_1.NodeType = pikoruntime.NodeElement
	staticNode_1.TagName = "span"
	staticNode_1.Attributes = make([]pikoruntime.HTMLAttribute, 0, 2)
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_comprehensive_3b6160d5"})
	staticNode_1.Attributes = append(staticNode_1.Attributes, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:2"})
	staticNode_1.Children = make([]*pikoruntime.TemplateNode, 0, 1)
	staticNode_1_child_0 = &pikoruntime.TemplateNode{}
	staticNode_1_child_0.NodeType = pikoruntime.NodeText
	staticNode_1_child_0.TextContent = "Highlighted!"
	staticNode_1.Children = append(staticNode_1.Children, staticNode_1_child_0)
	staticAttrs_4 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_comprehensive_3b6160d5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:3"}}
	staticAttrs_5 = []pikoruntime.HTMLAttribute{pikoruntime.HTMLAttribute{Name: "partial", Value: "partials_comprehensive_3b6160d5"}, pikoruntime.HTMLAttribute{Name: "p-key", Value: "r.0:4"}}
}
func init() {
	pikoruntime.RegisterASTFunc("testcase_072_prop_tags_comprehensive/dist/partials/partials_comprehensive_3b6160d5", BuildAST)
}
