// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"

// dotF64Kern computes sum(a[i]*b[i]) for f64 vectors using 8-way NEON unrolling.
TEXT ·dotF64Kern(SB), NOSPLIT, $0-56
	MOVD a_base+0(FP), R0
	MOVD a_len+8(FP), R2
	MOVD b_base+24(FP), R1

	VEOR V0.B16, V0.B16, V0.B16
	VEOR V4.B16, V4.B16, V4.B16
	VEOR V5.B16, V5.B16, V5.B16
	VEOR V6.B16, V6.B16, V6.B16
	VEOR V7.B16, V7.B16, V7.B16
	VEOR V8.B16, V8.B16, V8.B16
	VEOR V9.B16, V9.B16, V9.B16
	VEOR V10.B16, V10.B16, V10.B16
	VEOR V3.B16, V3.B16, V3.B16

	CMP  $16, R2
	BLT  dotf64_tail2

dotf64_loop16:
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC20

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC24

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC25

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC26

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC27

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC28

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC29

	ADD  $16, R0
	ADD  $16, R1
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC2A

	ADD  $16, R0
	ADD  $16, R1
	SUB  $16, R2
	CMP  $16, R2
	BGE  dotf64_loop16

	WORD $0x4E64D400
	WORD $0x4E65D400
	WORD $0x4E66D400
	WORD $0x4E67D400
	WORD $0x4E68D400
	WORD $0x4E69D400
	WORD $0x4E6AD400

dotf64_tail2:
	CMP  $2, R2
	BLT  dotf64_tail

dotf64_loop2:
	VLD1 (R0), [V1.D2]
	VLD1 (R1), [V2.D2]
	WORD $0x4E62CC20
	ADD  $16, R0
	ADD  $16, R1
	SUB  $2, R2
	CMP  $2, R2
	BGE  dotf64_loop2

dotf64_tail:
	CBZ  R2, dotf64_reduce

dotf64_tail_loop:
	FMOVD (R0), F1
	FMOVD (R1), F2
	FMULD F1, F2, F1
	FADDD F1, F3, F3
	ADD  $8, R0
	ADD  $8, R1
	SUB  $1, R2
	CBNZ R2, dotf64_tail_loop

dotf64_reduce:
	WORD $0x6E60D400
	FADDD F3, F0, F0

	FMOVD F0, ret+48(FP)
	RET
