// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package spamdetect_dto

import (
	"slices"
	"sort"
	"time"
	"unicode/utf8"
)

const (
	// maxRemoteIPLength is the maximum byte length for the remote IP field.
	maxRemoteIPLength = 256

	// maxUserAgentLength is the maximum byte length for the user agent field.
	maxUserAgentLength = 1024

	// maxHoneypotLength is the maximum byte length for the honeypot field.
	maxHoneypotLength = 1024

	// maxPageURLLength is the maximum byte length for the page URL field.
	maxPageURLLength = 2048

	// maxActionNameLength is the maximum byte length for the action name field.
	maxActionNameLength = 256

	// maxMetadataEntries is the upper bound on metadata key-value pairs.
	maxMetadataEntries = 32

	// maxMetadataValueLen is the maximum byte length for a metadata value.
	maxMetadataValueLen = 1024

	// maxHeaderEntries is the upper bound on captured header entries.
	maxHeaderEntries = 16

	// maxHeaderValueLen is the maximum byte length for a header value.
	maxHeaderValueLen = 2048
)

// FieldValue carries a form field's string value alongside its semantic
// type from the schema.
type FieldValue struct {
	// Value is the string content of the field.
	Value string

	// Type is the semantic type from the schema.
	Type FieldType
}

// Submission carries the form field values and request metadata to be
// analysed for spam.
type Submission struct {
	// Fields contains form field values keyed by the schema field key.
	Fields map[string]FieldValue

	// Metadata carries provider context declared by the schema.
	//
	// Populated from the schema's Meta entries (e.g. form type, site URL).
	Metadata map[string]string

	// Headers carries selected HTTP request headers declared by the
	// schema's CaptureHeader entries.
	Headers map[string]string

	// FormSubmittedAt is when the form was submitted.
	FormSubmittedAt time.Time

	// FormLoadedAt is when the form was initially loaded (from a signed
	// timestamp token).
	FormLoadedAt time.Time

	// ID is a unique identifier for this submission, generated by the
	// service during analysis. Used to correlate feedback reports.
	ID string

	// RemoteIP is the client IP address (without port).
	RemoteIP string

	// UserAgent is the client's User-Agent header.
	UserAgent string

	// HoneypotValue is the value of the hidden honeypot field.
	HoneypotValue string

	// PageURL is the page the form was submitted from.
	PageURL string

	// ActionName is the Piko action that received this submission.
	ActionName string

	// truncated is true when any field was truncated during sanitisation.
	truncated bool
}

// Sanitise clamps field lengths to safe maximums using per-field limits
// from the schema.
//
// Takes schema (*Schema) which provides per-field length limits.
func (s *Submission) Sanitise(schema *Schema) {
	s.RemoteIP = s.truncateAndTrack(s.RemoteIP, maxRemoteIPLength)
	s.UserAgent = s.truncateAndTrack(s.UserAgent, maxUserAgentLength)
	s.HoneypotValue = s.truncateAndTrack(s.HoneypotValue, maxHoneypotLength)
	s.PageURL = s.truncateAndTrack(s.PageURL, maxPageURLLength)
	s.ActionName = s.truncateAndTrack(s.ActionName, maxActionNameLength)

	s.sanitiseMap(s.Metadata, maxMetadataEntries, maxMetadataValueLen)
	s.sanitiseMap(s.Headers, maxHeaderEntries, maxHeaderValueLen)

	if schema == nil {
		return
	}

	schemaFields := schema.Fields()
	fieldLimits := make(map[string]int, len(schemaFields))
	for _, field := range schemaFields {
		fieldLimits[field.Key] = field.MaxLength
	}

	for key, fieldValue := range s.Fields {
		limit, exists := fieldLimits[key]
		if !exists {
			delete(s.Fields, key)
			continue
		}
		fieldValue.Value = s.truncateAndTrack(fieldValue.Value, limit)
		s.Fields[key] = fieldValue
	}
}

// WasTruncated reports whether any field value was truncated during
// sanitisation.
//
// Returns bool which is true when truncation occurred.
func (s *Submission) WasTruncated() bool {
	return s.truncated
}

// FieldString returns the string value of a field by key, or an empty
// string if the key is not present.
//
// Takes key (string) which is the field key.
//
// Returns string which is the field value.
func (s *Submission) FieldString(key string) string {
	if s.Fields == nil {
		return ""
	}
	return s.Fields[key].Value
}

// GetField returns the full FieldValue for a key, or a zero value if
// the key is not present.
//
// Takes key (string) which is the field key.
//
// Returns FieldValue which is the field value and type.
func (s *Submission) GetField(key string) FieldValue {
	if s.Fields == nil {
		return FieldValue{}
	}
	return s.Fields[key]
}

// MetadataValue returns a metadata value by key, or an empty string.
//
// Takes key (string) which is the metadata key.
//
// Returns string which is the metadata value.
func (s *Submission) MetadataValue(key string) string {
	if s.Metadata == nil {
		return ""
	}
	return s.Metadata[key]
}

// HeaderValue returns a captured header value by name, or an empty string.
//
// Takes name (string) which is the header name.
//
// Returns string which is the header value.
func (s *Submission) HeaderValue(name string) string {
	if s.Headers == nil {
		return ""
	}
	return s.Headers[name]
}

// truncateAndTrack truncates a string and sets the truncated flag if
// shortened.
//
// Takes value (string) which is the string to truncate.
// Takes maximum (int) which is the byte length limit.
//
// Returns string which is the truncated value.
func (s *Submission) truncateAndTrack(value string, maximum int) string {
	truncated := truncateStringUTF8(value, maximum)
	if len(truncated) < len(value) {
		s.truncated = true
	}
	return truncated
}

// sanitiseMap truncates map values and evicts excess entries.
//
// Takes entries (map[string]string) which is the map to sanitise.
// Takes maxEntries (int) which is the maximum entry count.
// Takes maxValueLength (int) which is the maximum value byte length.
func (s *Submission) sanitiseMap(entries map[string]string, maxEntries int, maxValueLength int) {
	for key := range entries {
		if len(key) > maxValueLength {
			delete(entries, key)
		}
	}

	if len(entries) <= maxEntries {
		for key, value := range entries {
			entries[key] = s.truncateAndTrack(value, maxValueLength)
		}
		return
	}

	sortedKeys := make([]string, 0, len(entries))
	for key := range entries {
		sortedKeys = append(sortedKeys, key)
	}
	sort.Strings(sortedKeys)

	keepKeys := slices.Clone(sortedKeys[:maxEntries])
	keepSet := make(map[string]struct{}, maxEntries)
	for _, key := range keepKeys {
		keepSet[key] = struct{}{}
	}

	for _, key := range sortedKeys {
		if _, keep := keepSet[key]; !keep {
			delete(entries, key)
		} else {
			entries[key] = s.truncateAndTrack(entries[key], maxValueLength)
		}
	}
}

// truncateStringUTF8 truncates a string to a maximum byte length
// respecting rune boundaries.
//
// Takes value (string) which is the string to truncate.
// Takes maximum (int) which is the byte length limit.
//
// Returns string which is the truncated value.
func truncateStringUTF8(value string, maximum int) string {
	if len(value) <= maximum {
		return value
	}

	truncated := value[:maximum]
	for len(truncated) > 0 && !utf8.ValidString(truncated) {
		truncated = truncated[:len(truncated)-1]
	}

	return truncated
}
