// Code generated by Piko. DO NOT EDIT.

package db

import "context"

const listallartefactswithdata = `SELECT id, source_path, created_at, updated_at, data_fbs
FROM artefact;`

type ListAllArtefactsWithDataRow struct {
	ID         string
	SourcePath string
	CreatedAt  int32
	UpdatedAt  int32
	DataFbs    []byte
}

func (queries *Queries) ListAllArtefactsWithData(ctx context.Context) ([]ListAllArtefactsWithDataRow, error) {
	rows, err := queries.reader.QueryContext(ctx, listallartefactswithdata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []ListAllArtefactsWithDataRow
	for rows.Next() {
		var row ListAllArtefactsWithDataRow
		if err := rows.Scan(&row.ID, &row.SourcePath, &row.CreatedAt, &row.UpdatedAt, &row.DataFbs); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const listrecentartefactswithdata = `SELECT id, source_path, created_at, updated_at, data_fbs
FROM artefact
ORDER BY updated_at DESC
LIMIT ?;`

type ListRecentArtefactsWithDataRow struct {
	ID         string
	SourcePath string
	CreatedAt  int32
	UpdatedAt  int32
	DataFbs    []byte
}

func (queries *Queries) ListRecentArtefactsWithData(ctx context.Context, p1 int32) ([]ListRecentArtefactsWithDataRow, error) {
	rows, err := queries.reader.QueryContext(ctx, listrecentartefactswithdata, p1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []ListRecentArtefactsWithDataRow
	for rows.Next() {
		var row ListRecentArtefactsWithDataRow
		if err := rows.Scan(&row.ID, &row.SourcePath, &row.CreatedAt, &row.UpdatedAt, &row.DataFbs); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const listvariantstatuscounts = `SELECT status, COUNT(*) AS variant_count
FROM variant
GROUP BY status;`

type ListVariantStatusCountsRow struct {
	Status       string
	VariantCount int32
}

func (queries *Queries) ListVariantStatusCounts(ctx context.Context) ([]ListVariantStatusCountsRow, error) {
	rows, err := queries.reader.QueryContext(ctx, listvariantstatuscounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []ListVariantStatusCountsRow
	for rows.Next() {
		var row ListVariantStatusCountsRow
		if err := rows.Scan(&row.Status, &row.VariantCount); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}
