// Code generated by Piko. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"errors"
)

const claimrelease = `INSERT INTO release_lease (release_id, publish_digest, state, first_seen_at, heartbeat_at)
VALUES (?, ?, 'publishing', ?, ?)
ON CONFLICT(release_id) DO NOTHING
RETURNING release_id;`

type ClaimReleaseParams struct {
	ReleaseID     string
	PublishDigest string
	FirstSeenAt   int64
	HeartbeatAt   int64
}
type ClaimReleaseRow struct {
	ReleaseID string `json:"release_id"`
}

func (queries *Queries) ClaimRelease(ctx context.Context, params ClaimReleaseParams) (ClaimReleaseRow, bool, error) {
	var row ClaimReleaseRow
	err := queries.writer.QueryRowContext(ctx, claimrelease, params.ReleaseID, params.PublishDigest, params.FirstSeenAt, params.HeartbeatAt).Scan(&row.ReleaseID)
	if errors.Is(err, sql.ErrNoRows) {
		return ClaimReleaseRow{}, false, nil
	}
	if err != nil {
		return ClaimReleaseRow{}, false, err
	}
	return row, true, nil
}

const deletereleaselease = `DELETE FROM release_lease WHERE release_id = ?;`

func (queries *Queries) DeleteReleaseLease(ctx context.Context, releaseID string) error {
	_, err := queries.writer.ExecContext(ctx, deletereleaselease, releaseID)
	return err
}

const deletestalepublishinglease = `DELETE FROM release_lease
WHERE release_id = ? AND state = 'publishing' AND heartbeat_at < ?;`

type DeleteStalePublishingLeaseParams struct {
	ReleaseID   string
	HeartbeatAt int64
}

func (queries *Queries) DeleteStalePublishingLease(ctx context.Context, params DeleteStalePublishingLeaseParams) error {
	_, err := queries.writer.ExecContext(ctx, deletestalepublishinglease, params.ReleaseID, params.HeartbeatAt)
	return err
}

const getrelease = `SELECT release_id, publish_digest, state, first_seen_at, published_at, heartbeat_at, retired_at
FROM release_lease
WHERE release_id = ?;`

type GetReleaseRow struct {
	ReleaseID     string `json:"release_id"`
	PublishDigest string `json:"publish_digest"`
	State         string `json:"state"`
	FirstSeenAt   int64  `json:"first_seen_at"`
	PublishedAt   int64  `json:"published_at"`
	HeartbeatAt   int64  `json:"heartbeat_at"`
	RetiredAt     int64  `json:"retired_at"`
}

func (queries *Queries) GetRelease(ctx context.Context, releaseID string) (GetReleaseRow, bool, error) {
	var row GetReleaseRow
	err := queries.reader.QueryRowContext(ctx, getrelease, releaseID).Scan(&row.ReleaseID, &row.PublishDigest, &row.State, &row.FirstSeenAt, &row.PublishedAt, &row.HeartbeatAt, &row.RetiredAt)
	if errors.Is(err, sql.ErrNoRows) {
		return GetReleaseRow{}, false, nil
	}
	if err != nil {
		return GetReleaseRow{}, false, err
	}
	return row, true, nil
}

const heartbeatrelease = `UPDATE release_lease
SET heartbeat_at = ?
WHERE release_id = ? AND heartbeat_at < ?;`

type HeartbeatReleaseParams struct {
	HeartbeatAt  int64
	ReleaseID    string
	HeartbeatAt2 int64
}

func (queries *Queries) HeartbeatRelease(ctx context.Context, params HeartbeatReleaseParams) error {
	_, err := queries.writer.ExecContext(ctx, heartbeatrelease, params.HeartbeatAt, params.ReleaseID, params.HeartbeatAt2)
	return err
}

const listexpiredreleases = `SELECT release_id
FROM release_lease
WHERE state = 'published' AND heartbeat_at < ? AND release_id <> ?;`

type ListExpiredReleasesParams struct {
	HeartbeatAt int64
	ReleaseID   string
}
type ListExpiredReleasesRow struct {
	ReleaseID string `json:"release_id"`
}

func (queries *Queries) ListExpiredReleases(ctx context.Context, params ListExpiredReleasesParams) ([]ListExpiredReleasesRow, error) {
	rows, err := queries.reader.QueryContext(ctx, listexpiredreleases, params.HeartbeatAt, params.ReleaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []ListExpiredReleasesRow
	for rows.Next() {
		var row ListExpiredReleasesRow
		if err := rows.Scan(&row.ReleaseID); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const markreleasepublished = `UPDATE release_lease
SET state = 'published', published_at = ?, heartbeat_at = MAX(heartbeat_at, ?)
WHERE release_id = ?;`

type MarkReleasePublishedParams struct {
	PublishedAt int64
	HeartbeatAt int64
	ReleaseID   string
}

func (queries *Queries) MarkReleasePublished(ctx context.Context, params MarkReleasePublishedParams) error {
	_, err := queries.writer.ExecContext(ctx, markreleasepublished, params.PublishedAt, params.HeartbeatAt, params.ReleaseID)
	return err
}
