// Code generated by Piko. DO NOT EDIT.

package db

import "context"

const findartefactbyvariantstoragekey = `SELECT artefact_id
FROM variant
WHERE storage_key = ?
LIMIT 1;`

type FindArtefactByVariantStorageKeyRow struct {
	ArtefactID string
}

func (queries *Queries) FindArtefactByVariantStorageKey(ctx context.Context, p1 string) (FindArtefactByVariantStorageKeyRow, error) {
	var row FindArtefactByVariantStorageKeyRow
	err := queries.reader.QueryRowContext(ctx, findartefactbyvariantstoragekey, p1).Scan(&row.ArtefactID)
	if err != nil {
		return FindArtefactByVariantStorageKeyRow{}, err
	}
	return row, nil
}

const findartefactidsbytag = `SELECT DISTINCT artefact_id
FROM variant_tag
WHERE tag_key = ? AND tag_value = ?;`

type FindArtefactIDsByTagParams struct {
	P1 string
	P2 string
}
type FindArtefactIDsByTagRow struct {
	ArtefactID string
}

func (queries *Queries) FindArtefactIDsByTag(ctx context.Context, params FindArtefactIDsByTagParams) ([]FindArtefactIDsByTagRow, error) {
	rows, err := queries.reader.QueryContext(ctx, findartefactidsbytag, params.P1, params.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []FindArtefactIDsByTagRow
	for rows.Next() {
		var row FindArtefactIDsByTagRow
		if err := rows.Scan(&row.ArtefactID); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const findartefactidsbytagvalues = `SELECT DISTINCT artefact_id
FROM variant_tag
WHERE tag_key = ?1 AND tag_value IN (?2);`

type FindArtefactIDsByTagValuesParams struct {
	P1        string
	TagValues []string
}
type FindArtefactIDsByTagValuesRow struct {
	ArtefactID string
}

func (queries *Queries) FindArtefactIDsByTagValues(ctx context.Context, params FindArtefactIDsByTagValuesParams) ([]FindArtefactIDsByTagValuesRow, error) {
	query := pikoExpandSlicePlaceholders(findartefactidsbytagvalues, []pikoSliceExpansionSpec{{1, 1}, {2, len(params.TagValues)}})
	args := make([]any, 0, len(params.TagValues)+1)
	args = append(args, params.P1)
	for _, v := range params.TagValues {
		args = append(args, v)
	}
	rows, err := queries.reader.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []FindArtefactIDsByTagValuesRow
	for rows.Next() {
		var row FindArtefactIDsByTagValuesRow
		if err := rows.Scan(&row.ArtefactID); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}
