// Code generated by Piko. DO NOT EDIT.

package db

import "context"

const deletevarianttagsforartefact = `DELETE FROM variant_tag WHERE artefact_id = ?;`

func (queries *Queries) DeleteVariantTagsForArtefact(ctx context.Context, p1 string) error {
	_, err := queries.writer.ExecContext(ctx, deletevarianttagsforartefact, p1)
	return err
}

const deletevariantsforartefact = `DELETE FROM variant WHERE artefact_id = ?;`

func (queries *Queries) DeleteVariantsForArtefact(ctx context.Context, p1 string) error {
	_, err := queries.writer.ExecContext(ctx, deletevariantsforartefact, p1)
	return err
}

const getalltagsforartefact = `SELECT variant_id, tag_key, tag_value
FROM variant_tag
WHERE artefact_id = ?;`

type GetAllTagsForArtefactRow struct {
	VariantID string
	TagKey    string
	TagValue  string
}

func (queries *Queries) GetAllTagsForArtefact(ctx context.Context, p1 string) ([]GetAllTagsForArtefactRow, error) {
	rows, err := queries.reader.QueryContext(ctx, getalltagsforartefact, p1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetAllTagsForArtefactRow
	for rows.Next() {
		var row GetAllTagsForArtefactRow
		if err := rows.Scan(&row.VariantID, &row.TagKey, &row.TagValue); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const gettagsforartefactids = `SELECT artefact_id, variant_id, tag_key, tag_value
FROM variant_tag
WHERE artefact_id IN (?1);`

type GetTagsForArtefactIDsParams struct {
	IDs []string
}
type GetTagsForArtefactIDsRow struct {
	ArtefactID string
	VariantID  string
	TagKey     string
	TagValue   string
}

func (queries *Queries) GetTagsForArtefactIDs(ctx context.Context, params GetTagsForArtefactIDsParams) ([]GetTagsForArtefactIDsRow, error) {
	query := pikoExpandSlicePlaceholders(gettagsforartefactids, []pikoSliceExpansionSpec{{1, len(params.IDs)}})
	args := make([]any, 0, len(params.IDs))
	for _, v := range params.IDs {
		args = append(args, v)
	}
	rows, err := queries.reader.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetTagsForArtefactIDsRow
	for rows.Next() {
		var row GetTagsForArtefactIDsRow
		if err := rows.Scan(&row.ArtefactID, &row.VariantID, &row.TagKey, &row.TagValue); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const gettagsforvariant = `SELECT tag_key, tag_value
FROM variant_tag
WHERE artefact_id = ? AND variant_id = ?;`

type GetTagsForVariantParams struct {
	P1 string
	P2 string
}
type GetTagsForVariantRow struct {
	TagKey   string
	TagValue string
}

func (queries *Queries) GetTagsForVariant(ctx context.Context, params GetTagsForVariantParams) ([]GetTagsForVariantRow, error) {
	rows, err := queries.reader.QueryContext(ctx, gettagsforvariant, params.P1, params.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetTagsForVariantRow
	for rows.Next() {
		var row GetTagsForVariantRow
		if err := rows.Scan(&row.TagKey, &row.TagValue); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const getvariantsforartefact = `SELECT variant_id, storage_key, storage_backend_id, mime_type, size_bytes, status, created_at
FROM variant
WHERE artefact_id = ?;`

type GetVariantsForArtefactRow struct {
	VariantID        string
	StorageKey       string
	StorageBackendID string
	MimeType         string
	SizeBytes        int32
	Status           string
	CreatedAt        int32
}

func (queries *Queries) GetVariantsForArtefact(ctx context.Context, p1 string) ([]GetVariantsForArtefactRow, error) {
	rows, err := queries.reader.QueryContext(ctx, getvariantsforartefact, p1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetVariantsForArtefactRow
	for rows.Next() {
		var row GetVariantsForArtefactRow
		if err := rows.Scan(&row.VariantID, &row.StorageKey, &row.StorageBackendID, &row.MimeType, &row.SizeBytes, &row.Status, &row.CreatedAt); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const getvariantsforartefactids = `SELECT artefact_id, variant_id, storage_key, storage_backend_id, mime_type, size_bytes, status, created_at
FROM variant
WHERE artefact_id IN (?1);`

type GetVariantsForArtefactIDsParams struct {
	IDs []string
}
type GetVariantsForArtefactIDsRow struct {
	ArtefactID       string
	VariantID        string
	StorageKey       string
	StorageBackendID string
	MimeType         string
	SizeBytes        int32
	Status           string
	CreatedAt        int32
}

func (queries *Queries) GetVariantsForArtefactIDs(ctx context.Context, params GetVariantsForArtefactIDsParams) ([]GetVariantsForArtefactIDsRow, error) {
	query := pikoExpandSlicePlaceholders(getvariantsforartefactids, []pikoSliceExpansionSpec{{1, len(params.IDs)}})
	args := make([]any, 0, len(params.IDs))
	for _, v := range params.IDs {
		args = append(args, v)
	}
	rows, err := queries.reader.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []GetVariantsForArtefactIDsRow
	for rows.Next() {
		var row GetVariantsForArtefactIDsRow
		if err := rows.Scan(&row.ArtefactID, &row.VariantID, &row.StorageKey, &row.StorageBackendID, &row.MimeType, &row.SizeBytes, &row.Status, &row.CreatedAt); err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return results, nil
}

const insertvariant = `INSERT INTO variant (artefact_id, variant_id, storage_key, storage_backend_id, mime_type, size_bytes, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?);`

type InsertVariantParams struct {
	P1 string
	P2 string
	P3 string
	P4 string
	P5 string
	P6 int32
	P7 string
	P8 int32
}

func (queries *Queries) InsertVariant(ctx context.Context, params InsertVariantParams) error {
	_, err := queries.writer.ExecContext(ctx, insertvariant, params.P1, params.P2, params.P3, params.P4, params.P5, params.P6, params.P7, params.P8)
	return err
}

const insertvarianttag = `INSERT INTO variant_tag (artefact_id, variant_id, tag_key, tag_value)
VALUES (?, ?, ?, ?);`

type InsertVariantTagParams struct {
	P1 string
	P2 string
	P3 string
	P4 string
}

func (queries *Queries) InsertVariantTag(ctx context.Context, params InsertVariantTagParams) error {
	_, err := queries.writer.ExecContext(ctx, insertvarianttag, params.P1, params.P2, params.P3, params.P4)
	return err
}
